### ISSUE TITLE
ADB backup with --twrp option unrestorable

### ISSUE THREAD

**Issue by rrama** [TeamWin/Team-Win-Recovery-Project#1011]
I created a backup with ADB and the `--twrp` option and compression enabled. I am unable to restore the backup with `adb restore` whilst running TWRP (hangs, see below) or normally. Copying the file to a USB or internal storage to restore through TWRP displays no partitions in the backup. Also, trying with Titanium Backup it complains that it is incorrectly formatted.

---

#### When restoring with `adb restore` running TWRP:
```
Updating partition details...
...done
Full SELinux support is present.
MTP Enabled
command is: 'adbrestore' and there is no value
Wiping System
Formatting System using make_ext4fs...
Restoring System...
[System done (1 seconds)]
```
Then it continues to do the loading bar animation at the bottom, but nothing more is outputted (I left it running overnight).

#### Logs:
If there is a way to access the logs whilst running the restore, please let me know.
[recovery.log](https://pastebin.com/LfD3GL2k)
[dmesg.log](https://pastebin.com/Vv0ufABc)

#### Specs:
 - Nexus 5
 - twrp-3.1.1-0-hammerhead

#### Steps taken to produce backup:
1. Launch TWRP.
1. `adb -f backupofph --twrp`.
1. Select all partitions.
1. Enable compression in the options.
1. Ensure password is not set. (I know passwords seem to mess everything up)
1. Make backup.

#### Manually trying to uncompress the backup:
I could not find appropriate documentation on how to manually uncompress the backup.  
I have tried the following to no success:
 - `pigz -d backupofph` (and with renaming the file to add the `zz` suffix).
 - `cat backupofph | zlib-flate -uncompress`
 - `printf "\x1f\x8b\x08\x00\x00\x00\x00\x00" |cat - backupofph |gzip -dc` [found here](https://unix.stackexchange.com/a/49066)
 - I have also tried the above with chopping of parts of the first sections of the file with `dd if=backupofph bs=24 skip=1 of=backupSKIP24.zz` and `dd if=backupofph bs=512 skip=1 of=backupSKIP512.zz`
I would be grateful for a way to access the data manually (on either Windows or Linux).

---

Thanks in advance!

**Comment by exentio** [comment]
Same error here, I tried to extract the data in different ways without success. I need at least to recover Authenticator's data. I'm using TWRP-3.1.1-0 for Redmi 4 Prime (markw)

**Comment by manoskav** [comment]
I faced the same issue on Nexus 4, TWRP 3.1.1-0.
Backed up with adb backup --twrp
Restored with adb restore backup.ab
Seems to restore boot properly but hangs on system partition (says done 1 sec and freezes)

**Comment by bigbiff** [comment]
This will be fixed in the next release.

**Comment by bigbiff** [comment]
Please leave a new issue if you still have problems. There are some more bugfixes going in the next release.

**Comment by Ten0** [comment]
Looks like I have a TWRP version that has this issue (3.3.1-62) - or at least the same symptoms, from here:
https://xdaforums.com/t/recovery-3-4-0-10-cepheus-official-unofficial-twrp-for-xiaomi-mi-9-stable.3905825/

Is this a backup issue, or a restore issue? Is there any workaround? (Such as copying the backup file (or files extracted from the backup file) to the SD and triggering the restoration from there?

Thanks,
