### ISSUE TITLE
Build failed: klte-prod 

### ISSUE THREAD

**Issue by fitittome** [TeamWin/Team-Win-Recovery-Project#1017]
It looks like the build failed on klte-prod some months ago.  

"Device in multiple trees. Please remove from trees not ready to build in"

https://jenkins.twrp.me/view/prod/job/klte-prod/lastBuild/console

Could you ask the maintainer to have a look as it would be nice if we could get the adopted storage keys included in the backup please?

Thanks.

**Comment by bigbiff** [comment]
Last build was OK.
