### ISSUE TITLE
Backup exclude dalvik cache

### ISSUE THREAD

**Issue by aaronpoweruser** [TeamWin/Team-Win-Recovery-Project#102]
For aosp based roms, dalvik cache is stored in data/dalvikcache, this on average is 200+ mb , and is often wiped when restoring anmyway, thus it doesnt need to be part of the backup.

**Comment by ameer1234567890** [comment]
Since a nandroid denotes "a full copy of the current system", it should include dalvik cache as well, IMHO. Excluding it, however, can be a great space-saver. Thus, this could be included as an option for the user to choose?
