### ISSUE TITLE
PGP keys broken!

### ISSUE THREAD

**Issue by R3gHex** [TeamWin/Team-Win-Recovery-Project#1026]
Hello guys,
I was checking the signature for the images of twrp, and they seems all broken.

I've tried this one: 

twrp-3.0.2-0-t03g.img.tar | 6.6M | 2016-04-05 02:58:28 EDT
twrp-3.0.2-0-t03g.img | 6.5M | 2016-04-05 02:58:28 EDT
twrp-3.0.1-0-t03g.img.tar | 6.5M | 2016-04-02 14:53:47 EDT
twrp-3.0.1-0-t03g.img | 6.5M | 2016-04-02 14:53:47 EDT
twrp-3.0.0-0-t03g.img.tar | 6.5M | 2016-02-20 07:15:56 EST

and then I stopped, as all where not matching.

I tried with your 'public.asc' key presented in your homepage and also tried to retrieve from key server (the public keys match).

Anyway for all of the above it give me 'BAD signature'. I think you should recheck the signature.
Neither the MD5 is matching! I think this is very bad!!

gpg --import public.asc
gpg --verify twrp-3.0.2-0-t03g.img.tar.asc twrp-3.0.2-0-t03g.img.tar

gpg: Signature made Sun 21 May 2017 03:48:05 AM CEST using RSA key ID 891A43DF
gpg: BAD signature from "TeamWin <admin@teamw.in>

Please check if you can

**Comment by andyg0808** [comment]
I did find that an old download of `twrp-3.0.2-0-mako.img` matched the current signature file.

**Comment by bigbiff** [comment]
Looks ok on the server:

gpg: Signature made Sat 20 May 2017 09:48:05 PM EDT using RSA key ID 891A43DF
gpg: Good signature from "TeamWin <admin@teamw.in>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 9570 7D42 307C 9D41 D09B  F709 1D85 97D7 891A 43DF
root@ix-0078:/www/dl.twrp.me/t03g# gpg --verify twrp-3.0.2-0-t03g.img.tar.asc twrp-3.0.2-0-t03g.img.tar
gpg: Signature made Sat 20 May 2017 09:48:05 PM EDT using RSA key ID 891A43DF
gpg: Good signature from "TeamWin <admin@teamw.in>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 9570 7D42 307C 9D41 D09B  F709 1D85 97D7 891A 43DF
root@ix-0078:/www/dl.twrp.me/t03g# gpg --verify twrp-3.0.1-0-t03g.img.asc twrp-3.0.1-0-t03g.img
gpg: Signature made Sat 20 May 2017 09:48:04 PM EDT using RSA key ID 891A43DF
gpg: Good signature from "TeamWin <admin@teamw.in>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 9570 7D42 307C 9D41 D09B  F709 1D85 97D7 891A 43DF
root@ix-0078:/www/dl.twrp.me/t03g# gpg --verify twrp-3.0.1-0-t03g.img.tar.asc twrp-3.0.1-0-t03g.img.tar
gpg: Signature made Sat 20 May 2017 09:48:05 PM EDT using RSA key ID 891A43DF
gpg: Good signature from "TeamWin <admin@teamw.in>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 9570 7D42 307C 9D41 D09B  F709 1D85 97D7 891A 43DF
root@ix-0078:/www/dl.twrp.me/t03g# gpg --verify twrp-3.0.0-0-t03g.img.tar.asc twrp-3.0.0-0-t03g.img.tar
gpg: Signature made Sat 20 May 2017 09:48:04 PM EDT using RSA key ID 891A43DF
gpg: Good signature from "TeamWin <admin@teamw.in>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 9570 7D42 307C 9D41 D09B  F709 1D85 97D7 891A 43DF
