### ISSUE TITLE
[TWRP 3.1.1-0] [F8131] Xperia X Performance blackscreen

### ISSUE THREAD

**Issue by lyn1337** [TeamWin/Team-Win-Recovery-Project#1029]
Greetings!

My sony xperia x performance "dora" struggles with a note stating 

> Your device is corrupt. It can't be trusted and may not work

 plus blackscreen thus fails to boot after flashing twrp and entering twrp for at least one time. It's running stock android nougat.

**Comment by RootOfJessey** [comment]
EIC

**Comment by z89735651** [comment]
on issue

**Comment by z89735651** [comment]
on issue
