### ISSUE TITLE
Date and Size sort orders reversed

### ISSUE THREAD

**Issue by frankieGom** [TeamWin/Team-Win-Recovery-Project#103]
TWRP 2.4.1.0 on GT-N7105
In Advanced/File Manager, ascending and descending sort orders for date and size are reversed. Ascending dates starts with newest files instead of oldest and ascending size starts with biggest files instead of smallest.

**Comment by Dees-Troy** [comment]
This is fixed in the mainline code for our next release. Thanks for reporting it.
