### ISSUE TITLE
[feature request] 'Skip ro.build.product checks' option

### ISSUE THREAD

**Issue by dimqua** [TeamWin/Team-Win-Recovery-Project#1034]
I often install new firmwares for compatible devices (not always mine), that's why I have problems with _ro.build.product_ checks all the time:
>This package is for 'X' devices this is a 'Y'.

To avoid this I edit the firmware's updater-script to _ro.build.product_ match my device name.

Please add an option to skip _ro.build.product_ checks.

**Comment by that1** [comment]
These checks are done by your ZIP, not by TWRP.
