### ISSUE TITLE
Support for Samsung Galaxy S5 SM-G900D?

### ISSUE THREAD

**Issue by toktobuhe** [TeamWin/Team-Win-Recovery-Project#1039]
The SM-G900D isn't listed among the S5 models, but I've used Heimdall to flash two versions each of
klte (3.1.0-1 ; 2.8.7.0)
klteduos (3.1.1-0 ; 3.0.1-0)
kltechn (3.1.1-0 ; 3.0.2-0)

Flash appears successful, but on boot in recovery mode get "Could not do normal boot." and the same ODIN MODE download mode load screen.

Acc. to the wikipedia (where model is listed as SM-G9009D) the specs are a little different from the others, so it might make sense that the other images wouldn't work.

Let me know if there is any further diagnostic info that would be helpful, or other workarounds to try. Thanks!

**Comment by bigbiff** [comment]
Someone with the device has to create a port.
