### ISSUE TITLE
24-Hour Time

### ISSUE THREAD

**Issue by PeterGuru** [TeamWin/Team-Win-Recovery-Project#105]
I'm currently using TWRP v2.4.1.0 on my Samsung Galaxy Note II (Telus).

Is it possible to display 24-hour time instead of 12-hour time?  I would prefer to see, for example, 17:45 instead of 5:45 PM.  It helps me when I'm setting backup names.

**Comment by bigbiff** [comment]
http://review.teamw.in/#/c/488/

**Comment by PeterGuru** [comment]
Thank you for addressing my request for Military Time so quickly.

However, it does not seem to work.  I added the section from the github to my ui, and the checkbox is there, but enabling it does not appear to do anything; 12-hour time continues to be displayed.  Furthermore, when I reboot into recovery, the checkbox is no longer enabled … and the time continues to be 12-hour.

Regards,

Peter Beyer

President

WECO  GREEN LIGHTING LTD.

26-6033 Shawson Drive

Mississauga, ON, Canada, L5T 1H8

Phone:  905-670-9584  •  Fax:  1-888-471-7784

Email:   mailto:pbeyer@wecoLED.com pbeyer@wecoLED.com  •   mailto:pbeyer@wecogreen.com pbeyer@wecogreen.com

Web:  wecoLED.com  •   http://wecogreen.com/ wecogreen.com

CANADA • USA • CHINA • IRELAND • GERMANY • FRANCE • SPAIN • ITALY • INDIA

**Comment by bigbiff** [comment]
Not sure how you built TWRP, but the link was meant to show it was being worked on and included in the next release of TWRP.

**Comment by PeterGuru** [comment]
Ahh, my apologies.  I guess I’m getting ahead of myself.  Thank you for all your great work.  I will wait for the next release.

Regards,

Peter Beyer

President

WECO  GREEN LIGHTING LTD.

26-6033 Shawson Drive

Mississauga, ON, Canada, L5T 1H8

Phone:  905-670-9584  •  Fax:  1-888-471-7784

Email:   mailto:pbeyer@wecoLED.com pbeyer@wecoLED.com  •   mailto:pbeyer@wecogreen.com pbeyer@wecogreen.com

Web:  wecoLED.com  •   http://wecogreen.com/ wecogreen.com

CANADA • USA • CHINA • IRELAND • GERMANY • FRANCE • SPAIN • ITALY • INDIA
