### ISSUE TITLE
Removal of Bricked Kernel leads to overheating on mako

### ISSUE THREAD

**Issue by Lownita** [TeamWin/Team-Win-Recovery-Project#106]
Since 2.4.0.0, at least 2.4.1.0, people using TWRP on mako are suffering from overheating phones, very high battery drain and "red leds of death" while doing a backup, preferably with compression activated.
This was also discussed in the official thread on xda developers and confirmed by show-p1984 (developer of bricked kernel) in the corresponding post: http://forum.xda-developers.com/showpost.php?p=38265378&postcount=434

**Comment by Dees-Troy** [comment]
I believe that the 2.4.2.0 version that we shipped today should include bricked kernel. If you can confirm by doing a "uname -a" via adb shell or the terminal command under advanced, that would be appreciated. I don't have a mako to test with myself.

**Comment by Lownita** [comment]
Yes, indeed it does! It is 3.4.0-Bricked-v0.7-nos2w-TWRP-ge64003f-00946-g65b0e8a. Thermal throttling should be fine again :)

**Comment by showp1984** [comment]
Sadly that is the old kernel version, you  might want to update it to the one I gave you over irc or posted in the thread :-)

Here: http://forum.xda-developers.com/showpost.php?p=38396691&postcount=450

As you can see here: https://github.com/showp1984/bricked-mako/commit/0d8a3e7d7b0e0a6bf936406359292dc3fe01713d it already has lowered temp limits.

**Comment by Lownita** [comment]
Aaand updated again with latest bricked kernel, thanks!
