### ISSUE TITLE
Pollux Windy TWRP 3.0.2 not decrypting data partition

### ISSUE THREAD

**Issue by Naklarsuper** [TeamWin/Team-Win-Recovery-Project#1061]
Having issues with TWRP and Lineage on pollux_windy (Sony Xperia Tablet Z). All worked fine until I encrypted the device. Not TWRP can't read the data partition anymore, just shows it with "0 MB". Doesn't ask for a password, throws no error. So can' do backups anymore.

**Comment by Naklarsuper** [comment]
Tried all kinds of different OS and Lineage version combinations - TWRP just does not seem to be able to decrypt the data partition on pollux_(windy). Thoughts?

**Comment by Naklarsuper** [comment]
Does anyone know if TWRP is SUPPOSED to work with encrypted pollux / Sony devices?

**Comment by nailyk-fr** [comment]
It do not work this way. 
Maintainer need to make twrp compatible for encryption.

**Comment by Naklarsuper** [comment]
So I assume TWRP is not compatible for encryption on pollux_windy? too bad, would have been good to know beforehand (maybe I missed this point)

**Comment by nailyk-fr** [comment]
isn't pollux_windy a z2 variant? 
We are currently bringing the whole shinano platform with encryption support.

**Comment by Naklarsuper** [comment]
Its the tablet Z (so the one before Z2). Still a phenomenal tablet (waterproof and all), cheap, and now with official LineageOS. My hope is that shinano encrypition support would be identical / very similar?

**Comment by Naklarsuper** [comment]
Its the tablet Z (so the one before Z2). Still a phenomenal tablet (waterproof and all), cheap, and now with official LineageOS.

**Comment by Naklarsuper** [comment]
Sorry that I keep pushing on this. I'd be happy to throw in a donation if you could look into tablet Z decryption for one of the next releases. Thanks! appreciate the work
