### ISSUE TITLE
Flashing FDroid Privileged Extension OTA fails

### ISSUE THREAD

**Issue by shtrom** [TeamWin/Team-Win-Recovery-Project#1079]
When flashing the OTA ZIP for the FDroid Privileged Extension https://gitlab.com/fdroid/privileged-extension.
It comes as a ZIP for initial install https://f-droid.org/packages/org.fdroid.fdroid.privileged.ota, which is what I'm trying to flash through the recovery but, inspecting the filesystem afterwards, I only have two new directories: `/system/app/Fdroid` and `/system/priv-app/FDroidPrivilegedExtension`, but both are empty.

I tried several time with two subsequent versions of the FDroid Privileged Extension.

I noticed that I have to mount the `/system` partition before flashing (though flashing would apparently succeed without it, but the directories would not be created [I think]), and it would be unmounted immediately after flashing the ZIP was said to be successful.

* Hammerhead running LineageOS 14.1 (Android 7.1.2)
* TWRP 2.8.7.1
* re-locked bootloader and encrypted system partition

Matching issue with FDroid: https://gitlab.com/fdroid/privileged-extension/issues/35

**Comment by shtrom** [comment]
Same thing on CM 13.0-20160418 on a different Hammerhead with the same version of TWRP, and the 2070 OTA zip downloaded from the F-Droid app.

**Comment by shtrom** [comment]
Updated TWRP to 3.2.0, which seems to have fixed the issue.

**Comment by etam** [comment]
What if my device is not supported by twrp 3? Can I install this OTA manually?

**Comment by etam** [comment]
Never mind. I've managed to do it. See https://gitlab.com/fdroid/privileged-extension/issues/35#note_58970388
