### ISSUE TITLE
BZZZZ after long operations

### ISSUE THREAD

**Issue by S-trace** [TeamWin/Team-Win-Recovery-Project#108]
Hello. 
Can You add option to TWRP to make it BZZZZ phone when long operations (such as backup/restore/installation of update) finished?
When display is off we now need to wake it to see if operation is done. It will be nice to just put phone to desktop and wait for BZZZZ.

**Comment by Dees-Troy** [comment]
The screen automatically wakes at the end of any operation, though we do plan to eventually offer various forms of haptic feedback.

**Comment by Dees-Troy** [comment]
Haptic feedback / vibration has been added.
