### ISSUE TITLE
Flash "aroma" Package Reboot on Samsung S5(Kltechn)

### ISSUE THREAD

**Issue by CyanTrigger** [TeamWin/Team-Win-Recovery-Project#1082]
I Flash have "arome" Package at Newest twrp version(3.1.1-0) ,But wait few second ,it is reboot to recovery,I changed version 3.0.2-0 ,but It is have a same bug
Please Fix This Bug

Phone Model:SM-G9008V

**Comment by bigbiff** [comment]
Please post issue on device repository.
