### ISSUE TITLE
Stuck in recovery mode when Reboot Recovery from Official TWRP App

### ISSUE THREAD

**Issue by leclairn** [TeamWin/Team-Win-Recovery-Project#1088]
Device : Samsung Galaxy Grand Prime SM-G530FZ
TWRP version : 3.1.1-1

When I reboot my phone in recovery mode using Reboot Recovery from Official TWRP App, I can not reboot in system mode. My phone always boot in recovery mode even if I want to boot in system mode.

Reflashing TWRP zip with ODIN has resolved this problem.

Then, when I boot in recovery mode using Volume Up + Home + Power, this issue does not happen and I can reboot in system mode.

**Comment by bigbiff** [comment]
Not a twrp bug.
