### ISSUE TITLE
When Will TWRP Get Serious About Security and Upgrade Its File Verification To At Least SHA256?

### ISSUE THREAD

**Issue by HardenedArray** [TeamWin/Team-Win-Recovery-Project#1089]
Gentlemen:

I use a wide range of TWRP's functionalities daily and find it to be excellent and reliable code.  
For that, I am very appreciative of your development efforts.

However, I find TWRP's reliance on md5 verification quite bothersome from a security perspective.

The use of md5 has been widely considered insecure for many years.

Every major Linux distro that I am aware of deprecated the use of md5 several years ago, given its lack of security.

No large FOSS project that I am aware of still relies on any use of md5.

Even the world's largest database company, Oracle, which knows a thing or two about security, has this explicit statement regarding the 'security' of md5 on its VBox website:

"You might want to compare the SHA256 checksums or the MD5 checksums to verify the integrity of downloaded packages.  The SHA256 checksums should be favored as the MD5 algorithm must be treated as insecure!"

quoted from:  https://www.virtualbox.org/wiki/Downloads

As I'm sure you are aware, LineageOS offers sha256 verification files for each of its nightly builds.

Therefore, given the vastly more secure, and the very widespread distro and major FOSS project use of sha256 and sha512 for package verification, when is TWRP also going to get serious about security?

The correct answer is now.

Cheers,

HardenedArray

**Comment by bigbiff** [comment]
This has been implemented by selecting sha256 by default for digests.

**Comment by jmichael2497** [comment]
has it though? i've looked at the code, and it seems like it should be searching for rom.zip.sh* similar to rom.zip.md5 but even though i have the LOS rom.zip and rom.zip.sha256 in the same folder, on klte it still reports digest file not found, but finds md5 for the opengapps just fine.
