### ISSUE TITLE
Broken tar in busybox issue

### ISSUE THREAD

**Issue by mperkel** [TeamWin/Team-Win-Recovery-Project#1093]
I'm not sure how much of this is a tar issue or the rom I'm using. I had a restore problem yesterday with the error "extractTarFork() process ended with ERROR: 255". 

I noticed you had toybox as tar, and it works. However there was also a busybox in the /system/sbin directory, probably from the restore of the system partition, and it also had tar, it that tar was broken. "segmentation fault".

The PATH was set to something like /system/sbin;/bin; which caused the broken tar to be ahead of the working tar. What I think happened is that before system was restored it ran the working tar and then after restoring the system it found the broken tar.

I'm not sure of all the details. There might also be an issue with the tar in toybox having a bug in the expand code. But I have run into this error before and it seems to be a common error I see in searching on it. I think that you might want to check various toybox/busybox programs to make sure tar works correctly.

**Comment by bigbiff** [comment]
Please post bug on device repo.
