### ISSUE TITLE
G950F flash kernel issue

### ISSUE THREAD

**Issue by simonk206** [TeamWin/Team-Win-Recovery-Project#1096]
Hello, i have g950f Samsung S8 Exynos with Custom TW ROM Android 7.0

if i flash a new kernel with new released twrp 3.2.0-0, install seems to be ok (no error)
But if i reboot to system, the old kernel i used before is still present.
tried it 4 times now.

i switched back to twrp 3.1.1-2 and it works fine.

**Comment by bigbiff** [comment]
Please post the issue on the device repository.
