### ISSUE TITLE
TWRP 3.2.0-0 problem on Huawei P8(grace)

### ISSUE THREAD

**Issue by erayrafet** [TeamWin/Team-Win-Recovery-Project#1098]
The latest version of TWRP doesn't work and prevents the phone from booting up. I'm using EMUI 4.0.3 with Android 6.0 and firmware version GRA-L09C432B399

**Comment by bigbiff** [comment]
Removed the files from dl.twrp.me for now.

**Comment by erayrafet** [comment]
V3.2.1-0 also doesn't work. The maintainer AD2076 seems like he has retired.

**Comment by bigbiff** [comment]
Thanks, I removed the bad images from the download server and disabled the build for now.
