### ISSUE TITLE
twrp-3.2.0-0-i9300.img MD5 sum incorrect

### ISSUE THREAD

**Issue by ghost** [TeamWin/Team-Win-Recovery-Project#1109]
https://dl.twrp.me/i9300/twrp-3.2.0-0-i9300.img.html

has https://dl.twrp.me/i9300/twrp-3.2.0-0-i9300.img with md5sum d7ac407a79e950cf1238b74b11892d53

and https://dl.twrp.me/i9300/twrp-3.2.0-0-i9300.img.md5 contains 1c934697743702ae84acf156c90f4422, presumably from another build

**Note:** https://dl.twrp.me/i9300/twrp-3.2.0-0-i9300.img.tar.html is correct:

<pre>
$ gpg --verify twrp-3.2.0-0-i9300.img.tar.asc twrp-3.2.0-0-i9300.img.tar
gpg: Note: old default options file '/home/loic/.gnupg/options' ignored
gpg: Signature made Fri 01 Dec 2017 07:01:45 PM CET
gpg:                using RSA key 1D8597D7891A43DF
gpg: Good signature from "TeamWin <admin@teamw.in>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 9570 7D42 307C 9D41 D09B  F709 1D85 97D7 891A 43DF
</pre>

**Comment by ghost** [comment]
Here is what I did a minute ago:

<pre>
loic@raise:/tmp$ wget 'https://dl.twrp.me/i9300/twrp-3.2.0-0-i9300.img'
--2017-12-09 16:16:57--  https://dl.twrp.me/i9300/twrp-3.2.0-0-i9300.img
Resolving dl.twrp.me (dl.twrp.me)... 199.168.142.244
Connecting to dl.twrp.me (dl.twrp.me)|199.168.142.244|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7173 (7.0K) [text/html]
Saving to: ‘twrp-3.2.0-0-i9300.img’

twrp-3.2.0-0-i9300.img     100%[======================================>]   7.00K  --.-KB/s    in 0.002s  

2017-12-09 16:16:59 (3.19 MB/s) - ‘twrp-3.2.0-0-i9300.img’ saved [7173/7173]

loic@raise:/tmp$ wget https://dl.twrp.me/i9300/twrp-3.2.0-0-i9300.img.asc
--2017-12-09 16:17:12--  https://dl.twrp.me/i9300/twrp-3.2.0-0-i9300.img.asc
Resolving dl.twrp.me (dl.twrp.me)... 199.168.142.244
Connecting to dl.twrp.me (dl.twrp.me)|199.168.142.244|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 543 [application/octet-stream]
Saving to: ‘twrp-3.2.0-0-i9300.img.asc’

twrp-3.2.0-0-i9300.img.asc 100%[======================================>]     543  --.-KB/s    in 0s      

2017-12-09 16:17:13 (4.87 MB/s) - ‘twrp-3.2.0-0-i9300.img.asc’ saved [543/543]

loic@raise:/tmp$ gpg --verify twrp-3.2.0-0-i9300.img.asc twrp-3.2.0-0-i9300.img
gpg: Note: old default options file '/home/loic/.gnupg/options' ignored
gpg: Signature made Fri 01 Dec 2017 07:01:45 PM CET
gpg:                using RSA key 1D8597D7891A43DF
gpg: BAD signature from "TeamWin <admin@teamw.in>" [unknown]
loic@raise:/tmp$ wget https://dl.twrp.me/i9300/twrp-3.2.0-0-i9300.img.md5
--2017-12-09 16:18:37--  https://dl.twrp.me/i9300/twrp-3.2.0-0-i9300.img.md5
Resolving dl.twrp.me (dl.twrp.me)... 199.168.142.244
Connecting to dl.twrp.me (dl.twrp.me)|199.168.142.244|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 56 [application/octet-stream]
Saving to: ‘twrp-3.2.0-0-i9300.img.md5’

twrp-3.2.0-0-i9300.img.md5 100%[======================================>]      56  --.-KB/s    in 0s      

2017-12-09 16:18:37 (42.7 MB/s) - ‘twrp-3.2.0-0-i9300.img.md5’ saved [56/56]

loic@raise:/tmp$ md5sum -c twrp-3.2.0-0-i9300.img.md5
twrp-3.2.0-0-i9300.img: FAILED
md5sum: WARNING: 1 computed checksum did NOT match
loic@raise:/tmp$ 
</pre>

**Comment by ghost** [comment]
Hum, that's because I download a web page, that's why... sorry for the noise.

**Comment by ghost** [comment]
It would be a good idea for https://dl.twrp.me/i9300/twrp-3.2.0-0-i9300.img to deliver the same content regardless of the context.

**Comment by bigbiff** [comment]
We don't support wget

**Comment by ghost** [comment]
That's an interesting statement ;-) I know you don't mean it like that but it's slightly amusing because wget just does an HTTP request to the URL and it's almost like you were saying: "we don't support http". I'm kidding, not trolling. I'm very grateful for twrp which is an excellent software.

**Comment by bigbiff** [comment]
The technical reason is we require referral to be sent to the download pages.

**Comment by ghost** [comment]
Indeed:
<pre>
wget --referer https://dl.twrp.me/i9300/twrp-3.2.0-0-i9300.img https://dl.twrp.me/i9300/twrp-3.2.0-0-i9300.img
</pre>
works as expected !

**Comment by bigbiff** [comment]
But it deprives us of ad revenue.

**Comment by ghost** [comment]
I'd be more than happy to display ads when and if they are [done ethically](https://docs.readthedocs.io/en/latest/ethical-advertising.html). Supporting twrp is great. Voluntarily contributing to privacy violations by Google or other advertising agencies is a price I'm not ready to pay.

**Comment by shaggyskunk** [comment]
Looks like some people should just build their own custom recovery then....
smh

**Comment by ghost** [comment]
@shaggyskunk you're mistaking my need for privacy for hostility towards the project. I donated to support twrp. You seem a little sensitive on that topic :-)
