### ISSUE TITLE
YU Yureka (tomato) Device is not booting into Recovery after flashing latest recovery

### ISSUE THREAD

**Issue by AmolGangadhare** [TeamWin/Team-Win-Recovery-Project#1118]
Device name : YU Yureka tomato
TWRP Version: twrp-3.2.1-0-tomato.img
Flash method : fastboot and update through recovery (tried both)

Issue: After successful flash when i press Volume UP+Down+ Power button device stuck at YU logo for infinite time until i remove battery. Device unable to boot into recovery.

**Comment by deshmanth** [comment]
Even I am also getting stuck on the logo after flashing 3.1.1.0 version.But twrp-2.8.4.0-tomato is working fine

**Comment by AmolGangadhare** [comment]
Fixed in the latest release so closing this
