### ISSUE TITLE
I9300, TWRP 2.4.2.0, 24-Hour Time option is not saved across reboots

### ISSUE THREAD

**Issue by qwerty22** [TeamWin/Team-Win-Recovery-Project#112]
I9300, TWRP 2.4.2.0 and 24-Hour Time option.
After rebooting the i9300, the option is not saved. I see again the 12-hour time.

**Comment by bigbiff** [comment]
Working on this tonight. Have to test the code and will submit to gerrit.

**Comment by bigbiff** [comment]
Will be fixed in net release: http://review.teamw.in/#/c/508/
