### ISSUE TITLE
Broken downloads system

### ISSUE THREAD

**Issue by lol768** [TeamWin/Team-Win-Recovery-Project#1120]
Like a bunch of other people I was caught out by the fact your webserver serves `text/html` in response to a perfectly legitimate `curl` command to a URL with a `.img` filename (because it doesn't have a `Referer` set) which I executed after copying the download link URL to the clipboard after viewing the download page. This made the subsequent signature check fail, which led me to believe the webserver had been compromised.

Please fix your downloads page. If you want users to view ads on the page first, fine: Use a different (tokenised, if necessary) URL for the actual binary and link it from the page with ads. The current implementation where you get different resources back based on your `Referer` header is honestly incredibly stupid, has wasted a lot of people's time (https://github.com/TeamWin/Team-Win-Recovery-Project/issues/904 https://github.com/TeamWin/Team-Win-Recovery-Project/issues/625 https://github.com/TeamWin/Team-Win-Recovery-Project/issues/931 https://github.com/TeamWin/Team-Win-Recovery-Project/issues/656) and isn't in line with how a webserver and HTTP are supposed to work.

Please sort it out.

**Comment by xerces8** [comment]
I'll add my case here, as there are already enough tickets opened.

I tried to download TWRP 3.2.1 for i9300 (this URL: https://eu.dl.twrp.me/i9300/twrp-3.2.1-0-i9300.img.html )
And ... it didn't work.
In the default LineageOS browser, just nothing happens after tapping the link.
I thought that browser is "too simple" , so I installed Firefox.
Same story. After tapping the download link a "download started" message pops up, but then nothing. If I open the "Downloads" menu, the download is listed, with a "failed" remark.

I also tried on another phone (MIUI) using Chrome. Same.

At the end I downloaded the file under Windows on my PC.

Please attend to this issue and fix it.
Thank you.

**Comment by shaggyskunk** [comment]
Did you try the TWRP app from the Play Store (as an interim solution for
you)?

**Comment by xerces8** [comment]
I used Windows as an interim solution.

**Comment by shaggyskunk** [comment]
Downloaded fine with Samsung Internet FYI 🐧

**Comment by rancidfrog** [comment]
How is this not being addressed?
None of my browsers are able to download img file. They all download html instead.

Horrible solution that does not seem to work, unless for the 2 cases of samsung and Microsoft being your official sponsors

**Comment by bigbiff** [comment]
Closing as wontfix

**Comment by rancidfrog** [comment]
@bigbiff

This is silly.
Finally was able to download with curl:
```
curl -e https://dl.twrp.me/polaris/twrp-3.2.3-0-polaris.img.html  -L  -O https://dl.twrp.me/polaris/twrp-3.2.3-0-polaris.img
```

**Comment by lol768** [comment]
>Closing as wontfix

Poor response to a legitimate bug.

**Comment by lol768** [comment]
Pixel 2:

```
$ curl -e https://dl.twrp.me/walleye/twrp-3.3.0-0-walleye.img.html  -L  -O https://dl.twrp.me/walleye/twrp-3.3.0-0-walleye.img
```
