### ISSUE TITLE
UPDATE TWRP-3.2.1-0 FOR YUREKA (tomato)

### ISSUE THREAD

**Issue by agxpro** [TeamWin/Team-Win-Recovery-Project#1127]
Device name : YU Yureka (tomato)
TWRP Version: twrp-3.2.1-0-tomato

Request: Want to continue twrp builds for YUREKA as it was stopped due to outdated source code.
I have updated the twrp source code for YUREKA which can be found on my git repo.
Its now working fine without any issue tested by me and many other users...

Updated Source Link: https://github.com/Ankit-Gourav/android_device_yu_tomato.git
Working twrp xda thread by me: https://forum.xda-developers.com/yureka/orig-development/unofficial-twrp-3-2-1-0-tomato-t3717099
twrp direct download: https://www.androidfilehost.com/?fid=889964283620773344

**Comment by bigbiff** [comment]
Please use the contact us page at twrp.me if you are still interested.
