### ISSUE TITLE
TWRP 3.2.1 unable to decrypt data on OnePlus 5T running OmniRom (Android 8.1)

### ISSUE THREAD

**Issue by SapiensAnatis** [TeamWin/Team-Win-Recovery-Project#1129]
Hi. I successfully flashed TWRP to my device using fastboot, and used it to install OmniRom/dm-verity fix/OpenGapps/etc. However, I found that after installing a ROM I was unable to use TWRP further; it prompts me for a password, which is neither the password I have set as my lock screen code or "default_password".

Upon closer inspection, the error given (when attempting to decrypt with any password) is as follows:

```
E:This TWRP does not have synthetic password decrypt support
Unable to decrypt with default password. You may need to perform a Format Data.
```

I don't know if this is an issue on my end (I am really stupid at times) or if there's something wrong with this particular build or what. I also apologize if this is a duplicate but my brief search didn't turn up anything. I haven't tried any other versions, nor have I tried removing my password. 

I am still able to wipe everything and start from scratch. However, I'd rather not when I just want to flash Magisk on a fairly established install with quite a bit of data.

I saw some forum thread about using a modified TWRP to support decryption when using Oreo on the 5/5T, but the links to the modified files were taken down. I'm not sure if that would've worked, but I figure it's worth mentioning.

**Comment by Madis0** [comment]
See #1113 and the original [OmniROM post](https://forum.xda-developers.com/showpost.php?p=74808525&postcount=413) when 8.1 version was released. 

Basically TWRP just does not support encryption on 8.1 yet.

**Comment by SapiensAnatis** [comment]
Thanks!
