### ISSUE TITLE
Does not Backup Correctly

### ISSUE THREAD

**Issue by slinky1914** [TeamWin/Team-Win-Recovery-Project#113]
Love the new recovery I also had this problem with the previous version. When I do a backup it backups the system as it should but not the data portion. For example, I did a backup of a rom today. When I restored it, the log on the screen said it took 130 seconds to restore the system portion and 0 seconds for the data portion. When the phone reboots it acts like it does when a new rom is flashed. It takes a while for the phone to boot and I am back at the original setup screen. When I click next it remembers the last wifi I was on but the rest of the data is gone. Thank you for looking at this. I am using a Nexus 4 on TWRP 2.4.2.0 I have also tried to reflash the recovery and I get the same result.

**Comment by bigbiff** [comment]
Can you post recovery.log please?

**Comment by slinky1914** [comment]
This gonna sound aweful, but where do I find the logs. Lol sorry and thank
you

**Comment by bigbiff** [comment]
The next time it happens go to advanced then copy log to sdcard. Then boot into android and paste /sdcard/recovery.log at http://paste.tinyw.in then paste the link here.

**Comment by slinky1914** [comment]
ok I will do that thank you

On Wed, Feb 27, 2013 at 7:01 PM, bigbiff notifications@github.com wrote:

> The next time it happens go to advanced then copy log to sdcard. Then boot
> into android and paste /sdcard/recovery.log at http://paste.tinyw.in then
> paste the link here.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/TeamWin/Team-Win-Recovery-Project/issues/113#issuecomment-14210561
> .

## 

Dominick Ford
DominickFord@gmail.com

**Comment by slinky1914** [comment]
I did a backup and restore. Here is the backup log: http://tinyw.in/xg79
Here is the restore log: http://tinyw.in/AKKR

Thank you for your help

**Comment by bigbiff** [comment]
Backup is fine, restore is failing on mknod. This issue will be fixed in the next release of TWRP: http://review.teamw.in/#/c/503/

**Comment by slinky1914** [comment]
Thank you very much.

**Comment by Dees-Troy** [comment]
This should be fixed in 2.4.4.0

**Comment by slinky1914** [comment]
Thank you for your hard work.
