### ISSUE TITLE
twrp-3.2.1-0 does not boot on Mi A1 Oreo Update

### ISSUE THREAD

**Issue by michailmotos** [TeamWin/Team-Win-Recovery-Project#1138]
Mi A1 just got updated today from N to O(8.0.0). No released version of TWRP works on the new update(3.1 fails to mount the storage - maybe because of the new encryption on O) and 3.2.1-0 does not even boot with:
fastboot boot twrp.img
The phone just boots normally instead of booting to TWRP.
Multiple reports of this on xda forums, so it is not just me.

**Comment by Theliel** [comment]
Similar to Mi6 Oreo. TWRP boot, but dont detect (and promp) encryption, no pin/pattern is asked. You can use most of all features, but you need format data and use TWRP just after that, without reboot.

I believe that for some reason, encryption is not detected
