### ISSUE TITLE
Installed 2.4 now can't get into download mode

### ISSUE THREAD

**Issue by pendres** [TeamWin/Team-Win-Recovery-Project#114]
I was on a previous version of TWRP (possibly 2.3.2) and was on the newest CM 10.1 rom for 4.2.2 Android. Installed 2.4 zip and install went fine.  I pressed to reboot system and now my Samsung Epic 4G is only able to get to the Samsung  www.samsungmobile.com screen.  If I hold down volume down, camera button and power the phone will light up the 4 buttons on the bottom for a second and cycle through a the samsung screen, the lower buttons, and repeat until I let go of a button then it will stay on the samsung screen.  I am unable to connect to my PC.  When the 4 lights are on the computer recognizes the phone yet this is only for 1 second cycles.

**Comment by Dees-Troy** [comment]
If you can get the Samsung screen then your device is only soft-bricked and you will be able to get into download mode if you do it correctly. On the original Epic 4G with the slide-out keyboard, download mode is done by holding the 1 key on the keyboard and power.
