### ISSUE TITLE
twrp adb restore fail

### ISSUE THREAD

**Issue by uberohr** [TeamWin/Team-Win-Recovery-Project#1142]
i am using twrp recovery 3.2.1.0 on a sm-g800f samsung s5 mini.
when doing a adb restore from a system-data-boot backup on my pc via usb, 
it only restores the system partition.
checking the size of the backup, it does contain system, data, and boot parts.
if i make a separate data backup and restore from that, it got stuck at 50%.
the restore of the boot partition resulted in a md5 error during the restore process.

PS: when a restore or backup finishes, the logscreen disappears so a user does not
know if the action was successfull. The logscreen should stay open until exited by the
user.

**Comment by bigbiff** [comment]
Issues for adb backup were fixed in 3.2.3. Unfortunately older backups are not restorable.
