### ISSUE TITLE
Backup encryption PW: nearly no special characters are taken

### ISSUE THREAD

**Issue by HidingCherry** [TeamWin/Team-Win-Recovery-Project#1147]
On two different devices (griffin and flo) I noticed that nearly no special characters are accepted for the password.

On flo I tested all special characters and only _ is taken.
Installed version: 3.2.1-0

Please confirm for more devices.

**Comment by HidingCherry** [comment]
This issue is useless at this place, no one gives attention to it, even if it is security related.
That's why I closed it.

**Comment by CaptainThrowback** [comment]
This is a known issue. Encrypted backups feature will likely be removed soon.
