### ISSUE TITLE
twrp-3.2.1-0-bacon.img md5 and signature do not match

### ISSUE THREAD

**Issue by mitya57** [TeamWin/Team-Win-Recovery-Project#1149]
I downloaded [twrp-3.2.1-0-bacon.img](https://dl.twrp.me/bacon/twrp-3.2.1-0-bacon.img), but the md5sum does not match:

    $ md5sum twrp-3.2.1-0-bacon.img
    4750e0dd261544dfbbf13905eb0eba65  twrp-3.2.1-0-bacon.img
    $ cat twrp-3.2.1-0-bacon.img.md5 
    0a1f6e1fdb7397617e7da4e2caf71b83  twrp-3.2.1-0-bacon.img

The PGP signature also does not verify:

    $ gpg --verify twrp-3.2.1-0-bacon.img.asc 
    gpg: assuming signed data in 'twrp-3.2.1-0-bacon.img'
    gpg: Signature made Sun 10 Dec 2017 11:55:26 PM MSK
    gpg:                using RSA key 1D8597D7891A43DF
    gpg: BAD signature from "TeamWin <admin@teamw.in>" [unknown]

Obviously I tried to download the same file again, but the result is always the same.

**Comment by mitya57** [comment]
Sorry, my mistake, I missed that the link is not direct and points to an HTML page rather than the actual file. Sorry for the noise…

**Comment by lol768** [comment]
#1120

>Sorry, your mistake

Not your fault!
