### ISSUE TITLE
3.2.1-0 fails to decrypt data on "potter" (moto g5 plus)

### ISSUE THREAD

**Issue by kerlerm** [TeamWin/Team-Win-Recovery-Project#1153]
twrp fails to decrypt /data partition on potter device. Please tell me how to extract logfiles if you need them...

There are several attempts to fix decryption:
https://forum.xda-developers.com/g5-plus/development/unofficial-twrp-3-1-0-0-moto-g5-plus-t3576575
But it does not work with the official 3.2.1-0:
https://twrp.me/motorola/motorolamotog5plus.html

**Comment by kerlerm** [comment]
This TWRP by SanthoshM can decrypt data: 
http://149.56.164.10:1990/moto/twrp_3.1.1-0_potter.zip (is on https://www.androiddevs.net/downloads/)

This one fails: twrp-3.1.1-r7-Gtrcraft.img by @GtrCraft
https://forum.xda-developers.com/attachment.php?attachmentid=4324639&d=1509962393

**Comment by yonjah** [comment]
Here is my recovery.log when trying to decrypt LineangeOS 14.1 -
```
I:sdk version is 25
I:Set page: 'trydecrypt'
I:operation_start: 'Decrypt'
crypt_ftr->fs_size = 51568607
Using scrypt with keymaster for cryptfs KDF
Invalid hex string
Failed to convert passwd from hex, using passwd instead
could not find any keystore module
Failed to init keymaster
Signing failed
kdf failed
failure decrypting master key
Failed to decrypt master key
crypt_ftr->fs_size = 51568607
Using scrypt with keymaster for cryptfs KDF
could not find any keystore module
Failed to init keymaster
Signing failed
kdf failed
failure decrypting master key
Failed to decrypt master key
Failed to decrypt data.
I:Set page: 'decrypt'
I:Set page: 'decrypt_pattern'
I:operation_end - status=1
```
I also tried to follow the requests here https://github.com/TeamWin/Team-Win-Recovery-Project/issues/484#issue-104257049 but other than checking that the encryption is hardware based I couldn't find any of the mentioned strings in the log or mount output.

Other useful information in the log is the data partition -
```
/data | /dev/block/mmcblk0p54 | Size: 0MB
   Flags: Can_Be_Wiped Can_Be_Backed_Up Wipe_During_Factory_Reset Wipe_Available_in_GUI IsPresent Can_Be_Encrypted Is_Encrypted Has_Data_Media Can_Encrypt_Backup Use_Userdata_Encryption Is_Storage Is_Settings_Storage 
   Symlink_Path: /data/media
   Symlink_Mount_Point: /sdcard
   Primary_Block_Device: /dev/block/mmcblk0p54
   Crypto_Key_Location: /dev/block/bootdevice/by-name/metadata
   Display_Name: data
   Storage_Name: Internal Storage
   Backup_Path: /data
   Backup_Name: data
   Backup_Display_Name: Data
   Storage_Path: /data/media
   Current_File_System: emmc
   Fstab_File_System: f2fs
   Backup_Method: dd
   MTP_Storage_ID: 65537
```
It seem to be detected the encryption fine but fails to detect the size (not sure if this is an issue)
the `Crypto_Key_Location: /dev/block/bootdevice/by-name/metadata` is actually pointing to '/dev/block/mmcblk0p35' which does not appear in the partition output.

**Comment by GtrCraft** [comment]
Check the potter twrp thread, I fixed it

**Comment by kerlerm** [comment]
Could you point to the mentioned resource "potter twrp thread"? Thx.

**Comment by ghost** [comment]
@GtrCraft awesome, thank you very much! Can you please trigger a new build for potter so we can actually use the fix?

**Comment by yonjah** [comment]
Just wondering is there any news about this fix ?
I mostly use TWRP to get proper backups of my phone and this doesn't seem possible without decrypting the data (Unless I'm missing something)

**Comment by GtrCraft** [comment]
I fixed it already, the xda thread has working img's. Next official will have it fixed too

**Comment by bllngr** [comment]
In case anyone is looking for it, here's the relevant post: https://forum.xda-developers.com/g5-plus/development/recovery-twrp-3-1-1-0-touch-recovery-t3701488/post75306024#post75306024

**Comment by RootOfJessey** [comment]
As in old ass harold potter

**Comment by CaptainThrowback** [comment]
@bigbiff - this one appears resolved. Please close.
