### ISSUE TITLE
Can't build dtbToolCM missing

### ISSUE THREAD

**Issue by turtle-bazon** [TeamWin/Team-Win-Recovery-Project#1156]
So, all in subj. out/host/linux-x86/bin/ doesn't contains dtbToolCM, needed when separate dt.img used.

**Comment by CaptainThrowback** [comment]
Use the TeamWin device_qcom_common. Or use a prebuilt kernel & dtb so you don't need the repo.

**Comment by turtle-bazon** [comment]
Ok. I use prebuilt kernel and dtb from original firmware. But I have same problem? What I do wrong?

**Comment by CaptainThrowback** [comment]
Remove the "separated dt" flag in your boardconfig. That's only needed if you're building from source.

**Comment by turtle-bazon** [comment]
Ok, thanks. But now it says that missing out/system/bin/linker needed by out/target/product/S10Pro/obj/SHARED_LIBRARIES/libbmlutils_intermediates/teamwin

**Comment by CaptainThrowback** [comment]
Then that's a different issue than you're reporting about in your initial issue, and really isn't a TWRP problem.

**Comment by turtle-bazon** [comment]
Okay, thanks.
