### ISSUE TITLE
No samsung galaxy s6 edge plus 928v 

### ISSUE THREAD

**Issue by yrkndn9** [TeamWin/Team-Win-Recovery-Project#1158]
I have been trying to root my fone fkr months but i cant find anywhere that has my galaxy s6 edge plus model 928v...

**Comment by shaggyskunk** [comment]
Probably not the right place to post - If you have a Snapdragon Device -
you probably have a Locked Bootloader & Can't Root it - Search on XDA for
your device - Not here.

**Comment by Dees-Troy** [comment]
Hey, the V stand for Verizon and Verizon stands for "locked down can't do anything with it!"

If you want something you can root or modify, don't buy anything that they sell in a Verizon store. There are several Verizon-compatible devices that aren't locked down -- mostly from Motorola or the non-Verizon Pixel devices from Google Play. As always, check for TWRP support before you buy, not after!
