### ISSUE TITLE
adb backup restore

### ISSUE THREAD

**Issue by jontis** [TeamWin/Team-Win-Recovery-Project#1159]
Seems to be many having problems with this.
Is anyone working on this?

**Comment by jontis** [comment]
Would be great with instructions how to extract and test backup archive on desktop.

**Comment by jontis** [comment]
Check your file:
$ head backup.ab

Twrp has added some things in the beginning. Skipping those with:
$ dd if=backup.ab bs=512 skip=3 | head

Got me to a semiworking extraction.

$ dd if=backup.ab bs=512 skip=3 | tar -x

**Comment by julien-lang** [comment]
I experienced the same issue. After digging into the TWRP-ADB file format, I think I found an issue in the data structure: the first _twdatablock_ packet is not 1MB size but smaller. So, as TWRP is reading 1MB blocks (hardcoded?), it fails to get the next _twdatablock_ header.

I wrote a Python script to read the data structure, detect the error in the first and last _twdatablock_ blocks and then export the files. So I can manually copy the files on my device and restore the backup.

Please check https://github.com/julien-lang/twrp-adb-backup-extractor

By the way, as we have free space in the _twdatablock_ header (480 bytes available), it'd be a good idea to store the chunk size (1MB or different). So in case of issue, it's easier to read the structure. Also, it would avoid to assume reading 1MB.

**Comment by bigbiff** [comment]
This was fixed in 3.2.3
