### ISSUE TITLE
Screen does not turn off on TWRP for some devices

### ISSUE THREAD

**Issue by tiny4579** [TeamWin/Team-Win-Recovery-Project#117]
I tested the new screen timeout feature on my Droid Incredible with the new TWRP 2.4.2.0 but instead of turning off, the screen just locks.  The same issue occurs when hitting the power button manually; I simply get a lockpad.  That may just be a hardware limitation as my Galaxy Nexus is fine.

**Comment by Dees-Troy** [comment]
Boot TWRP on the Droid Incredible. You can get the information that I need one of two ways:
adb shell
find /sys -name brightness
Paste the output

Or, from the TWRP GUI, Advanced, Terminal Command:
find /sys -name brightness
press the home button then go to Advanced, Copy Log then upload or paste the log file.

**Comment by tiny4579** [comment]
Output of above command:

~ # find /sys -name brightness
/sys/devices/platform/flashlight.0/leds/flashlight/brightness
/sys/devices/platform/leds-gpio/leds/button-backlight/brightness
/sys/devices/platform/leds-microp/leds/amber/brightness
/sys/devices/platform/leds-microp/leds/green/brightness
/sys/devices/virtual/leds/lcd-backlight/brightness

**Comment by bigbiff** [comment]
Might need to add TW_NO_SCREEN_BLANK to flags.

**Comment by Dees-Troy** [comment]
This should be fixed in the next release.
