### ISSUE TITLE
TWRP 3.2.1 fails to decrypt Data Partition on OnePlus 5 after installing Lineage 15.1 (Oreo 8.1)

### ISSUE THREAD

**Issue by moudy01** [TeamWin/Team-Win-Recovery-Project#1193]
After installing Lineageos 15.1 on my OnePlus 5 by sideload TWRP fails to decrypt data partition. After rebooting into recovery mode, TWRP doesn't accept correct password

**Comment by storm49152** [comment]
There is an unofficial build of TWRP-3.2.1 for the OnePlus 5 that should be able to read the encrypted data partition. They say "it works", but I didn't test it (yet).
https://forum.xda-developers.com/oneplus-5/development/recovery-twrp-3-2-1-0-oreo-oxygenos-5-0-t3725723

Can you please make the required changes to make this work in the official build? I guess the same goes for the OP 5T model.

**Comment by moudy01** [comment]
The unofficials builds stillt dont't decrypt data. password isn't accepted although the correct pw has been entered. 
I only get: "Please enter correct password"

**Comment by storm49152** [comment]
Apparently, if you remove the pin and/or pattern, the unofficial TWRP is supposed to be able to decrypt. But I still didn't have time to test this.

https://forum.xda-developers.com/showpost.php?p=75531551&postcount=191

**Comment by moudy01** [comment]
Just tested: removed pin, booted into the unofficial TWRP. Data i.e. sdcard was **de**crypted. So it works this way.
After reboot I entered a new pin, booted into recovery - pw could't be read, data was **en**crypted.

**Comment by moudy01** [comment]
Tested:
https://sourceforge.net/projects/cheeseburgerdumplings/files/15.1/cheeseburger/recovery/twrp-3.2.1-0-20180309-codeworkx-cheeseburger.img/download
decrypts data again with pin on!
