### ISSUE TITLE
Enhancement: Any chance of supporting ICS-style encrypted userdata?

### ISSUE THREAD

**Issue by ghost** [TeamWin/Team-Win-Recovery-Project#12]
Have you guys considered supporting encrypted userdata partitions by presenting a password dialog to the user, unscrambling the encryption key, then remounting the partition through the decrypting device driver like ICS does?  This would give users the security of encrypted data with the flexibility to use TWRP for their flashing and backup needs.

**Comment by lsimoneau** [comment]
+1 for this

**Comment by segv11** [comment]
Looks like they are already working on this:

http://forum.xda-developers.com/showpost.php?p=27454066&postcount=73

**Comment by Dees-Troy** [comment]
We added support that works on the Galaxy Nexus. Not sure that it works on any other devices, but since I don't own a lot of devices, other users / developers will have to take what we have so far and enhance if needed.
