### ISSUE TITLE
Backups Don't Restore Properly

### ISSUE THREAD

**Issue by jcm1979** [TeamWin/Team-Win-Recovery-Project#120]
Here's the TWRP log file
https://dl.dropbox.com/u/580946/recovery.log

Here's the logcat
http://pastebin.com/ugn5z3yc

I restored several of my backups and the data partition doesn't seem to restore correctly.  All my apps are there but none of the personalized data restores.  This occurs on TWRP 2.4.3.0 and 2.4.2.0.

**Comment by Dees-Troy** [comment]
If it exists, can you also provide the recovery.log from:
/sdcard/TWRP/BACKUPS/014E054713008011/2013-03-01--10-28-16/recovery.log
Please?

**Comment by jcm1979** [comment]
http://pastebin.com/rQ7eDU9c

Here you go.
Thanks.

**Comment by Dees-Troy** [comment]
Give this build a try and see if it fixes your problems please:
http://techerrata.com/dees_troy/toroplus.img
Thanks.

**Comment by jcm1979** [comment]
It worked perfectly.  I tried several different backups just for good measure.

**Comment by Dees-Troy** [comment]
The code fix for this is now in 2.4.4.0.
