### ISSUE TITLE
Unable to restore backup -- v2.4.3.0

### ISSUE THREAD

**Issue by alias8818** [TeamWin/Team-Win-Recovery-Project#122]
d-h.st/HKa -- Recovery from backup
d-h.st/9Rb -- Log Copied to SDcard from Recovery option

Restore "completes" in roughly 2 seconds.
It appears that the issue would like with some Ubuntu data on there not restoring correctly.

**Comment by Dees-Troy** [comment]
Your bug is the same as the bug reported in this issue:
https://github.com/TeamWin/Team-Win-Recovery-Project/issues/120
It will be fixed in the next release of TWRP and is related to the hardlinks that Ubuntu Touch is trying to use.
