### ISSUE TITLE
2.4.3 doesn't process the jobs I request in goomanager

### ISSUE THREAD

**Issue by buffal0b1ll** [TeamWin/Team-Win-Recovery-Project#123]
Updated to TWRP 2.4.3 from 2.4.1 yesterday on my VZW Galaxy S3

In 2.4.1 and prior versions I never had a problem ordering and flashing 6 or 7 zips, wiping cache/dalvik, naming and requesting backup job from GooManager. It would reboot into recovery and I'd come back in 15 minutes and everything would be done waiting for me to reboot.

Yesterday I tried twice to flash 7 zips and wipe cache/dalvik in goomanager with TWRP 2.4.3.

The device reboots into recovery but it never processes the jobs I entered in GooMangler;-(  

I was still able use TWRP 2.4.3 to order and flash the zips and wipe.  I just can't seem to request the jobs via GooManager anymore.

**Comment by Dees-Troy** [comment]
After the OpenRecoveryScript process ends, go to Advanced, Copy Log and then upload or paste the log.

**Comment by Dees-Troy** [comment]
Closed due to no logs provided.
