### ISSUE TITLE
problem about download?

### ISSUE THREAD

**Issue by kudou** [TeamWin/Team-Win-Recovery-Project#1230]
on the page https://dl.twrp.me/r5/twrp-3.0.2-0-r5.img
>Thank you for choosing TWRP. Please click the link below to start your download.
Download twrp-3.2.1-0-r5.img

when i click the link ,it just jump to the same page,and did not start to download,is there some block?

**Comment by thany** [comment]
Works for me on Firefox 61 Dev Edition.
There's a chance you may have messed up some preferences in your browser, or your ad blocker is acting up. I suggest you try again with a clean browser with default settings. Thtat'll isolate whether the problem is in your settings, the browser, or the site.

**Comment by kudou** [comment]
Last night solved the problem,that is it! This issue can be closed.
