### ISSUE TITLE
Preferences not persisted

### ISSUE THREAD

**Issue by thany** [TeamWin/Team-Win-Recovery-Project#1232]
It's not really a biggie, since let's face it, TWRP is only needed once in a blue moon when flashing something. But even then it stands out to me that, for example the back button is in the "wrong" place.

I'm using a Galaxy S9 (`starlte`), and since TWRP is built specifically for every type of phone, I'd expect it to follow the back button on the right side, as Samsung does. I guess not. But there is a setting for it, which is great. That setting in particular bugs me, because I have to tick it every single time I boot into TWRP.

All that because TWRP fails to persist its preferences. Can it be fixed? Or are the preferences meant to be nonpersistent?

**Comment by ooonea** [comment]
With version 3.2.3-0, preferences continue to be non-persistent. But I remembered differently.

**Comment by bigbiff** [comment]
TWRP can't persist settings unless the maintainer either gets decryption working to store on data, or changes the persist settings in the configuration for the device tree. This doesn't affect TWRP as a whole and should be opened on the device tree github project.

**Comment by thany** [comment]
Or find the SD-card, if present, and store preferences there? Since SD-cards are typically FAT32 or exFAT, they cannot be encrypted.

Or, I guess, find _any_ non-encrypted partition and use that.

**Comment by CaptainThrowback** [comment]
Most devices don't have an SD card. Someone would need to add code for that. Feel free to submit a patch to Gerrit to handle this instance. Currently settings are already backed up to /persist, which exists for all Android devices at least from Oreo (maybe even Nougat?). But the issue might be that that specific setting isn't being set up as a persistent TWRP setting, if your other settings aren't being reset every boot. It wasn't clear from the OP whether that's the case or not.
