### ISSUE TITLE
Unnecessary file system compatibility warning

### ISSUE THREAD

**Issue by MarcinOrlowski** [TeamWin/Team-Win-Recovery-Project#1236]
Using TWRP 3.2.1-0, on restore I was presented with the following warning:

> WARNING: This /data backup was made with **ext4** file system! The backup may not boot unless you change back to **ext4**.

**Comment by CaptainThrowback** [comment]
Well, is your current file system something else, perhaps f2fs? I don't see anything wrong with the message.

**Comment by MarcinOrlowski** [comment]
If TWRP thinks so, shouldn't it be part of the message to make all clear? Otherwise it is as useful as "Error occured" message.

**Comment by CaptainThrowback** [comment]
You're welcome to submit a patch to Gerrit to update it.

**Comment by lucidBrot** [comment]
I am currently encountering this warning and I don't really understand it. If it is saying it was made with ext4 and it may not boot unless I change it back to ext4, then ... it is already ext4 so I shouldn't have to do anything?

However, it does indeed not boot (or rather, it is booting forever).

**Comment by bigbiff** [comment]
The warning is intended to tell the user that if they change the filesystem, android may not be able to use it on reboot.
