### ISSUE TITLE
2.4.3 failed installing custom rom

### ISSUE THREAD

**Issue by ghost** [TeamWin/Team-Win-Recovery-Project#124]
HTC One S s4.  S-ON, HBOOT v1.13

I did everything I was supposed to.  Wiped everything and cleared caches multiple times.  When trying to install ViperOneS 2.1.0 custom rom it always failed at the part where it is formatting system and cache (I think) as ext4.  I tried multiple times.  There were no fail messages just the reboot button would show up as if it had finished successfully but I know it should take more than 10 seconds to install.  Tried rebooting and downloading the rom again.  Tried answering the questions differently each time.   Ie. the custom vs stock kernel question and the clear cache question.

The solution for me was flashing TWRP v2.4.1.  After I did that it worked first try.  Sorry I don't have more information than that.  There was obviously some problem there related to twrp v2.4.3.  I also tried installing AKOP 4.2.2 unofficial ROM for HTC One S which is a non-sense jellybean rom and it also failed.

**Comment by Dees-Troy** [comment]
After installing the zip, go to Advanced, Copy Log and then upload or paste the log.

**Comment by ulmo20** [comment]
This sounds similar to the problem I reported about wiping the Ext4.  I had similar errors after flashing a rom.

**Comment by Dees-Troy** [comment]
Closing due to no logs provided.
