### ISSUE TITLE
TWRP Manager crash at select device

### ISSUE THREAD

**Issue by LordSith77** [TeamWin/Team-Win-Recovery-Project#1241]
TWRP App:
Build Version: 9.8
Build Date: 1979-11-30  <--- ???????
Current Date: 2018-05-25 
Device: ASUS Nexus 7 (2013)

Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONArray org.json.JSONObject.getJSONArray(java.lang.String)' on a null object reference
	at com.jmz.soft.twrpmanager.utils.RecoveryDialog$1.run(Unknown Source)

**Comment by CaptainThrowback** [comment]
Contact the app dev of TWRP Manager via the support email address on the Google Play Store. This is not an official TWRP app. @bigbiff Please close this issue.
