### ISSUE TITLE
twrp 3.2.1-0 enchilada - Freeze

### ISSUE THREAD

**Issue by amithiel** [TeamWin/Team-Win-Recovery-Project#1248]
Hello,

After several tries, i conclude the following:

- When booting twrp with no security code, it works like a charm.
- When booting with encryption code ON, you only have 1 try. If you fail at entering the code, it looks like twrp reboots itself and freezes the entire device. You have to force power off. Touch stops working.
Tried several times, always same result.
Device used: Oneplus 6
This behaviour is present either booting twrp or with flashed version.

**Comment by NateDev100** [comment]
Experiencing this as well.
