### ISSUE TITLE
[enchilada]No option to wipe cache in oneplus6 recovery

### ISSUE THREAD

**Issue by NMBlanco** [TeamWin/Team-Win-Recovery-Project#1254]

**Comment by CaptainThrowback** [comment]
The device doesn't have a cache partition.

**Comment by computersalat** [comment]
closing issues which are obviously solved would be a nice thing ...

**Comment by fusk-l** [comment]
I am well aware this is old, but over creating a new i will comment here as this is exactly what i am looking for.
Device: 1+7 running a10 w. twrp 3.3.1-70.
Support told me to wipe cache, but this is not possible through twrp. I've been told that dalvik and cache is not the same thing, so if you want to wipe cache you need to flash stock recovery.
AFAIK there is no other way.
