### ISSUE TITLE
Missing tulip TRWP

### ISSUE THREAD

**Issue by MagicFab** [TeamWin/Team-Win-Recovery-Project#1260]
The ZTE Axon 7 Mini (tulip) is listed as supported by LineageOS at https://download.lineageos.org/tulip.

Instructions at https://wiki.lineageos.org/devices/tulip/install point to https://dl.twrp.me/tulip to get TWRP for this phone, however the link is broken. Searching on the site the tulip is not among devices at https://twrp.me/Devices/ZTE/.

Where can I find it now?

**Comment by CaptainThrowback** [comment]
It doesn't appear to be officially supported. That's probably a generic link that's provided in the LineageOS template, regardless of whether the device is actually officially supported by TWRP. You'll need to work with your Lineage maintainer to get the device officially supported. In the meantime, you can check the LineageOS and/or XDA forums for an unofficial TWRP version for your device (if it exists).

**Comment by MagicFab** [comment]
Thank you for clarifying this.
