### ISSUE TITLE
Bad GPG signature on all image files

### ISSUE THREAD

**Issue by RomainL972** [TeamWin/Team-Win-Recovery-Project#1269]
Hello,
It seems there is a problem with the GPG signature on the files from https://twrp.me. I checked the signature of many files, many different devices and both America and Europe servers and it always resulted in 
```
gpg: Signature made Sun 10 Dec 2017 10:00:13 PM CET
gpg:                using RSA key 1D8597D7891A43DF
gpg: BAD signature from "TeamWin <admin@teamw.in>"
```
I tried all the Samsung Galaxy J7 2016 files, the files from the TWRP device, the fairphone files and others.

**Comment by beerisgood** [comment]
Cant confirm that:

> gpg: Signatur vom 12/10/17 21:58:59 Mitteleuropõische Zeit
gpg:                mittels RSA-Schlüssel 1D8597D7891A43DF
gpg: Korrekte Signatur von "TeamWin <admin@teamw.in>" [vollständig]

Looks like you use a wrong key. The creation date & time is different

Fingerprint is:
**9570 7D42 307C 9D41 D09B F709 1D85 97D7 891A 43DF**

**Comment by felipedau** [comment]
I can confirm what @RomainL972 reported. I got the same key as @beerisgood:

```
$ curl https://eu.dl.twrp.me/public.asc | gpg --import
$ gpg --fingerprint teamwin
pub   rsa4096 2016-11-27 [SC]
      9570 7D42 307C 9D41 D09B  F709 1D85 97D7 891A 43DF
uid           [ unknown] TeamWin <admin@teamw.in>
sub   rsa4096 2016-11-27 [E]
```

Still, couldn't verify:

```
$ wget https://eu.dl.twrp.me/star2lte/twrp-3.2.1-2-star2lte.img.asc
$ wget https://eu.dl.twrp.me/star2lte/twrp-3.2.1-2-star2lte.img
$ gpg -v --verify twrp-3.2.1-2-star2lte.img.asc 
gpg: assuming signed data in 'twrp-3.2.1-2-star2lte.img'
gpg: Signature made Wed 18 Apr 2018 09:36:29 PM -03
gpg:                using RSA key 1D8597D7891A43DF
gpg: using pgp trust model
gpg: BAD signature from "TeamWin <admin@teamw.in>" [unknown]
gpg: binary signature, digest algorithm SHA1, key algorithm rsa4096
```
The checksum doesn't match either:

```
$ wget https://eu.dl.twrp.me/star2lte/twrp-3.2.1-2-star2lte.img.md5
$ md5sum twrp-3.2.1-2-star2lte.img | diff - twrp-3.2.1-2-star2lte.img.md5 
1c1
< 009997b55656de885ad47864ae1920bb  twrp-3.2.1-2-star2lte.img
---
> 700aff69142166ff7b8afd323860e9b5  twrp-3.2.1-2-star2lte.img
\ No newline at end of file
```

I also got the same results when downloading from the America server (`dl.twrp.me`).

Here is my gpg config:

```
$ gpg --version
gpg (GnuPG) 2.1.18
libgcrypt 1.7.6-beta
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/user/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

**Comment by JacobRoth** [comment]
I'm getting essentially the same result as felipedau, with the same --fingerprint output and the same "BAD signature" error, for twrp-3.2.2-0-kugo.img (a different official image file). However for this file the .md5 checksum does match the image file.

**Comment by JacobRoth** [comment]
Does anyone know if it's still safe to flash the .img files even with the bad signature? It looks like the website operators haven't noticed this issue yet...

**Comment by bigbiff** [comment]
My guess is corrupted downloads. I get on the server itself:

gpg: assuming signed data in 'twrp-3.2.1-2-star2lte.img'
gpg: Signature made Wed 18 Apr 2018 08:36:29 PM EDT
gpg:                using RSA key 1D8597D7891A43DF
gpg: Good signature from "TeamWin <admin@teamw.in>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 9570 7D42 307C 9D41 D09B  F709 1D85 97D7 891A 43DF

**Comment by JacobRoth** [comment]
That's funny... can you check twrp-3.2.2-0-kugo.img on the server as well? I get a matching md5sum but BAD signature, regardless if I download from dl.twrp.me or eu.dl.twrp.me and regardless if I use the browser or wget to download.

**Comment by bigbiff** [comment]
Thanks, I guess the creation was corrupted for that file. It has been regenerated. Please let me know of any others that are bad.
