### ISSUE TITLE
Could someone give a detailed introduction about how to compile it?

### ISSUE THREAD

**Issue by javaeryang** [TeamWin/Team-Win-Recovery-Project#1270]
the xda guide is not so clear,  i don't know how to compile it for. i really want to learn,Tks.

**Comment by CaptainThrowback** [comment]
This isn't a TWRP issue. There are plenty of guides on how to compile AOSP and AOSP-based ROMs. Please start there, and if you have an issue building TWRP once you assimilate that data, you can post in the guide thread on XDA. Please close this issue.

**Comment by javaeryang** [comment]
ok, i will close it, i mean how to compile twrp on aosp, i had sync the aosp source, and build it, as i din't know how to build twrp. does it right?
clone this project to an empty folder, then, replace the folder to recovery folder, then (example, compile twrp for xiaomi MIX2) go to device folder, and clone mix2 device, and config device message, finally, cd root of source make recoveryimage.
