### ISSUE TITLE
Screen registers touches in wrong places after flashing TWRP 3.2.2-0 on Xiaomi Mi A1

### ISSUE THREAD

**Issue by alextov** [TeamWin/Team-Win-Recovery-Project#1271]
I’ve had this problem that I think may be related to TWRP. Yesterday I flashed an official LineageOS 15.1 build to my Xiaomi Mi A1. It had its own recovery and I wanted to flash TWRP, so I downloaded the latest version from the official website, rebooted to bootloader and performed `fastboot flash recovery twrp-3.2.2-0-tissot.img`. The flashing failed:
```
Sending 'recovery' (30972 KB)                      OKAY [  0.783s]
Writing 'recovery'                                 FAILED (remote: partition table doesn't exist)
Finished. Total time: 0.828s
```
I lurked a bit and found advice to run `fastboot boot twrp-3.2.2-0-tissot.img`, which I did. Supposedly, it should have booted me directly into TWRP; however, I was met with the usual boot process instead. That’s when I figured out that my screen seems to have gone mad: it registered touches in seemingly random places of the screen, but not where I actually tap. Entering correct unlock pattern was a real pain, and after a few hours I somehow managed to enable tap tracking in Developer options to help better illustrate the issue: https://streamable.com/rbfrn

I tried factory reset, but it didn’t help. In fact, _even within the recovery_ the screen still exhibits this broken behavior. So now I’m left wondering what to do next. Since it started after I flashed TWRP, I assume it is connected, that’s why I chose to report this here.

**Comment by bigbiff** [comment]
Please post your issue to your device tree github repository.

**Comment by alextov** [comment]
@bigbiff If you mean https://github.com/TeamWin/android_device_xiaomi_tissot, there is no “Issues” tab there.

**Comment by bigbiff** [comment]
Sorry, it's added now.
