### ISSUE TITLE
What the hell is wrong with v3.2.2-0???

### ISSUE THREAD

**Issue by stavr0cks** [TeamWin/Team-Win-Recovery-Project#1272]
Is decryption of data completely broken in this build?

Completely unable to automatically install an update to LineageOS on Nexus 6P.

**Comment by CaptainThrowback** [comment]
This isn't how you submit a bug report. Please do it properly, or this issue will be ignored.

**Comment by z89735651** [comment]
。。。。。

**Comment by stavr0cks** [comment]
Tons of people down the list have the same issue on various devices. After clicking Install on a downloaded update, the phone just reboots to recovery and does absolutely nothing. It doesn't even require my pattern to decrypt, neither it installs the update.

**Comment by bigbiff** [comment]
Fixed in 3.2.3
