### ISSUE TITLE
3.2.2 fails LineageOS OTA updates - various devices

### ISSUE THREAD

**Issue by NeatNit** [TeamWin/Team-Win-Recovery-Project#1273]
Possible duplicates:
- #1264 - Flash error with 3.2.2-0 on Nexus 5x (bullhead)
- #1265 - "could not mount /data and unable to find crypto footer" Redmi Note 4 / mido
- #1268 - TWRP 3.2.2-0 at OnePlus 5: No access to Data partition when your device is encrypted
- #1272 - What the hell is wrong with v3.2.2-0???

I'm opening this as a new issue in an attempt to make it more comprehensive and useful for the developers who want to fix it. Those other issues are a bit too vague about some things.

**The issue (to the extent I can confirm) is: TWRP fails to install LineageOS OTA updates due to a decryption issue.** The update is initialized from within LineageOS, it then boots into TWRP, but TWRP doesn't install the update. Instead, it first asks whether to modify system partition, and regardless of whether the user allows or denies it, TWRP returns to its main menu.

If the user taps Install from the main menu, he (or she) discovers that all of the folders are completely empty.

**A work-around is to reboot into recovery, at which point TWRP will ask the user for the unlock pattern and the user can install the update manually.** This is not ideal; many users prefer to revert back to TWRP 3.2.1, which would simply ask for the unlock pattern when installing OTA updates, and installed them fine. This is likely related to this line from the [3.2.2-0 changelog](https://twrp.me/site/update/2018/07/01/twrp-3.2.2-0-released.html):

> * OTA style update zips will now install automatically without prompting for decrypt

I'm having this issue with Nexus 5X.

I've seen reports (in the issues linked above) for the same issue on the following devices:
- Nexus 5X
- Nexus 6P
- OnePlus 5
- OnePlus 5T

This issue may be exclusive to the Pattern Unlock + LineageOS combination.

**Comment by bigbiff** [comment]
Can you try reverting https://github.com/omnirom/android_bootable_recovery/commit/72638b6437822300fefd77569d98fbad3dad5c28 and see if it works for you?

**Comment by NeatNit** [comment]
Well.... Sorry to disappoint, I'm actually not a developer of any kind on Android, I just wanted to make a proper bug report. I don't have the needed tools installed, and I don't have the confidence to start tinkering with these things - I can't risk my phone right now.

Sorry. I hope you can still find a device that does this or someone else to test things, and fix the bug.

**Comment by RootOfJessey** [comment]
Thank you to all the Generation X for Your faith and continuous faith in each other.God bless all For Their constant part in Selfless deeds in the Kingdom of Heaven here on Earth.Today's Questions Are Trully Tomorrows Answers.

**Comment by bigbiff** [comment]
@NeatNit can you try http://build.twrp.me/twrp-3.2.2-enc-test-bullhead.img

**Comment by truenicoco** [comment]
I have a (probably) related issue. I installed LineageOS monday on my brand new mido. While setting it up, I activated an option to "enter my unlock pattern before boot for security" or something similar, which resulted in having to enter my unlock pattern twice at startup. It was a mistake and I didn't want to encrypt my device, but maybe this resulted in encrypting it… unfortunately I cannot know for sure right now. What is certain is that I did not want to encrypt my device.

Anyway, today I wanted to install the LineageOS weekly update. But instead of applying the OTA automatically, my device just boots into TWRP. After looking at [this thread](https://www.reddit.com/r/LineageOS/comments/5wg26e/installing_otaupdate_just_reboots_to_twrp/), I tried to manually locate the update but found an empty `/data/` directory. I tried wiping my device to solve the issue, as advised on the thread, but instead of just wiping the dalvik cache, I factory reset my device (I know, I'm stupid).

It didn't help regarding OTA updates through TWRP. Here's the state of my device right now :

- When I boot into LineageOS, I no longer have to enter my unlock pattern "before boot". In settings, anything encryption related is disabled.
- If I try to upgrade through LineageOS update mechanism, everything seems OK at first but TWRP just boots without applying the update.
- If I manually reboot to recovery, TWRP prompts for the unlock pattern to "mount" and "decrypt" (which doesn't happen when rebooting throught LineageOS update mechanism). Now this is where it gets weird, even if I enter my unlock pattern, it states it cannot decrypt/mount the storage.
- If I cancel this unlock pattern step, all storages show as 0MB in TWRP, and the `/data` dir only has one subdir `tmp_mnt` which is empty.

I hope this help you guys in fixing this issue.

**Comment by NeatNit** [comment]
@bigbiff it works - it asked for my pattern, then installed, just like 3.2.1 used to do!

I think users really don't care about inputting their pattern one extra time when installing an update. If this can't be avoided, no worries!

**Comment by truenicoco** [comment]
For the record I solved my issue by flashing a TWRP 3.2.1 with treble support found on the XDA forums. I have no idea if it works because it's 3.2.1 or because it has treble support.

**Comment by bigbiff** [comment]
Does lineage install updates from storage?

**Comment by NeatNit** [comment]
The update zip is saved under /data/lineageos_updates/

Edit: and as far as I can tell, they're the same zips as available from https://download.lineageos.org/bullhead

**Comment by Taijian** [comment]
I can confirm the same issue applies to the FP2 with LOS 14.1 and TWRP 3.2.2-0

**Comment by bigbiff** [comment]
Hi, there is a fix building now for 3.2.3 to fix this issue.

**Comment by stephanlachnit** [comment]
More possible duplicates: #1226 #1217 #1245 #1193 #1207 #1196 #1165 #1141 #1168 #1153 #854 #1169 #1117 #1108 #1113 #1129 #1067 #1054 #1047 #1044 

Btw im still on 3.2.1 and have the issue, so i dont think its a 3.2.2 problem.
Removing encyption doesnt help either, then TWRP shows 0MB partitions.

**Comment by NeatNit** [comment]
That seems to me like a different issue. This one is specifically about OTA-style LineageOS updates in 3.2.2 only. The ones you linked seem to be about failure to decrypt regardless of how you got to recovery.

They may be related in some way, but they're not duplicates of this. (though from the few I've clicked, it seems like many of them are duplicates of each other)

**Comment by DavidBerdik** [comment]
This issue is also present on my Nexus 6 (codename Shamu) running LineageOS 15.1 with TWRP 3.2.2.

**Comment by WyattBest** [comment]
Oops, I didn't find this via searching and created another duplicate: #1277

**Comment by DavidBerdik** [comment]
> This issue may be exclusive to the Pattern Unlock + LineageOS combination.

It may be exclusive to LineageOS, but the pattern unlock is not the only one that has the issue. I use a pin and it's doing the same thing.

**Comment by DavidBerdik** [comment]
> This issue may be exclusive to the Pattern Unlock + LineageOS combination.

It may be exclusive to LineageOS, but the pattern unlock is not the only one that has the issue. I use a pin and it's doing the same thing.

@bigbiff - Is 3.2.3 going to be officially released soon, or should we grab the source and compile it ourselves?

**Comment by bigbiff** [comment]
It should be out by the weekend.

**Comment by DavidBerdik** [comment]
@bigbiff Awesome! Thanks!

**Comment by Yannik** [comment]
@bigbiff Thanks! Hopefully it'll be available soon :-)

**Comment by DavidBerdik** [comment]
@bigbiff I installed 3.2.3 on my Nexus 6 today, and decryption is unfortunately still not working.

**Comment by Yannik** [comment]
3.2.3 fixed the automatic updates through the block.map file, so the issue reported here is fixed IMO.

However I can confirm, that decryption still does not work. (redmi note 4 w/ lineageos 15.1)

**Comment by DavidBerdik** [comment]
Oops. My bad. I thought this issue was related to decryption not working.

**Comment by ZJaume** [comment]
I'm on LOS 15.1 with Mi5(gemini) with the same bug on 3.2.2 and persists on 3.2.3.
EDIT: encryption works if I mount data manually.

**Comment by ZJaume** [comment]
[Here](https://pastebin.com/K502Y77B) is my log.

**Comment by DavidBerdik** [comment]
@ZJaume I was not aware that a log could be grabbed for TWRP. How do I do that? Also, how do you mount data manually?

**Comment by ZJaume** [comment]
@DavidBerdik `Advanced > Copy log` creates a `recovery.log` file on internal storage (I don't know where if data isn't mounted). `Mount > Decrypt data` to decrypt and mount /data partition.

**Comment by ZJaume** [comment]
I also noticed that TWRP prompts the pattern to decrypt data if I reboot to TWRP manually. It doesn't prompts for the pattern if LOS reboots to perform the update.

**Comment by DavidBerdik** [comment]
@ZJaume Okay thanks! I'll have to give that a try once I get the chance. As for not being prompted when LOS reboots to update, I am reasonably sure that this is deliberate. I recall seeing this in the TWRP changelog recently.

**Comment by ZJaume** [comment]
I think the problem could be with partitions formatted with F2FS, here is what I find on my log:

> `/data | /dev/block/dm-0 | Size: 56117MB Used: 3954MB Free: 43079MB Backup Size: 3954MB`
`...`
`Current_File_System: f2fs`
`Fstab_File_System: ext4`

**Comment by DavidBerdik** [comment]
I tried using @ZJaume 's `Mount > Decrypt data` trick on my Nexus 6, but it did not work. Perhaps it's device-dependent?

**Comment by ZJaume** [comment]
@DavidBerdik I'm not saying that trick works. I'm saying that manual decryption lets you flash the zip manually.

**Comment by ZJaume** [comment]
I think this issue should be reopened

**Comment by NeatNit** [comment]
I don't see why. The specific issue reported here is fixed. I think the issue you guys are having is a separate issue.

Just today I updated LineageOS on Nexus 5X, on TWRP 3.2.3 and it worked perfectly - it didn't even ask for my pattern, it just worked immediately (the way they intended). **This issue** is fixed.

Just open another issue for the problem you're having, with detailed information.

**Comment by DavidBerdik** [comment]
@ZJaume Ah, I misunderstood you. My mistake. And yes it should be reopened.

**Comment by WyattBest** [comment]
This issue is fixed for me also.

**Comment by Taijian** [comment]
This issue is fixed for me also on 3.2.3.
