### ISSUE TITLE
Galaxy A serie 2017, wrong color R,G,B order

### ISSUE THREAD

**Issue by f5bud** [TeamWin/Team-Win-Recovery-Project#1275]
After several tries to find the correct format, I discovered a bug in the color assignment in fbdev_init ()

My actual config is:
 `TARGET_RECOVERY_PIXEL_FORMAT := RGB_565`
and the manifests:
`<project path="bootable/recovery" name="android_bootable_recovery" remote="omnirom" revision="android-8.1" />`

the color blue is orange
![screenshot_2018-07-25-16-08-56](https://user-images.githubusercontent.com/3526773/43206274-991e4a22-9025-11e8-80fc-7458f5b07e0b.jpg)

Greetings, Daniel
```
Starting the UI...
setting DRM_FORMAT_RGB565 and GGL_PIXEL_FORMAT_RGB_565
Skipping drm graphics -- not present in build tree
fb0 reports (possibly inaccurate):
  vi.bits_per_pixel = 32
  vi.red.offset   =  16   .length =   8
  vi.green.offset =   8   .length =   8
  vi.blue.offset  =   0   .length =   8
setting GGL_PIXEL_FORMAT_BGRA_8888
double buffered
framebuffer: 0 (1080 x 1920)
Using fbdev graphics.

```

**Comment by bigbiff** [comment]
Please post your issue to your device tree github repository.
