### ISSUE TITLE
TWRP 3.2.2-0 doesn't install OTA updates (LineageOS updates) with LOS 15.1 on bacon

### ISSUE THREAD

**Issue by WyattBest** [TeamWin/Team-Win-Recovery-Project#1277]
Since flashing twrp-3.2.2-0-bacon.img and LOS 15.1 to my OnePlus One (bacon), the ROM's built-in updater no longer works. The phone is encrypted. I can still flash updates manually from TWRP.

Entering TWRP normally:
1. OnePlus logo
2. TWRP logo
3. Mount (Decrypt Data) screen prompts "Enter Password."
4. After entering password, I am taking to the main menu.  /data is mounted.

Entering TWRP via updater:
1. OnePlus logo
2. TWRP logo
3. "Unmodified System Partition" with slider "Swipe to Allow Modifications."
4. After swiping, it goes to the main menu. /data is not mounted. I am never asked for encryption passphrase.

I can try suggestions or supply additional information.

**Comment by bigbiff** [comment]
Fixed in 3.2.3
