### ISSUE TITLE
newbie question-what does "updating partition details" do?

### ISSUE THREAD

**Issue by harvon** [TeamWin/Team-Win-Recovery-Project#1278]
Hi, so I can use twrp to flash/back up my phones (moto e4 plus) with no problems except for one phone that always stuck on a step called "updating partition details." I have to turn the phone off to get out of it. I mean whatever I wanted to flash seems to install fine despite being stuck at this step, so I am just wondering what may be causing this problem? I have the same twrp image on other phones with identical builts that do not run into this problem. Many thanks!

**Comment by bigbiff** [comment]
Non-bug. You probably opened the console from the button. Press the console button again to close it.

**Comment by harvon** [comment]
dumb question but what is the console button? I had to press the power button and swipe the unlock to turn it off.
