### ISSUE TITLE
Data partition restoring wrong?

### ISSUE THREAD

**Issue by Mike-Ferretti** [TeamWin/Team-Win-Recovery-Project#128]
I backed up my CM10.1 ROM using the newest TWRP (2.4.3.0) and flashed a TW ROM so I could flash a newer PRL (Wicked Sensations). Backup was fine, no error messages. Wiped to factory settings, installed TW ROM, flashed new PRL, no problems. Went back into TWRP to restore, all looked fine. Rebooted, saw CM logo, and it went into CM10.1. Saw my wallpaper and apps, but none of my personal settings saved. Any idea how to fix this? I am currently flashing older versions of TWRP to see if I can remedy this issue, but just in case that doesn't work, any solutions? This is essentially the same issue as  #120 and saw that you fixed it so I was wondering if you could do the same for the D2SPR! (Sprint Galaxy S3) Thank you!

**Comment by Mike-Ferretti** [comment]
Here is my recovery.log file after a failed restore: https://www.dropbox.com/s/oc58dgqfsreuxfa/recovery.log

**Comment by Dees-Troy** [comment]
Are you sure that you're still having this issue? That log shows a successful restore, no errors, and you went from having:

I:Data backup size is 164MB

to:

I:Data backup size is 3684MB

To me it looks like it's working fine. Also the restore of data took 950 seconds:
[Data done (950 seconds)]

**Comment by Mike-Ferretti** [comment]
The restore doesn't fail. It boots into CM10.1 just fine. All of my Play Store apps are there, but it seems all of my system apps lost all of their settings. My notification light is a different color, my texts are all erased, my contacts are gone, and none of my apps have their data, such as levels I have beat in certain apps.

**Comment by Dees-Troy** [comment]
Try to be more specific. E.g. select a certain game or app that's missing its settings / data and tell us which apps those are.

**Comment by Mike-Ferretti** [comment]
Upon booting, it tells me how to use the app drawer and such. I go into the settings and none of my pre-backup settings are there. I then opened the stock messaging app, all my texts are gone. Opened up my contacts, nobody is there. Every single app that I have used no longer has any data on it. For instance, Angry Birds does not have my current level saved. An app I use for notetaking no longer has any notes in it. Basically, every single app is treated as if it were just cleanly installed from the play store.

**Comment by Dees-Troy** [comment]
So you listed Angry Birds. According to the restore log, TWRP restored several files/folders for Angry Birds. Specifically use a file browser that can use root access such as Root Explorer or ES File Explorer to browse to:
/data/data/com.rovio.angrybirds/files/cacert.pem
Do you have that file present on your device?

**Comment by Mike-Ferretti** [comment]
Yes I do. However, for some reason, the Angry Birds app just shows a black screen after being launched. And also, my home button does not seem to function properly when pressed.

**Comment by Mike-Ferretti** [comment]
I have solved this issue! I had to fix permissions right after restoring the backup (before rebooting!)

**Comment by landstander668** [comment]
I think that more-or-less verifies that this issue and #140 are indeed the same.

**Comment by Mike-Ferretti** [comment]
I am so thankful for your contribution landstander668! If I had not known to fix permissions after the restore, I would have lost my installation!

**Comment by Dees-Troy** [comment]
Fix merged here: http://review.teamw.in/#/c/536
It will be in the next release of TWRP.

**Comment by Mike-Ferretti** [comment]
Great! Thank you! :)
