### ISSUE TITLE
Moto Z2 Force Nash - Error during LOS Flashing

### ISSUE THREAD

**Issue by FunkyH** [TeamWin/Team-Win-Recovery-Project#1283]
Hi There,

is there already a solution according to this issue (see links below)? I am still not able to install LOS due to this error.

Thanks a lot for help / advice!

https://www.reddit.com/r/LineageOS/comments/93d390/nash_nightly_builds_public_key_verification/

https://forum.xda-developers.com/z2-force/development/twrp-3-1-1-0-moto-z2-force-nash-t3687421/page53

**Comment by bigbiff** [comment]
Please post your issue to your device tree github repository.
