### ISSUE TITLE
twrp 3.2.3 fails to decrypt Oneplus One on Lineage 15.1

### ISSUE THREAD

**Issue by vincez201** [TeamWin/Team-Win-Recovery-Project#1289]
Hi,

I have a Oneplus One running Lineage 15.1 and install the Linage OTA roughly every month after the Android security patches come out. Last month when I tried to install an update I noticed I wasn't able to because TWRP was unable to decrypt my phone - on entering my pattern I received the error 

> Pattern failed, please try again!

At the time I noticed I was running TWRP 3.2.1 so I flashed to 3.2.2, but received the same error when trying to boot to recovery. I then tried removing my pattern lock and trying again, but TWRP asked me to 

> Enter Password.

despite there not being one. I also tried setting a PIN for my screen lock (and selecting "Yes" when Android asked me if I wanted to use this PIN for secure start-up) and using this PIN when booting to recovery, but TWRP still wasn't able to decrypt it.

I then resorted to some Googling where I found people suggested that removing the screen lock and the using the password `default_password` worked for them. However, this didn't work for me (TWRP gives the error `Password failed, please try again!`). I also noticed someone suggested that TWRP 3.2.3 fixes some issues with encrypted devices so to wait for this to be released. I've just flashed my phone with 3.2.3 and can now install the Linage OTA updates. However, I'm still not able to decrypt my phone when booting to recovery mode.

I have attached the `recovery.log` and am happy to provide any further information that may help. If no-one has any ideas or can spot any bugs then I'll just factory reset my phone and install the latest Lineage OS from scratch.

[recovery.log](https://github.com/TeamWin/Team-Win-Recovery-Project/files/2270650/recovery.log)

**Comment by vincez201** [comment]
I think this is a duplicate of:

#1226 #1217 #1245 #1193 #1165 #1108 #1054

There are also some notes about this issue on #1273 although #1273 is for a problem that was solved in 3.2.3

**Comment by bigbiff** [comment]
Please open device specific issues on the device tree.
