### ISSUE TITLE
TWRP freezes after deleting a directory in file manager

### ISSUE THREAD

**Issue by patrickli** [TeamWin/Team-Win-Recovery-Project#129]
How to reproduce on Samsung Galaxy SIII i9300:
1. Goto advanced, file manager.
2. Select a directory, click "select" from the bottom.
3. Select "delete" and slide to confirm.
4. TWRP will prompt a success message.
5. Click on the "Back" button the recovery will freeze.

Hold the power button and the system will return to recovery, everything is normal and the directory is deleted.

**Comment by Dees-Troy** [comment]
This is fixed in 2.4.4.0
