### ISSUE TITLE
mkfs.ext4 command required

### ISSUE THREAD

**Issue by ghost** [TeamWin/Team-Win-Recovery-Project#1304]
- [x] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [ ] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [ ] I have searched for my issue and it does not already exist

**Device codename**: any device
**TWRP version**: future development
#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
mkfs.ext4 required in twrp adb shell

#### WHAT IS THE EXPECTED RESULT?
mkfs.ext4 available

#### WHAT HAPPENS INSTEAD?
only mkfs.ext2 available

**Comment by Dees-Troy** [comment]
Before Android 9.0 Pie, the preferred method for formatting ext4 is to use make_ext4fs. You should use make_ext4fs instead.

**Comment by vinibali** [comment]
i'm here because i didn't find any of the commands I've used before. so just a note:
* in the 3.7.x versions it's called mke2fs
