### ISSUE TITLE
TWRP fails to decrypt data on Pixel

### ISSUE THREAD

**Issue by SilverMight** [TeamWin/Team-Win-Recovery-Project#1307]
**Device codename**: sailfish
**TWRP version**: 3.2.3-0

Trying to decrypt the data results on saying "Password failed", even though the password is correct. Removing the PIN allows TWRP to access it fine
`/tmp/recovery.log`: https://paste.omnirom.org/view/b16a82c3#YEqReV5NdLSNgbNbP33dMZEHz3TRmrae
`dmesg`: https://paste.omnirom.org/view/76abce55#uhCvbT18ZVoFbxl6TwwKb8GhlYuFDRnV

**Comment by ASoTNetworks** [comment]
I am seeing the same problem on Oneplus One (bacon) also.

**Comment by dmig** [comment]
Same on Xiaomi note 4x.
The problem is related to PIN verification. Plain password works fine.

**Comment by ipkpjersi** [comment]
This also happens on my OP5 Android 8.1 with TWRP 3.2.3-0. Reverting to 3.2.1-1 fixes this.

**Comment by ShatteredRPG** [comment]
Same problem here. I'm using fastboot to get root but no dice on Android P.

**Comment by SilverMight** [comment]
Works fine on 3.2.3-1 now

**Comment by marcofugaro** [comment]
This issue happens again with TWRP v3.3.0-0 for the blueline!
