### ISSUE TITLE
Found NO way to combine the split-ed data.ext4.win00x in nandroid backup.

### ISSUE THREAD

**Issue by ccchan234** [TeamWin/Team-Win-Recovery-Project#1309]
- [N ] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [N ] I am running the latest version of TWRP
- [Y ] I have read the FAQ (https://twrp.me/FAQ/)
- [Y ] I have searched for my issue and it does not already exist

**Device codename**:  kenzo aka red mi note 3 
**TWRP version**:  3.0.2.x

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?

Use twrp to make nandroid backup of /data,
the /data will be split into several data.ext4.win00x.

I can manually untar them by renaming into *.tar and extract the say 13 files.

Yet if I want to combine them,
if fail by the method I found online,
which is cat data.ext4.win00* | tar xvf - (something like that)

It may produce a large file that is 16GB (the same size as all my file),
but when untar, it only produce 1.6GB file, which I think is the 1st tar file.

And I cant combine by other means.

#### WHAT IS THE EXPECTED RESULT?

I expect I can simply join back the data.ext4.win00* into ONE single large file containing
/data, and untar and got back the files.

#### WHAT HAPPENS INSTEAD?

One can join the files, but using command from web, the large file only untar into part of
the files (the 1st *.tar's file I think)

#### ADDITIONAL INFORMATION

`/tmp/recovery.log`: 
`dmesg`:

**Comment by bigbiff** [comment]
You cannot concentrate then because they are separate tar files.
