### ISSUE TITLE
Possibility to disable the check of enough free space on storage before backup

### ISSUE THREAD

**Issue by morbloe** [TeamWin/Team-Win-Recovery-Project#131]
As an example: I have to backup about 3.1 GB of data in one backup and with compression enabled it results in about 1.9 GB. 

So I have to free up 3.1 GB before backup but only 1.9 GB will be used.

**Comment by Dees-Troy** [comment]
It's impossible to know exactly how compressible the data is so we require that you have enough space for an uncompressed backup. At best we could offer a way to override or ignore the size/space check.

**Comment by morbloe** [comment]
Yeah this would be great and would perfectly fit. :-)
Am 12.03.2013 19:42 schrieb "Dees-Troy" notifications@github.com:

**Comment by ameer1234567890** [comment]
Doesn't it actually use more than the compressed backup size during the backup process (used by pigz)?

**Comment by marduk191** [comment]
This would be a great feature as I have a device that refuses to report the correct space to begin with.

**Comment by ghost** [comment]
Bump.  I run into this issue all the time.  Naturally the software can't know the end result after compression.  No one blames it for stating insufficient space if you don't have enough for a 1:1 copy.  However, it shouldn't absolutely refuse to continue no matter what when compression is enabled -- especially with modern devices where compression is quite fast even in the recovery (my old SGS3 took a long time I'll admit, but my HTC M7 really doesn't take that much longer than uncompressed.)  Simply warn the user and give them an option to bypass (heck, require us to type "YES" in all caps if you want.  I don't care.  Just don't force me to have to go through deleting a bunch of stuff I really didn't want to delete to make a bunch of extra space that it doesn't actually need.)  At times I've actually been forced to manually move data off, make the backup, then move the data right back over in all of the plenty of free space still remaining after said backup...

**Comment by CaptainThrowback** [comment]
This option was added a while ago, wasn't it?

EDIT: https://github.com/omnirom/android_bootable_recovery/commit/bf1d67245ebce9d63e1167920e5dec6728843b11 Looks like it was merged 4 months ago . . .

**Comment by ghost** [comment]
Not in 2.8.5.0 that I can find anywhere anyway.  It just simply says error, insufficient space and aborts without asking or anything.  (I'll try updating in just a bit, but 2.8.5.0 is not old at all so definitely anything added in 2.8.6.0 or 2.8.7.0 would not qualify as "a while ago.")

**Comment by CaptainThrowback** [comment]
You'd need to be using at least 2.8.6.0 to have that feature. Seems that you need an update.

(see my edit above)

**Comment by CaptainThrowback** [comment]
You know the current version is 2.8.7.0, right?

**Comment by ghost** [comment]
Yes.  I admit I thought I had it on 2.8.7.0.  I will update it as soon as the backup process is complete and test that.  If this is the case, however, I would definitely describe it as a very very new feature.

**Comment by CaptainThrowback** [comment]
I guess you didn't look at my edit. It was merged 4 months ago. I guess it really depends on your concept of time, doesn't it?

**Comment by ghost** [comment]
Ok, finally got it updated (somehow my fastboot drivers were broken and the TWRP manager didn't want to work.)  Yes, the option is indeed finally available.  Sorry for the unnecessary bump then.  I would have sworn I was on 2.8.7.0 specifically (as I remembered that specific number even) but I guess I only updated my tablet.

As for the edit, this site shows new comments automatically, but you must refresh to see edits apparently.
