### ISSUE TITLE
TWRP Black Screen while loading recovery on Redmi Note 5(Whyred)

### ISSUE THREAD

**Issue by Tao-kun** [TeamWin/Team-Win-Recovery-Project#1314]
**Device codename**: Redmi Note 5 (Whyred)
**TWRP version**: twrp-3.2.3-0 and twrp-3.2.2-0 

**Is's fixed in official twrp 3.2.3-1**

Redmi Note 5 with the latest MIUI 10 developer version(Chinese version, with official root), with anti-rollback check lock, which result in I couldn't use fastboot flash to flash twrp.img.

Using fastboot boot twrp.img or the TWRP Official APP and reboot to recovery, I couldn't enter the TWRP recovery and black screen. After I restsrt my device, I could only load official MI-recovery.

So, why I reboot the TWRP recovery failed? In addition, my device's LCD Vendor is huaxing(华星), is this result in this problem?

(The link of log file is [recovery.log](https://paste.omnirom.org/view/d922065b) and [another try](https://paste.omnirom.org/view/76d8a602) (1 month available))

**Comment by elf128** [comment]
Got the same issue with Redmi 5+ ( vince ).
MIUI 9.6.5
In fact I have two identical devices, but purchased from different vendors. One work as expected, another gives black screen upon load of TWRP.
Device visible and accessible via adb during  black screen.

**Comment by Tao-kun** [comment]
I found that the [vendor blob file of TRWP](https://github.com/Ankit-Gourav/android_vendor_xiaomi_whyred) is too outdated to support my device. The vendor blob file should be updated from this [repo](https://github.com/GuaiYiHu/android_vendor_xiaomi_whyred/tree/lineage-16.0/proprietary/recovery/root), which contains MIUI's latest vendor blob file.

**Comment by NiNoXowl** [comment]
hello 
i have similar problem thats my [issue ](https://github.com/TeamWin/Team-Win-Recovery-Project/issues/1335) can you link twrp img that worked for you ?
