### ISSUE TITLE
TWRP 3.2.3 not able to decrypt /data for Wileyfox Swift aka crackling

### ISSUE THREAD

**Issue by uspoma** [TeamWin/Team-Win-Recovery-Project#1315]
- [x] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**Device codename**: Wileyfox Swift | crackling
**TWRP version**: 3.2.3

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
1. Install Oreo
2. Set password for device
3. Activate encryption
4. Boot to TWRP

#### WHAT IS THE EXPECTED RESULT?
Should accept password and mount /data

#### WHAT HAPPENS INSTEAD?
Fails to mount /data because it does not accept password

#### ADDITIONAL INFORMATION
Tried to remove password/pin in Oreo but still TWRP fails to decrypt /data

I know this is a known issue for many devices - just want to add Wileyfox Swift to the affected devices list.

**Comment by CaptainThrowback** [comment]
Please post this issue to the official TeamWin repo for your device. This needs to be addressed by your device maintainer, and is not a general TWRP bug.

**Comment by uspoma** [comment]
Just to be sure - would that be the right place to post this issue?: https://github.com/TeamWin/android_device_wileyfox_crackling/issues

Because the code base there is cm 12.1 but twrp for crackling is actually 3.2.3. Also nobody seems to be responding there...

**Comment by CaptainThrowback** [comment]
Yes that's the right place. Your other option is to try and contact your device maintainer on XDA.

P.S. The latest TWRP source builds with device trees going back to Lollipop, so there's nothing wrong with a cm-12.1 tree.
