### ISSUE TITLE
Issues with TWRP v3.2.3-0 

### ISSUE THREAD

**Issue by Ibuprophen** [TeamWin/Team-Win-Recovery-Project#1318]
The following is an issue that has been experienced by myself with TWRP v3.2.3-0 for the kltevzw, d2vzw and jfltevzw devices...

The attached image reflects 1 single setting that I'm unable to Toggle Off. I unchecked the box and if i go anywhere else in TWRP, it Toggles back ON.

If I were to Toggle On/Off any of the others options in the same screen, they will remain as I had Toggled them last but, not that specific one.

Thank you very much! :-)

~Ibuprophen

https://github.com/ibuprophen1/Odds-N-Ends/raw/master/TWRP/v3.2.3-0/Issues/TWRP%20SHA1%20Issue.png

**Comment by Ibuprophen** [comment]
This issue was just E-Mailed and previously submitted via Google+ approx a week ago... 

https://plus.google.com/106219330808234257266/posts/eppyeWg7u8c


~Ibuprophen

**Comment by CaptainThrowback** [comment]
Yes, I confirmed this issue after your G+ post. A fix will need to be submitted to Gerrit for it - it's probably just an xml issue. Hopefully someone can identify the problem and fix it for the next release.
@bigbiff @Dees-Troy

**Comment by Ibuprophen** [comment]
I am just following up... 

I did see @Dees-Troy had recognized this and another issue I had submitted in Google Plus. 

Unless otherwise noted, I'll just close this issue since the big guy doesn't comment much here and "Keep my Fingers Crossed"! :-) 


~Ibuprophen

**Comment by bigbiff** [comment]
I usually leave things alone here because there are so many dupe/bad issues added and I can't keep up with anything.
