### ISSUE TITLE
Possibility to backup directly to an mounted storage without using internal storage

### ISSUE THREAD

**Issue by morbloe** [TeamWin/Team-Win-Recovery-Project#132]
Something like ADB-backup: you connect your phone via USB and TWRP will save the created backup (TWRP-Backup! (not ADB Backup)) directly on PC (via ADB (or something else)).

**Comment by Dees-Troy** [comment]
This really isn't within the focus or scope of TWRP. Backing up to a computer via ADB would require some kind of software support on the computer itself.

**Comment by morbloe** [comment]
A samba Client would be enough.
Am 28.05.2013 17:37 schrieb "Dees-Troy" notifications@github.com:
