### ISSUE TITLE
createTarFork() process ended with ERROR: 255

### ISSUE THREAD

**Issue by UntouchedWagons** [TeamWin/Team-Win-Recovery-Project#1326]
- [ Yes ] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [ Yes ] I am running the latest version of TWRP
- [ Yes ] I have read the FAQ (https://twrp.me/FAQ/)
- [ Yes ] I have searched for my issue and it does not already exist

**Device codename**: pioneer
**TWRP version**: 3.2.3-1

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Backup Boot, System and Data partition to SD Card

#### WHAT IS THE EXPECTED RESULT?
Backup of Boot, System and Data completes successfully

#### WHAT HAPPENS INSTEAD?
Backing up Data fails with error `createTarFork() process ended with ERROR: 255`

#### ADDITIONAL INFORMATION
I've tried backing up to an external flash drive formatted with exfat, same error

`/tmp/recovery.log`: https://github.com/TeamWin/Team-Win-Recovery-Project/files/2446599/recovery.log
`dmesg`: https://paste.omnirom.org/view/0d8b4610

**Comment by bigbiff** [comment]
It looks like the policy for /data/data was corrupted from FBE somehow. I am not sure if this can be fixed.

**Comment by UntouchedWagons** [comment]
Sorry I don't know what that means. Is my only option to wipe the Data partition without making a backup? What's even stored on that partition? From what I read in the backup progress output it seems like folders I've made aren't included which sounds odd

**Comment by UntouchedWagons** [comment]
It turns out this error was caused by a PEBKAC error (PEBSAC?). I had no idea the Data partition was encrypted with my PIN which is what TWRP asks for every time it loads. So entering my PIN allows TWRP to backup the Data partition.
