### ISSUE TITLE
twrp is not booting simply goes blackscreen

### ISSUE THREAD

**Issue by NiNoXowl** [TeamWin/Team-Win-Recovery-Project#1335]
- [x] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**Device codename**: whyred
**TWRP version**: 3.2.3-0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
basically every try of booting or flashing recovery
after trying to boot recovery via fastboot phone goes blackscreen 

#### WHAT IS THE EXPECTED RESULT?
booted recovery on phone 

#### WHAT HAPPENS INSTEAD?
phone goes blackscreen and nothing happends

#### ADDITIONAL INFORMATION
hardware of my phone:
https://i.imgur.com/giIki1W.png
https://i.imgur.com/v8jyDkQ.png

cmd promt: 
https://i.imgur.com/GbD6lkk.png

`/tmp/recovery.log`: https://paste.omnirom.org/view/e2d3ea1f
`dmesg`: https://paste.omnirom.org/view/e96171c3

**Comment by agxpro** [comment]
> 
> 
>     * [x]  I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
> 
>     * [x]  I am running the latest version of TWRP
> 
>     * [x]  I have read the FAQ (https://twrp.me/FAQ/)
> 
>     * [x]  I have searched for my issue and it does not already exist
> 
> 
> **Device codename**: whyred
> **TWRP version**: 3.2.3-0
> #### WHAT STEPS WILL REPRODUCE THE PROBLEM?
> 
> basically every try of booting or flashing recovery
> after trying to boot recovery via fastboot phone goes blackscreen
> #### WHAT IS THE EXPECTED RESULT?
> 
> booted recovery on phone
> #### WHAT HAPPENS INSTEAD?
> 
> phone goes blackscreen and nothing happends
> #### ADDITIONAL INFORMATION
> 
> hardware of my phone:
> https://i.imgur.com/giIki1W.png
> https://i.imgur.com/v8jyDkQ.png
> 
> cmd promt:
> https://i.imgur.com/GbD6lkk.png
> 
> `/tmp/recovery.log`: https://paste.omnirom.org/view/e2d3ea1f
> `dmesg`: https://paste.omnirom.org/view/e96171c3

Hi,
contact me on telegram (https://t.me/AnkitGourav) or xda (https://forum.xda-developers.com/member.php?u=7124940) I want more info about your device and vendor.

**Comment by starbrights** [comment]
(sorry, I think I misunderstood the problem. for me TWRP itselfs boots, but not the restored image)

Have the same or simular problem here. Want to transfer one setup from a A320FL (A3 2017) to another one. Using latest official TWRP 3.2.3.0
It seems to boot properly (can see final LOS bootlogo 15.1), but than screen is all black. Only by pressing power buttom it shows "Power off or Restart".  
After reboot into TWRP and wiping data all is fine - except that all my apps and settings are lost. But that's exactly I want to backup, as restoring this takes days :(

**Comment by bigbiff** [comment]
This should be taken care of in 3.2.3.1 which is building now.
