### ISSUE TITLE
Decrypt does not work (star2lte)

### ISSUE THREAD

**Issue by johnnybubonic** [TeamWin/Team-Win-Recovery-Project#1336]
- [x] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**Device codename**: star2lte
**TWRP version**: 3.2.3-0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
TWRP fails to decrypt the data partition, always reporting as "wrong password". LineageOS 15.1, the firmware used to encrypt said partition, decrypts it fine using the same passphrase.

#### WHAT IS THE EXPECTED RESULT?
See above.

#### WHAT HAPPENS INSTEAD?
See above.

#### ADDITIONAL INFORMATION
Doubt it's relevant since they're entirely different ring levels, but my device passphrase (the one used to e.g. unlock the screen) is different from my disk encryption passphrase.

Seems related to #1333.

**Comment by geronimoge** [comment]
Same here with a starlte (S9).

**Comment by timstoffel** [comment]
Same here with starlte.

**Comment by Grammate** [comment]
Yep, same here with S9.

**Comment by johnnybubonic** [comment]
still no response? i literally have no way of updating my firmware without this.

**Comment by CaptainThrowback** [comment]
https://twrp.me/faq/encryptionsupport.html

**Comment by bigbiff** [comment]
You should be able to update system without decrypting data. I am closing this because it's not a universal issue for TWRP, but a device issue.

**Comment by rodrigoaguilera** [comment]
I don't see how I can open issues for the star2lte device so we can track this appropriately 

https://github.com/TeamWin/android_device_samsung_star2lte

**Comment by CaptainThrowback** [comment]
You currently can't. Report it in the XDA support thread for now.

**Comment by bigbiff** [comment]
Added issues, I thought I had enabled Issues on all our repositories via a curl script.

**Comment by rodrigoaguilera** [comment]
Thanks
