### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by FatCatTuxedo** [TeamWin/Team-Win-Recovery-Project#1338]
Feature Request

Ability to get device ID without making a backup first

**Comment by CaptainThrowback** [comment]
Use adb?

**Comment by FatCatTuxedo** [comment]
> Use adb?

adb doesnt show the same device ID that TWRP does.

**Comment by CaptainThrowback** [comment]
It does on all of my devices, so that's curious.

**Comment by FatCatTuxedo** [comment]
> It does on all of my devices, so that's curious.

my device on adb always shows 0123456789ABCD

**Comment by Dees-Troy** [comment]
This feature already exists, you just have to know what to do to get it:
adb shell twrp get device_id
