### ISSUE TITLE
Timezone ASIA/Yakutsk

### ISSUE THREAD

**Issue by VecH** [TeamWin/Team-Win-Recovery-Project#134]
Correct timezone. I live in Yakutsk which is GMT+10, without daylight savings

**Comment by Dees-Troy** [comment]
You can select (UTC +10) Eastern Australia, Guam, uncheck the box for use daylight savings time, and select none for offset to get your timezone.

**Comment by VecH** [comment]
This should be changed in the source code
configured at myself I've already changed
