### ISSUE TITLE
twrp file download is not image

### ISSUE THREAD

**Issue by ghost** [TeamWin/Team-Win-Recovery-Project#1342]
just a website link issue afaik..

for moto g5 plus, downloading from official twrp site.. the image files (all versions) are supposed to be around 12 to 15 MB. but upon download it's just a 6 KB file...

did i miss something?

https://dl.twrp.me/potter/twrp-3.2.3-1-potter.img.html

**Comment by ghost** [comment]
so the 6 KB file is the html of the page itself.. so i suspected my Android "FOSS Browser" might be being weird.

used Chrome browser. no issue there. so i guess you can close this... or punt it to the FOSS people :)

**Comment by bigbiff** [comment]
Make sure your browser sets referrer.
