### ISSUE TITLE
Bad signatures on TeamWin GPG key

### ISSUE THREAD

**Issue by brainy** [TeamWin/Team-Win-Recovery-Project#1348]
- [ ] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [ ] I am running the latest version of TWRP
- [X] I have read the FAQ (https://twrp.me/FAQ/)
- [X] I have searched for my issue and it does not already exist

**Device codename**: flounder
**TWRP version**: 3.2.3-0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
`gpg --verify twrp-3.2.3-0-flounder.img.asc`

#### WHAT IS THE EXPECTED RESULT?
All key signatures should be valid, even if not trusted.

#### WHAT HAPPENS INSTEAD?
```
$ gpg --verify twrp-3.2.3-0-flounder.img.asc 
gpg: assuming signed data in 'twrp-3.2.3-0-flounder.img'
gpg: Signature made Tue  7 Aug 04:22:34 2018 CEST
gpg:                using RSA key 95707D42307C9D41D09BF7091D8597D7891A43DF
gpg: key 1D8597D7891A43DF: 43 signatures not checked due to missing keys
gpg: key 1D8597D7891A43DF: public key "TeamWin <admin@teamw.in>" imported
gpg: public key 51F13EED3B82E870 is 80739 seconds newer than the signature
gpg: bad key signature from key CD74E0D4A7483979: Wrong key usage (0x10, 0x0)
gpg: bad key signature from key 16F9CB0085E26E51: Wrong key usage (0x10, 0x0)
gpg: bad key signature from key 6BD4E9859AC6DDFF: Wrong key usage (0x10, 0x0)
gpg: bad key signature from key 77F2E8CD38754E54: Wrong key usage (0x10, 0x0)
gpg: bad key signature from key 9EF8F8135404158F: Wrong key usage (0x10, 0x0)
gpg: bad key signature from key 7110B0EA7C758598: Wrong key usage (0x10, 0x0)
gpg: bad key signature from key E5EDEFEC70C3F47C: Wrong key usage (0x10, 0x0)
gpg: key 1D8597D7891A43DF: no user ID for key signature packet of class 10
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   3  signed:   3  trust: 0-, 0q, 0n, 0m, 0f, 3u
gpg: depth: 1  valid:   3  signed:  20  trust: 0-, 0q, 0n, 0m, 3f, 0u
gpg: depth: 2  valid:  20  signed:  48  trust: 18-, 2q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2019-02-26
gpg: Total number processed: 1
gpg:               imported: 1
gpg: Good signature from "TeamWin <admin@teamw.in>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 9570 7D42 307C 9D41 D09B  F709 1D85 97D7 891A 43DF
```

**Comment by bigbiff** [comment]
Can you verify the md5 of the downloaded file?

**Comment by brainy** [comment]
Well, no, I can't _verify_ the MD5 hash because it's not published [here](https://eu.dl.twrp.me/flounder/), but I can calculate it, it's `1d11ce03609a7d94e4fbaef721bf9e2f`.

However: file corruption is not the problem, the signature from the TeamWin key is correct. The problem is that the signatures on the key itself are not valid. That does not affect the validity of the signatures made by that key, but it's annoying.

**Comment by bigbiff** [comment]
Please try redownloading the asc file. I am getting 

jenkins@build:/www/dl.twrp.me/flounder$ gpg --verify twrp-3.2.3-0-flounder.img.asc
gpg: assuming signed data in 'twrp-3.2.3-0-flounder.img'
gpg: Signature made Mon 06 Aug 2018 10:22:34 PM EDT
gpg:                using RSA key 95707D42307C9D41D09BF7091D8597D7891A43DF
gpg: Good signature from "TeamWin <admin@teamw.in>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 9570 7D42 307C 9D41 D09B  F709 1D85 97D7 891A 43DF
