### ISSUE TITLE
[HTC DESIRE C] TWRP 2.4.4.0 - 2.3.4.0 Cant Flash ROMS

### ISSUE THREAD

**Issue by nikhil16242** [TeamWin/Team-Win-Recovery-Project#135]
The recent version of TWRP seems to have the following issue. When  I try to flash a new rom having an aroma installer , after doing a full wipe the rom installation ends with a status 1 error. The earlier versions(TWRP 2.4.2.0 and before) seemed to work fine.

Heres the log : http://pastebin.com/v2UjZzis

**Comment by Dees-Troy** [comment]
Can you provide a link to the ROM zip itself?
ROM Name    : Nameless ROM
ROM Version : 7.2 Build 5

**Comment by nikhil16242** [comment]
Yeah sure . Heres the the rom thread http://forum.xda-developers.com/showthread.php?t=1812583
And the link : http://d-h.st/axO

**Comment by evanjd** [comment]
Same issue with me on evita.

Offending ROM: http://www.4sync.com/zip/_8CLQVVk/radavs-pablo11-TelstraJB-stock.html

Like the user above, reverting to 2.4.2.0 fixed the issue.

**Comment by Phiber2000** [comment]
Same issue on HTC Desire C and HTC Desire HD.

Affected TWRP versions: 2.4.3.0 to current 2.5.0.0.
Tested with AROMA installer v2.5

Reverting to 2.4.2.0 "fixed" the issue.
