### ISSUE TITLE
Stuck on TeamWin screen using fastboot

### ISSUE THREAD

**Issue by nilsbebelaar** [TeamWin/Team-Win-Recovery-Project#1353]
- [yes ] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [yes ] I am running the latest version of TWRP
- [yes ] I have read the FAQ (https://twrp.me/FAQ/)
- [yes ] I have searched for my issue and it does not already exist

**Device codename**: Pixel 2 XL (taimen)
**TWRP version**: twrp-3.2.3-1-taimen

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
When using `fastboot boot twrp-3.2.3-1-taimen.img` I get to the TeamWin load screen but then it just freezes. 

#### WHAT IS THE EXPECTED RESULT?
To boot into TWRP.

#### WHAT HAPPENS INSTEAD?
The startup freezes at the TeamWin screen

#### ADDITIONAL INFORMATION
This started happening today, while it was working fine until yesterday. ADB works cause I can still use `adb reboot` to restart, so that tells me the phone is not entirely frozen, right? 
I can still boot into the OS normally, the only thing I changed since yesterday for as far as I can remember is that I added my fingerprint. I read somewhere that this can cause issues so I removed both my fingerpint and my PIN, but it still freezes. 
The funny thing is that if I use `fastboot --set-active=b` while I'm in the bootloader, then `fastboot boot twrp-3.2.3-1-taimen.img` does in fact not freeze, but when I enter TWRP the decryption seems broken and using `twrp decrypt <passcode>` fails. So I guess there is something in slot a preventing TWRP from launching correctly, is there some way of clearing the cache or something? Although that shouldn't matter in the first place because I'm not running the internal recovery partition but using the `fastboot boot` command, so there should be no cache files left behind right?

Please correct me if I'm wrong, any help or ideas would be appreciated!

**Comment by nilsbebelaar** [comment]
Update:
Even after a factory reset of my phone it's not working, I didn't setup any fingerprint or PIN.
This was the last thing I could think of, any ideas how I could get into TWRP again?

**Comment by AuspiciumHacky** [comment]
> Atualização: 
> mesmo depois que uma redefinição de fábrica do meu telefone não está funcionando, não configurei nenhuma impressão digital ou PIN. 
> Esta foi a última coisa que eu pude pensar, alguma idéia de como eu poderia entrar no TWRP novamente?

Conseguiu resolver?

**Comment by nilsbebelaar** [comment]
I got it working by flashing my entire device, don't know what caused the problem but it's working every time now, even with PIN.
