### ISSUE TITLE
Can't find twrp of Samsung note8 Qualcomm

### ISSUE THREAD

**Issue by buyixjh** [TeamWin/Team-Win-Recovery-Project#1356]
On the device page, only find Samsung note 8(Exynos)  and Samsung note 8.0 (n5100)(Qualcomm), it is a pad, can not find Samsung note8   N9500(Qualcomm) OR N950U twrp.

**Comment by bigbiff** [comment]
Device requests are not a bug.

**Comment by buyixjh** [comment]
What does this mean? I did not understand

**Comment by CaptainThrowback** [comment]
It means your device isn't officially supported. So there is no issue.
