### ISSUE TITLE
md5sum check fails for twrp-3.2.3-1-mido.img

### ISSUE THREAD

**Issue by mrchen077** [TeamWin/Team-Win-Recovery-Project#1357]
#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
go to:
https://eu.dl.twrp.me/mido/twrp-3.2.3-1-mido.img.html
check md5sum on website:
https://eu.dl.twrp.me/mido/twrp-3.2.3-1-mido.img.md5 , currently:
d91fb97af4cd5b68365c4caf5153c1b6  twrp-3.2.3-1-mido.img

Download actual image:
https://eu.dl.twrp.me/mido/twrp-3.2.3-1-mido.img
check its md5sum:
md5sum twrp-3.2.3-1-mido.img 
874a02b4dc549bef617316ccc021a04c  twrp-3.2.3-1-mido.img

**Comment by alexalexson143** [comment]
Hi, same goes for https://dl.twrp.me/rolex/twrp-3.2.3-0-rolex.img.html

MD5 file `cat twrp-3.2.3-0-rolex.img.md5`
```
f0af4915164ec6afdfb3235f219d33ce  twrp-3.2.3-0-rolex.img
```

MD5SUM output `md5sum twrp-3.2.3-0-rolex.img`
```
3039ffb8b642eb27a2d97778a5bc717b  twrp-3.2.3-0-rolex.img
```

GPG verification using `wget -c https://dl.twrp.me/public.asc && gpg --import public.asc`
Output of `gpg --verify twrp-3.2.3-0-rolex.img.asc`
```
gpg: assuming signed data in 'twrp-3.2.3-0-rolex.img'
gpg: Signature made Tuesday, 07 August, 2018 11:08:48 AM PST
gpg:                using RSA key 95707D42307C9D41D09BF7091D8597D7891A43DF
gpg: BAD signature from "TeamWin <admin@teamw.in>" [unknown]
```

**Comment by bigbiff** [comment]
Everything looks ok:

jenkins@build:/www/dl.twrp.me/mido$ md5sum -c twrp-3.2.3-1-mido.img.md5
twrp-3.2.3-1-mido.img: OK
jenkins@build:/www/dl.twrp.me/mido$ sha256sum -c twrp-3.2.3-1-mido.img.sha256
twrp-3.2.3-1-mido.img: OK
jenkins@build:/www/dl.twrp.me/rolex$ md5sum -c twrp-3.2.3-0-rolex.img.md5
twrp-3.2.3-0-rolex.img: OK
gpg: assuming signed data in 'twrp-3.2.3-0-rolex.img'
gpg: Signature made Mon 06 Aug 2018 11:08:48 PM EDT
gpg:                using RSA key 95707D42307C9D41D09BF7091D8597D7891A43DF
gpg: Good signature from "TeamWin <admin@teamw.in>" [unknown]

Make sure your download worked.

**Comment by alexalexson143** [comment]
Hi, in my case, I used `wget -c https://dl.twrp.me/rolex/twrp-3.2.3-0-rolex.img` but it keeps downloading the webpage. I just clicked on the link instead and downloaded normally and it worked.
