### ISSUE TITLE
digest file not found for sha256 hash and only md5 checksum recognized

### ISSUE THREAD

**Issue by jmichael2497** [TeamWin/Team-Win-Recovery-Project#1358]
- [x] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**Device codename**: klte
**TWRP version**: 3.2.3.0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
install LOS15.1rom.zip with LOS15.1rom.zip.sha256 in same folder.

#### WHAT IS THE EXPECTED RESULT?
find and verify against digest, as currently happens with opengapps8.1nano.zip and opengapps8.1nano.zip.md5 in same folder.

#### WHAT HAPPENS INSTEAD?
digest file not found.

#### ADDITIONAL INFORMATION
i've reviewed the relevant code and at a glance it looks like the extension with wildcard search should accept sha256 files, so i'm not sure why it isn't working.

i'm using current Fx 63.0.3 to download the matching digest file from the LOS download site for my device, specifically https://download.lineageos.org/klte and giving it the .sha256 extension manually.

`/tmp/recovery.log`: 
`dmesg`: 

(i can try to grab this if really necessary, but should be pretty quick to verify likely on any device, otherwise curious to know on which device this works and under what circumstances)

anyway, hope that helps, thanks for a very useful tool (and template that made it easy to get useful data).

**Comment by NoNameForMee** [comment]
This issue looks to be related to the issue I reported almost a year ago (in what is described as the up-to date repository for TWRP): omnirom/android_bootable_recovery/issues/198 but non of the devs cared to have a look...

**Comment by CaptainThrowback** [comment]
The issues in the other repository are not monitored, as the TWRP team doesn't have control over them. All issues have to be reported here to be addressed (which is why it's this issues url that's linked in the TWRP thread OPs on XDA).

**Comment by NoNameForMee** [comment]
This is fixed as of TWRP 3.3.0-0 released the other day.
