### ISSUE TITLE
"set backup name" to keep default name/date

### ISSUE THREAD

**Issue by nedamdam** [TeamWin/Team-Win-Recovery-Project#136]
When creating a backup choosing the option set backup name the box is empty. Would be good to keep the default name there so we can use the default or date if we just want to add some word. We can delete the default name if not needed later. Or make the default name highlighted so it will delete on character press, but will stay when touching into the box.

**Comment by bigbiff** [comment]
Currently if you don't set a backupname it will use the data and time as a name. I am not sure how putting this in the text box would help.

**Comment by bigbiff** [comment]
Closed because of the reason in last comment.
