### ISSUE TITLE
Failure to install TWRP for Asus Max Pro M1 (codename X00TD)

### ISSUE THREAD

**Issue by ghost** [TeamWin/Team-Win-Recovery-Project#1369]
- [ ] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/) (No topic *seems to* cover it.)
- [x] I have searched for my issue and it does not already exist

**Device codename**: X00TD
**TWRP version**: twrp-3.2.2-1-20180727-X00TD.img

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?

I'm trying to install Lineage using the TWRP image available through this [thread](https://forum.xda-developers.com/asus-zenfone-max-pro-m1/development/recovery-twrp-3-2-1-x-t3787134) on XDA. In fact, I was oriented by it to come here if I had any problems. These are the specifications for my phone:

**Model**
ASUS_X00TDB

**Android Version**
8.1.0

**Kernel Version**
4.4.78-perf+ (gcc version 4.9.x 20150123 (prerelease) (GCC))
queen@4ef93ead2d92 #1
Fri Oct 19 15:22:14 CST 2018

**Version Number**
OPM1.WW_Phone-15.2016.1810.334-20181019

I was able to unlock the bootloader using the official ASUS apk as described in Lineage's [installation instructions](https://wiki.lineageos.org/devices/X00TD/install), still I was unable to flash the recovery image:

```
> sudo fastboot devices                                                 16:36:13
[sudo] password for user:                                                       
C4ATAS000000VLW fastboot                                                        
> sudo fastboot flash recovery twrp-3.2.2-1-20180727-X00TD.img          16:36:28
target didn't report max-download-size                                          
sending 'recovery' (58328 KB)...                                                
FAILED (remote: Requested download size is more than max allowed                
)                                                                               
finished. total time: 0.001s                                                    
> sudo fastboot flash recovery twrp-3.2.2-1-20180727-X00TD.img          16:37:45
target reported max download size of 536870912 bytes                            
sending 'recovery' (58328 KB)...                                                
FAILED (remote: unknown command)                                                
finished. total time: 0.001s
```

This attempt was made using the [SDK platform tools v28.0.1](https://developer.android.com/studio/releases/platform-tools) for Linux.

I then attempted to unlock the bootloader again, by following [these instructions](https://www.youtube.com/watch?v=HilHjKo_gMo) for Windows, but the results were the same.

#### WHAT IS THE EXPECTED RESULT?
To have TWRP, and eventually Lineage, installed.

#### WHAT HAPPENS INSTEAD?
The error messages described previously are shown, and nothing happens.

**Comment by ghost** [comment]
I experienced the exact same problem. Here's how I fixed it:

1. Get the unlock.rar from XDA.
2. Boot into a Windows system (sorry, I couldn't get it to work on Linux).
3. After connecting the phone, from it's device manager entry under Windows, select update driver and go for "select files from disk".
4. Select the *.inf file in the driver folder from the unlock.rar
5. Unlock the bootloader using the official app (did not test the unlock.rar scripts, so try that if you don't want to share your IMEI with Asus).
6. Get the latest platform-tools for Windows and flash the twrp build at XDA using fastboot.

**Comment by ghost** [comment]
Things which I've tried/noticed:
1. Under Linux, the fastboot commands are often returned by "Unknown command" or a freeze on the phone end.
2. The 'fastboot oem get_random_partition' command in the unlock.rar actually works if you try it 3 or 4 times under Linux (mostly returns "unknown command" error). 
3. I guess the faulty connection under linux prevents any sort of flashing from completing successfully (mostly freezes up the fastboot program and makes the device unresponsive).
4. I've tried changing cables, applying Android specific udev rules, updating platform-tools. All of this yielded the afore-mentioned errors under Linux.
5. Initially, under Windows, I received the "download size is more than max allowed" error. Updating the platform-tools (NOT minimal-ADB) and installing the device drivers from unlock.rar did the trick. After that, the fastboot commands worked as expected.

**Comment by ghost** [comment]
This seems to be a Linux related problem. Using Windows for flashing is currently the solution.

P.S. please close this issue as this is not a  TWRP related problem.

**Comment by bigbiff** [comment]
Thanks for the detailed write up.
