### ISSUE TITLE
Samsung crypto 0xD0B5B1C5

### ISSUE THREAD

**Issue by berndfuhrmann** [TeamWin/Team-Win-Recovery-Project#1375]
- [ yes] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [ yes ] I am running the latest version of TWRP
- [ yes ] I have read the FAQ (https://twrp.me/FAQ/)
- [ yes ] I have searched for my issue and it does not already exist

**SM-G930F**: 
**3.2.3-0**: 

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Encrypt phone, Allow OEM modifications
Use ODIN to flash TWRP onto it
Boot TWRP

#### WHAT IS THE EXPECTED RESULT?
The device should still be able to boot up it's normally and be usable.
I'd expect TWRP to mount /data

#### WHAT HAPPENS INSTEAD?
The device is stuck in a boot loop. I cannot use it.
Furthermore, I cannot access my data.
Error messages in TWRP:
```
Coult not mount /data and unable to find crypto footer.
Failed to mount '/data' (Invalid agument)
Unable to create /data/media folder.
Updating partition details...
Failed to mount '/data' (Invalid argument)
...done
Unable to mount storage
Failed to mount '/data' (Invalid argument)
Full SELinux support is present.
Unable to mount /data/media/TWRP/.twrps
MTP Enabled
```

#### ADDITIONAL INFORMATION

I had a look at the data partition /dev/block/sda18. The last 16384 bytes seem to be the crypto footer that TWRP cannot find. The reason it cannot find it is this:
[crypto.h](https://github.com/TeamWin/Team-Win-Recovery-Project/blob/android-9.0/crypto/lollipop/cryptfs.h) says:
#define CRYPT_MNT_MAGIC 0xD0B5B1C4

However, in my crypto footer it says 0xD0B5B1C5

So the magic number is a different one. When you search for that number in github, you'll find many old projects (e.g. [this](https://github.com/tuxafgmur/DhollmenK_bootable/blob/master/recovery/crypto/ics/cryptfs.h)) that had support for a thing called Samsung crypto. I don't know how and why it removed. Besides, the algo used in the devices crypto footer is: aes-xts-fmp

It would be very helpful and much less dangerous if:
You could warn people from using TWRP on encrypted Samsung phones, since their crypto seems unsupported.
Support Samsung crypto.
Also, more verbose error messages, e.g. in the twrp command line utility would be nice.

**Comment by CaptainThrowback** [comment]
https://twrp.me/faq/encryptionsupport.html

**Comment by berndfuhrmann** [comment]
Thanks for the pointer to the FAQ. I missed it, sorry. However, there doesn't seem to be a way to know if a specific (Samsung) devices encryption is supported. Maybe some information could be included, in the devices specific section via Markdown.
Then there is still this issue with the boot loop. It is possible that I somehow tripped dm-verity. I never swiped to enable write access, but maybe I triggered it via adb shell. If there is any way to know if a boot loop was triggered because of this, it would also be helpful in the docs.
I guess this bug can be closed. Thanks for your good work!
