### ISSUE TITLE
TWRP

### ISSUE THREAD

**Issue by linlin1980** [TeamWin/Team-Win-Recovery-Project#138]
2.4.2.0 Requires a password,but l didnot set a password
![122](https://f.cloud.github.com/assets/3862318/257995/6320f87c-8c82-11e2-9160-daf05e463797.JPG)

**Comment by linlin1980** [comment]
我的设备是ASUS TF300T 从来没在TWRP设定过密码，一开机就进入TWRP，并且需要密码，求助~！SOS
!我的邮箱是woshilinlin1980@gmail.com
![122](https://f.cloud.github.com/assets/3862318/258125/b6d32ec0-8c89-11e2-82b7-d6e922ed4ac3.JPG)

**Comment by Dees-Troy** [comment]
For the 4.2 bootloader on TF300, you need to use this build of TWRP:
http://techerrata.com/file/twrp2/tf300t/openrecovery-twrp-2.4.4.0-tf300t-4.2.blob
The external sdcard may not work with this build, but we can't fix that until Asus drops kernel source for their latest kernel.

**Comment by linlin1980** [comment]
But my computer can not enter fastboot mode, how to install?TWRP has my machine lockup

**Comment by linlin1980** [comment]
TWRPmy machinehasbeenlocked,Ican notbrushinto

**Comment by linlin1980** [comment]
I need a password! Thank you!

**Comment by linlin1980** [comment]
I needa password!Thank you!
