### ISSUE TITLE
Fairphone 2: No USB connection with TWRP

### ISSUE THREAD

**Issue by CPUFronz** [TeamWin/Team-Win-Recovery-Project#1380]
- [x] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**Device codename**: fp2
**TWRP version**: 3.2.3

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
* Downloading TWRP 3.2.3.0 for Fairphone 2 (FP2) from https://dl.twrp.me/FP2/twrp-3.2.3-0-FP2.img.html 
* Connect FP2  to my computer (running Ubuntu 18.04) via USB
* Install TWRP (`adb reboot bootloader` followed by `fastboot flash recovery twrp-3.2.2-0-FP2.img`)
* Reboot FP2 (`fastboot reboot`)
* Waiting until FP2 booted and boot into recovery (`adb reboot recovery`)

#### WHAT IS THE EXPECTED RESULT?
Being able to access FP2 from my computer when booting into TWRP, e.g. when using `adb devices` FP2 should be listed.

#### WHAT HAPPENS INSTEAD?
FP2 is not accessible from my computer when booting into TWRP, e.g. `adb devices` returns nothing.

#### ADDITIONAL INFORMATION
It looks like USB is deactivated for TWRP, when I connect FP2 running the operating system `lsusb` gives the following output:
```
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 04f2:b5a7 Chicony Electronics Co., Ltd 
Bus 001 Device 004: ID 8087:0aa7 Intel Corp. 
Bus 001 Device 042: ID 05c6:901d Qualcomm, Inc. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
When FP2 is running TWRP, it gives the following output instead:
```
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 04f2:b5a7 Chicony Electronics Co., Ltd 
Bus 001 Device 004: ID 8087:0aa7 Intel Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

On an unrelated note: even though I installed TWRP 3.2.3-0, TWRP always shows that it is version 3.1.1-0.

**Comment by z3ntu** [comment]
Then you didn't install TWRP correctly..? TWRP 3.2.3-0 shows that it's TWRP 3.2.3-0

**Comment by CPUFronz** [comment]
Yes, that was the problem. I tried to install it again and it worked. I think my mistake was to not unplug FP2 when rebooting after flashing. Now it correctly shows version 3.2.3-0 of TWRP and is able to communicate with adb via USB.
