### ISSUE TITLE
rotate twrp

### ISSUE THREAD

**Issue by hakimarx** [TeamWin/Team-Win-Recovery-Project#1382]
my device mako, nexus 4.
my touchscreen is half broken.
i cannot flash anything with my twrp, because the slide bottom to execute flash is not work.
how to rotate twrp?

**Comment by teppyboy** [comment]
wait 4 upd8 by dev

EDIT: why using a half broken screen device lol

**Comment by CaptainThrowback** [comment]
Use adb sideload to install. You'll have to issue the command "twrp sideload" from adb shell, but then you can open a second adb prompt and use adb sideload to install a zip from PC. You can also use the TWRP CLI to install files that are already on the device.

EDIT: You can find the TWRP CLI guide [here](https://twrp.me/faq/openrecoveryscript.html).

**Comment by TheRadioGuy** [comment]
Alright, I can't swipe in TWRP 'cause bottom of my screen is broken, How can I enable sideload from TWRP?

**Comment by ghost** [comment]
I was have thsame prblem hen i removed twrp and installeed phliz touch recovery which supports touch and volume keys

**Comment by bigbiff** [comment]
This is not a general TWRP bug so closing,
