### ISSUE TITLE
Twrp FAQ decrypt pattern note no 6x6 pattern

### ISSUE THREAD

**Issue by kokutoukiritsugu** [TeamWin/Team-Win-Recovery-Project#1388]
https://twrp.me/faq/openrecoveryscript.html
only 3x3 4x4 5x5 , no 6x6

I have to made this, and I test it works on my phone.

add to FAQ ?

1 | 2 | 3 | 4 | 5 | 6
-- | -- | -- | -- | -- | --
7 | 8 | 9 | : | ; | <
= | > | ? | @ | A | B
C | D | E | F | G | H
I | J | K | L | M | N
O | P | Q | R | S | T

**Comment by bigbiff** [comment]
What phone do you have? Can you update the markdown on gerrit.twrp.me and submit a review for the twrpme project? This isn't really a bug btw.
