### ISSUE TITLE
Not able to decrypt folders of second profile (work profile)

### ISSUE THREAD

**Issue by DrFunx** [TeamWin/Team-Win-Recovery-Project#1389]
- [x] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**Device codename**: Chiron
**TWRP version**: 3.2.3-0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
- Have a ROM with encryption enabled
- Enable a second user profile in the ROM (I used the Island app which creates a work profile for app cloning)
- Reboot to recovery
- Enter pin of the primary profile
- All folders will be decrypted except for the second profile folders. Because of this, I am unable to make a backup.

#### WHAT IS THE EXPECTED RESULT?
- An option to decrypt the folders of a second user profile OR an option to backup/restore encrypted data

#### WHAT HAPPENS INSTEAD?
- Making a backup will fail with an error because of the encrypted folders.

**Comment by CaptainThrowback** [comment]
Think this is a duplicate of this one: https://github.com/TeamWin/Team-Win-Recovery-Project/issues/1373

**Comment by DrFunx** [comment]
> Think this is a duplicate of this one: #1373

Correct. Will close this issue.
