### ISSUE TITLE
[Nexus 7] TWRP 2.4.4.0 erroneous md5 validation failure

### ISSUE THREAD

**Issue by landstander668** [TeamWin/Team-Win-Recovery-Project#139]
When performing a backup/recovery test, TWRP seems to consistently report an apparently bogus md5sum verification failure during the recovery portion.  Both the backup and recovery were performed using version 2.4.4.0.  The sequence of events was:

1) Boot into recovery, and perform a backup using a non-default name.
2) Reboot recovery (probably not required, but keeps the logs distinct)
3) Attempt to restore the backup with the "Enable MD5 verification" option enabled

If I attempt to manually verify the md5sums (via adb while still in recovery), however, everything seems to check out properly.

/data/media/0/TWRP/BACKUPS/015d25787d50141b/tsunami-CM10.1.0nightly-20130314 # md5sum -c *.md5
boot.emmc.win: OK
cache.ext4.win: OK
data.ext4.win000: OK
data.ext4.win001: OK
system.ext4.win: OK

I'll post recovery.log for both the backup and restore portions later today.

**Comment by landstander668** [comment]
For what it's worth, TWRP 2.3.3.0 doesn't complain when restoring the same backup with MD5 verification enabled.

**Comment by t18matt** [comment]
i'll have to check, i thought i turned off MD5 verification on mine. unless it's only for flashing a rom, not restoring nandroids.

**Comment by landstander668** [comment]
All of my logs for this issue should now be available at https://www.dropbox.com/s/wh82w1a8efh6z13/TWRP_issue139_logs.zip.  It contains the following items, all of which come from version 2.4.4.0 unless otherwise noted:
- recovery-backup.log -- recovery.log from the backup location
- recovery.log from the backup location -- recovery.log from the original restore attempt
- recovery-restore-md5error-2.4.4.0test.log -- recovery log from restore attempt using the TWRP 2.4.4.0test image posted on issue #140

**Comment by bigbiff** [comment]
Are you able to flash img files? If so please flash http://techerrata.com/bigbiff/grouper.img and paste recovery.log after a backup and restore.

**Comment by landstander668** [comment]
Sure, running it now.  Will provide backup and restore logs later tonight.

**Comment by landstander668** [comment]
OK, the backup and restore logs from the image you provided are at https://www.dropbox.com/s/gtlvib53d666yef/TWRP_issue139_logs-bigbiff.zip.  I didn't do a full restore... just until it aborted with the bogus MD5 verification error.

Since you asked for a directory listing in issue #141, which sounds like the same problem, here's what my backup location looks like:

```
/data/media/0/TWRP/BACKUPS/015d25787d50141b/test-bigbiff # ls -l
-rw-rw-rw-    1 root     root       8388608 Mar 15 23:17 boot.emmc.win
-rw-rw-rw-    1 root     root            48 Mar 15 23:17 boot.emmc.win.md5
-rw-rw-rw-    1 root     root      26861310 Mar 15 23:17 cache.ext4.win
-rw-rw-rw-    1 root     root            49 Mar 15 23:17 cache.ext4.win.md5
-rw-rw-rw-    1 root     root     1165437697 Mar 15 23:13 data.ext4.win000
-rw-rw-rw-    1 root     root            51 Mar 15 23:17 data.ext4.win000.md5
-rw-rw-rw-    1 root     root           140 Mar 15 23:13 data.ext4.win001
-rw-rw-rw-    1 root     root            51 Mar 15 23:17 data.ext4.win001.md5
-rw-rw-rw-    1 root     root      76231457 Mar 15 23:14 data.ext4.win002
-rw-rw-rw-    1 root     root            51 Mar 15 23:17 data.ext4.win002.md5
-rw-r--r--    1 root     root        359074 Mar 15 23:17 recovery.log
-rw-rw-rw-    1 root     root     226129550 Mar 15 23:04 system.ext4.win
-rw-rw-rw-    1 root     root            50 Mar 15 23:04 system.ext4.win.md5
```

It seems odd, however, that _data.ext4.win001_ is such a small size.  None of the other backups I've made (including the one where I originally noticed this issue) have more than 2 pieces, all of which have always been _much_ larger.  I have no idea if this is relevant, however.

Finally, here's the results of manual MD5 verification:

```
/data/media/0/TWRP/BACKUPS/015d25787d50141b/test-bigbiff # md5sum -c *.md5
boot.emmc.win: OK
cache.ext4.win: OK
data.ext4.win000: OK
data.ext4.win001: OK
data.ext4.win002: OK
system.ext4.win: OK
```

**Comment by bigbiff** [comment]
Thanks for your help. It looks like the md5s are generated right but they are not being read correctly from the files. I will look into the issue.

**Comment by bigbiff** [comment]
Can you try this build: http://techerrata.com/bigbiff/grouper-md5fix.img to restore your old backups?

**Comment by landstander668** [comment]
Yes, that one was able to successfully perform MD5 validation and restore the backup. :)

**Comment by Dees-Troy** [comment]
Merged fix: http://review.teamw.in/#/c/537/
