### ISSUE TITLE
Device name changed after installing TWRP

### ISSUE THREAD

**Issue by effek70** [TeamWin/Team-Win-Recovery-Project#1391]
I am running and downloaded from https://drive.google.com/drive/folde...GRSNDRvcWhPOGs

Device - Blu Grand Max (G110)
TWRP version 3.0.0.0

After installing using SP Flash Tool, I go to the advance option & go to emulator and typing the getprop. 
that's the inside. 
My device name now is Moto G 2013, and the bootloader is unknown. 

Can you help me?

![screenshot_2019-01-30-22-10-25](https://user-images.githubusercontent.com/47221064/52186571-1c1c4980-2863-11e9-8bb3-9216e98c5d3c.png)
![inkedscreenshot_2019-01-30-22-10-38_li](https://user-images.githubusercontent.com/47221064/52186575-20e0fd80-2863-11e9-9611-3f9a4f6bbc73.jpg)
![screenshot_2019-01-30-22-10-50](https://user-images.githubusercontent.com/47221064/52186580-276f7500-2863-11e9-9ebe-f79ddc6036f8.png)
![screenshot_2019-01-30-22-11-06](https://user-images.githubusercontent.com/47221064/52186581-29393880-2863-11e9-9d82-d28477542187.png)

**Comment by bigbiff** [comment]
Is this a build from twrp.me?

**Comment by effek70** [comment]
no sir, I downloaded it from this site. https://forum.xda-developers.com/android/development/blu-grand-max-g110q-twrp-t3716436

**Comment by effek70** [comment]
when I flashing magisk there is a red letter words.....
![screenshot_2018-11-14-03-53-10](https://user-images.githubusercontent.com/47221064/52187092-66eb9080-2866-11e9-9743-83edece2b518.png)

**Comment by bigbiff** [comment]
Sorry this is an unsupported build.

**Comment by effek70** [comment]
Is there a supported build for this device?

**Comment by bigbiff** [comment]
Sorry we don't support this device.
