### ISSUE TITLE
Xiaomi Redmi Note 6 Pro

### ISSUE THREAD

**Issue by xxxsadistxxx** [TeamWin/Team-Win-Recovery-Project#1394]
Hello. Do you plan to support Xiaomi Redmi Note 6 Pro? Maybe you need testers? The whole topic on the phone, on the forum (4 pda) is ready to become test assistants. They are waiting for the release of the official version of twrp.

**Comment by xxxsadistxxx** [comment]
Source code https://github.com/MiCode/Xiaomi_Kernel_OpenSource/commit/efbbb9cce47475c49f28d227b2a52eca6f0d02a7

**Comment by bigbiff** [comment]
Device requests are not a bug or issue.
