### ISSUE TITLE
extractTarFork() restore error left pixel 3 scrambled

### ISSUE THREAD

**Issue by srothkin** [TeamWin/Team-Win-Recovery-Project#1395]
- [ y] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [ y] I am running the latest version of TWRP
- [ y] I have read the FAQ (https://twrp.me/FAQ/)
- [ y] I have searched for my issue and it does not already exist

**Device codename**: Blueline
**TWRP version**: 3.2.3-0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Backup boot, data, system image, vendor image.
Reboot
Restore same
Reboot
Answer Yes when prompted to install TWRP app (probably not necessary - suspect system was already screwed at this point)

#### WHAT IS THE EXPECTED RESULT?
Boots back into Android with restored data

#### WHAT HAPPENS INSTEAD?
Only boots to recovery now (doesn't boot to android)
Doesn't prompt for unlock pin when TWRP starts
/sdcard/0 shows a bunch of nonsense filenames (I suspect this is because it is not able to decrypt them since it never prompted me for the PIN).

#### ADDITIONAL INFORMATION
Attached recovery.log from when I backed up (I don't have access to the restore recovery.log at the moment because of the above problems).

Not sure how much of this is relevant but the Pixel is running Android PQ1A.181205.006, Dec 2018 rooted with Magisk v17.3. I wanted to update to the February build so I did a fresh backup in TWRP rebooted and then copied it over to my PC.
Then I went to Magisk Manager to follow instructions for getting OTA update but it said there was a Magisk Manager Update and then was stuck in a state saying Magisk Manager doesn't support Magisk less than v18.0. So I rebooted to TWRP recovery to restore the just created backup - this is when the problems started. I tried restoring twice and each time it gave me the same failure.

At that point I tried to reboot figuring it probably didn't restore but didn't overwrite the data that it couldn't open from the backup. That's when I found I could no longer get into Android or access my sdcard files.

`/tmp/recovery.log`: 
`dmesg`:

**Comment by bigbiff** [comment]
We will need logs for debugging.

**Comment by srothkin** [comment]
Unfortunately the debug logs from the restore were on the encrypted internal SD card (with the rest of the my encrypted data) and could not be read in TWRP since it was no longer prompting for the unlock PIN on boot into recovery. So all I have for you is the backup log that I attached. Note that I made the backup less than an hour before I tried to restore it.

I do also have the full backup (I saved it to my laptop before I tried the upgrade and then restore) if that would be of any use. It is 9GB

I ended up flashing the latest Android stock image (Feb 2019 patch level) which had the side effect of resetting me to factory so I then had to re-setup everything.

**Comment by srothkin** [comment]
Going forward, I'd like to know what is the best approach to taking backups with TWRP that I can rely in if I need to restore.

What I had been doing (based on the TWRP FAQ) was backing up system image, vendor image, data, boot with compression enabled.

I found an XDA post from late last year that suggests I should backing system and vendor (NOT image) - is that true?

Also, I found a post from 2017 (from another device that had the same restore error) that suggested the compression (or decompression) has a bug and that I should not compress. Is that true?

Is it necessary to wipe any of the partitions before restoring (in the past on the Nexus 6 and 5x it wasn't)? And is it possible to wipe without losing the sdcard data where the restore is to be done from?

Note that it isn't really practical for me to test to determine which of the above possibilities is the correct way to get a restorable image (one that can successfully restore to my current phone or to a replacement Pixel 3) because this is my regular/only phone and the failure cases leave it unusable until I factory reset and go through setting it all up again. That's why I'm asking for an expert declaration of what combination is known to work.

FWIW, I've been using TWRP for years across a number of phones and have restored a number of times without issue. This is the first time there has ever been a problem and it's seriously shaking my faith in TWRP.

**Comment by CaptainThrowback** [comment]
For any device running a current version of Android where dm-verity is enabled, you should always backup using the "Image" options if you've left system read-only, to allow future OTAs to be installed. If you have dm-verity disabled or you're running a custom ROM, the non-Image options are fine.

Both compression and encryption seem to have some issues, so the safest bet is to not use either of those options when creating a backup. The compression option was from a time when devices had very little storage space, so saving it was a necessity to have room to store multiple backups. That's really not much of an issue with the amount of storage on today's devices. So leaving those options disabled shouldn't be a big deal.

The partitions that are being restored will automatically be wiped prior to restoring, so wiping them beforehand is redundant. Internal Storage will never be deleted when doing a restore in official, unmodified TWRP.
