### ISSUE TITLE
How Can We Use TWRP Keyboard In System?

### ISSUE THREAD

**Issue by r00t34** [TeamWin/Team-Win-Recovery-Project#1396]
Hi Guys,

As you know TWRP keyboard has Ctrl, Tab, Arrow and many keys. This is perfect while using in Terminal. I am looking for a way to use this awesome keyboard in system, not recovery.

Is there any way to extract this keyboard from the app or something else.

Can you share your ideas?

Thanks.

**Comment by bigbiff** [comment]
This is not an issue. Closing.

**Comment by r00t34** [comment]
:)
