### ISSUE TITLE
[3.2.3-2][beryllium] Battery problems

### ISSUE THREAD

**Issue by derKief** [TeamWin/Team-Win-Recovery-Project#1397]
- [x ] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [ x] I am running the latest version of TWRP
- [x ] I have read the FAQ (https://twrp.me/FAQ/)
- [x ] I have searched for my issue and it does not already exist

**Device codename**: beryllium
**TWRP version**: 3.2.3-2

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
reboot to recovery

#### WHAT IS THE EXPECTED RESULT?
battery level should be downgraded max. 1%

#### WHAT HAPPENS INSTEAD?
every reboot to recovery downgrades battery level by 5-10% 

#### ADDITIONAL INFORMATION
a simple reboot to recovery shouldnt be downgrade the battery level by multiple percentage.
This is just a reboot to recovery and nothing done in recovery.
When device is rebooting to ROM there is not just a big difference in battery level ....

**Comment by derKief** [comment]
is there any solution or workaround to prevent battery drop ?

**Comment by CaptainThrowback** [comment]
This is not a TWRP issue. TWRP doesn't control how much battery your device uses to boot into recovery. The TWRP code just handles actions when you're booted to recovery. Please close.

**Comment by derKief** [comment]
I do not agree...
There are other custom recoveries (also TWRP variants) for the Poco which doesn't have that issue !
So please do not close this bug report and try to fix that issue.
Thanks.

**Comment by CaptainThrowback** [comment]
This isn't a TWRP upstream issue. If you're saying it's a device-specific issue, then you should open an issue in the device tree and close this one. It does not belong here.

**Comment by derKief** [comment]
outdated
