### ISSUE TITLE
Some backup files are corrupted as tar files

### ISSUE THREAD

**Issue by equaeghe** [TeamWin/Team-Win-Recovery-Project#1399]
- [x] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**Device codename**: serranodsdd
**TWRP version**: 3.2.3-0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
1. create backup of all partitions in TWRP
2. try to view backup content using tar

#### WHAT IS THE EXPECTED RESULT?
This works for all backup files

#### WHAT HAPPENS INSTEAD?
This does not work for `boot.emmc.win`, `firmware.emmc.win`, and `recovery.emmc.win` files.

#### ADDITIONAL INFORMATION
* I looked at all three of my backups. They all had the same problem.
* The sha2 hash validates for the problematic files
* I have successfully used a backup to restore my phone to a previous version, but perhaps those partitions weren't restored (because they weren't changed?)
* There is another person hitting the same issue: https://stosb.com/blog/recovering-data-from-a-corrupt-tar-archive/. It is not clear whether he reported it.
* I can provide one of the corrupted files on request.

`/tmp/recovery.log`: (https://paste.omnirom.org/ fails on link creation; please provide alternative instructions)
`dmesg`: (I do not know how to get this)

**Comment by CaptainThrowback** [comment]
Emmc partitions are not backed up as tar files. They are raw image backups. Look into Android Image Kitchen for extracting boot and recovery image files. If the firmware partition is an ext4 image, then you can find a tool to mount or extract it. This is not an issue.

**Comment by equaeghe** [comment]
Ok, I see. Thanks to https://unix.stackexchange.com/questions/32008/how-to-mount-an-image-file-without-root-permission, I learned that

```
$ udisksctl loop-setup -r -f firmware.emmc.win
Mapped file firmware.emmc.win as /dev/loop0.
$ udisksctl mount -b /dev/loop0
Mounted /dev/loop0 at /run/media/equaeghe/00BC-614E.
```

would give me access. The material there is in a format that I do not recognize (file extensions `bxy`—with `x` and `y` digits—, `fli`, and `mdt`), but that is a separate issue.
