### ISSUE TITLE
TWRP on Verizon SG S3 time and date

### ISSUE THREAD

**Issue by jnehama** [TeamWin/Team-Win-Recovery-Project#14]
I have a rooted Verizon SG S3 working perfectly. Installed TWRP via GOO manager app without difficulty. It appears to be backing up normally, but it shows the wrong date and time on start up: Wed Jan 7 15:21:55 EST 1970. Time continues from there. Is there a way to reset it or is it unneccessary and does not affect the function. It seems to work beautifully though I wont be sure until I need to restore the back up but so far so good. Thanks

**Comment by Dees-Troy** [comment]
The date/time issue is specific to the Galaxy S3 devices and exists in other recoveries as well.  It might be fixable, but I don't have a Galaxy S3 device myself to work on, so at this time I have no plans to fix it. Sorry.
