### ISSUE TITLE
[Nexus 7] TWRP 2.4.4.0 bad permissions in /data/data after restore

### ISSUE THREAD

**Issue by landstander668** [TeamWin/Team-Win-Recovery-Project#140]
Immediately after restoring a backup taken with 2.4.4.0, ownership of all directories under /data/data are root:root with permissions of drwxrwxrwx.  Items underneath these subdirectories do appear to have the correct ownership and permissions, however.

If I reboot normally at this point, the ROM (a CyanogenMod 10.1 nightly build, in my case) comes up with all of the expected apps installed but most/all of them are unable to access data.  It's essentially like a fresh installation, except for all of the additional launcher items.  Rebooting into recovery shows a number of items underneath the /data/data/\* directories, which were present immediately after the restore, are now missing.

If I repeat the restore operation, followed immediately by running Fix Permissions (before rebooting), then everything comes up normally when the ROM is booted.

I'll post recovery.log for both the backup and restore portions later today.

Note: I tested using the same backup referenced under issue #139, which was restored with MD5 validation disabled.  I'm virtually certain there's no relation between the 2 issues, however, because I previously encountered this one under 2.4.3.0 (which didn't share the other problem) as well.  It wasn't reported it at the time, because 2.4.4.0 was released roughly one hour afterward.

**Comment by Dees-Troy** [comment]
Looking forward to getting logs of this issue.

**Comment by Dees-Troy** [comment]
There should be a recovery.log in the backup folder from when you made the initial backup if you made the backup with 2.4.1.0 or newer. Please post that as well. Also, try restoring with a 2.3 version of TWRP and let us know if that restore is correct (this will tell us if the problem exists during backup creation or restore, which narrows things down).

**Comment by landstander668** [comment]
Permissions under /data/data look exactly the same following a restore via 2.3.3.0, with identical symptoms once the ROM boots.

**Comment by Dees-Troy** [comment]
When you get a chance, try restoring with this build of TWRP (it has some improved restore logging):
http://techerrata.com/dees_troy/grouper.img
Also would like the recovery.log from the /sdcard/TWRP/BACKUPS/(serial number)/backupname/recovery.log location if it exists.

**Comment by Mike-Ferretti** [comment]
Dees_Troy, could this be the issue I am also experiencing on my D2SPR in issue #128 ? His symptoms seem similar to mine as far as losing app data is concerned. I have tried every 2.3 version of TWRP and every version from 2.4. Same problems as him.

**Comment by landstander668** [comment]
OK, all of the requested logs should now be available from https://www.dropbox.com/s/4fj77ushhsoviza/TWRP_issue140_logs.zip.  It contains the following items, all of which come from version 2.4.4.0 unless otherwise noted:
- recovery-backup.log -- recovery.log from the backup location
- recovery-restore.log -- recovery.log from the original restore
- recovery-restore-2.3.3.0.log -- recovery log from restore using version 2.3.3.0
- recovery-restore-2.4.4.0test.log -- recovery.log from restore using the grouper.img test version you posted above
- post-restore_permissions.txt -- "ls -l" output from /data/data, showing permissions immediately following the restore and also after running Fix Permissions

Please let me know if you need any additional information... I'll be happy to assist if I'm able.

**Comment by Dees-Troy** [comment]
Unfortunately this problem exists at the backup level, so existing backups will still exhibit this issue when restored. Of course it helps that fix permissions works around the issue. This issue also only affects backups that were split into multiple archives.
I created a new test image (same link new file):
http://techerrata.com/dees_troy/grouper.img
It has this patch applied:
http://review.teamw.in/#/c/536/
Specifically in the new twrpTar.cpp file at lines 350 to 351 it has some code that ensure that the initial or root directory that we called tarDirs with will get included in the tar file so that we capture its permissions. I also cleaned up a few other things while I was at it.
I was able to reproduce the issue and this appears to fix it, however you're welcome to make a new backup with this version and restore if you would like to verify the fix.

**Comment by landstander668** [comment]
I made a fresh backup (multiple data archive parts) using the 2.4.4.0test2 image you posted above, and was able to restore it successfully.  Everything looks good after booting up normally... there doesn't appear to be any trace of this issue. :)

**Comment by Dees-Troy** [comment]
http://review.teamw.in/#/c/536/ is merged.
