### ISSUE TITLE
athene images give wrong signature and hash sums

### ISSUE THREAD

**Issue by aetherfaerber** [TeamWin/Team-Win-Recovery-Project#1403]
Hi,

(I know this is a legacy device, but offering corrupted images seems worse than not offering any at all.)

I downloaded all image files, signatures and hash sums available at https://dl.twrp.me/athene/ .
The hash sums do not match the ones I'm getting for the image files AND signatures do not match the key from https://dl.twrp.me/public.asc .

I found an alternative download of the oldest version at https://devfiles.co/download/iqUkKrFK/twrp-3.0.2-0-athene.img . For this file, the signatures and hash sums do match. So I don't assume any error at my end but therefor must assume that either the athene image files or all of the hash sums and the main signature key have been tinkered with. The former seems more likely as I can also successfully verify the signatures of other image files I tested.

Please remove the manipulated image files downloads to prevent any harm and, if possible, reupload the correct ones.

Steps to reproduce:
- wget files from https://dl.twrp.me/athene/twrp-3.2.1-0-athene.img.html https://dl.twrp.me/athene/twrp-3.1.1-0-athene.img.html https://dl.twrp.me/athene/twrp-3.1.0-0-athene.img.html or https://dl.twrp.me/athene/twrp-3.0.2-0-athene.img.html
- check signature and hash sums

Thanks a lot for bringing a free and awesome recovery to our phones!

**Comment by bigbiff** [comment]
If you don't set referrer it will download the html page.

**Comment by aetherfaerber** [comment]
Hi bigbiff,

oops, you're perfectly right. Thanks for the fast reply and once again huge thanks for the project!
