### ISSUE TITLE
Feature Request: Support for NFTS

### ISSUE THREAD

**Issue by Mattwmaster58** [TeamWin/Team-Win-Recovery-Project#1404]
- [X] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [X] I am running the latest version of TWRP
- [X] I have read the FAQ (https://twrp.me/FAQ/)
- [X] I have searched for my issue and it does not already exist

Basically the title. I realize it's a niche use, as not many backup to a USB OTG device and fewer still backup to a USB OTG device that's formatted to NFTS, but I was wondering how difficult this would be to implement.

**Comment by CaptainThrowback** [comment]
[Already supported](https://github.com/omnirom/android_bootable_recovery/commit/b81d90516555d5bca585577ba555b20e1c14cace) (for several years). If your device build and/or kernel don't include the support, then you will need to talk to your specific maintainer to add it. Please close.
