### ISSUE TITLE
OnePlus 3T Encryption Broken

### ISSUE THREAD

**Issue by SuniteL** [TeamWin/Team-Win-Recovery-Project#1405]
- [X ] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [X ] I am running the latest version of TWRP
- [X ] I have read the FAQ (https://twrp.me/FAQ/)
- [X ] I have searched for my issue and it does not already exist

**Device codename**: One Plus 3T
**TWRP version**: 3.2.3-1

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Encryption on the 3T is broken with the latest Lineage OS 16 builds, problem seems to be pointing towards TWRP has not accounted for the filesystem storage correctly and thus encryption has been compromised.

#### WHAT IS THE EXPECTED RESULT?
Device should automatically begin encryption process, but does not.

#### WHAT HAPPENS INSTEAD?
Device is left unencrypted.

**Comment by CaptainThrowback** [comment]
https://twrp.me/faq/encryptionsupport.html

Device maintainer will likely need to make updates to support Pie decryption once the next TWRP version is released.

In the meantime, you can check on XDA to see if any unofficial updated release with this support has been compiled.
