### ISSUE TITLE
Vibration starts and never stops and can't be disabled on crosshatch/Pixel 3 XL

### ISSUE THREAD

**Issue by ghost** [TeamWin/Team-Win-Recovery-Project#1407]
- [✔] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [✔] I am running the latest version of TWRP
- [✔] I have read the FAQ (https://twrp.me/FAQ/)
- [✔] I have searched for my issue and it does not already exist

**Device codename**:  crosshatch
**TWRP version**:  3.2.3-4

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?

Download TWRP 3.2.3-4 from [here](https://dl.twrp.me/crosshatch/) and install it on a device with a lockscreen/encryption password/pin. 

#### WHAT IS THE EXPECTED RESULT?

The device will vibrate (or not if vibration is disabled in settings) when a key is pressed, but stop afterwards when the key is released.

#### WHAT HAPPENS INSTEAD?

Pressing any key on the PIN/pass keyboard will cause vibration to start and it does not stop until TWRP is exited. Disabling vibration in settings does not fix this behavior during the current or on subsequent boots of TWRP.

#### ADDITIONAL INFORMATION

This doesn't occur with 3.2.3-1, so the bug must have been introduced fairly recently. 

`/tmp/recovery.log`:  https://paste.omnirom.org/view/0533d27e
`dmesg`:  https://paste.omnirom.org/view/2624b554

**Comment by bigbiff** [comment]
3.2.3-5 was released to fix this.
