### ISSUE TITLE
date time wrong on trlte

### ISSUE THREAD

**Issue by fennectech** [TeamWin/Team-Win-Recovery-Project#1409]
- [X ] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [ X] I am running the latest version of TWRP
- [X ] I have read the FAQ (https://twrp.me/FAQ/)
- [ ]X I have searched for my issue and it does not already exist

**Device codename**: 
**TWRP version**: 

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Set RTC via android
#### WHAT IS THE EXPECTED RESULT?
Date should match current date and time
#### WHAT HAPPENS INSTEAD?
Date is about a month off  

at 3/13/2019 the  date in the backup is 2/14/2019

#### ADDITIONAL INFORMATION
I have tried setting the clock in android to no avail. 

<!-- Use https://paste.omnirom.org/ and upload `/tmp/recovery.log` and the output of `dmesg` --

**Comment by fennectech** [comment]
Recovery.log https://pastebin.com/CLZcPFGz 
dmesg.log    https://pastebin.com/CXVeRP8c

**Comment by mauronofrio** [comment]
There are no problem of data/time, you need only to select the right time zone from settings. From the log you added can be seen
2019-02-14--07-40-19
i think then is setted a wrong time zone

**Comment by fennectech** [comment]
Nope.  That wouldent make the date be 30 days off.   I have it set to UTC-6 (with is my time zone)

**Comment by Ibuprophen** [comment]
Hopefully the following image is helpful regarding the TWRP Location to Adjust the Time Zone... 

![TWRP_Time-Zone](https://user-images.githubusercontent.com/18060271/54498482-78e93600-48de-11e9-97e5-62c0f610c04d.jpg)

Good Luck! :-) 


~Ibuprophen

**Comment by fennectech** [comment]
I have done that already.  
But it says 2019-02-18 but the current date and time is 2019-03-17.  The date/time is about 30 days behind.     
![image](https://user-images.githubusercontent.com/11953665/54498548-d5e0ee00-48d6-11e9-8070-8ff70c283fcb.jpg)
 Unless there is an option to set it to UTC+642 then this wont help

**Comment by Ibuprophen** [comment]
I see... 

So it's 1 Month off on the backup label created by TWRP. 

That's weird to see all the other information correct but, the month itself. 

After creating a backup, wouldn't the TWRP logs reflect something more regarding the backup? 

Try making another backup, and then after its done, make a copy of the TWRP logs to the SD Card and provide them here for the TWRP developers to take a look at them. 

Unless they have any other options for you... 


~Ibuprophen

**Comment by fennectech** [comment]
Already did that.   You can get dmesg.log and recovery.log up there.  Unless i biffed and forgot to make a backup.

**Comment by mauronofrio** [comment]
So can you try to delete twrp folder in your internal storage and reboot again in twrp?

**Comment by fennectech** [comment]
I deleted TWRP/.twrps   I’d rather keep my zips and backups folder

**Comment by fennectech** [comment]
Renamed the twrp folder and it reset all my settings. But the date is still a month off.

**Comment by mauronofrio** [comment]
So, actually the twrp is taking time from /data/time/ats_2 and from the log you send us seems the data wrote in that ats_2 is 2019-02-14--07-40-19
Now what can be tried is, add persist in the fstab and see if in persist there is a good time. Actually i'm not the maintainer for trlte so we need the help of @ripee

**Comment by fennectech** [comment]
That was taken the day i made that issue.

**Comment by fennectech** [comment]
So how do i put a thingy in fstab?  What should i put in there?

**Comment by mauronofrio** [comment]
You should add this line in recovery.fstab, actually i don't know if your device have a persist partition:
`/persist       ext4   /dev/block/bootdevice/by-name/persist                      flags=display="Persist"`

**Comment by fennectech** [comment]
[android] shell@trltevzw [20:39] /system/etc
# blkid
/dev/block/vnswap0: LABEL="swap" UUID="b19377ca-7847-4917-e5f4-8f9ee546b7c1" TYPE="swap" 
/dev/block/mmcblk0p1: SEC_TYPE="msdos" UUID="00BC-614E" TYPE="vfat" 
/dev/block/mmcblk0p2: SEC_TYPE="msdos" UUID="00BC-614E" TYPE="vfat" 
/dev/block/mmcblk0p13: UUID="57f8f4bc-abf4-655f-bf67-946fc0f9f25b" TYPE="ext4" 
/dev/block/mmcblk0p22: UUID="57f8f4bc-abf4-655f-bf67-946fc0f9f25b" TYPE="ext4" 
/dev/block/mmcblk0p23: UUID="57f8f4bc-abf4-655f-bf67-946fc0f9f25b" TYPE="ext4" 
/dev/block/mmcblk0p24: UUID="57f8f4bc-abf4-655f-bf67-946fc0f9f25b" TYPE="ext4" 
/dev/block/mmcblk0p25: UUID="57f8f4bc-abf4-655f-bf67-946fc0f9f25b" TYPE="ext4" 
/dev/block/mmcblk0p26: UUID="57f8f4bc-abf4-655f-bf67-946fc0f9f25b" TYPE="ext4" 
/dev/block/mmcblk0p27: UUID="57f8f4bc-abf4-655f-bf67-946fc0f9f25b" TYPE="ext4" 
/dev/block/loop64: UUID="57f8f4bc-abf4-655f-bf67-946fc0f9f25b" TYPE="ext4" 

Output of blkid

**Comment by mauronofrio** [comment]
And what is this? I can't ge information from here

**Comment by fennectech** [comment]
generaly its a list of partitions on a linux system

**Comment by fennectech** [comment]
im not sure how to tell if i have a persist partition

**Comment by mauronofrio** [comment]
Generally on android devices i used these commands to read all partitions list with related sizes, the second command should say if there is a persist partition, but i'm not sure the path is good also for trlte
```
cat /proc/partitions
ls -l /dev/block/bootdevice/by-name/
```

**Comment by fennectech** [comment]
[android] shell@trltevzw [20:51] /
# cat /proc/partitions                                                                                                                             
major minor  #blocks  name

 253        0    1572864 vnswap0
 179        0   30535680 mmcblk0
 179        1      19456 mmcblk0p1
 179        2      66464 mmcblk0p2
 179        3        512 mmcblk0p3
 179        4        512 mmcblk0p4
 179        5         64 mmcblk0p5
 179        6         32 mmcblk0p6
 179        7       2048 mmcblk0p7
 179        8        512 mmcblk0p8
 179        9        512 mmcblk0p9
 179       10       4096 mmcblk0p10
 179       11       6144 mmcblk0p11
 179       12      10240 mmcblk0p12
 179       13      14336 mmcblk0p13
 179       14       4096 mmcblk0p14
 179       15       4096 mmcblk0p15
 179       16          4 mmcblk0p16
 179       17      17408 mmcblk0p17
 179       18      19456 mmcblk0p18
 179       19       4084 mmcblk0p19
 179       20       1024 mmcblk0p20
 179       21          8 mmcblk0p21
 179       22       8192 mmcblk0p22
 179       23       9216 mmcblk0p23
 179       24    4259840 mmcblk0p24
 179       25    1048576 mmcblk0p25
 179       26      15360 mmcblk0p26
 179       27   25015276 mmcblk0p27
 179       32       4096 mmcblk0rpmb
   7       64      65536 loop64

**Comment by fennectech** [comment]
[android] shell@trltevzw [20:51] /
# ls -l /dev/block/bootdevice/by-name/
total 0
lrwxrwxrwx 1 root root 20 2014-01-05 23:44 aboot -> /dev/block/mmcblk0p7
lrwxrwxrwx 1 root root 20 2014-01-05 23:44 apnhlos -> /dev/block/mmcblk0p1
lrwxrwxrwx 1 root root 21 2014-01-05 23:44 boot -> /dev/block/mmcblk0p17
lrwxrwxrwx 1 root root 21 2014-01-05 23:44 cache -> /dev/block/mmcblk0p25
lrwxrwxrwx 1 root root 21 2014-01-05 23:44 carrier -> /dev/block/mmcblk0p26
lrwxrwxrwx 1 root root 20 2014-01-05 23:44 dbi -> /dev/block/mmcblk0p5
lrwxrwxrwx 1 root root 20 2014-01-05 23:44 ddr -> /dev/block/mmcblk0p6
lrwxrwxrwx 1 root root 21 2014-01-05 23:44 efs -> /dev/block/mmcblk0p13
lrwxrwxrwx 1 root root 21 2014-01-05 23:44 fota -> /dev/block/mmcblk0p19
lrwxrwxrwx 1 root root 21 2014-01-05 23:44 mdm1m9kefs1 -> /dev/block/mmcblk0p14
lrwxrwxrwx 1 root root 21 2014-01-05 23:44 mdm1m9kefs2 -> /dev/block/mmcblk0p15
lrwxrwxrwx 1 root root 21 2014-01-05 23:44 mdm1m9kefs3 -> /dev/block/mmcblk0p10
lrwxrwxrwx 1 root root 21 2014-01-05 23:44 mdm1m9kefsc -> /dev/block/mmcblk0p16
lrwxrwxrwx 1 root root 21 2014-01-05 23:44 misc -> /dev/block/mmcblk0p20
lrwxrwxrwx 1 root root 20 2014-01-05 23:44 modem -> /dev/block/mmcblk0p2
lrwxrwxrwx 1 root root 21 2014-01-05 23:44 pad -> /dev/block/mmcblk0p11
lrwxrwxrwx 1 root root 21 2014-01-05 23:44 param -> /dev/block/mmcblk0p12
lrwxrwxrwx 1 root root 21 2014-01-05 23:44 persdata -> /dev/block/mmcblk0p23
lrwxrwxrwx 1 root root 21 2014-01-05 23:44 persist -> /dev/block/mmcblk0p22
lrwxrwxrwx 1 root root 21 2014-01-05 23:44 recovery -> /dev/block/mmcblk0p18
lrwxrwxrwx 1 root root 20 2014-01-05 23:44 rpm -> /dev/block/mmcblk0p8
lrwxrwxrwx 1 root root 20 2014-01-05 23:44 sbl1 -> /dev/block/mmcblk0p3
lrwxrwxrwx 1 root root 20 2014-01-05 23:44 sbl1bak -> /dev/block/mmcblk0p4
lrwxrwxrwx 1 root root 21 2014-01-05 23:44 ssd -> /dev/block/mmcblk0p21
lrwxrwxrwx 1 root root 21 2014-01-05 23:44 system -> /dev/block/mmcblk0p24
lrwxrwxrwx 1 root root 20 2014-01-05 23:44 tz -> /dev/block/mmcblk0p9
lrwxrwxrwx 1 root root 21 2014-01-05 23:44 userdata -> /dev/block/mmcblk0p27
[android] shell@trltevzw [20:53] /

**Comment by mauronofrio** [comment]
Persist is there, so you can try to add persist in the fstab for data and time recognition

**Comment by fennectech** [comment]
okay   where do i find fstab  it snot in the normal place (/etc/fstab)

**Comment by mauronofrio** [comment]
Wait, i will build a new twrp for you in some minutes

**Comment by fennectech** [comment]
okay :)

**Comment by mauronofrio** [comment]
@fennectech test this twrp please:
https://www.androidfilehost.com/?fid=1395089523397919539

Try also deleting twrp folder in your internal storage

**Comment by fennectech** [comment]
This fix works like a charm  didnt even have to wipe out my twrp folder

**Comment by mauronofrio** [comment]
Sent the commit to fix it, we need to wait a bit to merge it
https://gerrit.twrp.me/#/c/android_device_samsung_trlte/+/734/

**Comment by fennectech** [comment]
Glad i could help  Ill close this issue.
