### ISSUE TITLE
VZW Gnex Fails Nandroid Restore at MD5 Check

### ISSUE THREAD

**Issue by t18matt** [TeamWin/Team-Win-Recovery-Project#141]
Hey Dees, here's the log as requested. I made a backup with 2.4.1.0, upgraded to 2.4.4.0, did a whole system wipe minus internal of course, flashed rom and gapps. Let rom load, went back into recovery and tried to restore nandroid and immediately got "Verify MD5- E:MD5 failed to match on ". That was it. Fastboot flashed 2.4.1.0 and nandroid restored perfectly. https://www.dropbox.com/s/qa664pyi6lo9edg/recovery.log. Thanks for telling me how to get a log to you and taking a look.

**Comment by landstander668** [comment]
Sounds like this is the same problem as issue #139.

**Comment by landstander668** [comment]
On Thu, Mar 14, 2013 at 5:33 PM, t18matt notifications@github.com wrote:

> yeah, i'm not sure about checking it in adb like you were saying, not too
> good at figuring that stuff out. was it happening pretty much as soon as
> you swiped to restore?

Yes, MD5 validation occurs immediately after you perform the swipe to begin.

**Comment by bigbiff** [comment]
Hi, can you paste the contents of /data/media/0/TWRP/BACKUPS/014688280100F006/rtbx-4.22/
ls -l /data/media/0/TWRP/BACKUPS/014688280100F006/rtbx-4.22/

Thanks!

**Comment by t18matt** [comment]
what do you need that for?

**Comment by bigbiff** [comment]
I want to see the file listing that twrp created.

**Comment by t18matt** [comment]
ok, just leary of giving people stuff that contains my data. do you need the whole nandroid file? all of my backups were done with 2.4.1.0, not 2.4.4.0

**Comment by bigbiff** [comment]
No I just want a listing of the files not the files themselves. You can execute the ls command I posted in adb shell or something like terminal emulator. Thanks you for your help.

**Comment by t18matt** [comment]
ok, i typed the command in terminal and got this;

error: device not found
KUPS/014688280100F006/rtbx-4.22/
-rw-rw-rw-   root    root   8388608 2013-03-14 17:20 boot.emmc.win
-rw-r--r--   root    root   23552 2013-03-14 17:20 cache.ext4.win
-rw-r--r--   root    root   591803392 2013-03-14 17:20 data.ext4.win
-rw-rw-rw-   root    root   154570 2013-03-14 17:20 recovery.log
-rw-r--r--   root    root   402907648 2013-03-14 17:20 system.ext.4.win

Should have done it from adb shell from my computer instead, took a while to type all of this in looking at that small screen. Hope this helps. I looked at the recovery.log in rtbx-4.22 and it was blank.

**Comment by bigbiff** [comment]
There are no md5 files in the directory it seems. You cant check md5 sums if you didn't generate them.

**Comment by t18matt** [comment]
right, i have generate md5 turned off, so why would it fail at the check? here's my settings:

Backup-system, data, boot, cache, skip md5 generation during backup.
Settings-Skip Md5 generation during backup, enable md5 verification of backup, ignore image size errors during backup

Hmm, if i disable "enable backup verification of backup", what are the chances it would work? and why does it work on 2.4.1.0 with it enabled even though i don't have md5 sums in my backups but doesn't work on 2.4.4.0? sounds like i have conflicting settings going on.

**Comment by bigbiff** [comment]
Yeah that needs to be disabled if you are not creating the md5 verification files. But your logs might be pointing out an issue with that option being enabled we should tell the user there were no MD5 files created.

**Comment by t18matt** [comment]
well, i'll upgrade again and see if it was my fault all along. if it was, i'm very sorry for wasting your time.

**Comment by bigbiff** [comment]
No waste of time at all. I will be looking into the error you had reported and make it more informative to the user. Let me know if this solves your issue.

**Comment by t18matt** [comment]
sure will, waiting for this rom to load up and to restore my apps then i'll try it. i just don't understand why the option is there twice, once in the settings and once in the backup settings?

**Comment by t18matt** [comment]
problem solved. still can't figure out why it worked on 2.4.1.0 but not on 2.4.4.0 with the settings the way i had them. it's like it was bypassing the settings and someone figured that it was doing it and figured it out in the latest version. one question though, is there any way to turn off where the screen turns itself off after a minute or two, that is annoying in my eyes. i think it shut itself down when that happens.

**Comment by Dees-Troy** [comment]
Final fixes are here:
http://review.teamw.in/#/c/537/
