### ISSUE TITLE
[dumpling] [3.2.3-2] Black screen

### ISSUE THREAD

**Issue by bthylafh** [TeamWin/Team-Win-Recovery-Project#1410]
- [X] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [X] I am running the latest version of TWRP
- [X] I have read the FAQ (https://twrp.me/FAQ/)
- [X] I have searched for my issue and it does not already exist

**Device codename**: dumpling
**TWRP version**: 3.2.3-2

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Install TWRP from Official TWRP App, then reboot into recovery.

#### WHAT IS THE EXPECTED RESULT?
Boot into TWRP recovery GUI.

#### WHAT HAPPENS INSTEAD?
Black screen with the notification LED on solid.

#### ADDITIONAL INFORMATION
Previously ran 3.2.3-1, which would boot to GUI but at some point stopped accepting my PIN for the encryption password.  My phone is presently running Lineage 15.1.

`/tmp/recovery.log`: no such file or directory
`dmesg`: https://paste.omnirom.org/view/8707e44e  [note: from booted OS, not recovery]

**Comment by Yamakaky** [comment]
Literally same (tm) ^^

**Comment by bthylafh** [comment]
After some digging, the problem is because this new build of TWRP requires part of the latest official firmware for this phone. If the firmware is missing then you get the problem we're having.

I wound up completely redoing my phone for unrelated reasons.  A crucial part of that process was downloading the newest OnePlus firmware and deleting the "compatibility.zip" from the zipfile, then adb push'ing it to the phone and installing it from TWRP 3.2.3-1.  That updated the necessary firmware and after that the phone could successfully run TWRP 3.2.3-2.

It's be spiffy if there'd be a warning about this on the download page, or if TWRP would check for outdated firmware during the install process and pop up a warning.  Requiring people to check the thread on XDA even if they're using the official updater app isn't cool.

**Comment by bthylafh** [comment]
There's someone who will package up and upload the minimal files needed to update OP's firmware; I think it's hosted on SourceForge somewhere.  Flashing those from old-TWRP might do the job without having to totally wipe your phone.

**Comment by bthylafh** [comment]
Ah, here we are: https://sourceforge.net/projects/cheeseburgerdumplings/files/16.0/dumpling/firmware/

**Comment by bthylafh** [comment]
Give that a shot from old-TWRP, then reboot and update to new-TWRP.

**Comment by igalic** [comment]
anyone ever mentioned how extremely dodgy it feels to install any third-party software on android, cuz crucial files are just hosted randomly somewhere?

**Comment by bennofs** [comment]
@igalic you can generate the firmware `update.zip` from official OTAs yourself with this script: https://gist.github.com/480078ad80d833350251c9a7a5838239

**Comment by bennofs** [comment]
@bthylafh for the future, how did you debug this issue and track it down to missing firmware?

**Comment by bthylafh** [comment]
@bennofs It's been so long that I don't precisely remember.

Something like the usual digging through a few XDA threads, IIRC, and remembering from a previous thread (either there or on Reddit) that someone was making the vendor.zip available.

**Comment by Yamakaky** [comment]
@bennofs are you sure your script is complete? It's missing a lot of function definitions.

**Comment by bennofs** [comment]
@Yamakaky it worked for me. what function definitions do you think are missing?

**Comment by Yamakaky** [comment]
Oh god sorry, I didn't see that the code in the middle was a bash script in a python string, my bad. Will try!

**Comment by bthylafh** [comment]
This bug isn't present in newer versions, so I'm closing this.
