### ISSUE TITLE
Bad signatures on twrp-3.2.3-0-surnia.img

### ISSUE THREAD

**Issue by ghost** [TeamWin/Team-Win-Recovery-Project#1412]
- [ ] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [ ] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**Device codename**: Moto E LTE (surnia)
**TWRP version**: twrp-3.2.3-0-surnia.img

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
gpg --verify twrp-3.2.3-0-surnia.img.asc twrp-3.2.3-0-surnia.img

#### WHAT HAPPENS INSTEAD?
gpg: Signature made wto, 7 sie 2018, 05:14:59 CEST
gpg:                using RSA key 95707D42307C9D41D09BF7091D8597D7891A43DF
gpg: BAD signature from "TeamWin <admin@teamw.in>" [unknown]

**Comment by bigbiff** [comment]
Just checked on the server and it looks good:

gpg: assuming signed data in 'twrp-3.2.3-0-surnia.img'
gpg: Signature made Mon 06 Aug 2018 11:14:59 PM EDT
gpg:                using RSA key 95707D42307C9D41D09BF7091D8597D7891A43DF
gpg: Good signature from "TeamWin <admin@teamw.in>" [unknown]

**Comment by ghost** [comment]
I check again - download all new files from **https://eu.dl.twrp.me/surnia/** and I have the same results.
I also check sha256sum and they are different.

This same problem is on TWRP for **Motorola Moto G5 Plus (potter)**
Can you explain me what is going on. Help ;)

**Comment by bigbiff** [comment]
Are you downloading from the website through a browser?

**Comment by ghost** [comment]
Yes, I download directly from this links:
https://eu.dl.twrp.me/surnia/twrp-3.2.3-0-surnia.img
https://eu.dl.twrp.me/surnia/twrp-3.2.3-0-surnia.img.asc

**Comment by bigbiff** [comment]
Make sure you have referrer on.

I checked both dl.twrp.me and eu.dl.twrp.me

eu.dl.twrp.me:

sha256sum twrp-3.2.3-0-surnia.img twrp-3.2.3-0-surnia.img.asc
5bf027357aeb19a4f65388390a8c9c6e8d46c8483326f4e59904688d580cb28b  twrp-3.2.3-0-surnia.img
d72c621188f1fee8c53c9c906c8d6deca9ee6dfdfa26577e9bd3073994ed9e21  twrp-3.2.3-0-surnia.img.asc
cat twrp-3.2.3-0-surnia.img.sha256
5bf027357aeb19a4f65388390a8c9c6e8d46c8483326f4e59904688d580cb28b  twrp-3.2.3-0-surnia.img

dl.twrp.me:

sha256sum twrp-3.2.3-0-surnia.img twrp-3.2.3-0-surnia.img.asc
5bf027357aeb19a4f65388390a8c9c6e8d46c8483326f4e59904688d580cb28b  twrp-3.2.3-0-surnia.img
d72c621188f1fee8c53c9c906c8d6deca9ee6dfdfa26577e9bd3073994ed9e21  twrp-3.2.3-0-surnia.img.asc
cat twrp-3.2.3-0-surnia.img.sha256
5bf027357aeb19a4f65388390a8c9c6e8d46c8483326f4e59904688d580cb28b
