### ISSUE TITLE
Contact Us Results In Undeliverable... 

### ISSUE THREAD

**Issue by Ibuprophen** [TeamWin/Team-Win-Recovery-Project#1415]
I was under the impression that I had submitted the https://github.com/TeamWin/twrpme/issues/74 issue within the correct location. 

Should I have submitted it here instead? 

Thank you very much for your time and understanding with this! :-) 

~Ibuprophen

**Comment by bigbiff** [comment]
I think I am going to have to figure another way to send messages to us. We can't seem to do on behalf of users anymore for some domains.

**Comment by bigbiff** [comment]
Closing since it's open on twrpme project.
