### ISSUE TITLE
[twrp-3.2.3-0-tulip][BUG] Huge Light Bleeding At The Bottom Of The Screen

### ISSUE THREAD

**Issue by Birraque** [TeamWin/Team-Win-Recovery-Project#1416]
- [X] I am running an official build of TWRP, downloaded from [https://twrp.me/xiaomi/xiaomiredminote6.html](https://twrp.me/xiaomi/xiaomiredminote6.html)
- [X] I am running the latest version of TWRP 3.2.3-0 for tulip - Xiaomi Redmi Note 6 Pro (Global), Model M1806E7TH
- [X] I have read the FAQ (https://twrp.me/FAQ/)
- [X] I have searched for my issue and it does not already exist

**Device codename**:  tulip - Xiaomi Redmi Note 6 Pro (Global), Model M1806E7TH
**TWRP version**:  [twrp-3.2.3-0-tulip.img 36M 2019-02-26 17:38:58 EST](https://dl.twrp.me/tulip/)

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?

Boot your device on TWRP Recovery Mode and go to Home (TWRP Main Screen), the issue occurs 100% of the time

#### WHAT IS THE EXPECTED RESULT?

TWRP UI match the screen size correctly when in the Home (TWRP Main Screen) and all others Submenus.

#### WHAT HAPPENS INSTEAD?

The Official TWRP for tulip version has a huge issue of light bleeding at the bottom of the screen that can permanently damage it with burn in.
TWRP doesn't match the screen size when in the Home (TWRP Main Menu). The Bug approximately 0.5 cm below the navigation buttons without UI and bleeding bright light (see picture link), [https://i.imgur.com/Lc4oQWa.jpg](https://i.imgur.com/Lc4oQWa.jpg)

#### ADDITIONAL INFORMATION

It doesn't seems to be a screen resolution Bug but rather a parameter error over the hardware on which it is installed. A very BRIGHT light bleeding that could damage the screen.
Already tested with 3 different Redmi Note 6  Pro (Global), Models M1806E7TH and M1806E7TG with same result. Please fix it ASAP.

`/tmp/recovery.log`: 
`dmesg`: 
Not available

Let me know if you need another inputs.
Best Regards,

**Comment by mauronofrio** [comment]
@Birraque  please test this twrp:
https://www.androidfilehost.com/?fid=1395089523397918994

**Comment by Birraque** [comment]
@mauronofrio thanks for your prompt reply (and fix).
I would like to **_CONFIRM_** that test-twrp-tulip.img has been fixed for Light Bleeding issue.
Already tested on Main Home Screen and all other sub menus. All of them seems to be correctly matching on screen size now.

ADB Commands => [https://i.imgur.com/WsPQbeR.jpg](https://i.imgur.com/WsPQbeR.jpg)
TWRP Home Screen => [https://i.imgur.com/djQ7tof.jpg](https://i.imgur.com/djQ7tof.jpg)
Settings \ Screen => [https://i.imgur.com/qrl1XrF.jpg](https://i.imgur.com/qrl1XrF.jpg)
Settings \ Screen (Timeout) => [https://i.imgur.com/kKbwLLg.jpg](https://i.imgur.com/kKbwLLg.jpg)

Thank you very much! :-)

Note: If you allow me I would like to ask if you have future plans to implement Decryption/Encryption on Official TWRP.

Current version can't handle Stock MIUI Decryption/Encryption => [https://i.imgur.com/DwH2qUk.jpg](https://i.imgur.com/DwH2qUk.jpg)

Suggestion: There is an active thread in XDA-Developers about TWRP for Redmi Note 6 Pro. Your participation and comments are very welcome if you wish to participate. => [https://forum.xda-developers.com/redmi-note-6-pro/how-to/official-twrp-xiaomi-mi-mix-3-redmi-t3905444](https://forum.xda-developers.com/redmi-note-6-pro/how-to/official-twrp-xiaomi-mi-mix-3-redmi-t3905444)

Best Regards,

**Comment by mauronofrio** [comment]
So it thought the decryption was working, if this is not true i will check better in the next days and i will fix it. For bleeding fix in official build you need to wait some hours or maybe a day

**Comment by Birraque** [comment]
Hi @mauronofrio 
As you can confirm in my previous photo ([image link above](https://i.imgur.com/DwH2qUk.jpg)) I cannot mount the encrypted volume from Stock MIUI (Developer ROM - Android Pie).
The only way to install Official TWRP with Stock MIUI is following the step-by-step [Tutorial from Android Explained - Install TWRP on the Redmi Note 6 Pro](https://www.androidexplained.com/redmi-note-6-install-twrp/). The author Doug double checked with me and wasn't able either to decrypt the internal partition of the Stock MIUI. You can see our messages in the comments of the site.
We're handling this Decryption / Encryption issue with [Universal DM-Verity, ForceEncrypt, Disk Quota Disablers](https://forum.xda-developers.com/android/software/universal-dm-verity-forceencrypt-t3817389) file.
I'm glad to know that you are committed in implement a full Decryption / Encryption build in Official TWRP version. Count with me to test any pre-release TWRP version (Beta) and let me know if you need any other input.
Keep improving and kicking some bugs.
Best Regards,

**Comment by mauronofrio** [comment]
Ok, so, can you please @Birraque take some logs? I think there is missing one or 2 files.
```
adb shell cat /tmp/recovery.log
adb shell dmesg
```
You should run these 2 commands when you are in twrp from your pc, and then copy the output on a pastebin ora a file

**Comment by Birraque** [comment]
Hi @mauronofrio 
Done! Follow the Log Files (recovery.log & dmesg.txt) as requested.
The **_[Download Link](https://www.sendthisfile.com/CsKQ5cXUE5FmwCHEHbhz0G9a)_** will EXPIRE in 3 days. Please let me know if you have received the .ZIP file.
Regards,

**Comment by mauronofrio** [comment]
Thanks i will check and i will let you know

**Comment by Birraque** [comment]
Hi @mauronofrio 

I tested the official [twrp-3.2.3-1-tulip.img](https://dl.twrp.me/tulip/twrp-3.2.3-1-tulip.img.html) version available for download today and the Bug of light bleeding is back this time on Main Home Screen and all Sub Menus. Did you changed anything?

ADB Commands => [https://i.imgur.com/FwmiClA.jpg](https://i.imgur.com/FwmiClA.jpg)
TWRP Home Screen => [https://i.imgur.com/wnfxLzI.jpg](https://i.imgur.com/wnfxLzI.jpg)
Settings \ Screen => [https://i.imgur.com/0uVlk8Z.jpg](https://i.imgur.com/0uVlk8Z.jpg)
Mount => [https://i.imgur.com/EbnDgU3.jpg](https://i.imgur.com/EbnDgU3.jpg)
Stock MIUI Encrypted Data => [https://i.imgur.com/889rCvT.jpg](https://i.imgur.com/889rCvT.jpg)

Even when prompted to reboot did not work remaining stuck in Mi screen. I had to press Power button for 10 seconds to get the system back.

Stuck Mi Screen => [https://i.imgur.com/0QkJCOu.jpg](https://i.imgur.com/0QkJCOu.jpg)

From my side the only change is that I receive two OTA updates per week (MIUI Special Team Member) so Beta Nightly 9.3.14 was upgraded to 9.3.18

OTA Beta Nightly 9.3.18 (Full) => [http://bigota.d.miui.com/9.3.18/miui_HMNote6ProGlobal_9.3.18_230af162f5_9.0.zip](http://bigota.d.miui.com/9.3.18/miui_HMNote6ProGlobal_9.3.18_230af162f5_9.0.zip)

[Xiaomi Redmi Note 6 Pro (M1806E7TH)](https://i.imgur.com/CSXmbaS.png) - 4GB/64GB + 128GB microSD
[MIUI 10 Beta Nightly | Global 9.3.18 | Android 9 PKQ1.180904.001 | Security Patch 2019-04-05
MPSS.AT.3.1-00777-SDM660_GEN_PACK-1.192385.1.193652.1 | Kernel 4.4.153-perf+](https://imgur.com/9V3c1jX)

Note: My system has been upgraded to **Android Pie** (Beta Nightly) two weeks ago.

Please let me know if you need other inputs to handle with this Bug.

Best Regards,

**Comment by mauronofrio** [comment]
Can you test again the twrp i sent you some messages ago?

**Comment by Birraque** [comment]
Hi @mauronofrio 

After the stuck on Mi screen that I reported before I had some issue now to recover the Fastboot mode again. When pressed Volume Down + Power the Fastboot screen appear but just for a second and then goes to Mi stuck screen again. It was mandatory to enter the Stock Mi Recovery to select Reboot then volume down + Power to enter on Fastboot mode. This kind of issue never happened before on my device. I was concerned it might have damaged my device.
I've tested both versions now (test-twrp-tulip.img and twrp-3.2.3-1-tulip.img) with same bleeding light bug.

test-twrp-tulip.img bleeding light => [https://i.imgur.com/w5S7wbG.jpg](https://i.imgur.com/w5S7wbG.jpg)

Follow the Log Files (recovery.log & dmesg.txt) for twrp-3.2.3-1-tulip.img and Beta Nightly 9.3.18
(*) The download link will EXPIRE in 3 days. Please let me know if you have received the .ZIP file.
[https://www.sendthisfile.com/Kjxk0DMPtYtYogphWxmljd0K](https://www.sendthisfile.com/Kjxk0DMPtYtYogphWxmljd0K)

The bleeding light on the screen could permanently damage the screen with burn in and now occurs to me that some parameter on TWRP seems to be electrically wrong for RN6's hardware. Even the touch of Back, Home, and Menu buttons are not corresponding to the on-screen position.
XDA-Developers has reports from the Unofficial TWRP versions that after upgraded to Android Pie the Touch Screen has stopped working
I imagine that you have the Redmi Note 6 for test. Did You try to reproduce the Bug?

How can we handle it?

Regards,

**Comment by Birraque** [comment]
@mauronofrio 

Same Bug reported on MIUI Forum today.
[http://en.miui.com/thread-6064768-1-1.html](http://en.miui.com/thread-6064768-1-1.html)

FYI,

**Comment by Birraque** [comment]
Hi @mauronofrio 

[Developer ROM (Android Pie) is Beta Public now - Beta Weekly 9.3.21](http://en.miui.com/thread-6087251-1-1.html)

Download Links:

OTA (Full) => [http://bigota.d.miui.com/9.3.21/miui_HMNote6ProGlobal_9.3.21_6a1846b420_9.0.zip](http://bigota.d.miui.com/9.3.21/miui_HMNote6ProGlobal_9.3.21_6a1846b420_9.0.zip)

Fastboot (Full) => [http://bigota.d.miui.com/9.3.21/tulip_global_images_9.3.21_20190321.0000.00_9.0_global_ebc9e27333.tgz](http://bigota.d.miui.com/9.3.21/tulip_global_images_9.3.21_20190321.0000.00_9.0_global_ebc9e27333.tgz)

Do you have any feedback about this Bug (Fix) status?

Best Regards,

**Comment by CaptainThrowback** [comment]
Please use the issue you opened in the device repo: https://github.com/TeamWin/android_device_xiaomi_tulip/issues/2

Please close this one, as these issues are for overall TWRP bugs, not device-specific ones.

**Comment by Birraque** [comment]
Hi @CaptainThrowback and @mauronofrio 

I will Do sequence of this Bug (troubleshoot) as requested at [[twrp-3.2.3-0-tulip][BUG] Huge Light Bleeding At The Bottom Of The Screen #2](https://github.com/TeamWin/android_device_xiaomi_tulip/issues/2)

Regards,
