### ISSUE TITLE
Question Regarding TWRP Error Codes... 

### ISSUE THREAD

**Issue by Ibuprophen** [TeamWin/Team-Win-Recovery-Project#1418]
I was hoping to receive some guidance with the following question that I cannot locate myself. 

Is there (or could you please provide) a list of the TWRP Error Codes? 

I can only locate a very small number of them that are more common ones but, I can't locate a listing of them and their basic definitions. 

This would be very helpful for those who receive an uncommon error code and what it actually entails as to its typical cause. 

I hope that it's okay to ask here and, if not, please point me in the right direction as to where it would be more appropriate to ask. 

Thank you for your time and understanding with this question. 

~Ibuprophen

**Comment by bigbiff** [comment]
I believe you are talking about updater. You should look at aosp documentation for error codes.

**Comment by Ibuprophen** [comment]
@bigbiff, my apologies for not being a bit more clear... 

I'm referring to a basic definition listing of the TWRP "Error Status" codes. 


~Ibuprophen

**Comment by bigbiff** [comment]
Those come from updater in the rom zip. Unless you can be more specific please.
