### ISSUE TITLE
Issues on samsung galaxy j700H(exynos 2015)

### ISSUE THREAD

**Issue by shadmansaleh** [TeamWin/Team-Win-Recovery-Project#1421]
- [√] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [√] I am running the latest version of TWRP
- [√] I have read the FAQ (https://twrp.me/FAQ/)
- [ ] I have searched for my issue and it does not already exist

**sm-j700H(J7elte)**: 
**3.2.3-0**: 

#### ADDITIONAL INFORMATION

`/tmp/recovery.log`: 
`dmesg`:

**Comment by bigbiff** [comment]
Not sure what this is about. Closing.
