### ISSUE TITLE
[CHIRON] TWRP missing driver for third party replacement screen

### ISSUE THREAD

**Issue by lnghrdntcr** [TeamWin/Team-Win-Recovery-Project#1425]
- [X] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [X] I am running the latest version of TWRP
- [X] I have read the FAQ (https://twrp.me/FAQ/)
- [X] I have searched for my issue and it does not already exist

**Device codename**: Chiron
**TWRP version**: 3.2.3-0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Use current TWRP on the aforementioned device after replacing the original screen.

#### WHAT IS THE EXPECTED RESULT?
TWRP should be displayed on screen.

#### WHAT HAPPENS INSTEAD?
Only a blank, gray-ish screen is displayed

#### ADDITIONAL INFORMATION
[Here the screen I used for replacement](https://it.aliexpress.com/item/5-99-IPS-Display-Per-XIAOMI-Della-Miscela-2-LCD-di-Tocco-Digitale-Dello-Schermo-di/32880212042.html?spm=a2g0s.9042311.0.0.10384c4dZxdpUV)

**Comment by CaptainThrowback** [comment]
This is a device-specific issue and should be posted as an issue in the device repo. @bigbiff, please enable issues for this device so this can be posted there.

@lnghrdntcr you should contact your device maintainer and work with them to resolve the issue. This is not an upstream TWRP issue.

**Comment by lnghrdntcr** [comment]
Great! I'll close the issue then. Thank you for your help.

**Comment by bigbiff** [comment]
Issues has been enabled for chiron device tree.
