### ISSUE TITLE
Galaxy s3 (I9300), TWRP 2.4.4.0, Time settings for Backup files

### ISSUE THREAD

**Issue by qwerty22** [TeamWin/Team-Win-Recovery-Project#143]
Backup was created at GMT+4 (Moscow) 22:51 or 22:59 (I do not remember) 2013-03-18 but SN-dir marked 0:20 next day, date name - _15-45_, image files marked 11:59. List:
# ls -l /storage/extSdCard/TWRP/BACKUPS

drwxrwxr-x system   media_rw          2013-03-19 00:20 4df1645e34836fa5
# ls -l /storage/extSdCard/TWRP/BACKUPS/4df1645e34836fa5

drwxrwxr-x system   media_rw          2013-03-18 11:59 2013-03-18--15-45-01
# ls -l /storage/extSdCard/TWRP/BACKUPS/4df1645e34836fa5/2013-03-18--15-45-01

-rwxrwxr-x system   media_rw  8388608 2013-03-18 11:59 boot.emmc.win
-rwxrwxr-x system   media_rw       48 2013-03-18 11:59 boot.emmc.win.md5
-rwxrwxr-x system   media_rw     2891 2013-03-18 11:59 cache.ext4.win
etc.

(sorry for my english)

**Comment by bigbiff** [comment]
We are only currently setting the TZ environment inside of TWRP itself. Might need to do it in device configs to have files created with the right time.
