### ISSUE TITLE
It seems backup of system image is not exact bit-to-bit

### ISSUE THREAD

**Issue by linux019** [TeamWin/Team-Win-Recovery-Project#1433]
**Device codename**: HTC U11 EYES (haydugl)
**TWRP version**: twrp-3.2.3-0-hay.img

I made a full backup of `system` partition as image. Then I decided to restore image and FOTA refuse to install any updates as SHA1 of `/dev/block/bootdevice/by-name/system` doesn't match to original SHA1.

Then I did `dd if=/dev/block/bootdevice/by-name/system of=/sdcard/system-dd`
The **dd** created a file of 3992977408 bytes
however same image of `system` has only 3887972352 bytes. (made in TWRP)

I compared SHA2 hash of the `system` image made by TWRP with a result of `sha2sum system_image.emmc.win` and both hashes are identical.

There is a difference of more than 100M. How that can be possible?

Also I can mount `dd` image as ext4 raw image and walk through files, but with TWRP image this is not possible.

**Comment by bigbiff** [comment]
Is this not a problem anymore?

**Comment by linux019** [comment]
I'm not sure, I have extracted an original *system.img *from vendor's FOTA
and flashed the one, will let you know if the issue occurs again.

вс, 21 апр. 2019 г. в 03:21, bigbiff <notifications@github.com>:
