### ISSUE TITLE
HTC M7 International

### ISSUE THREAD

**Issue by daywalk3r666** [TeamWin/Team-Win-Recovery-Project#1438]
- [ ☑] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [ ✖] I am running the latest version of TWRP
- [ ☑] I have read the FAQ (https://twrp.me/FAQ/)
- [ ☑] I have searched for my issue and it does not already exist

**Device codename**: HTC M7 
**TWRP version**: 3.2.3-0 

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Flash the new 3.3.0-0 update per TWRP 3.2.3-0
https://dl.twrp.me/m7univ/twrp-3.3.0-0-m7univ.img 

#### WHAT IS THE EXPECTED RESULT?
Boot into recovery

#### WHAT HAPPENS INSTEAD?
After flashing and rebooting it won' t boot up into recovery 

#### ADDITIONAL INFORMATION
TWRP 3.3.0-0 is 3.4mb smaller then others
![Anmerkung 2019-04-16 092129](https://user-images.githubusercontent.com/15938117/56190092-cbc32400-6029-11e9-97d2-7efa4d2b7860.png)
twres is missing in the ramdisk folder too

`/tmp/recovery.log`: 
`dmesg`:

**Comment by bigbiff** [comment]
Thanks, I removed the image until this can be fixed.

**Comment by daywalk3r666** [comment]
[twrp-3.3.0-0-m7univ.zip](https://github.com/TeamWin/Team-Win-Recovery-Project/files/3088184/twrp-3.3.0-0-m7univ.zip)
i edit the twrp 3.3.0-0 with android kernel kitchen.i paste the missing files [twres and sbin] from a working twrp and i'm able to boot up into recovery.
[dmesg.log](https://github.com/TeamWin/Team-Win-Recovery-Project/files/3088207/dmesg.log)
[recovery.log](https://github.com/TeamWin/Team-Win-Recovery-Project/files/3088208/recovery.log)
![Screenshot_2019-04-17-08-31-14](https://user-images.githubusercontent.com/15938117/56266327-363c9880-60ec-11e9-9580-a7a489af23b2.png)
![Screenshot_2019-04-17-08-32-02](https://user-images.githubusercontent.com/15938117/56266328-363c9880-60ec-11e9-96e1-b31585516533.png)

@bigbiff maybe you can check my twrp.img

**Comment by bigbiff** [comment]
Hi, can you test http://build.twrp.me/twrp-3.3.0-0-m7univ.img

**Comment by daywalk3r666** [comment]
this twrp is working

**Comment by bigbiff** [comment]
Thanks, a prod build is running.

**Comment by daywalk3r666** [comment]
twrp 3.3.1-0 the same as twrp 3.3.0-0.
