### ISSUE TITLE
Black screen on Xiaomi Mi A2(Android 9)

### ISSUE THREAD

**Issue by DeNcHiK3713** [TeamWin/Team-Win-Recovery-Project#1439]
- [x] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**Device codename**: jasmine_sprout
**TWRP version**: 3.3.0-0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Install TWRP from Official TWRP App, then reboot into recovery.
`fastboot boot twrp-3.3.0-0-jasmine_sprout.img`

#### WHAT IS THE EXPECTED RESULT?
Boot into TWRP recovery GUI.

#### WHAT HAPPENS INSTEAD?
I see black screen instead of twrp GUI

**Comment by bigbiff** [comment]
Thanks for the report. I removed the images until this can be fixed.

**Comment by DeNcHiK3713** [comment]
Screen backlight is off. Phone is visible as an MTP device. I can send adb comands.
`/tmp/recovery.log`: https://paste.omnirom.org/view/3f549979
`dmesg`: https://gist.github.com/DeNcHiK3713/39c517d51efd1432121fc54f401e39c1

**Comment by bigbiff** [comment]
Thanks for the report. I have removed the image until it can be fixed.
