### ISSUE TITLE
Zip signature verification fails under 3.3.0.0 on FP2, switching off not possible (3.2.3.0 works)

### ISSUE THREAD

**Issue by ghost** [TeamWin/Team-Win-Recovery-Project#1441]
- [x] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**Device codename**: Fairphone 2
**TWRP version**: 3.3.0.0 from 2019-04-10

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
I tried to install LineageOS 15.1 on my Fairphone 2 using the nightly builds from 2019-04-17, 2019-04-10 and 2019-04-03 via adb sideload from my desktop PC.

#### WHAT IS THE EXPECTED RESULT?
Adb sideload completes and installs the image on my phone.

#### WHAT HAPPENS INSTEAD?
Installation fails at zip signature verification

#### ADDITIONAL INFORMATION
Zip file verification was switched off in the settings. Changing the setting leads to the same result.
I managed installing the image after switching to TWRP 3.2.3.0.

**Comment by bigbiff** [comment]
Hello, please pull and post /tmp/recovery.log

**Comment by ghost** [comment]
Here is recovery.log: https://paste.omnirom.org/view/4de94f38
Unfortunately it is the log file from TWRP 3.2.3.0 since I used this version to install LineageOS

**Comment by bigbiff** [comment]
We would need a log of the issue. Not the default log from an older twrp.

**Comment by ghost** [comment]
Fortunately LineageOS issued an update a few days ago. I updated TWRP to version 3.3.0.0 and tried to install the upgrade using the LineageOS updater (which uses TWRP to apply the update). This seemed to work but I have no idea why I could not initially install the system from the zip-file.
Since this phone is my production system I will not consider to re-install everything from scratch, so I will close this issue for now. If I experience any further problems I know now which data you need for debugging.
Thanks a lot for your help.
