### ISSUE TITLE
Restore Error when Restoring System and Vendor Partition

### ISSUE THREAD

**Issue by zephyr88** [TeamWin/Team-Win-Recovery-Project#1444]
- [ x] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [ x] I am running the latest version of TWRP
- [ x] I have read the FAQ (https://twrp.me/FAQ/)
- [ x] I have searched for my issue and it does not already exist

**Device codename**: Beryllium 
**TWRP version**: 3.2.3-2

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Backup And Restore 

#### WHAT IS THE EXPECTED RESULT?

Backup and Restore should work if System and Vendor partitions are backed up and restored

#### WHAT HAPPENS INSTEAD?
Restore fails if System and Vendor Partition are backed up, It works if System-Image and Vendor-Image are backed up.  Can this be fixed so I can automate my TWRP backup using openrecoveryscript ?  Alternatively, add backup and restore options for System-Image and Vendor-Image in OpenRecoveryScript

**Comment by CaptainThrowback** [comment]
If the "mount read-only" option is selected, then those options are supposed to fail.

**Comment by cherryhoax** [comment]
where is that option exactly

**Comment by bigbiff** [comment]
Closing old issue.
