### ISSUE TITLE
Manta (Nexus 10) bricked on update to TWRP 3.3.0-0 using TWRP install

### ISSUE THREAD

**Issue by ghost** [TeamWin/Team-Win-Recovery-Project#1446]
- [X ] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [X] I am running the latest version of TWRP
- [X] I have read the FAQ (https://twrp.me/FAQ/)
- [X] I have searched for my issue and it does not already exist

**Device codename**: MANTA
**TWRP version**: twrp-3.2.3-0-manta.img

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Tried to flash the latest twrp-3.3.0-0-manta.img using TWRP Install method.

#### WHAT IS THE EXPECTED RESULT?
TWRP update to latest twrp-3.3.0-0.

#### WHAT HAPPENS INSTEAD?
Result was a brick. Can't boot to recovery. Can't boot to system. I just get a bootloader screen with REBOOT MODE FLAG: Recovery.

#### ADDITIONAL INFORMATION
None.

`/tmp/recovery.log`: None.
`dmesg`: None.

Don't have additional information because I cannot even get into my manta. Tried to manually flash recovery using adb... no luck as devices are not showing.

**Comment by ghost** [comment]
So, after researching the TWRP MANTA forum, I share the frustration of user: aheeejd...
<FRUSTRATION> "WTF and this blows" (and a few other four letter words of my own : ) </FRUSTRATION>
PROBLEM: https://forum.xda-developers.com/sho...&postcount=653

He was able to fix it using WUGS Toolkit
WUGS TOOLKIT: https://forum.xda-developers.com/nex...1-9-8-t2947452

which asks to flash an older MANTA recovery
SOLUTION: https://forum.xda-developers.com/sho...&postcount=643

which I did; then, I updated the TWRP to latest working and flashed @followmsi latest manta ROM
https://forum.xda-developers.com/nex...icial-t3557735

So, this has happened at least once before in 2016... [not trying to piss anyone off]. I will be careful next time~!

**Comment by bigbiff** [comment]
So is the image fine and can I close this issue?

**Comment by ghost** [comment]
No! When I flashed 
Image: twrp-3.3.0-0-manta.img 
I was unable to get into recovery/system. So, it is not fine. 

Like I said, I had to use WUGS to flash 
image: twrp-3.0.2-0-manta.img

then upgrade using 
image: twrp: twrp-3.2.3-0-manta.img

My problem has been fixed, but the twrp image for manta is still broken.

**Comment by ghost** [comment]
There is no /tmp/recovery.log and no /var/log 
dmesg > dmesg.txt says cannot create file... RO file system.

I am not sure if dmesg will be helpful since I have flashed other twrps and rebooted a few times.

**Comment by followmsi** [comment]
Just updated my 2 Nexus 10 devices to latest 3.3.0.0 TWRP version without
any problems !

It sounds like you did flash TWRP recovery.img onto boot partition.

Fix via fastboot .. normally no need for any other 3rd party tools.

Cheers

**Comment by ghost** [comment]
@followmsi 

I updated to the latest 3.3.0.0 TWRP version using fastboot, because of your post and it worked :  )

There are two possibilities... one is that I hit **boot** instead of **recovery;** however, I remember pausing to think and then hitting **recovery.** Another possibility is that because the buttons are so close together that I hit **boot** my mistake. 

@bigbiff 

This is where TWRP devs can make some changes to the TWRP interface... maybe add a line gap between stacked choices or have **boot** on the left and **recovery** on the right, instead of being stacked. 

Reason: This happened in 2016 and it is still happening with other devices.

And lastly, I hope the underline code of **boot** and **recovery**  option did not get messed up (swapped or has extra lines). As it is happening with other devices, it's worth another look...
