### ISSUE TITLE
No ADB Access on Encrypted Devices

### ISSUE THREAD

**Issue by UncertainSpin** [TeamWin/Team-Win-Recovery-Project#1449]
- [✓] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [✓] I am running the latest version of TWRP
- [✓] I have read the FAQ (https://twrp.me/FAQ/)
- [✓] I have searched for my issue and it does not already exist

**Device codename**: blueline
**TWRP version**: 3.3.0-0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Flash TWRP, Set Lockscreen Password/PIN, reboot recovery, *No ADB Access*

#### WHAT IS THE EXPECTED RESULT?
Flash TWRP, Set Lockscreen Password/PIN, reboot recovery, ADB shell, twrp decrypt "password" -> ADB access in recovery mode

#### WHAT HAPPENS INSTEAD?
No ADB connection is detectable on the device while the password prompt is visible. Entering the correct password will unlock TWRP operations on the device and allow ADB connectivity.

#### ADDITIONAL INFORMATION
This seems like an oversight or bug, as the twrp decrypt command still, rightfully I believe, exists. Without the ability to connect to an encrypted device, this seems pointless. This bug affects a lot of us performing programmatic tasks with recovery and we're having major issues because of it. 

Thanks for the work!

**Comment by CaptainThrowback** [comment]
This isn't a general TWRP problem. This is a device-specific issue. Adb works fine on my devices while at the decryption prompt. Please close this issue and open in your device's repo.

**Comment by UncertainSpin** [comment]
Reposted here: https://github.com/TeamWin/android_device_google_crosshatch/issues/2
