### ISSUE TITLE
Signature verification broken?

### ISSUE THREAD

**Issue by 0-kaladin** [TeamWin/Team-Win-Recovery-Project#145]
Is signature verification working? I've done a search and don't see anything regarding issues but I'm signing a flashable zip I've made and it fails signature verification. I'm using the same keystore/cert to sign an apk I compile and it installs fine on a phone. I use the same keystore with jarsigner, ensuring i'm using SHA1withRSA and specifying -sigfile CERT and everything passes. Even the jarsigner -verify checks out. 

But once i reboot to recovery and turn on signature verification I can't flash the file. Is this a known issue/bug or am I missing something?

To further verify I wasn't fat fingering anything on the command line i've also tried with zipsigner app from the play store and my keystore and fails there too.

For completeness' sake, i've only tested this on a nexus 7 so far.

**Comment by landstander668** [comment]
For what it's worth, my Nexus 7 and Galaxy Nexus (running TWRP 2.4.4.0) were both able to successfully verify the signature on todays CyanogenMod nightly build.

**Comment by 0-kaladin** [comment]
Well yea that's worth a lot.  Guess I'll see what jarsigner verify sees in there vs what I am doing.  Unless there are certain rsa keys programmed in here that are "verified".

I get this:
jarsigner -verify cm-10.1-20130321-NIGHTLY-grouper.zip 
jar verified.

Warning: 
This jar contains unsigned entries which have not been integrity-checked. 
This jar contains entries whose certificate chain is not validated.

Re-run with the -verbose and -certs options for more details.

and then on mine i get:
jarsigner -verify OneAroma7oBind7hem-v1.7_signed.zip 
jar verified.

Warning: 
This jar contains entries whose certificate chain is not validated.

Even one less warning.  Yet mine fails on TWRP...

**Comment by 0-kaladin** [comment]
with verbose here is my sign
X.509, CN=mrRobinson, OU=Unknown, O=XDA, L=Unknown, ST=Unknown, C=US
      [certificate is valid from 3/14/13 2:19 PM to 7/30/40 2:19 PM]
      [CertPath not validated: Path does not chain with any of the trust anchors]

Here is theirs:
X.509, EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
      [certificate is valid from 2/28/08 8:33 PM to 7/16/35 9:33 PM]
      [CertPath not validated: Path does not chain with any of the trust anchors]

only difference is I don't provide emailaddress but that shouldn't break it verifying.  It still is verfied in jarsigner.

**Comment by 0-kaladin** [comment]
Well i just checked gapps and an AOKP build I do myself that gets signed with test-keys.  they all have
X.509, EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US

So my only assumption now is that TWRP verifies THIS signature not that something is validly signed.
Guess I'll try just signing with the generic test-keys for now until I see this get addressed at all.

**Comment by Dees-Troy** [comment]
What device are you using?

**Comment by 0-kaladin** [comment]
I tested this on nexus7 grouper
