### ISSUE TITLE
Error entering to the TWRP Recovery

### ISSUE THREAD

**Issue by joseemdc** [TeamWin/Team-Win-Recovery-Project#1456]
- [.] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [. ] I am running the latest version of TWRP
- [. ] I have read the FAQ (https://twrp.me/FAQ/)
- [ .] I have searched for my issue and it does not already exist

**Device codename**: gtaxlwifi (galaxy tab a2016 10.1)
**TWRP version**: 3.3.0-0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
I have installed the TWRP recovery with ODIN , but when i go to the recovery mode , it shows a black screen with horizontal red lines and the I need to install again the official rom of my tablet to fix this error but without the TWRP

**Comment by bigbiff** [comment]
Thanks for the report. I have removed the image until it can be fixed.

**Comment by joseemdc** [comment]
Thanks , when it will be ready?
