### ISSUE TITLE
[pioneer] "install recovery ramdisk" option missing

### ISSUE THREAD

**Issue by Zealot2000** [TeamWin/Team-Win-Recovery-Project#1458]
- [x] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist (if it does, I wasn't able to find it)

**Device codename**: pioneer
**TWRP version installed**: 3.3.0-0

Hello,
according to https://www.xda-developers.com/twrp-3-3-0-release, TWRP can now be permanently installed using a new option called "install recovery ramdisk" instead of flashing a zip-file. But I cannot find this option anywhere. Any help is appreciated.

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
- Download https://eu.dl.twrp.me/pioneer/twrp-3.3.0-0-pioneer.img
- Connect USB-cable to phone while holding volume up key
- Open Windows command prompt, type "fastboot boot twrp-3.3.0-0-pioneer.img"
- Wait for TWRP to start
- In TWRP, look for the option "install recovery ramdisk"

#### WHAT IS THE EXPECTED RESULT?
The option "install recovery ramdisk" should be present somewhere within TWRP

#### WHAT HAPPENS INSTEAD?
The option "install recovery ramdisk" cannot be found anywhere within TWRP

#### ADDITIONAL INFORMATION
Sony Xperia XA2 H3113, Firmware H3113_Customized CE5_1312-5086_50.1.A.13.123_R2A

**Comment by bigbiff** [comment]
Unfortunately this feature cannot be implemented for this device:
"it would fail to decrypt data whenever ramdisk SPL date doesn't match date from boot image header."

when repacking. Sorry for the inconvenience.

**Comment by Zealot2000** [comment]
Thanks for your answer. Is it possible to provide zip-files for flashing TWRP the old-fashioned way for devices that don't support the recovery ramdisk option?

**Comment by Zealot2000** [comment]
Anyone?

**Comment by phuzz** [comment]
I also have this problem as well., latest TWRP on the site is `twrp-3.3.1-2-pioneer.img`, but the latest installable zip is `twrp-installer-pioneer-3.2.2-0.zip`.

**Comment by atlas0fd00m** [comment]
@bigbiff is there an answer to this?  we see that the zip files have no longer been provided since 3.3.0 (3.2.x for some phones), but i need 3.3.1 to decrypt my data.  right now i'm using fastboot *every* time i want to use twrp.  is there a path forward?  it seems like a disconnect to provide a great new way to install, to take away the old way, and have the new way not work on all phones.  right now i'm trying to use it on Sailfish.
