### ISSUE TITLE
Can't restore backup v.2.4.4.0

### ISSUE THREAD

**Issue by frbouba** [TeamWin/Team-Win-Recovery-Project#146]
Hi,

I tried to restore a backup of a custom rom. When I boot, it seems like a fresh install, all my apps are gone, some configuration files are there (wifi parameters). When navigating through the sdcard, the apps are there.

Here's a link for the recovery.log http://dl.free.fr/rNAXfw9Kp

Thanks for your help

**Comment by landstander668** [comment]
Try running Fix Permissions (under Advanced) IMMEDIATELY after the restore completes, before rebooting.  If this works as expected, then you're most likely encountering issue #140.

**Comment by frbouba** [comment]
It's failing saying "Can't check permissions after Factory Reset.". Do you have an other way to launch fix permissions ?

**Comment by landstander668** [comment]
OK, sounds like this isn't the same issue after all.  Sorry for the confusion.

**Comment by DefinityX** [comment]
I can second this issue, running on Manta. It wipes/restores system just fine, then wipes data fine, but halfway through the data restore, it will reboot into recovery (like nothing happened).

**Comment by frbouba** [comment]
The restoration of the data partition stop because of this : "pigz: write error code 32
pigz: abort: write error on <stdout>"
Is there any way to manually restore the data partition with the terminal command or adb ?

**Comment by bigbiff** [comment]
Can you upload log to http://paste.tinyw.in?

**Comment by frbouba** [comment]
http://tinyw.in/4ffY

I solved partially my problem by pushing the files from a computer. Some files couldn't be restored by i got almost all my files.
Something was wrong with the tar file

**Comment by Dees-Troy** [comment]
Yes, it seems that your backup file was corrupted somehow.
