### ISSUE TITLE
Device request

### ISSUE THREAD

**Issue by KhanMohamed** [TeamWin/Team-Win-Recovery-Project#1463]
TWRP custom recovery for Allcall Mix 2 please

**Comment by CaptainThrowback** [comment]
This is not a place for device requests. Please close.

**Comment by KhanMohamed** [comment]
Oh sorry my bad, by the way I found a 3.2.1 version but In the Russian servers (website and cloud) so... I got through. Thanks anyways have a nice day

**Comment by bigbiff** [comment]
Closing due to not a bug.
