### ISSUE TITLE
TWRP Cannot decrypt data partition in Sharp 507SH

### ISSUE THREAD

**Issue by knight-ryu12** [TeamWin/Team-Win-Recovery-Project#1464]
- [X] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [X] I am running the latest version of TWRP
- [X] I have read the FAQ (https://twrp.me/FAQ/)
- [X] I have searched for my issue and it does not already exist

**Device codename**: eve_sprout
**TWRP version**: 3.3.X (All ver aside 3.3 confirmed didn't work)

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
1. Boot into TWRP anyway possible
2. Asking for password (Which is I don't know)
3. storage and data cannot be seen

#### WHAT IS THE EXPECTED RESULT?
1. boot into TWRP anyway possible
2. Doesn't ask for password

#### WHAT HAPPENS INSTEAD?
Decryption of data will always fail.

#### ADDITIONAL INFORMATION
Using patch from rote66; but I doubt that containing actual patches.

`/tmp/recovery.log`: [here](https://paste.omnirom.org/view/9879febf)
`dmesg`:

**Comment by knight-ryu12** [comment]
I'm happy to provide any information possible, including backed up data.

**Comment by knight-ryu12** [comment]
```
I:Device is encrypted with the default password, attempting to decrypt.
D:crypt_ftr->fs_size = 22953984
I:Using scrypt with keymaster for cryptfs KDF
I:TWRP keymaster max API: 1
I:Signing safely-padded objectkeymaster module name is Keymaster QTI HAL
keymaster version is 256
Found keymaster1 module, using keymaster1 API.
E:Decrypt took too long, killing process
I:Child process killed successfully
Failed to decrypt data.
Unable to decrypt with default password.```
I think this is important for this problem; maybe keymaster is busted.

**Comment by CaptainThrowback** [comment]
This doesn't appear to be an officially supported device. Please refer to wherever you got the build for assistance.

**Comment by knight-ryu12** [comment]
Maybe this was important for upstream, I guess so...
well closing.

**Comment by knight-ryu12** [comment]
atleast I've figured that this device is abandoned.

**Comment by knight-ryu12** [comment]
from this: https://github.com/rote66/twrp_device_SHARP_eve_sprout 
(I think I misread your message :\) @CaptainThrowback

**Comment by CaptainThrowback** [comment]
Please close. This is not an officially supported device. You should refer to the thread you linked for assistance, not the official TWRP Github.
