### ISSUE TITLE
HTC M7 International

### ISSUE THREAD

**Issue by daywalk3r666** [TeamWin/Team-Win-Recovery-Project#1469]
- [ ☑] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [ ✖] I am running the latest version of TWRP
- [ ☑] I have read the FAQ (https://twrp.me/FAQ/)
- [ ☑] I have searched for my issue and it does not already exist

**Device codename**: HTC M7 
**TWRP version**: 3.3.0-0 

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Flash the new 3.3.1-0 update per TWRP 3.3.0-0
https://dl.twrp.me/m7univ/twrp-3.3.1-0-m7univ.img 

#### WHAT IS THE EXPECTED RESULT?
Boot into recovery

#### WHAT HAPPENS INSTEAD?
After flashing and rebooting it won' t boot up into recovery 

#### ADDITIONAL INFORMATION
TWRP 3.3.1-0 is 3.4mb smaller then others
![Anmerkung 2019-04-16 092129](https://user-images.githubusercontent.com/15938117/56190092-cbc32400-6029-11e9-97d2-7efa4d2b7860.png)
twres is missing in the ramdisk folder too.same as twrp 3.3.0-0 before fixing

`/tmp/recovery.log`: 
`dmesg`:

**Comment by bigbiff** [comment]
I rebuilt all the cm-12.1 based images. Can you redownload 3.3.0 and let me know if it works?

**Comment by daywalk3r666** [comment]
i can test it next week.my battery is dead.the new ones comes next week.
but why should i test 3.3.0-0 this build is already fixed?

**Comment by gehess** [comment]
Hi. I just tried both 3.3.0 and 3.3.1 on my M7. 
3.3.0 works. 3.3.1 doesn't (can confirm daywalk3r666's result). Am currently using 3.3.0

**Comment by daywalk3r666** [comment]
my m7 is back in business.i have build a working twrp 3.3.1-0

https://daywalk3r666.ocloud.de/index.php/s/4U17R8wIwalUK9C

**Comment by bigbiff** [comment]
Would you like to maintain this device?

**Comment by daywalk3r666** [comment]
thanks for the offer.but i only edit the build with android kernel kitchen.for fixing bugs and add new features fails me the experience

**Comment by gehess** [comment]
I'm using daywalk3r666's 3.3.1 build and have no problems. 

I recommend it for upload to the official page.

**Comment by CaptainThrowback** [comment]
That's not how this works. Whatever fixes were made need to be pushed to the official via Gerrit, and then a new official build can be run.

**Comment by daywalk3r666** [comment]
its not a "fix". it seems jenkins or some buildscripts forgot to include twres and sbin files into the build.
i only push the missing files from a working build into the m7 twrp build and recompile it with kernel kitchen

i can push the decompile files to my github acc but i don't know if it helps to fix the problem

**Comment by bigbiff** [comment]
Hello, I rebuilt 3.3.1 with the fix for cm-12.1 to include sbin and twres. Please let me know if this issue persists.

**Comment by daywalk3r666** [comment]
yeah the new 3.3.1 build is working now
