### ISSUE TITLE
Help!Plz. Need password when TWRP load.Just flash official 4.2package

### ISSUE THREAD

**Issue by linlin1980** [TeamWin/Team-Win-Recovery-Project#147]
Help!Plz. Need password when TWRP load.Just flash official 4.2package

Recently I noticed that Asus tf300t receives 4.2 update. I download, and use twrp 2.4 to flash system. While, sad things happen. I can't get into system so I press volume down + battery , there I cant find a USB icon, and when I get into TWRP, it required me ****ing password. I swear to God I never ever set up one. And, much more sad, I can't fond any files using install.I really need ur HELP now. Anyone, plz give me some suggestions.
I need a password! Thank you!

**Comment by linlin1980** [comment]
![3](https://f.cloud.github.com/assets/3862318/301595/c094a252-95dc-11e2-8c61-15bb4756d0a8.JPG)

**Comment by Dees-Troy** [comment]
You need to install this build of TWRP:
http://techerrata.com/file/twrp2/tf300t/openrecovery-twrp-2.4.4.0-tf300t-4.2.blob
The 4.2 bootloader does not work with older kernels.
