### ISSUE TITLE
SONY XA2 PIONEER

### ISSUE THREAD

**Issue by thomasrich007** [TeamWin/Team-Win-Recovery-Project#1470]
- [ X] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [ X] I am running the latest version of TWRP
- [ X] I have read the FAQ (https://twrp.me/FAQ/)
- [ X] I have searched for my issue and it does not already exist

**Device codename**: H4113
**TWRP version**: tried - twrp-3.3.1-0-pioneer.img
tried - twrp-3.2.1-0-pioneer.img

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Installed TWRP on Opensuse 15.0
Bootloader is unlocked. Upload with volume key up and power button. Installed per instruction.
Rebooted into recovery mode. Can only see a Grey screen. Then phone boots with Please lock the bootloader.

#### WHAT IS THE EXPECTED RESULT?
See the TWRP screen.

#### WHAT HAPPENS INSTEAD?
 Can only see a Grey screen.

#### ADDITIONAL INFORMATION
PHONE SOFTWARE VERSION 1311-2918_50.2.A.0.352
S1 BOOT VERSION
1310-0301_X_Boot_SDM630_LA3.0_P_35

**Comment by luk1337** [comment]
Make Sony release 50.2.A.0.* kernel source and then we can talk :^)

**Comment by thomasrich007** [comment]
Well I sent a email to Sony.
Below is the question I asked them. They didn't give me any direct response. Just a feedback telling me how to fix my phone.

There is nothing broken. I just want you to point me in the direction of
the Source Code of this Android version 50.2.A.0.352

If I goto this Website
https://developer.sony.com/develop/open-devices/downloads/open-source-archives
I see different Open source versions. BUT NOT THIS VERSION.

Email comes from here questions.za@support.sonymobile.com
I've sent another one to this site.

I'm wanting to do this because I upgraded to Android Pie not knowing that Phone Recording would be stopped. I've been to the Forms where this has been discussed, In my opinion this should be your choice, not Google stopping the function.

**Comment by pExeen** [comment]
I am having the same problem. Is there any way I can still wipe and advanced wipe without having access to the screen?

**Comment by luk1337** [comment]
twrp-3.3.1-2-pioneer.img should work on 50.2 ^.^

**Comment by bigbiff** [comment]
Thanks to @luk1337 for the investigation and fixing of this issue.

**Comment by thomasrich007** [comment]
Thank you for the hard work . Will try it much later as I use the phone with banking app. So wiping is not a good idea at the moment. Will it work with any XA2 build number. I'm using 50.2.A.0.379
