### ISSUE TITLE
Mi A2 Lite official twrp

### ISSUE THREAD

**Issue by ghost** [TeamWin/Team-Win-Recovery-Project#1471]
I am running an unofficial build of TWRP, downloaded from https://androidfilehost.com/?fid=1395089523397933315
I have searched for my issue and it does not already exist

Mi A2 Lite                 Daisy
3.3.0-0              3.3.0-0 is installed

My issue is, official twrp is not working well, who uses mi a2 lite, they use 33bca's twrp. official one has issue while installing custom roms, backup/restore.

So if you care my post Every Mi A2 Lite users will be happy (I think)

**Comment by bigbiff** [comment]
Please refer to the creator of this unofficial port. We are unable to support unofficial versions of TWRP.
