### ISSUE TITLE
Y550 not booting (again)

### ISSUE THREAD

**Issue by hippi-viking** [TeamWin/Team-Win-Recovery-Project#1477]
- [X] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [X] I am running the latest version of TWRP
- [X] I have read the FAQ (https://twrp.me/FAQ/)
- [X] I have searched for my issue and it does not already exist

**Device codename**: y550
**TWRP version**: 3.3.1-0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
-flash recovery
-boot to recovery

#### WHAT IS THE EXPECTED RESULT?
phone boots to recovery

#### WHAT HAPPENS INSTEAD?
phone does not boot into recovery (of course) :)
probably bootloops at manufacturer logo

#### ADDITIONAL INFORMATION
probably kernel or initramfs issue

**Comment by bigbiff** [comment]
Thanks for the report. I have removed the images and marked this device as not current for support. The last commits were 3 years ago.
