### ISSUE TITLE
OnePlus3 ROM Updates Fail LOS16

### ISSUE THREAD

**Issue by stonerl** [TeamWin/Team-Win-Recovery-Project#1478]
- [x] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**Device**: oneplus3
**TWRP version**: 3.3.1-0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Download a LineageOS-16-nightly update via the build-in updater. Execute the update from within the updater app.

#### WHAT IS THE EXPECTED RESULT?
- auto-reboot into TWRP
- update gets installed
- ueboot into OS
- use phone

#### WHAT HAPPENS INSTEAD?
- auto reboot into TWRP
- update gets installed
- LineageOS boot screen shows up for 2 minutes
- phone boots into recovery again, says "Recovery Fest"
- Phone cannot be booted into LOS anymore

#### ADDITIONAL INFORMATION
Manually installing the update after the failed auto update. Results in all apps permissions being reset and the First Start Assistant being started again. So the phone is kind of factory reset. The userdata are still there though.

**Comment by hammer-is** [comment]
**Device:** oneplus3T
**TWRP version:** 3.3.1-0

I have a similar issue with LineageOS 16 and the build in updater on my OnePlus3**T**. It reboots into TWRP, flashes the new nightly and reboots again. 
Then it prompts me for the pin code and starts booting but hangs at the boot screen forever.

I did several factory resets and (google cloud) restores to pinpoint the issue. **For me it seems it's related to having the phone encrypted.** If the phone is not encrypted there is no issue using the build in updater.

Also note that the upgrade works fine also with phone being encrypted if I boot into recovery and manually install the update.

All my tests where done using lineage-16.0-201906**18**-nightly-oneplus3-signed.zip to lineage-16.0-201906**19**-nightly-oneplus3-signed.zip
I'm using OxygenOS 9.0.3 firmware with locked bootloader

I don't know if TWRP is the issue to be honest...

**Comment by stonerl** [comment]
Well since the maintainer for oneplus3/T LOS and TWRP is the same person, @dianlujitao I guess it does not matter. We just need to make him aware of this issue.

**Comment by CaptainThrowback** [comment]
Try building with this patch: https://gerrit.omnirom.org/c/android_bootable_recovery/+/34338

And see if it helps. It'll prompt for your password, and when entered successfully, it will proceed with the install. Having data decrypted should fix any non-booting issues you're facing.

**Comment by stonerl** [comment]
@CaptainThrowback thank you for your effort. I just figured that the problem isn't caused by TWRP, but rather the scripts in `/system/addon.d`.

The restore-case needs to look like this:
```
  restore)
    list_files | while read FILE REPLACEMENT; do
      R=""
      [ -n "$REPLACEMENT" ] && R="$S/$REPLACEMENT"
      [ -f "$C/$S/$FILE" ] && restore_file $S/"$FILE" "$R"
    done
  ;;
```

Some scripts e.g. addonsu from Lineage are different and do not restore correctly.
