### ISSUE TITLE
Unable to decrypt on d2vzw (Verizon Samsung Galaxy S III) using Stock OS

### ISSUE THREAD

**Issue by ahrenstein** [TeamWin/Team-Win-Recovery-Project#148]
Enabling the encryption on the stock (but rooted) ROM version 4.1.2 (VRBMB1) works, but when entering TWRP I am unable to decrypt. I enter the correct password (typed very slowly and meticulously to be sure) but I get an error saying "Password Failed, Please Try Again"

Encryption is required, but it would be very nice to have the ability to NANDroid backup to an unencrypted eternal sd card I could leave at home.

Thanks

**Comment by Spudnic1** [comment]
I'm having the same issue on a S4 running rooted stock MDK with both the phone and SD card encrypted. TWRP 2.5.0.2. Getting "E: Failed to decrypt data."

**Comment by generalmx** [comment]
I have a different problem, where it says the decryption from rooted stock SGS3 succeeded, but then /data fails to mount. I posted my workaround here: https://github.com/TeamWin/Team-Win-Recovery-Project/issues/174

**Comment by Alxoom33** [comment]
I have same issue with Verizon S4 I was told there is a patch on github, but where is it?

**Comment by scubamike** [comment]
I have the same issue with my d2vzw.
