### ISSUE TITLE
Xiaomi Mi A1 - Screen stays dark after booting

### ISSUE THREAD

**Issue by selste** [TeamWin/Team-Win-Recovery-Project#1481]
- [x] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**tissot**: 
**3.3.0-2**: 

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Power on device in fastboot mode, then run 'fastboot boot twrp-3.3.0-2.img'

#### WHAT IS THE EXPECTED RESULT?
Team Win Recorvery Project Splashscreen should appear, after a few more seconds the regular screen with the various option buttons (Install, Wipe, Backup, etc.) is shown

#### WHAT HAPPENS INSTEAD?
Display stays dark, in case the device is connected to the computer the internal storage is mounted

#### ADDITIONAL INFORMATION
Version 3.3.0-1 is affected as well, Version 3.3.0-0 does not have this problem - boots up as expected, but - unrelated to this issue - fails to install LineageOS 16.0 on the device, sadly.

**Comment by selste** [comment]
[recovery.log](https://github.com/TeamWin/Team-Win-Recovery-Project/files/3317096/recovery.log)

**Comment by bigbiff** [comment]
Hello, I think that is the default recovery.log. Please post the one with your issue documented. Please post dmesg.

**Comment by selste** [comment]
Ran 'fastboot boot [...]' again, and directly afterwards 'dmesg' - this is the output i got:
[dmesg.log](https://github.com/TeamWin/Team-Win-Recovery-Project/files/3319681/dmesg.log)

**Comment by niclimcy** [comment]
Are you on the latest 9.0 firmware?

**Comment by selste** [comment]
I ran into this problem when i tried to upgrade from LineageOS 15.1 to 16.0 - there's currently nothing installed, both slots are empty.

**Comment by TheGabrielHoward** [comment]
> I ran into this problem when i tried to upgrade from LineageOS 15.1 to 16.0 - there's currently nothing installed, both slots are empty.

i have this twrp and is working without problems, as @nicknitewolf said. Yuou need latest pie firmware, try May or June firmware

**Comment by niclimcy** [comment]
Uh if you really can't update with this recovery, I have provided recoveries based off the 3.18 kernel, which your old firmware would definitely support: https://drive.google.com/open?id=1e8iUu8Bsm7ywg9-XZ1eVxsMfxOFhE5my

https://forum.xda-developers.com/mi-a1/development/recovery-twrp-3-2-2-1-touch-recovery-t3821469

**Comment by selste** [comment]
Thx,
but i got twrp 3.2.2-1, unfortunately it doesn't work with LineageOS 16, and i'd really like to install the latest version.
I haven't had a look at the changes made to twrp between 3.3.0-0 and 3.3.0-2, and what could have had any effect regarding the display.

Is there any base firmware update from Xiaomi available that You know of which i could try to apply?

**Comment by selste** [comment]
Just to clarify: I wiped the phone (both slots), am now booting the recovery (twrp) to install the current LineageOS.
TWRP 3.3.0-2 and 3.3.0-1 both sort of boot, but the display stays completely dark, which makes it impossible to install a ROM (LineageOS 16 in my case).

**Comment by selste** [comment]
@nicknitewolf: Successfully flashed the ROM with your version of TWRP for 3.18 kernels - Thanks

FYI - could not flash the current 'MindTheGapps' archive with that TWRP version, i had to use 3.3.0-2

Guess the issue can be closed.

**Comment by bigbiff** [comment]
Thanks for helping out @selste
