### ISSUE TITLE
Payton 3.3.1-0 PGP signatures appear to be incorrect

### ISSUE THREAD

**Issue by koloughlin** [TeamWin/Team-Win-Recovery-Project#1483]
**Device codename**: payton (Moto X4)
**TWRP version**: 3.3.1-0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Navigate to https://dl.twrp.me/payton/, download the TeamWin PGP Public key.

Click on twrp-installer-3.3.1-0-payton.zip, twrp-3.3.1-0-payton.img.  Download the files and the PGP signature files.

Inport the TeamWin PGP Public key with "gpg --import twrp-public.asc".

Verify the signature files with "gpg --verify twrp-installer-3.3.1-0-payton.zip.asc twrp-installer-3.3.1-0-payton.zip" and "gpg --verify twrp-3.3.1-0-payton.img.asc twrp-3.3.1-0-payton.img".  Gpg says both have bad signatures.

$ gpg --verify twrp-installer-3.3.1-0-payton.zip.asc twrp-installer-3.3.1-0-payton.zip
gpg: Signature made Wed 22 May 2019 06:23:16 PM EDT
gpg:                using RSA key 95707D42307C9D41D09BF7091D8597D7891A43DF
gpg: BAD signature from "TeamWin <admin@teamw.in>" [unknown]

$ gpg --verify twrp-3.3.1-0-payton.img.asc twrp-3.3.1-0-payton.img
gpg: Signature made Wed 22 May 2019 06:23:14 PM EDT
gpg:                using RSA key 95707D42307C9D41D09BF7091D8597D7891A43DF
gpg: BAD signature from "TeamWin <admin@teamw.in>" [unknown]

Gpg says the signature files are dated 5/22/2019, which would be strange as the payton 3.3.1 recovery image and installer zip files appear to have been created on 6/15/2019.  Is it possible that the recovery image and installer zip files were built on 5/22/2019, then later rebuilt, but the signature files were not rebuilt?

**Comment by koloughlin** [comment]
I meant to also say that the SHA256 files do have the correct values for twrp-installer-3.3.1-0-payton.zip and twrp-3.3.1-0-payton.img.

**Comment by bigbiff** [comment]
Thanks for the report. The signatures are re-generated and checking out now.
