### ISSUE TITLE
Adding hardware-buttons control for TWRP

### ISSUE THREAD

**Issue by hmtheboy154** [TeamWin/Team-Win-Recovery-Project#1485]
Hello I'm using Nokia 8110 4G and I compiled TWRP for it. But the problem is I can't control twrp because it don't have touchscreen. 
Is TWRP support hardware-buttons control (like CWM) yet ? Because it's kinda nice to see TWRP on a feature phone like this :D

**Comment by CaptainThrowback** [comment]
No. TWRP is a touch-based recovery. You can try using a USB-OTG mouse, if your device supports it.

**Comment by hmtheboy154** [comment]
Oh, that's kinda sad because my device not support USB-OTG (It's a feature phone, I can't even use bluetooth keyboard with it). 
I still hope that someday you guys can support it , because feature phone with KaiOS are becoming more and more relevant now,

**Comment by CaptainThrowback** [comment]
Well, TWRP is open-source, so feel free to submit a patch to add this support in an emergency (perhaps as a build-time flag). The TWRP devs will not be spending time on this as I previously said, since TWRP is a touch-based recovery.

**Comment by 5E7EN** [comment]
@hmtheboy154 I've recently encountered this issue with a Kyocera E4810 touchless device.
I've forked and patched TWRP [here](https://github.com/5E7EN/android_bootable_recovery/tree/android-9.0) to support keypad-based navigation. See the android-9.0 branch.
Feel free to adjust your repo manifest to fetch this version.
