### ISSUE TITLE
This package is for "jfltespr" devices; this is a "jflte".

### ISSUE THREAD

**Issue by gliptak** [TeamWin/Team-Win-Recovery-Project#1489]
- [X] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [X] I am running the latest version of TWRP
- [X] I have read the FAQ (https://twrp.me/FAQ/)
- [X] I have searched for my issue and it does not already exist

**Device codename**: jflte(spr)
**TWRP version**: 3.3.1-0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Try to load old system zip file using current TWRP

#### WHAT IS THE EXPECTED RESULT?
System zip installs

#### WHAT HAPPENS INSTEAD?
```
Starting TWRP 3.3.1-0-f5955b1c on Sat Jul 20 13:30:14 2019
o.boot.bootloader=L720VPUFNG2
I:Set page: 'install'
I:Set page: 'flash_confirm'
I:Set page: 'flash_zip'
I:operation_start: 'Flashing'
Installing zip file '/external_sd/SPH-L720_OK3_Stock_Deodexed.zip'
Checking for Digest file...
I:Update binary zip
I:Extracting updater binary 'META-INF/com/google/android/update-binary'
I:Zip does not contain SELinux file_contexts file in its root.
I:has_legacy_properties: Found legacy property match!
I:Legacy property environment initialized.
script aborted: This package is for "jfltespr" devices; this is a "jflte".
This package is for "jfltespr" devices; this is a "jflte".
Updater process ended with ERROR: 7
I:Legacy property environment disabled.
I:Install took 0 second(s).
Error installing zip file '/external_sd/SPH-L720_OK3_Stock_Deodexed.zip'
```

#### ADDITIONAL INFORMATION
I'm installing older image to run carrier reset/PRL

https://github.com/TeamWin/Team-Win-Recovery-Project/issues/297

**Comment by bigbiff** [comment]
Zip install issues must be reported to the creator due to TWRP only executes updater binary in the zip, which proceeds to install the contents. Closing issue.

**Comment by gliptak** [comment]
Is there a way for TWRP to report a list of compatible device types (as jflte just replaced a number of other device types including jfltespr)?

**Comment by bigbiff** [comment]
It's defined by the PRODUCT_NAME typically, and it has to be matched by the zip creator. Both names can be arbitrary, so there is no feasible method for this unfortunately.

**Comment by gliptak** [comment]
@bigbiff thank you for the clarification
