### ISSUE TITLE
android_device_xiaomi_pine

### ISSUE THREAD

**Issue by 13-beta2** [TeamWin/Team-Win-Recovery-Project#1495]
Hi team,

Probably you missed it, but I sent an email with suggestion to use [my device tree](https://github.com/13-beta2/android_device_xiaomi_pine) for Redmi 7A few weeks ago. It is 100% working and ready to deploy.

**Comment by bigbiff** [comment]
Thanks for letting us know about it. Would you be willing to be the new maintainer for his device?

**Comment by 13-beta2** [comment]
Not really. I'm afraid I don't have enough relevant experience.

**Comment by bigbiff** [comment]
Closing this issue for now. Please let us know if you change your mind.

**Comment by JarlPenguin** [comment]
I'd be interested in maintaining this with @13-beta2, if he'd like to be the main maintainer.
