### ISSUE TITLE
walleye: Unable to decrypt data partition

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [TeamWin/Team-Win-Recovery-Project#1497]
- [x] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**Device codename**: walleye
**TWRP version**: 3.3.0-0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
- Enable encryption by setting PIN or pattern
- Attempt to decrypt in TWRP

#### WHAT IS THE EXPECTED RESULT?
For TWRP to successfully decrypt

#### WHAT HAPPENS INSTEAD?
TWRP fails to decrypt the partition.

#### ADDITIONAL INFORMATION
n/a

`/tmp/recovery.log`: https://paste.omnirom.org/view/1e35ea96
`dmesg`: https://paste.omnirom.org/view/bef3717d

**Comment by ThatNerdyPikachu** [comment]
> NOTE: Monthly security updates may break decrypt in TWRP. MTP does not work at this time, but you can use adb to transfer files.

**Comment by kesavanm** [comment]
What is the fix ?
