### ISSUE TITLE
Install TWRP recovery for Infinix Smart 2 X5515

### ISSUE THREAD

**Issue by thewebinarts** [TeamWin/Team-Win-Recovery-Project#1499]
Hello everyone,

I am looking for a version of twrp.img for Infinix Smart 2 X5515. But the website https://twrp.me/ I can not find that, only for the Infinix Hot 2 that you have on the website.

**Comment by bigbiff** [comment]
Porting requests should not be a an open issue against TWRP. Closing issue.
