### ISSUE TITLE
[enhancement] I9300, backup of /data/media (fuse filesystem)

### ISSUE THREAD

**Issue by qwerty22** [TeamWin/Team-Win-Recovery-Project#150]
Please add the ability to create a backup of /storage/sdcard0 on Galaxy S3 I9300.
The current version of TWRP makes a copy of partition DATA without sdcard0.

**Comment by bigbiff** [comment]
Why backup sdcard?

**Comment by qwerty22** [comment]
With the use of a multivolume archive for external card with fat32 ... Please explain your question.

About sdcard:
#mount
/dev/fuse /storage/sdcard0 fuse rw,nosuid,nodev,noexec,relatime,user_id=1023,group_id=1023,default_permissions,allow_other 0 0

**Comment by qwerty22** [comment]
Ok, I see in File Manager TWRP 2.5.0.0 dtrectory /sdcard (/data/media) and /external_sd (extSdCard, fat32)
In Terminal I run
tar -czf /external_sd/sd_backup.tgz /sdcard
After a very long time I got file sd_backup.tgz - 4 176 847 630 bytes (3.99Gb)
After that, I tried to run Backup but got the red message FAIL. Bug? After reload TWRP backup was successful.

**Comment by bigbiff** [comment]
Please always remember to upload recovery.log so we can see what happened.

**Comment by qwerty22** [comment]
# tar -cvzf external_sd/backup_sd.tgz /sdcard

was successful. After that, I tried to run Backup with all options (EFS, DATA etc.) and got the red message FAIL
Log: http://fcpm.ru/temp/recovery.rar

**Comment by qwerty22** [comment]
Please add the base ability to create a backup of /sdcard on Galaxy S3 I9300.
