### ISSUE TITLE
Check currently installed version of TWRP from `bash` on Android

### ISSUE THREAD

**Issue by tukusejssirs** [TeamWin/Team-Win-Recovery-Project#1502]
Sorry to posting a non-isue, but I’d like to get the currently installed version of TWRP from Android shell.

Reason: I’d like to create a shell script to upgrade TWRP on my OnePlus 3T whenever there is available newer version than the one already installed. Tasker would help me out with the scheduler part. Similarly to my [`ogus.sh`](https://github.com/tukusejssirs/lnx_scripts/blob/master/bash_functions/termux/) script that updates OpenGApps.

I asked this question [here](https://android.stackexchange.com/questions/216439/how-to-check-installed-twrp-version?noredirect=1) too, but I think it is better to be asked here, for if currently there is no way to check the version TWRP, it’d be nice to add it to `/persist/.twrps`.

**Comment by bigbiff** [comment]
Please only open issues specific to TWRP. This should be discussed elsewhere.

**Comment by tukusejssirs** [comment]
Okay, I get it, but could you tell me where is it appropriate to discuss this?

Still I think that this is _not_ a discussion, but a way to get a (sort of) _support_ to get the version of the TWRP.

**Comment by tukusejssirs** [comment]
I think TWRP should add `ro.twrp.version` entry to `/system/build.prop`. This entry already exists in TWRP backups in `recovery.log`, but not in `/system/build.prop` (and therefore it is not accessible using `getprop`. This would be very helpful to have. (Firelord from android.sx pointed me into this direction in his [comment](https://android.stackexchange.com/users/96277/firelord)).

**Comment by CaptainThrowback** [comment]
Adding a TWRP version to system/build.prop isn't feasible. For all current Android devices, touching the system partition is a big no-no, breaking dm-verity and preventing the device from even booting. But again, this isn't a TWRP issue, and this issue has been closed. Please discuss elsewhere.

**Comment by Str33t10** [comment]
for i in /sdcard/recovery.log; do
  recovery=$(grep -m 2 -E " Recovery v|Starting TWRP|Welcome to|PhilZ|Starting recovery \(" $i)
  case "$recovery" in
    *Welcome*)  recovery="$(grep -m 1 "Welcome to" $i | awk '{ print substr($0, index($0,$3)) }')$(grep -m 1 "^ext.version" $i | cut -d\" -f2)"; break;;
    *Recovery*) recovery=$(grep -m 1 "Recovery v" $i); recovery=${recovery/Recovery v/Recovery }; break;;
    *PhilZ*)    recovery=$(grep -m 2 -E "PhilZ|ClockworkMod" $i); recovery="${recovery/ClockworkMod v/(ClockworkMod })"; break;;
    *Starting\ recovery\ \(*) recovery=$(grep -m 1 "ro.cm.version=" $i| sed -e 's/.*ro.cm.version=/CM Recovery /gI'); break;;
    Starting*) recovery=$(echo "$recovery" | awk -F"Starting " '{ print $2 }' | awk -F" on " '{ print $1 }'); break;;
  esac
done
echo $recovery
