### ISSUE TITLE
TWRP 3.3.1-0 + Samsung S5, hangs with adoptable storage

### ISSUE THREAD

**Issue by huang-jy** [TeamWin/Team-Win-Recovery-Project#1504]
- [x] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**Device codename**: klte (Samsung S5)
**TWRP version**: 3.3.1-0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Enable adoptable storage in OS (I'm using Lineage OS), but it shouldn't make a difference which.
![image](https://user-images.githubusercontent.com/2756283/64332512-9d3fe880-cfcc-11e9-94ad-1ec2075e2897.png)

Reboot to recovery (for example to install an update)

#### WHAT IS THE EXPECTED RESULT?
TWRP runs

#### WHAT HAPPENS INSTEAD?
TWRP hangs on the splash screen

#### ADDITIONAL INFORMATION
This setup worked fine when I didn't have my sdcard formatted as adoptive storage 

`/tmp/recovery.log`: No file exists for /tmp/recovery.log
`dmesg`: https://paste.omnirom.org/view/e26fccb8

EDIT: Additional info.

When I tried to boot into recovery manually, and it hung, I decided to yank the sdcard out (not clean, I know)

I saw a mass of errors in the console, all paths in `/external_sd/`

Could TWRP still be expecting my sdcard to be "portable" and not adoptable? Hence why it's looking for /external_sd (since I used to install zips off the Download folder on the sd card when it was portable storage?)

**Comment by huang-jy** [comment]
Additional: When trying to get a logcat as TWRP starts up with adoptable storage, the logcat never even starts:

```
adb logcat | tee logcat.txt
- waiting for device -
```

**Comment by bigbiff** [comment]
logcat via adb isn't supported in TWRP.

**Comment by huang-jy** [comment]
Yes, but I still have no idea why TWRP hangs when I have an adoptable storage card in the phone

**Comment by huang-jy** [comment]
EDIT: Additional info.

When I tried to boot into recovery manually, and it hung, I decided to yank the sdcard out (not clean, I know)

I saw a mass of errors in the console, all paths in `/external_sd/`

Could TWRP still be expecting my sdcard to be "portable" and not adoptable? Hence why it's looking for /external_sd (since I used to install zips off the Download folder on the sd card when it was portable storage?)
