### ISSUE TITLE
TWRP filled up persist partition on crosshatch 

### ISSUE THREAD

**Issue by UltraPower31** [TeamWin/Team-Win-Recovery-Project#1506]
TWRP is writing its log files onto the persist partition. The partition's size is only 40MB, my log file on it was 20MB after using TWRP multiple times. For the Android Q update at some point files need to be copied to persist to make the sensors work but that's not possible when TWRP is filling up the partition with its log files. 
I would advise to not write to this partition at all.

**Comment by SyberHexen** [comment]
I'm reporting the same issue is present on Motorola G7 devices which only have a 27 mb persist partition, the logs exceed 8mb a piece making the partition 98% full which leads to the persist being over filled and out of space.

**Comment by bigbiff** [comment]
Hello, tonight -3 will be up on twrp.me and will start compressing the log files in /persist.

Sorry for the issues. I might consider adding the ability to disable storing logs on the device.

**Comment by SyberHexen** [comment]
> Hello, tonight -3 will be up on twrp.me and will start compressing the log files in /persist.
> 
> Sorry for the issues. I might consider adding the ability to disable storing logs on the device.

It's all good!
A BoardConfig.mk flag to disable logging of last_log and log would also solve the issue.
Otherwise I've submitted a patch [Here](https://gerrit.omnirom.org/c/android_bootable_recovery/+/35815) on gerrit.
 It appears writing these files to persist/cache/recovery vs data/cache/recovery on a/b devices could be in error?

**Comment by bigbiff** [comment]
Between log compression and detecting the correct location this issue is completed.

**Comment by UltraPower31** [comment]
Just a heads up. Seems like modifying this partition is breaking DRM Level 1. So please stop writing to persist at all
