### ISSUE TITLE
data partition Restore From Backup fails

### ISSUE THREAD

**Issue by bombardinotungtung** [TeamWin/Team-Win-Recovery-Project#1510]
- [y ] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [y ] I am running the latest version of TWRP
- [y ] I have read the FAQ (https://twrp.me/FAQ/)
- [n ] I have searched for my issue and it does not already exist

**Device codename**: dumpling (OnePlus 5T)
**TWRP version**: 3.3.1-0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
 TRY TO RESTORE FROM BACKUP 

#### WHAT IS THE EXPECTED RESULT?
BACKUP SUCCESSFULLY 

#### WHAT HAPPENS INSTEAD?
 extractTarFork() process ended with ERROR: 255 

#### ADDITIONAL INFORMATION
 Backed up to usb drive.Tried all fixes.there is 30g of free space .still cant restore data.everything except data restores succesfully.i dont get why it backups fine but doesnt restores.i need to restore it asap because i have all my 2FA keys bitcoin keys and recovery files inside my phone.i trusted twrp and now fucked up some people suggested to remove user 999 but i already backed up so i cant do that. 

`/tmp/recovery.log`: 
`dmesg`:

**Comment by bigbiff** [comment]
Hello, we must have the required logs requested in the template for any debugging of your issue.

**Comment by baritonerosecandytea** [comment]
i only have recovery.log from backup.no os is installed at the time i tried to restore.now i flashed original firmware but i have full backup .here is log its 50Mb so i uploaded to cloud.

https://drive.google.com/file/d/1bWBgXqeGPuY_mYT_8aXs3jZDgdQj9nlt/view

**Comment by bigbiff** [comment]
I see no errors backing up the data partition. Can you upload the log showing TWRP trying to restore data?

**Comment by baritonerosecandytea** [comment]
i dont get any log .just the "extractTarFork() process ended with ERROR: 255"

**Comment by CaptainThrowback** [comment]
@doggukan you have to pull the log after the failed restore attempt, either using adb or TWRP's "Copy Log" feature. The former probably makes the most sense in your case. The recovery log is always stored in /tmp as recovery.log. So using the command "adb pull /tmp/recovery.log" from your computer will pull the log to the folder you're running the command from on your computer and allow you to upload it.
