### ISSUE TITLE
Bad signature twrp-3.3.1-0-nozomi.img

### ISSUE THREAD

**Issue by ionphractal** [TeamWin/Team-Win-Recovery-Project#1515]
- [x] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [ ] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**Device codename**: nozomi
**TWRP version**: 3.3.1-0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Download 
* 391fb40eae7c17887be0ada0509ca8cf0fcd8cb063ef1c44bc6b2c09e7071da6  twrp-3.3.1-0-nozomi.img https://eu.dl.twrp.me/nozomi/twrp-3.3.1-0-nozomi.img.sha256
* image and signature https://eu.dl.twrp.me/nozomi/twrp-3.3.1-0-nozomi.img.html
* public key https://eu.dl.twrp.me/nozomi/
```
~/Downloads % gpg --import twrp-nozomi-public.asc
gpg: key 0x1D8597D7891A43DF: public key "TeamWin <admin@teamw.in>" imported
gpg: Total number processed: 1
gpg:               imported: 1
~/Downloads % sha256sum twrp-3.3.1-0-nozomi.img                   :(
391fb40eae7c17887be0ada0509ca8cf0fcd8cb063ef1c44bc6b2c09e7071da6  twrp-3.3.1-0-nozomi.img
~/Downloads % gpg --verify twrp-3.3.1-0-nozomi.img.asc     :(
gpg: assuming signed data in 'twrp-3.3.1-0-nozomi.img'
gpg: Signature made Thu May 23 00:17:48 2019 CEST
gpg:                using RSA key 95707D42307C9D41D09BF7091D8597D7891A43DF
gpg: BAD signature from "TeamWin <admin@teamw.in>" [unknown]
```

FYI twrp-3.3.0-1-nozomi.img has a valid signature.

#### WHAT IS THE EXPECTED RESULT?
Signature should be valid

#### WHAT HAPPENS INSTEAD?
Signature is invalid

**Comment by scde** [comment]
I can confirm the issue and am seeing the same for the [3.3.1 surnia image](https://eu.dl.twrp.me/surnia/twrp-3.3.1-0-surnia.img.html). The images before that were properly signed but this latest version (twrp-3.3.1-0-surnia.img) isn't any more.

Maybe something in the signing process of the release build went wrong?

Anyway thanks in advance and have a nice day.

**Comment by bigbiff** [comment]
Thanks for the report. I have had the images re-signed and verified the signatures are correct.
