### ISSUE TITLE
LineageOS 16 OTA  Update error @cache/recovery/block.map 

### ISSUE THREAD

**Issue by daywalk3r666** [TeamWin/Team-Win-Recovery-Project#1517]
- [ √] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [√ ] I am running the latest version of TWRP
- [√ ] I have read the FAQ (https://twrp.me/FAQ/)
- [ √] I have searched for my issue and it does not already exist

**Device codename**: j5nxlte
**TWRP version**: 3.3.1-0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
download the ota update and install it

#### WHAT IS THE EXPECTED RESULT?
TWRP installs OTA Update 

#### WHAT HAPPENS INSTEAD?
Install ends with error @cache/recovery/block.map

#### ADDITIONAL INFORMATION
https://daywalk3r666.ocloud.de/index.php/s/xxacvNiKEP2Xpo4

with TWRP_3.2.3_j5xnlte_20181222_jenslody works ota without any problems

https://android.jenslody.de/BootleggersROM/j5xnlte/TWRP/TWRP_3.2.3_j5xnlte_20181222_jenslody.img

`/tmp/recovery.log`: https://paste.omnirom.org/view/dc86a252
`dmesg`: https://paste.omnirom.org/view/e647dc28

**Comment by Exodusnick** [comment]
hopefully you'll find the clue.
that ota also works in the TWRP 3.3.1-0 version.
