### ISSUE TITLE
Twrp 2.5.0.0 breaks decryption

### ISSUE THREAD

**Issue by frankieGom** [TeamWin/Team-Win-Recovery-Project#153]
Twrp 2.5.0.0 breaks decryption on gt-n7105 running wanamLite v1.2 (xxdmb3 based] and adam kernel 1.3+
Recovery.log: http://tinyw.in/er3X

**Comment by bigbiff** [comment]
Can you flash http://techerrata.com/bigbiff/n7100.img and post recovery.log after trying decryption? Also is that ROM Touchwiz based?

**Comment by frankieGom** [comment]
I only have the Note 2 and mobile odin with meUnfortunately. Could you 
make that a tar, please?

And yes this is a touchwiz based rom.

François

**Comment by bigbiff** [comment]
Mobile odin will flash .img files.

**Comment by frankieGom** [comment]
Not here. It only lists tar files...

Worst case it will take a little longer before I can try you test load. 
No big deal.

## 

A+
François

**Comment by bigbiff** [comment]
I was able to select img files in the recovery section.

**Comment by frankieGom** [comment]
Weird. I tried both the open file and recovery sections with the same result.

This is on the paid for version which also won't allow me to select files 
on the sdcard as it does not seem to support 64GB media.

## Will hopefully be able to try layer today.

A+
François

**Comment by bigbiff** [comment]
Here is the tar version if you still need it: http://techerrata.com/bigbiff/n7100.img.tar. I will create odin tars for you from now on.

**Comment by frankieGom** [comment]
On 12/04/2013 13:08, bigbiff wrote:

> Here is the tar version if you still need it: 
> http://techerrata.com/bigbiff/n7100.img.tar. I will create odin tars 
> for you from now on.
> 
> ---
> 
> Reply to this email directly or view it on GitHub 
> https://github.com/TeamWin/Team-Win-Recovery-Project/issues/153#issuecomment-16287411.
> 
> Thanks! Actually, I finally got a PC and time to take the trace (right 
> as you were ending this, it so happens!) ;)

I don't know why it is such, but I had to dd the img through adb. Now, I 
see I could have applied it through a terminal in the device, but it is 
simpler to apply the tar through MobileOdin and less risky, so please do 
provide tars from now on.

here is the log from last night's build (assuming it is the same at today's)
http://tinyw.in/NFrd

François

**Comment by bigbiff** [comment]
I will send up a new test build, but I think it's executing the wrong code for checking MAGIC values. Thanks for testing quickly. Uploaded under same link: http://techerrata.com/bigbiff/n7100.img.tar

**Comment by frankieGom** [comment]
You're welcome. I like this recovery very much. Never was really hot on CWM, and the support was not as extensive (I have an AT&T Jetstream as well, which now has its own port of TWRP). I believe the project deserves the effort (I would participate if I had the time, but testing _is_ my specialty!)

If I read the 2.5 release notes correctly, a fix to a decrypting problem on certain devices was made. It must have introduced the regression...

----- Mail original -----
De: "bigbiff" notifications@github.com
À: "TeamWin/Team-Win-Recovery-Project" Team-Win-Recovery-Project@noreply.github.com
Cc: "frankieGom" francois.fornier@gmx.net
Envoyé: Vendredi 12 Avril 2013 13:50:12
Objet: Re: [Team-Win-Recovery-Project] Twrp 2.5.0.0 breaks decryption (#153)

I will send up a new test build, but I think it's executing the wrong code for checking MAGIC values. Thanks for testing quickly.

**Comment by bigbiff** [comment]
The crypt stuff was moved to a lib to avoid GPL violations.

**Comment by kristjankullerkann** [comment]
Probably same issue with Samsung Galaxy S3 (i9300 international).
recovery.log:
http://tinyw.in/y9Og

**Comment by frankieGom** [comment]
On 12/04/2013 14:37, bigbiff wrote:

> The crypt stuff was moved to a lib to avoid GPL violations.
> 
> ---
> 
> Reply to this email directly or view it on GitHub 
> https://github.com/TeamWin/Team-Win-Recovery-Project/issues/153#issuecomment-16290502.
> 
> Maybe, but also this:
> -Fixed a problem with decryption not being able to locate the decryption 
> key in some situations

Found in the 2.5.0.0 change log.

**Comment by bigbiff** [comment]
frankieGom, have you been able to run any new backups with the new image I posted above?

**Comment by frankieGom** [comment]
On 15/04/2013 16:20, bigbiff wrote:

> frankieGom, have you been able to run any new backups with the new 
> image I posted above?
> 
> ---
> 
> Reply to this email directly or view it on GitHub 
> https://github.com/TeamWin/Team-Win-Recovery-Project/issues/153#issuecomment-16387494.
> 
> I only saw the .img, then the .tar which I thought was the same build. I 
> only flashed the .img which would not decrypt my device and forwarded 
> the corresponding log.

I will try the tar right away, just in case it is a different build and 
report back.

sorry about that
François

**Comment by bigbiff** [comment]
It is a different build. I just called it the same file on te.

**Comment by bigbiff** [comment]
Trying to get info from your device, can you redownload the same file, install and upload recovery.log.

**Comment by bigbiff** [comment]
Please install http://techerrata.com/bigbiff/n7100-2.img.tar and upload log. Thank you for your help. I am trying to figure out if something changed in your encryption footer.

**Comment by frankieGom** [comment]
On 16/04/2013 14:37, bigbiff wrote:

> Please install http://techerrata.com/bigbiff/n7100-2.img.tar and 
> upload log. Thank you for your help. I am trying to figure out if 
> something changed in your encryption footer.
> 
> ---
> 
> Reply to this email directly or view it on GitHub 
> https://github.com/TeamWin/Team-Win-Recovery-Project/issues/153#issuecomment-16441970.

Here goes: http://tinyw.in/oa61

But I don't expect anything to have changed in that respect. How would 
we reconcile that with the fact that Touchwiz still decrypts the 
partitions fine, as does TWRP2.4.4.0?

**Comment by bigbiff** [comment]
I am having you debug the issue for me, because I don't have an encrypted device to test with. For some reason it's not printing my new log messages. Let me try another link. If you don't have time to test let me know and I will try to find another tester.

**Comment by frankieGom** [comment]
On 16/04/2013 18:37, bigbiff wrote:

> I am having you debug the issue for me, because I don't have an 
> encrypted device to test with. For some reason it's not printing my 
> new log messages. Let me try another link. If you don't have time to 
> test let me know and I will try to find another tester.
> 
> ---
> 
> Reply to this email directly or view it on GitHub 
> https://github.com/TeamWin/Team-Win-Recovery-Project/issues/153#issuecomment-16455866.
> 
> Understood.
> The file I last flashed is recovery.img last modified April 16 @2:35pm 
> and it is 7067648 bytes big.

Isn't there a way for you to check that new log messages (those not 
direcltly linked to decryption) appear on your device? Just to make sure 
there is nothing really basic at play here...

**Comment by bigbiff** [comment]
Please try: http://techerrata.com/bigbiff/n7100-test.img.tar and upload log. I changed the version string to make sure we are getting the right one.

**Comment by frankieGom** [comment]
On 16/04/2013 19:07, bigbiff wrote:

> Please try: http://techerrata.com/bigbiff/n7100-test.img.tar
> 
> ---
> 
> Reply to this email directly or view it on GitHub 
> https://github.com/TeamWin/Team-Win-Recovery-Project/issues/153#issuecomment-16457690.

http://tinyw.in/0H1Q

the first line says "Starting TWRP 2.5.0.0test1"

**Comment by bigbiff** [comment]
http://techerrata.com/bigbiff/n7100-test2.img.tar - please try this one for debugging information. Still trying to get your magic # printed in the logs.

**Comment by frankieGom** [comment]
On 16/04/2013 19:45, bigbiff wrote:

> http://techerrata.com/bigbiff/n7100-test2.img.tar - please try this 
> one for debugging information. Still trying to get your magic # 
> printed in the logs.
> 
> ---
> 
> Reply to this email directly or view it on GitHub 
> https://github.com/TeamWin/Team-Win-Recovery-Project/issues/153#issuecomment-16460027.
> 
> Forgot to add: behaviour was different this time around. Instead of 
> getting an incorrect password error message, in red, that leaves me with 
> the password filed still filled in, I get the TeamWin splash screen and 
> then back to the password field screen except this time it's been cleared.

http://tinyw.in/tMw6

**Comment by bigbiff** [comment]
Yeah my print was segfaulting. I need to figure out the data type I am trying to print out. I will send you a test build after that.

**Comment by bigbiff** [comment]
New build: http://techerrata.com/bigbiff/n7100-test3.tar

Changed the printf to use unsigned int according to the structure value.

**Comment by frankieGom** [comment]
On 17/04/2013 14:34, bigbiff wrote:

> New build: http://techerrata.com/bigbiff/n7100-test3.tar
> 
> Changed the printf to use unsigned int according to the structure value.
> 
> ---
> 
> Reply to this email directly or view it on GitHub 
> https://github.com/TeamWin/Team-Win-Recovery-Project/issues/153#issuecomment-16502772.
> 
> Here goes: http://tinyw.in/1ONQ
> And I confirm no more TeamWin splash screen

François

**Comment by bigbiff** [comment]
Same link as above, changed lseek64 back to lseek.

**Comment by bigbiff** [comment]
Try this please: http://techerrata.com/bigbiff/n7100-test4.img.tar

**Comment by frankieGom** [comment]
On 17/04/2013 17:00, bigbiff wrote:

> Try this please: http://techerrata.com/bigbiff/n7100-test4.img.tar
> 
> ---
> 
> Reply to this email directly or view it on GitHub 
> https://github.com/TeamWin/Team-Win-Recovery-Project/issues/153#issuecomment-16510959.
> 
> And another: http://tinyw.in/UKwh

Are you getting the data you need to isolate the problem? Have you tried 
comparing the code in 2.4.4.0 to 2.5.0.0?

**Comment by bigbiff** [comment]
Yes, you can do that easily right here in github. I am leaning toward your magic changing for some reason. Might need to get back with the original code submitter.

**Comment by frankieGom** [comment]
On 17/04/2013 17:54, bigbiff wrote:

> Yes, you can do that easily right here in github. I am leaning toward 
> your magic changing for some reason.
> 
> ---
> 
> Reply to this email directly or view it on GitHub 
> https://github.com/TeamWin/Team-Win-Recovery-Project/issues/153#issuecomment-16514384.
> 
> You certainly do know better than me, yet I fail to understand how the 
> magic could change and break 2.5.0.0 code while the older code (as well 
> as the regular ROM) still fare well. It's puzzling.

Do I understand correctly that the magic in question is part of the data 
needed to decrypt, that was generated when the device was encrypted? I 
definitely would not trust SW that can change its mind about that (the 
ROM that is, not TWRP).

I couldn't be a stray offset when reading the data, making it invalid?

Would it be possible to trace the 2.4.4.0 code as well and check what it 
reads and where?

**Comment by bigbiff** [comment]
I am guessing it's reading the wrong part of the footer, but I haven't found any code changes that would indicate why. The last build I put up was changed to use lseek instead of lseek64 which was the only thing I could see that could affect anything.

**Comment by bigbiff** [comment]
Please try http://goo.im/devs/OpenRecovery/n7100/openrecovery-twrp-2.5.0.1-n7100.img.tar

**Comment by frankieGom** [comment]
On 18/04/2013 19:41, bigbiff wrote:

> Please try 
> http://goo.im/devs/OpenRecovery/n7100/openrecovery-twrp-2.5.0.1-n7100.img.tar
> 
> ---
> 
> Reply to this email directly or view it on GitHub 
> https://github.com/TeamWin/Team-Win-Recovery-Project/issues/153#issuecomment-16591343.
> 
> That seems to work a lot better! ;)
> So you did it! You finally found out what it was... So, what went wrong?

Currently doing a backup to confirm all is well. I did get the 
recovery.log anyway, so just let me know if you need to see it.

Are there traces in that build that need to be removed?

François

**Comment by bigbiff** [comment]
Missing cflags was the culprit. We only leave debugs in when necessary.
http://review.teamw.in/#/c/594/
