### ISSUE TITLE
Samsung  galaxy a50 sm-a505gt

### ISSUE THREAD

**Issue by Flasker99** [TeamWin/Team-Win-Recovery-Project#1533]
Hello guys,
TWRP 3.3.1-0 work with phone Samsung  galaxy a50 sm-a505gt?

Because with Odin and magisk manager give me error in finish.

Please help me

**Comment by Flasker99** [comment]
> Please help me

**Comment by bigbiff** [comment]
It looks like we currently don't support this device.
