### ISSUE TITLE
Stuck in TWRP

### ISSUE THREAD

**Issue by Vanman989** [TeamWin/Team-Win-Recovery-Project#1537]
This keeps rebooting into TWRP and not my normal system unless I wipe/factory reset. I used twrp-3.3.1-0-davinci.img and MIUI Global 11.0.1.

**Comment by curiousrom** [comment]
Several users reported fail to boot & being thrown back to TWRP if you select install the TWRP app when asked in TWRP before booting to System.

**Comment by Vanman989** [comment]
Sorry. It is installing Magisk that causes the bootloop into recovery.

**Comment by bigbiff** [comment]
Thanks, closing as non TWRP issue.
