### ISSUE TITLE
twrp-3.3.1-0-jellypro.img fastboot flash doesn't install

### ISSUE THREAD

**Issue by ghost** [TeamWin/Team-Win-Recovery-Project#1546]
- [twrp-3.3.1-0-jellypro.img ] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [twrp-3.3.1-0] I am running the latest version of TWRP
- [yes] I have read the FAQ (https://twrp.me/FAQ/)
- [yes] I have searched for my issue and it does not already exist

**Device codename**: FABYIVDUCIY9KRQO
**TWRP version**: twrp-3.3.1-0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
# Check adb recognizes the device
$ adb devices
List of devices attached
* daemon not running; starting now at tcp:5037
* daemon started successfully
FABYIVDUCIY9KRQO        device

$ adb reboot bootloader
# Check fastboot recognizes the device
$ fastboot devices
FABYIVDUCIY9KRQO        fastboot
$ fastboot flash recovery twrp-3.3.1-0-jellypro.img
target reported max download size of 134217728 bytes
Sending 'recovery' (15212 KB)...
OKAY [  0.568s]
Writing 'recovery'...
OKAY [  0.469s]
Finished. Total time: 1.051s
$ fastboot reboot
Rebooting...

Finished. Total time: 0.059s
$ adb reboot recovery

#### WHAT IS THE EXPECTED RESULT?
See TWRP menu where to install zips, take backups, or
restore them.

#### WHAT HAPPENS INSTEAD?
A droid belly up with a red alert symbol turns up, with
a message stating "no command"

#### ADDITIONAL INFORMATION
Not to my knowledge.

Thanks!

**Comment by bigbiff** [comment]
You need to boot TWRP before android or it will be overwritten with stock recovery. This isn't a TWRP issue so closing.

**Comment by ghost** [comment]
Right, thanks @bigbiff !
