### ISSUE TITLE
Delta update issue

### ISSUE THREAD

**Issue by Viraj8456** [TeamWin/Team-Win-Recovery-Project#1553]
- [Y] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/Potter
- [Y] I am running the latest version of TWRP
- [Y] I have read the FAQ (https://twrp.me/FAQ/)
- [Y] I have searched for my issue and it does not already exist

**Device codename**: Potter
**TWRP version**: 3.3.1-0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
We are unable to flash Delta updates which is a New thing in Pixel experience ROM files in which have a new incremental package. The error and the logs we get is in the attachment below. Please provide a fix for it...
[Screenshot_2019-10-04-03-18-47](https://user-images.githubusercontent.com/36239072/72529934-4c060680-3894-11ea-93d9-53b7b8265d59.png)

#### WHAT IS THE EXPECTED RESULT?
It should flash the zip file as on other phones

#### WHAT HAPPENS INSTEAD?
we get an error 7

#### ADDITIONAL INFORMATION

`/tmp/recovery.log`: 
`dmesg`:

**Comment by bigbiff** [comment]
This is an issue with the zip not mounting system correctly. Please report this issue to the ROM creator.
