### ISSUE TITLE
Cannot download a file from site

### ISSUE THREAD

**Issue by vi** [TeamWin/Team-Win-Recovery-Project#1554]
#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Try to download official TWRP installer version 3.3.1-3 for Google Pixel 3 XL.

#### WHAT IS THE EXPECTED RESULT?
Browser saves a file

#### WHAT HAPPENS INSTEAD?
Download link lands on the very page with that download link.

#### ADDITIONAL INFORMATION
```
$ curl --head https://eu.dl.twrp.me/crosshatch/twrp-installer-3.3.1-3-crosshatch.zip
HTTP/1.1 200 OK
...
Content-Type: text/html
```

**Comment by bigbiff** [comment]
Please do not open issues that are not related to running TWRP. You need to have referrer set.

**Comment by vi** [comment]
Shall site problems be reported to https://twrp.me/contactus/ instead?
