### ISSUE TITLE
Twrp for J530X and J730X

### ISSUE THREAD

**Issue by Diobrando-prog** [TeamWin/Team-Win-Recovery-Project#1555]
I was wondering why the j530x and j730x are not supported by you? because we have twrp but it’s not official and it’s so outdated, we don’t have Dev to complement and much less to update, including the twrp we have is 3.3.0 and it’s not supporting the android pie, this is leaving the J community dies , I know it's not your problem, but the J 2017 line community asks for help .. we are tired of asking for help and nobody came to help

**Comment by bigbiff** [comment]
Please don't use this as a device request forum. We have limited resources and can't support every phone.
