### ISSUE TITLE
[BUG] TWRP backup files stored in wrong path

### ISSUE THREAD

**Issue by urain39** [TeamWin/Team-Win-Recovery-Project#1563]
- [x] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**Device codename**: m1721 
**TWRP version**: 3.3.1-0 

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?

When i try to backup or restore a system.

#### WHAT IS THE EXPECTED RESULT?

Backup files should stored in(or select from) `TWRP/BACKUPS/<serialno>` directory.

#### WHAT HAPPENS INSTEAD?

Actually backup files stored directly in TWRP or sdcard and external_sd(if no TWRP directory). And same as backup, restore a backup can only select from TWRP or sdcard and external_sd(sub-directory is not allowed).

#### ADDITIONAL INFORMATION

`/tmp/recovery.log`: 
`dmesg`:

**Comment by bigbiff** [comment]
Please provide recovery.log for debugging purposes.

**Comment by urain39** [comment]
> Please provide recovery.log for debugging purposes.

Sorry, this problem has been resolved.

 I formatted cache partition and removed the `.twrps` config under the /persist.

So i personally think that this problem may be related to the `.twrps` config file.

**Comment by urain39** [comment]
Hope this info useful for you.

**Comment by bigbiff** [comment]
Unfortunately we need the recovery.log to see what happened. Please re-open if you can upload it.
