### ISSUE TITLE
Twrp App installation bug AOSP ROMS

### ISSUE THREAD

**Issue by Ko-Hi-Dev** [TeamWin/Team-Win-Recovery-Project#1571]
- [X] I am running an official build of TWRP, downloaded from https://dl.twrp.me/cepheus/
- [X] I am running the latest version of TWRP
- [X] I have read the FAQ (https://twrp.me/FAQ/)
- [X] I have searched for my issue and it does not already exist

**Cepheus**:
**TWRP version 3.3.1-0**:

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Install twrp as system app causes bootloop on any AOSP 10 ROM (Cepheus)

#### WHAT IS THE EXPECTED RESULT?
System should boot normally

#### WHAT HAPPENS INSTEAD?
System got stuck in a boot loop after installed and trigger rescue party.

#### ADDITIONAL INFORMATION
The issue is causes by permissions in the app which seems to crash system on startup.

https://paste.omnirom.org/view/0b69c651

Issue is caused by android.permission.BATTERY_STATS, me.twrp.twrp: android.permission.PACKAGE_USAGE_STATS, me.twrp.twrp: android.permission.READ_PRECISE_PHONE_STATE}

Removing the permissions solves the issue

**Comment by galenzhao** [comment]
hi how can I remove the app from recovery?
or fix this problem.

**Comment by Ko-Hi-Dev** [comment]
> hi how can I remove the app from recovery?
> or fix this problem.

Meanwhile this isn't related to the problem

If you build from source you need to add TW_EXCLUDE_TWRPAPP

If you want to modify a current recovery you'll have to unpack it

**Comment by Ko-Hi-Dev** [comment]
Issue is to resolved with latest TWRP for cepheus with disabled. Twrp app installer

You can move the play store versn to system without issues
