### ISSUE TITLE
Android Pie build fails to find ld.config.txt, which is now called ld.config.28.txt

### ISSUE THREAD

**Issue by foresto** [TeamWin/Team-Win-Recovery-Project#1573]
[This commit](https://gerrit.omnirom.org/c/android_bootable_recovery/+/36041) broke my TWRP build on Android Pie. It expects `$(TARGET_OUT_ETC)` to contain `ld.config.txt`, but when I build with the android-9.0 branch of android_system_core, that file seems to be named `ld.config.$(PLATFORM_SDK_VERSION).txt` instead.

The build therefore fails: .../system/etc/ld.config.txt: No such file or directory

**Comment by bigbiff** [comment]
What tree are you using? Please post a link to your device tree too. Lastly, please make sure your android-9.0 is up to date and rm your out folder before rebuilding.

**Comment by foresto** [comment]
> What tree are you using?

`repo init -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-9.0`

`<remove-project name="android_bootable_recovery" />`
`<project name="omnirom/android_bootable_recovery" path="bootable/recovery" remote="github" revision="android-9.0" />`

> Please post a link to your device tree too.

Why? Doesn't the file in question get created by android_system_core or one of the other projects referenced above ? `grep -r ld\\.config device/* vendor/*` returns nothing, but if you have reason to believe there's something relevant in there, I'd like to know about it.

> Lastly, please make sure your android-9.0 is up to date and rm your out folder before rebuilding.

Yes, I did that. It's a new dev environment from less than 24 hours ago. The [commit history](https://github.com/omnirom/android_bootable_recovery/commits/android-9.0) shows the change that broke the build on the very first (most recent) page.

**Comment by CaptainThrowback** [comment]
@MartinX3 Isn't that the issue that this patch was supposed to fix?

https://github.com/TeamWin/android_bootable_recovery/commit/c630b3864f9ad0a7fe0b88b4180f42eefe3301db

**Comment by CaptainThrowback** [comment]
@foresto

You don't appear to be using the TeamWin recovery repo. Did you change it for some reason?

**Comment by foresto** [comment]
I used https://github.com/omnirom/android_bootable_recovery because that's what [the instructions](https://forum.xda-developers.com/showthread.php?t=1943625) say to do. I didn't even realize there was a https://github.com/TeamWin/ until now. Why are there both?

**Comment by bigbiff** [comment]
That thread and compile guide is 8 years old and links to the old repository. I am asking @Dees-Troy to update his thread. You can also follow https://twrp.me for updates.

**Comment by foresto** [comment]
Okay, but even the [README](https://github.com/TeamWin/Team-Win-Recovery-Project/#readme) in this very repo refers people to that thread for instructions. If you folks don't want people to use them, perhaps you should update your own link to point at some current instructions?

**Comment by foresto** [comment]
This repo's project description also refers people to the repo I was using:
https://github.com/omnirom/android_bootable_recovery/ 

I find this all pretty confusing.  All three of these exist, all three of them refer to that old xda thread for instructions, and it's not clear at all which one is preferred.

https://github.com/omnirom/android_bootable_recovery/ 
https://github.com/TeamWin/android_bootable_recovery/
https://github.com/TeamWin/Team-Win-Recovery-Project/

Are there more?

**Comment by foresto** [comment]
> You can also follow https://twrp.me for updates.

I'm looking at twrp.me right now. The FAQ on that site *also* [refers people to the same thread](https://twrp.me/faq/howtocompiletwrp.html) for build instructions.

**Comment by CaptainThrowback** [comment]
The minimal repo already includes the correct recovery repo. There's no need to add or change anything related to that.

**Comment by bigbiff** [comment]
Please use the pinned repository at https://github.com/TeamWin/android_bootable_recovery

**Comment by foresto** [comment]
Thanks, @bigbiff. ~~What does "pinned" mean in this context?~~ Oh, I see: You probably mean pinned in the Repositories tab of this project's owner page.

**Comment by bigbiff** [comment]
Yes. Sorry it wasn't clear.
