### ISSUE TITLE
[Error/Bug with 3.4.0] On hlte when installing new image

### ISSUE THREAD

**Issue by tfft** [TeamWin/Team-Win-Recovery-Project#1579]
- [ X] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [ X] I am running the latest version of TWRP
- [ X] I have read the FAQ (https://twrp.me/FAQ/)
- [ X] I have searched for my issue and it does not already exist

Device -- HLTE (Samsung N9005)
Version -- 3.4.0-0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
I've done these steps hundreds of times.  I backup my current image, wipe cache/dalvik, install newer image (of LineageOS FWIW).  When I do the install TWRP throws an error (E1001) noting that it is unable to create /cache/recovery/<long hash> directory and bombs. 

#### WHAT IS THE EXPECTED RESULT?
Akin to previous TWRP versions, it should be able to install new images of as directed.

#### WHAT HAPPENS INSTEAD?
I get an error (E1001) in red text and the install process exits/stops. 

#### ADDITIONAL INFORMATION

`last_log`: https://paste.omnirom.org/view/7cfc7b71
`dmesg`: https://paste.omnirom.org/view/2a6eedf4

**Comment by bigbiff** [comment]
Please test https://build.twrp.me/twrp-3.4.0-1-hlte.img.tar and let me know if it fixes your issue.

**Comment by tfft** [comment]
Yeah, that seems to have fixed the issue - Thanks !!
_Gotta love TWRP support !_

**Comment by bigbiff** [comment]
Thanks, a new release is out with this issue fixed.
