### ISSUE TITLE
Error meesages

### ISSUE THREAD

**Issue by robcop** [TeamWin/Team-Win-Recovery-Project#158]
im having a problem making a backup since a few days ago after my last backup. i keep getting the messages saying 
"E: error opening: '/data/lost+found/#12/#12/#12/#1
E: error: Too many open files
E: error opening: '/data/lost+found~0/#12/#12/#12/
E: error: Too many open files
E: error opening: '/data/lost+found~1/#12/#12/#12/
E: error: Too many open files
E: error opening: '/data/lost+found~2/#12/#12/#12/
E: error: Too many open files"
After that it says the normal [BACKUP STARTED] and 6 lines down and breaking backup it says
"E: Error tarring split files!"
I dont know how to fix this problem and im not some super advance android user, i just like flashing roms

ive tried it a few times and downloaded 2.5 to see if that might offer some fix but still nothing
i also wiped my dalvik cache and the only i dont want to do is a factory wipe (of course)
please help me see what i am doing wrong
should i go to fix permissions after upgrading to the new 2.5 also?
i am on a verizon galaxy s3 i535

**Comment by bigbiff** [comment]
Looks like you had a ton of corruption. Try removing /data/lost+found/ contents.

**Comment by robcop** [comment]
ive tried that with root explorer and every single time it force closes i guess because the folders are near infinite
i have checked this out and there isnt a way to delete but i have seen somewhere that running an fsck.fat file in the system to fix the curruption would clean it but i dont know how to run it because i dont know how to run commands in a terminal emulator.
this all happened though after running backups and i was wondering if twrp or anyone for that matter knew what to do about it so i can flash roms again because not even a factory reset will do it
But the thing is its not just the los+found data files but the error tarring split files. what is up with that? or is it because of the files?

**Comment by Dees-Troy** [comment]
You have a corrupt file system. You can try to repair it with fsck or do a format data to wipe the entire /data partition and start over.
