### ISSUE TITLE
Is TWRP 3.5.0 not customizable ?

### ISSUE THREAD

**Issue by kinesight** [TeamWin/Team-Win-Recovery-Project#1590]
- [ ] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**Device codename**: a20
**TWRP version**: 3.5.0_9 

#### WHAT IS THE EXPECTED RESULT?
Customized colours/images in TWRP

#### WHAT HAPPENS INSTEAD?
Everything remains stock

**[OUESTION]**

Can TWRP 3.5.0_9 not be customized in terms of the "twres" folder and "recovery.fstab" ?

I have modified previous versions (v3.4.0) with custom pngs and colour codes and disabled the partitions that I do not use in fstab but I tried to do this with v3.5.0_9 and nothing changed. I used Android Image Kitchen to repack the IMG.

**Comment by bigbiff** [comment]
We did not change anything regarding the location of twres or recovery.fstab. Since we do not officially support this I am closing the issue.
