### ISSUE TITLE
Backup recovery does not work on Android 10 (Lineage OS 17.1, SM-G900F)

### ISSUE THREAD

**Issue by JSUNFGH** [TeamWin/Team-Win-Recovery-Project#1591]
- [x] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**Device codename**: Samsung Galaxy S5 (SM-G900F, klte)
**TWRP version**: 3.5.0_9-0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
a) Clean device with format Data and Wipe Art/Cache/System
b) Flash Lineage OS 17.1 (2020-12-13) on phone
c) Reboot to see all is working with Lineage OS 17.1
d) Do backup (Data, System, Boot) in TWRP
e) Reboot to see all is working with Lineage OS 17.1
f) Restore backup (Data, System, Boot) in TWRP 
g) Reboot to system to see if it is restored

#### WHAT IS THE EXPECTED RESULT?
Phone should reboot to restored system

#### WHAT HAPPENS INSTEAD?
Phone boots to Download/Odin mode
Restarting system or pulling battery: phone still boots to Download/Odin mode
Can't boot system

#### ADDITIONAL INFORMATION
No adopted storage, no Magisk installed.

I tried the same with MicroG Lineage OS 17.1 with the same result. I tried the same with Lineage OS 16.0 and it restores just fine. I tried the same with MicroG Lineage OS 16.0 and it restores just fine. All with TWRP 3.5.0_9-0, the same settings and the same procedure.

Here are the logs for doing the backup and restore operation:
[backup_dmesg.log](https://github.com/TeamWin/Team-Win-Recovery-Project/files/5834560/backup_dmesg.log)
[backup_recovery.log](https://github.com/TeamWin/Team-Win-Recovery-Project/files/5834561/backup_recovery.log)
[restore_dmesg.log](https://github.com/TeamWin/Team-Win-Recovery-Project/files/5849267/restore_dmesg.log)
[restore_recovery.log](https://github.com/TeamWin/Team-Win-Recovery-Project/files/5849268/restore_recovery.log)

**Comment by bigbiff** [comment]
Please upload a recovery.log of the backup and restore sessions.

**Comment by JSUNFGH** [comment]
Done, see above. You think it could also be related to the backup process instead of the restore?

**Comment by bigbiff** [comment]
Hi, the restore log looks like a default log without the restore actions.

**Comment by JSUNFGH** [comment]
Sorry for that. The former restore logs were from after the failed boot attempt. I swapped them with restore logs taken right after the restore process but before rebooting.

**Comment by bigbiff** [comment]
I think you are encountering a bug with setting /system_root's context correctly. 

I:Cannot lookup security context for '/system_root'


Can you see if flashing this zip works after restoring: http://www.mediafire.com/file/a454nnpp8l7afbr/fix_rootfs_label.zip/file

**Comment by JSUNFGH** [comment]
Well, this worked like a charm. Thank you! I did several backups/restores. It worked with LOS 17.1 as well as MicroG LOS 17.1, even when the device is encrypetd and uses Magisk. If I'm not using the fix.zip I end up in Download mode again. But when I then boot to Recovery and flash fix.zip it's booting up to the system just fine. So it seems, the fix can be used at any time.

Only thing is I have to flash it after every restore. Is this a general bug in TWRP and you will implement the fix in the next version or is it something uncommon and the fix will stay standalone, just for users who need it, like me?

**Comment by bigbiff** [comment]
It is a general bug that I haven't been able to reproduce to fix yet. I would be grateful if you could test something for me. I might work on a patchset this weekend.

**Comment by JSUNFGH** [comment]
I can sure do this. If it's not bricking my phone :D

**Comment by JSUNFGH** [comment]
Since the fix.zip worked so well, I will close this issue. I suggest you integrate the fix into the next version of TWRP. 

As for testing, I'm moving my daily driver to the new phone this weekend, so I can't test much with it. Once I've moved I can use my old SM-G900F for testing.

Thanks again @bigbiff for providing a fix.
