### ISSUE TITLE
Nexus S 4G - Unable to wipe sdcard

### ISSUE THREAD

**Issue by HyenaSpace** [TeamWin/Team-Win-Recovery-Project#16]
As title states, using the latest 2.2 TWRP you are unable to wipe the SD Card on the Nexus S 4G.

Using rm -rf on '/dev/block/mmcblk0p3'
E:tw_format_rmfr: unable to locate volume for de [cuts off]

From my understanding, it looks like it's trying to wipe a block on the MMC that doesn't actually exist?

**Comment by Dees-Troy** [comment]
Can you try to wipe the sdcard then pull a log afterwards, please?  I need more detail.

http://rootzwiki.com/topic/24120-how-to-get-a-log-from-twrp/

**Comment by Dees-Troy** [comment]
Closing due to no reply.
