### ISSUE TITLE
Default directory for installation files

### ISSUE THREAD

**Issue by creeve4** [TeamWin/Team-Win-Recovery-Project#160]
TWRP 2.5.0.0 no longer remembers the last directory that a files was installed from.

I did modify my theme like this: http://pastebin.com/LZZ4CdzZ

But I have to go to Advanced > Reload Theme to get the custom location to work. All other theme elements load automatically, but not this one!

**Comment by Dees-Troy** [comment]
Should be fixed in 2.6 now.
