### ISSUE TITLE
regression: oneplus3: sha256 checksum files for zip signature verification stoped working in twrp-3.5.1_9-0

### ISSUE THREAD

**Issue by ghost** [TeamWin/Team-Win-Recovery-Project#1602]
- [x] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**Device codename**: oneplus3/oneplus3t
**TWRP version**: 3.5.1_9-0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?

Flash properly signed zip with properly formated and named sha256sum file results in "No  digest file found", if "Verify zip file signature" is checked.

For more details and a set of files to test: https://forum.xda-developers.com/t/recovery-unified-official-twrp-touch-recovery-for-oneplus-3-3t.3742894/post-84705357

Since lineageos only provodes sha256 checksums this is really annoying.

#### WHAT IS THE EXPECTED RESULT?

Successfull flash like with twrp 3.5.0_9-0 and before.

#### WHAT HAPPENS INSTEAD?

Flash fails with "No  digest file found".

#### ADDITIONAL INFORMATION

`/tmp/recovery.log`: https://drive.google.com/file/d/1Yw1R7Niep3GU_wGsjfQWSxWHuP5IpLX-/view?usp=sharing

**Comment by bigbiff** [comment]
This will be fixed on the twrp 3.5.2 release.
