### ISSUE TITLE
Had to use Nebrassy, took weeks to find that out

### ISSUE THREAD

**Issue by auwsom** [TeamWin/Team-Win-Recovery-Project#1612]
Was trying to use the `fastboot boot twrp.img` method to reinstall Magisk after an update, and it froze my phone. I had to download the stock image and extracter to get at the tiny stock boot.img file to restore, was a pain. Why is there no mention of the Nebrassy versions on the page below? And why are the newer versions of TWRP shown that dont work?? I had to bug the guys over at Magisk just to find this out, because none of the XDA forums had solutions. Many people are looking for a solution. Please post this information on the official TWRP pages!

https://dl.twrp.me/guacamole/

**Comment by bigbiff** [comment]
Is it an AOSP11 rom?

**Comment by auwsom** [comment]
@bigbiff Hi, yes it is. If there is some caveat about 11, I saw zero information about that anywhere on the site. It's a stock OnePlus 7 Pro as the version link above might imply.

**Comment by bigbiff** [comment]
We are working on aosp11 now. Closing this issue.

**Comment by auwsom** [comment]
@bigbiff Thank you for working on it. It has been this way for the better part of a year. I tried multiple times to fix it because I cant use SwiftBackup, my NFC for GPay is broken as well as other root functions like AppQuarantine and AppOpps. Shizuku helped the last two, but I have to send an adb command on every restart. Backup through adb is now disabled from Google. I tried even the depreciated full backup which supposedly still works with no luck. TWRP backup is the only other way available, so I dont lose all my device configuration on my device I use for work if I mess something up trying to get Magisk working again. 

Can you at least put some information on the TWRP pages, so people don't try the new and old files over and over, expecting them to work if there is no warning message?!
