### ISSUE TITLE
Work 11t 11tpro ? Xiomi

### ISSUE THREAD

**Issue by aalllq** [TeamWin/Team-Win-Recovery-Project#1615]
- [ ] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [ ] I am running the latest version of TWRP
- [ ] I have read the FAQ (https://twrp.me/FAQ/)
- [ ] I have searched for my issue and it does not already exist

**Device codename**: 
**TWRP version**: 

#### ADDITIONAL INFORMATION

`/tmp/recovery.log`: 
`dmesg`:

**Comment by FTyiming** [comment]
i want to try

**Comment by bigbiff** [comment]
Do not open device requests here.
