### ISSUE TITLE
E:Error executing updater binary in zip...

### ISSUE THREAD

**Issue by SparkyRih** [TeamWin/Team-Win-Recovery-Project#162]
This erro accurs while flashing a custom ROM on first generation Padfone devices (TWRP 2.5.0.0)...

**Comment by Dees-Troy** [comment]
This is a problem with the zip file and not with TWRP.

**Comment by rookie** [comment]
I had this problem yesterday and I solved it by downgrading twrp to 2.3.3.0. There were no longer errors and the install went fine using the same zip file with this old version.

It was on an AT&T HTC Inspire HD (Desire HD/Ace)

The zip files that I tried were the newest nightly(cm-7-20130301-NIGHTLY-ace.zip) and the newest stable(cm-7.2.0-ace.zip) from http://download.cyanogenmod.org/?device=ace

**Comment by keonji** [comment]
I have the same problem, but I can't downgrade the recovery, because i haven't other recovery on Asus Padfone Infinity
