### ISSUE TITLE
Partitioning on BML devices

### ISSUE THREAD

**Issue by dany547** [TeamWin/Team-Win-Recovery-Project#164]
hello there, i compiled TWRP 2.5.0.0 for Galaxy Mini, all works preatty well except the partitioning...when i select to create a 512mb EXT4/3 partition and 32 swap. It formats the SD then it creates just the the main FAT32 one and then the recovery reboots. Heres a log http://pastebin.com/3894P2Ut

Thanks

**Comment by dany547** [comment]
and also it creates the 512 partition but it doesnt format it...its just empty space

**Comment by Dees-Troy** [comment]
The log provided contains nothing related to actually partitioning the device.

**Comment by dany547** [comment]
thats weird
