### ISSUE TITLE
My TF300T doesn't work with 2.4.4.0

### ISSUE THREAD

**Issue by qqqqqq993** [TeamWin/Team-Win-Recovery-Project#165]
I can't enter my tf 300 and  I can't enter twrp
because it always ask me password
i've wipe data...so i can't use "fastboot"
How can I do??  
please give me password.

**Comment by mrjavum** [comment]
https://github.com/TeamWin/Team-Win-Recovery-Project/issues/147

**Comment by qqqqqq993** [comment]
but I can't use fastboot... 
Because I always enter TWRP,whem I do reboot..
so I can't flash -42 version.
Please tell me how can I do? 
What type of tool I can use?    NVflash? or other

**Comment by qqqqqq993** [comment]
WHO CAN ANSWER ME? PLEASE
t.t

**Comment by Dees-Troy** [comment]
Read the big note in red writing and make sure that you have the correct version installed for your bootloader. Directions for a manual install are there as well. If you cannot get the correct version of TWRP installed anymore then you will have to send the device to Asus for repair.
