### ISSUE TITLE
3-5m Load up time on VZW S4 2.5.0.3 update.. 

### ISSUE THREAD

**Issue by Proweedsmoker** [TeamWin/Team-Win-Recovery-Project#168]
Just updated to . 3 and booting into recovery now stalls at the splash screen for anywhere between 3-5m. .2 always booted instantly, definitely think there is an issue in  . 3. I'm worried to flash with this bug so I cannot report if there are flashing issues too.

**Comment by Dees-Troy** [comment]
S4 devices have been updated to use a different kernel in the TWRP recovery image which fixes this issue.
