### ISSUE TITLE
Excessively large 'Data' file in 'Backup'

### ISSUE THREAD

**Issue by mac1679** [TeamWin/Team-Win-Recovery-Project#170]
I am using 2.5.0.0 on d2att and I did not have any issues until recently.  All of a sudden I went to make a backup of my ROM and the size of the 'Data' file is calculated at 2,996,193MB.  I thought it might be a ROM issue so I flashed a different ROM but the same issue still persists.  Any thoughts on what may be causing the large data file calculation?

**Comment by morfiuss** [comment]
I'm having the same issue and I'm on 2.5.0.3. I tried searching the net but found nothing.

**Comment by aidfarh** [comment]
Maybe it's a problem with your data partition. Check the /data/lost+found directory. Are there any files in it?

**Comment by morfiuss** [comment]
There are a lot of folders and files in it

**Comment by mac1679** [comment]
Same here.

**Comment by morfiuss** [comment]
So the solution is to format. This worked. Thank you for pointing the lost+found.

**Comment by mac1679** [comment]
Thanks. That worked for me as well.  Any idea WHY that happened?

**Comment by generalmx** [comment]
Probably worth it to try mounting /data early in init.

**Comment by shotty53** [comment]
I'm having the same issue. I formatted the phone and re-installed several roms and every time, the /data is over 2TB in twrp.
