### ISSUE TITLE
unable to mount system

### ISSUE THREAD

**Issue by ghost** [TeamWin/Team-Win-Recovery-Project#173]
TWP 2.5.0.0 the logs says "unable to mount /system". Here is the recovery file: https://gist.github.com/fritz9/5790937
This was experienced on a device with no OS, specifically LG Optimus G e975.

**Comment by bigbiff** [comment]
Can you provide dmesg logs please?

**Comment by Dees-Troy** [comment]
No logs posted. Closing.
