### ISSUE TITLE
Possible fix to failure to mount SGS3 encrypted /data partition

### ISSUE THREAD

**Issue by generalmx** [TeamWin/Team-Win-Recovery-Project#174]
I've been racking my brain and yelling on IRC trying to fix this problem, until, finally, in a fit of insanity, I was able to get /data (encrypted by 4.x SGS3 stock firmware, so dm-crypt) mount by seemingly crashing TWRP 2.5.0.0, then letting it recover. Here's how I can reproduce it on my phone:
- TWRP 2.5.0.0 asks for password on startup to decrypt an encrypted partition.
- I correctly enter the password. Log shows successful decryption.
- Log also shows "unable to mount /data"
- Try to mount /data by going to "Mount" in TWRP. Same error.
- Went into terminal emulator, ran cat /tmp/recovery.log
- ran cat /tmp/recovery.log again
- ran cat /tmp/recovery.log yet again (yes, I'm catting my cat cat!)
- TWRP slows down until it seemingly crashes, going back to the "team win" splash screen
- _Now_ the /data partition is mounted, and I can perform operations on it.

Notes: As resetting TWRP fixes this one problem, I would suggest that whatever it's doing here be added in a safe way as a feature, for future mount/other problems. (Reloading the recovery binary without restarting the device?)

Further Notes: marduk191 suggested loading /data on early init.

The overflow bug/feature was reproduced on: SGS4 (required more cat calls)

Logs here: https://paste.tinyw.in/index.php/view/43034906

**Comment by bigbiff** [comment]
Hi, TWRP reports successful decryption. Can you paste the output of mount -v and df -h from adb shell in TWRP?

**Comment by bigbiff** [comment]
Actually just realized you encrypted with Samsung OEM Android which needs a patch on Gerrit. This is to be included in 2.6

**Comment by Alxoom33** [comment]
Thanks for responding.  So should I just wait for 2.6?
Thanks again,
Alan

**Comment by bigbiff** [comment]
Yes.

**Comment by Alxoom33** [comment]
Thanks Man, much appreciated.  Do you know I got banned for abusing you on
the help line?  I hope that you did not take anything I said as being
abusive.  That certainly was not my intention.  Best, Alan

**Comment by wertarbyte** [comment]
While I was able to use the mentioned workaround to access the encrypted data partition on my i9300, TWRP 2.6 completely breaks the process for me. After entering my password, I cannot decrypt the internal memory anymore ("Password Failed, Please Try Again" / "E:Failed to decrypt data"). The same works fine on my Nexus 7, so I guess it must be something specially related to the SGS3 build.

**Comment by viciouzex** [comment]
How do I find out what the password is to decrypt in TWRP? I have the Virgin Mobile flavor of the sgs3 SPH-L710

**Comment by generalmx** [comment]
@viciouzex, it would be the same password to decrypt as when you boot up normally. If you're on 2.6.0.0, there's currently a bug where it may not decrypt, so you'd have to go back to 2.5.0.0 and possibly use the workaround.

**Comment by generalmx** [comment]
@bigbiff, I'm not sure if it's TouchWiz-based encryption, but I don't think it is. LiquidSmooth (AOSP) seems to use Android 4.x's built-in cryptfs to decrypt and manage the volume, where stuff like http://nelenkov.blogspot.com/2012/08/changing-androids-disk-encryption.html?_escaped_fragment_=#! worked for me.

**Comment by edsantiago** [comment]
Could it be a problem with the keyboard? I don't think it's getting the right characters. I've just installed 2.6.3.1 on my Verizon SGS3 and am having a very difficult time getting TWRP to mount the fs. I've noticed that the keyboard acts wonky: sometimes I tap a key and no '*' appears in the password field (even though the key I've tapped gets the border highlight). Sometimes tapping a key has the result of wiping the entire password (a la ^U). My passphrase requires shifting from alpha to num/special often, and sometimes the 123/abc key has no effect. After about 20 attempts in 15 minutes I have been able to decrypt & mount, so it's clearly not a system problem. recovery.log available on request but to my eye it shows nothing useful. Is there a way to debug the keyboard? Possibly enable actual characters showing, instead of '*'? I consider my home location secure.

**Comment by MrSimmonsSr** [comment]
This comment from edsantiago makes sense to me. I'm seeing something similar with my AT&T Galaxy S3. I've encrypted both the device and the MicroSD per my company's requirements and then flashed TWRP, but TWRP seems to be unable to mount the relevant partitions. And my keyboard does seem janked up in TWRP as well. For example, long pressing on Q doesn't give a 1 as it should. 

I will try it a few more times as well and see if I can get in. Would love to be able to take a good backup now that it is setup properly! 

Anyone have any other thoughts on this topic? 

Thanks! 

MrSimmonsSr
