### ISSUE TITLE
Unable to decrypt data in TWRP 2.5.0.2 in Verizon Galaxy S4

### ISSUE THREAD

**Issue by Alxoom33** [TeamWin/Team-Win-Recovery-Project#175]

**Comment by Alxoom33** [comment]
Running stock rooted with latest twrp 2.5.0.2 when booting into twrp recovery and input my passcode does not recognize and gives error msg.  Also fails to backup data. Fail msg. I was told on freenode 2.5 is borked and there is a patch. Any ideas?  Thanks.

**Comment by bigbiff** [comment]
Closing, to be fixed in 2.6

**Comment by scubamike** [comment]
I'm running 2.6.3.0, and my problem remains. TWRP is asking for a password. I have no idea why my data is now encrypted and what the password could possibly be. My phone froze and rebooted randomly. That was the start of my problems. It wouldn't reboot after that, and TWRP has locked me out of my internal storage card.
