### ISSUE TITLE
Issues with HTC Sense Based

### ISSUE THREAD

**Issue by Rush2088** [TeamWin/Team-Win-Recovery-Project#177]
I have issues with installing .zip containing sense based roms using version 2.5.0.0

Some times it installs the rom with errors. (ie doesn't boot up after installation of the rom)

However TWRP works fine with both roms.

Device: HTC Desire HD
Problematic roms with V2.5: Muiu 3.6.7
                                  Team Venom viper hd 2.3

**Comment by Dees-Troy** [comment]
I don't have a Desire HD and without logs there's not much hope of being able to fix it. In the vast majority of cases, it's the ROM's fault and not the recovery's fault. The recovery does very little during ROM installation. Pretty much everything is done by the update binary that's included in the zip.
