### ISSUE TITLE
Galaxy S4 TWRP 2.5.0.2 Date/Time issues

### ISSUE THREAD

**Issue by grnspeed** [TeamWin/Team-Win-Recovery-Project#178]
1) Set Time Zone settings off by +5 hours (e.g. eastern time displays as 5 hours later than current time)

2) Nandroid default name starts "1970-"

**Comment by OneOfMany07** [comment]
+1

I'm seeing this too...just installed TWRP tonight with a one click rooter, and made my first backups.  Noticed the above issues when I tried to fix the bad date/time (set to +12 instead of +8 with DST to get my time almost right...still off by 15 minutes).

**Comment by Dees-Troy** [comment]
The real time clock on most newer Qualcomm devices isn't set properly in Android. We have implemented a fix by reading the offset from some files in /data when available. Other than reading those files there's really nothing else we can do about this issue.
