### ISSUE TITLE
2.6: Shift apparently acts as CapsLock when entering a password for encrypted backups

### ISSUE THREAD

**Issue by excarnate** [TeamWin/Team-Win-Recovery-Project#180]
TWRP 2.6 on Mako (Nexus 4).

When entering a password to encrypt a backup, pressing the shift key shows capital letters, but after entering the first letter, capital letters are still shown. The CapsLock 'light' doesn't light. Pressing the shift key again shows lower case letters.  Apparently the shift key is acting as a capslock key, albeit without the indicator light. Since the actual characters are not visible, I can not say if the upper and lower case letters are reflecting the actual password.  I will attempt to extract the backup and decrypt on my computer.

Expected behavior: Pressing shift gives a single shifted character then goes back to entering unshifted characters. Pressing shift twice in a row will give capslock and light the indicator and enter characters as the default Google keyboard does when capslock is active. When capslock is active, pressing shift will deactivate capslock.

**Comment by Dees-Troy** [comment]
Normal caps lock behavior will be available in the next release.
