### ISSUE TITLE
MD5Sum check fails when restoring a compressed backup on 2.6.0.0

### ISSUE THREAD

**Issue by Dees-Troy** [TeamWin/Team-Win-Recovery-Project#182]

**Comment by MikG** [comment]
When archiving in  compression mode twrp 2.6 incorrectly generates a checksum for cache.ext4.win. And just for this archive. For the rest other the checksums are generated correctly. Which module can I look to fix the issue?

**Comment by bigbiff** [comment]
I am looking through old tickets. Please provide a log.

**Comment by Dees-Troy** [comment]
We had an issue where md5 was being calculated before the backup file was fully written to disk. This has been corrected.
