### ISSUE TITLE
Encryption on SGH-I337M

### ISSUE THREAD

**Issue by Mrdindon** [TeamWin/Team-Win-Recovery-Project#184]
Up to version 2.6 it is still impossible to activate samsung encryption on the SGH-I337M while TWRP is installed...

After installing TWRP, if I try to initiate the device encryption, the device reboot to a black screen for around 20 seconds then reboot again to normal boot without lauching the encryption process. 

I can reproduce that by restoring normal recovery, encrypting, decrypt, install twrp, etc, etc....

**Comment by bigbiff** [comment]
Please provide /tmp/recovery.log

**Comment by bigbiff** [comment]
Closing due to lack of response.
