### ISSUE TITLE
Unable to decrypt on Samsung Galaxy S4 LTE (I9505)

### ISSUE THREAD

**Issue by houmles** [TeamWin/Team-Win-Recovery-Project#186]
Hi,

even after 2.6.0.0 release I am unable to decrypt /data partiton no matter what rom I have (tried couple of stock versions, custom touchwiz and also clean AOSP).
Tried many password combination but always stuck on unable to decrypt.
Also can't find this in issue list so I creates this one as this is important to me to have encrypted phone.
If you need any help from me let me know. I have no problem with flashing and send you logs or something..

Thank you

**Comment by Dees-Troy** [comment]
TouchWiz decryption is working fine on my Sprint SGS3 (d2spr) on 2.6.0.0. Unfortunately we don't have any S4 model to work with. You can adb pull /tmp/recovery.log after attempting to decrypt it, but there may not be much that we can do about this issue.

**Comment by houmles** [comment]
Thanks for reply... here is a recovery.log
http://pastebin.com/GTcXeDSm

**Comment by generalmx** [comment]
I can confirm this happens on the (d2spr) Samsung Galaxy S3 as well, where crashing/restarting TWRP does not fix the issue, unlike 2.5.0.0. I'm fairly sure this has to do with Android 4.x's built-in encryption and NOT TouchWiz encryption, unless TouchWiz also uses dm-crypt to manage the encryption.

For now, anyone on 2.6.0.0 who has encryption problems should try 2.5.0.0, and, if it doesn't decrypt right off the bat, go into Terminal and do "killall recovery" to restart TWRP.

**Comment by generalmx** [comment]
Oops - meant cryptfs not dm-crypt. As changing the password and getting encryption status works for me from this blog: http://nelenkov.blogspot.com/2012/08/changing-androids-disk-encryption.html?_escaped_fragment_=#!

**Comment by houmles** [comment]
I can confirm that in latest 2.6.1.0 version decrypting work successfully.
