### ISSUE TITLE
TWRP decryption of data partition fails: i9300. CyanogenMod

### ISSUE THREAD

**Issue by dojoko55** [TeamWin/Team-Win-Recovery-Project#187]
device model: i9300 
Rom : CM 10.1

issue: decrypting the encrypted /data partition has never worked on this device with TWRP.  Therefore there is no way to backup and upgrade my Rom from the recovery environment. I have attached the error log below. Please let me know if its enough to explain the problem. If there is any specific information you need to know about the device let me know too.

 TIA

http://www.sendspace.com/file/p0kzyr

**Comment by Dees-Troy** [comment]
There's nothing in that log about the actual decryption attempt. You might have to adb pull the log instead.

**Comment by dojoko55** [comment]
OK is this more useful instead?

http://www.sendspace.com/file/a7ri86

**Comment by ghost** [comment]
I'm experiencing the same issue with TWRP 2.7 and CM11 on my i9300.
