### ISSUE TITLE
TWRP 2.6.0.1: Decryption of data fails on N7105 (t0tle) with CyanogenMod 10.1

### ISSUE THREAD

**Issue by TimeTravellingMonkey** [TeamWin/Team-Win-Recovery-Project#188]
I am running a nightly build of CyanogenMod 10.1 on an Galaxy Note II N7105 (i.e. t0tle), using TWRP 2.6.0.1.

Attempting to decrypt and mount the data partition in TWRP fails no matter what I try.  Unfortunately I'm forced to use an encrypted data partition by corporate policy so I don't have much choice in the matter...

The terminal in TWRP displays "E: Failed to decrypt data." every time I enter my password.  The corresponding line in the log seems to be "Keysize of 128 bits not supported for real block device /dev/block/mmcblk0p12".  

I've captured the log from a session where I attempted to enter my password five times:
http://pastebin.com/Gd62q5YK

At face value this looks very similar to issue #187.

**Comment by bigbiff** [comment]
We are looking into the issue.

**Comment by bigbiff** [comment]
Fixed issue with including AOSP and Samsung encryption.

**Comment by scubamike** [comment]
How do I employ your fix? I have a Verizon Galaxy S3 that is demanding a password in TWRP. I've Odined 2.6.1.0, 2.5.0.0 and 2.4.4.0. Whenever I enter a password, which have all been wrong, it says "e:failed to decrypt data". I've even flashed 2.6.3.0 now that I think about it. I was running an AOSP 4.3.1 ROM when everything fell apart. The ROM won't boot, and I can reinstall, nandroid, etc... Any advice is greatly appreciated.
