### ISSUE TITLE
TWRP 2.6.0.0 fails to decrypt CM10.1 encrypted partition

### ISSUE THREAD

**Issue by insonifi** [TeamWin/Team-Win-Recovery-Project#190]
I have Samsung I9305, TWRP 2.6.0.0 and CM10.1 Nightly build. Have encrypted my devices and since then can't update anymore. 
When I enter my password in TWRP it always fails to mount the block device.

Here's the log: https://dpaste.de/OoKjn/

Looks like issue is similar to:
#186
#187
#188

**Comment by wertarbyte** [comment]
I can confirm this issue with Samsung I9300; at least with 2.5 the workaround (crashing/restarting TWRP) works, with 2.6 accessing the partition has become impossible.

**Comment by ScryerSteve** [comment]
Similar to my issue. Thanks for shedding some light.
