### ISSUE TITLE
Wiping Ext4

### ISSUE THREAD

**Issue by ghost** [TeamWin/Team-Win-Recovery-Project#191]
The latest build for Inc2 should be using mke2fs instead of make_ext4fs which should fix the wiping problems. Please let me know if you're still having issues with TWRP 2.4.4.0 or higher.

Tried the above solution with v2.6.0.0 without success. Unable to mount data cache etc

**Comment by lebuzzer** [comment]
Hi !
2.6.3 having the same problem with error in make_ext4fs. partition is unmoutable !
after multiple wipe try i have mountable system data and cache. deleting make_ext4fs everytime I want to restore or wipe seems to resolve the problem !

**Comment by lebuzzer** [comment]
It doesn't seems to be the same problem ! when wiping cache, system was no more mountable until reboot ! very stange !

**Comment by Dees-Troy** [comment]
mke2fs does not support SELinux. I'm pretty sure that we're building Inc2 in CM7 / gingerbread which also does not support SELinux which is needed for supporting installation of 4.4 Kit Kat ROMs. Unless someone steps up and forward ports the Inc2 to a newer tree that supports SELinux, we will be dropping support for this device.
