### ISSUE TITLE
Tar backups created with 6440 (-r-Sr-S---) permissions

### ISSUE THREAD

**Issue by drewis** [TeamWin/Team-Win-Recovery-Project#193]
Release 2.6.0.0
Devices all (with emulated sd)
On devices with emulated sd (tested grouper/mako) tar backups of data and system are stored with some pretty insane permissions. (Devices with fat32 partitions wont notice)

```
-rw-rw-rw-    1 root     root      23068672 Jul 28 18:43 boot.emmc.win
-rw-rw-rw-    1 root     root            48 Jul 28 18:43 boot.emmc.win.md5
-r-Sr-S---    1 root     root     771953664 Jul 28 18:43 data.ext4.win
-rw-rw-rw-    1 root     root            48 Jul 28 18:43 data.ext4.win.md5
-rw-r--r--    1 root     root        112017 Jul 28 18:43 recovery.log
-r-Sr-S---    1 root     root     578180096 Jul 28 18:42 system.ext4.win
-rw-rw-rw-    1 root     root            50 Jul 28 18:42 system.ext4.win.md5
```

Perusing the source i see your calling tar_fdopen with mode `0644`
I think this should be changed to `00644` or perhaps even `S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH` although i have not tested this.

**Comment by Dees-Troy** [comment]
I have merged a patch to fix this and it will be fixed in our next release.

**Comment by drewis** [comment]
thanks
