### ISSUE TITLE
TMobile Samsung Galaxy S4 TWRP hangs

### ISSUE THREAD

**Issue by demonr6** [TeamWin/Team-Win-Recovery-Project#195]
I recently rooted my handset and flashed the latest TWRP from Goo manager. I can boot into TWRP but it takes anywhere from 15 minutes or more.. correction now 18 minutes and counting. I don't want to even attempt flashing a ROM with an issue like this plaguing the recovery.

**Comment by Dees-Troy** [comment]
We updated the kernel used in the TWRP recovery images for most S4 devices to fix this problem.
