### ISSUE TITLE
Tarring of backup fails

### ISSUE THREAD

**Issue by kpsfoo** [TeamWin/Team-Win-Recovery-Project#197]
While tarring the backup on the Nexus 4, TWRP 2.6.0.0 fails repeatedly. Only when I uncheck the Compress Backups option does it complete a backup. I installed TWRP from GooManger! I am running Paranoid Android 3.95 ROM with the latest Gapps.

**Comment by mrjavum** [comment]
https://github.com/TeamWin/Team-Win-Recovery-Project/issues/185
