### ISSUE TITLE
Backup fails with broken symlink in /data (Nexus 4)

### ISSUE THREAD

**Issue by lefth** [TeamWin/Team-Win-Recovery-Project#198]
Backup fails with compression enabled and a symlink to a nonexistent file:
/data/bugreports -> /data/data/com.android.shell/files/bugreports

Backup works with compression disabled. The problem seems to be that "st.st_size" contains an extremely large number for the size of a broken symlink. I suspect the logic is also wrong for a non-broken symlink, because it may count the size of the symlink target.

Log says:
I:Closing tar '/data/media/0/TWRP/BACKUPS/xxxxxxxxxxxxxxxx/2013-08-15--05-55-34//data.ext4.win001', I:Creating tar '/data/media/0/TWRP/BACKUPS/xxxxxxxxxxxxxxxx/2013-08-15--05-55-34//data.ext4.win002'
Creating archive 3... I:Using compression...
I:Adding file: '/data/bugreports'...
I:added successfully, archive size: 32496501869997938
E:There is a file that is larger than 2GB in the file system
'/data/bugreports'

**Comment by bigbiff** [comment]
http://review.teamw.in/#/c/653/

Would you like a test build?

**Comment by lefth** [comment]
Hey, thanks! It looks good to me. If you send me a test build, I'll be
happy to test it, but I don't desperately need to make compressed backups,
so it's up to you. I can wait for the next version :)

Thanks again!
-Dan
