### ISSUE TITLE
SDXC exFAT

### ISSUE THREAD

**Issue by MrBrianGale** [TeamWin/Team-Win-Recovery-Project#199]
I have a 64 GB SDXC card formatted as exFAT (default) and I am unable to mount it via TWRP 2.6.0.0.  It works fine within my ROM (Hellybean android 4.3), and mounts it as fuseblk filesystem type, but if I try manually mounting it from adb while in recovery, it fails to mount.  My guess is that recovery doesn't support the filesystem type fuseblk.  I would rather do nandroids onto my large card instead if internal as it is easier to back up to other devices (sd card reader for PC works better than MTP with my computer and mass_storage is currently flaky and needs a reboot after making any changes to the external SD card from what I have found and it requires terminal knowledge to even get mass_storage working on a 4.3 ROM).
Thoughts?

**Comment by bigbiff** [comment]
Can you provide recovery.log? Also might want to try chkdsk /f driveletter: in windows.

**Comment by MrBrianGale** [comment]
I got the disk recognized by formatting it as fat32 instead of exfat.
Thanks though.

**Comment by OneOfMany07** [comment]
According to Sandisk 64 GB SDXC cards are by default exFAT, but it looks like Linux (and I assume Android) might not support it yet?

SD/SDHC/SDXC Specifications and Compatibility
http://kb.sandisk.com/app/answers/detail/a_id/2520/~/sd%2Fsdhc%2Fsdxc-specifications-and-compatibility

Operating Systems that Support the exFAT File System
http://kb.sandisk.com/app/answers/detail/a_id/3389

**Comment by MrBrianGale** [comment]
Thanks for the info.  I just recently upgraded to android 4.3 and am liking
that you guys kept up and made TWRP 2.6.1.0.  It works perfect on the
hercules from what I can tell.  I get an occasional bad nandroid (very
rarely), but I think that is my SD card or me playing with things before
the nandroid.  It happens more frequently if compression is turned on, so I
have compression off.

I'm reading a lot of reports on XDA though about wiping not wiping properly
unless you have "use rm -rf instead of format" turned on.  This seems
backwards to me as a format should be a better wipe than rm -rf.

On a different note, do you know what all of the 28 partitions are used for
on the hercules (SGH-T989)?

**Comment by OneOfMany07** [comment]
I'm a newb like you, but happened to have researched this a little so thought I'd share what I'd found.  Just got my phone last weekend and am seeing what I can do with it.  I've seen reports of the "break your phone if you format, so wipe" issue for my phone too (Samsung Galaxy S4 AT&T), even supposedly with v2.6.1.0 that lists fixing a corruption issue with TouchWiz.  So I'm staying on v2.5.0.2 for now.  I think formatting deleted an encryption key somewhere that the rm didn't, so in this case the less complete clean is better.

**Comment by MrBrianGale** [comment]
cool.  Thanks for the info.

One side project I wanted to do was muck around with the partitions on my
phone (scary stuff, no?).  I noticed there was a lot of gaps between
partitions once you get to partition 5 and higher (5 through 28 on my
specific phone).  I also was thinking could shrink the /system partition
down.  This would allow for:
1) a second /system partition and kernel-level dual boot
2) a swap partition (not recommended from things I've been reading online)
3) larger /data partition

I may do this if I can find a spare hercules for cheap... don't want to
kill my primary phone lol.  Could also resize the /storage/sdcard0
partition and make the new /system one (I know they are not actually called
that... they are mmcblk0pxx, but it is easier to say /storage/sdcard0 than
to say mmcblk0p28... plus I don't even know if 28 is sdcard0, but it is
easy to look up from recovery).  but a larger /data partition would mean
you can have more apps on your phone without it complaining about being out
of space... I think... If the external SD card mounted faster (kernel tweak
maybe?) you could have /data on external which would give you tons of
room... but your phone won't boot if you remove the SD card... so many fun
things we can do with our phone, but I have the problem of seeing 28
partitions and only knowing what MAYBE 1/2 of them are for (cache, efs,
system, boot1, boot2, recovery, firmware, internal SD, data, radio... not
sure what else... guess less than half :().  Oh, the fun things we can do
with our phones, eh?
I have the SGH-T989D which is a lot different than the galaxy S4, but since
it is samsung, I imagine you have a similar partition structure to me...
not identical, but probably fairly similar.
