### ISSUE TITLE
unable to boot cm9 roms when flashed with twrp 2/2.1

### ISSUE THREAD

**Issue by vevek** [TeamWin/Team-Win-Recovery-Project#2]
I've tried many things to solve this problem. I am hoping it will be solved.in a new release. 

Cm9 based roms cannot be booted when flashed with twrp. Only aosp rons can. I am not sure.if it occurs in all devices but it occurs for nexus s.
Thanks.

**Comment by Dees-Troy** [comment]
We released a 2.1.1 version that uses a different kernel that should fix this problem.  Please submit a new bug report if you are still having trouble installing CM9.

**Comment by vevek** [comment]
Hi, I upgraded my device to a Galaxy Nexus and no longer have a nexus s to
be freely flashed. Thus I can't test.
but thanks for fixing it. I really appreciate it. :)
On May 16, 2012 12:13 AM, "Dees-Troy" <
reply@reply.github.com>
wrote:
