### ISSUE TITLE
flipped screen issues with zte warp

### ISSUE THREAD

**Issue by QuietStorm1785** [TeamWin/Team-Win-Recovery-Project#20]
Well, Built twrp on my zte warp, and am having an issue with BOARD_HAS_FLIPPED_SCREEN. the zte warp comes with an inverted screen, so it is necessary to have that definition working. I have been trying for a few months to fix it, but have not come up with a fix yet. When twrp is loaded with that definition with TARGET_RECOVERY_PIXEL_FORMAT set to RGBX_8888, half the screen is upside down with the correct colors, and the other half is the correct way and hot pink. it's boggling my mind, and I cannot for the life of me figure out a fix.

**Comment by Dees-Troy** [comment]
I have poked at this issue before a little bit but fixing the flipped screen code to work with 32 bit frame buffers will probably be fairly tricky.  There aren't that many devices with a flipped screen, so it's not a high priority for me to fix it, though it is certainly a bug.  As a workaround you can probably use the touchscreen flags to flip the touch mapping around:
RECOVERY_TOUCHSCREEN_SWAP_XY := true -- swaps the mapping of touches between the X and Y axis
RECOVERY_TOUCHSCREEN_FLIP_Y := true -- flips y axis touchscreen values
RECOVERY_TOUCHSCREEN_FLIP_X := true -- flips x axis touchscreen values
You probably would need to swap xy and flip y.  Once you do that, the touches will map properly to the upside-down screen.  Not a perfect fix, but it'd at least be usable.

**Comment by QuietStorm1785** [comment]
Thanks, I have been trying to fix this for a while now and I cant seem to figure it out... lol I added some code to convert 16 to 32 bit, but it's only processing half of the screen. idk why, heres some of the code, it's basically the code I used in my cwm build for gr_flip32. I dont know if that's it. 

void gr_flip_32(unsigned *bits, unsigned short *ptr, unsigned count)
{
   unsigned i=0;
   while (i<count) {
        uint32_t rgb32, red, green, blue, alpha;

```
    /* convert 16 bits to 32 bits */
    rgb32 = ((ptr[i] >> 11) & 0x1F);
    red = (rgb32 << 3) | (rgb32 >> 2);
    rgb32 = ((ptr[i] >> 5) & 0x3F);
    green = (rgb32 << 2) | (rgb32 >> 4);
    rgb32 = ((ptr[i]) & 0x1F);
    blue = (rgb32 << 3) | (rgb32 >> 2);
    alpha = 0xff;
    rgb32 = (alpha << 24) | (blue << 16)
    | (green << 8) | (red);
    android_memset32((uint32_t *)bits, rgb32, 4);
    i++;
    bits++;
}
```

}

void gr_flip(void)
{
    GGLContext *gl = gr_context;

```
/* swap front and back buffers */
gr_active_fb = (gr_active_fb + 1) & 1;
```

#ifdef BOARD_HAS_FLIPPED_SCREEN
    /\* flip buffer 180 degrees for devices with physicaly inverted screens */
    unsigned int i;
    unsigned int tmp
    for (i = 1; i < (vi.xres \* vi.yres); i++) {
        tmp = gr_mem_surface.data[i];
        gr_mem_surface.data[i] = gr_mem_surface.data[(vi.xres \* vi.yres \* 2) - i];
        gr_mem_surface.data[(vi.xres \* vi.yres \* 2) - i] = tmp;
    }
#endif

```
/* copy data from the in-memory surface to the buffer we're about
 * to make active. */
```

  if( vi.bits_per_pixel == 32)
    {
        gr_flip_32((unsigned _)gr_framebuffer[gr_active_fb].data, \
                  (unsigned short *)gr_mem_surface.data, \
                   (vi.xres_virtual \* vi.yres); 
    }
    else
    { 
    memcpy(gr_framebuffer[gr_active_fb].data, gr_mem_surface.data,
           vi.xres_virtual \* vi.yres \* PIXEL_SIZE);
    }
    /_ inform the display driver */
    set_active_framebuffer(gr_active_fb);
}

**Comment by QuietStorm1785** [comment]
Also, flipping the x/y touchscreen values is not working either. Now it does not detect any of my touchscreen presses.

**Comment by Dees-Troy** [comment]
You can turn on touch event logging with this flag in your board config:
TWRP_EVENT_LOGGING := true
Then you can see where the touches are actually mapping.  0,0 is the upper left of the screen.
A lot of the graphics code in CWM won't work in TWRP because TWRP can render in 32bpp while CWM always renders in 16bpp then upconverts the 16 bit framebuffer at the very end to 32 bit.  That's why the screen flipping and conversion code doesn't work quite right in TWRP's graphics.c

With the right set of touchscreen flags you should be able to flip the touches around to match the upside-down screen.  I know I talked to one other person that flipped the touches around on a ZTE device and got it to work.
