### ISSUE TITLE
TWRP  2.6.3.0 doesn't ask for password of encrypted internal data and sdcard

### ISSUE THREAD

**Issue by pulsarice** [TeamWin/Team-Win-Recovery-Project#202]
I just encrypted my Samsung Google Nexus S (Crespo / I9023) within CyanogenMod CM-10.1.2 . Now whenever I boot into recovery, TWRP doesn't ask for encryption password and says in log: "Unable to mount '/sdcard' " and "Unable to mount '/data' ".

**Comment by rmats** [comment]
Same problem with Crespo and CM-10.1.3

**Comment by Overhear8805** [comment]
Same issue here on LG G-pad 8.3 (V500). TWRP 2.6.3.0

**Comment by wzstudio555** [comment]
TWRP 2.6.3. password tf201

**Comment by Isgar** [comment]
TWRP 2.8.6.0
CM 12.1
Device: manta / Nexus 10
Seems to be still relevant

**Comment by FlorianFiebig** [comment]
I got a similar problem with my Moto Z and LineageOS//TWRP
TWRP 3.1.0-0
Lineage OS Nightly  (Build from 25.04.2017)
My internal storage is encrypted (Settings --> Security --> Encrypt Phone (Encrpyted)). 
Yet TWRP does not ask me for a password and I can see the contents of the internal storage

**Comment by wokawoka** [comment]
I have the exactly same scary problem on TWRP 3.1.1 multirom on a Moto Z play running stock moto OS.
TWRP is no more asking me the PIN to decrypt the internal storage but once is starts I can read and write the internal storage (that means that the password is cached somewhere.
I believe that this should be treated as a really critical bug, as it basically defeat the purpouse of encrypting the phone.

**Comment by heinhuiz** [comment]
Why is this issue closed, what was the solution? The bug still exists (at least [on my Mi A1](https://forum.xda-developers.com/mi-a1/development/recovery-twrp-3-1-1-0-touch-recovery-t3688472)) and I agree with @wokawoka that it is a critical one.
