### ISSUE TITLE
2.6.1.0 on M7_ul backs up to /data/media

### ISSUE THREAD

**Issue by Sneakyghost** [TeamWin/Team-Win-Recovery-Project#205]
2.6.1.0 on M7_ul (HTC ONE) backs up to /data/media by default but should be backing up to /data/media/0/ instead.
Was working on 2.6.0.1.

EDIT: done for multi-user environment? Or bug?

LOG: http://pastebin.com/1X8ZzGf8

![fb0](https://f.cloud.github.com/assets/4991069/1062955/944ddbe8-127b-11e3-9bbb-c1b79f617328.png)

**Comment by bigbiff** [comment]
Please post recovery.log

**Comment by Sneakyghost** [comment]
posted recovery.log to original issue. Please note: log says storage set to /data/media/0 but its not backing up there.
