### ISSUE TITLE
GT-i9505G (jgedlte) data decryption

### ISSUE THREAD

**Issue by chriscjs** [TeamWin/Team-Win-Recovery-Project#208]
I am running cm 10.2 nightly.  Encryption works in cm but TWRP 2.6.1.0 fails to decrypt data.  Towards the end of the log file it shows the decryption process.  It tries to access a (non-existent?)
/dev/block/mmcblk0p29

According to the partition logs earlier in the log file-
/data on i9505g is /dev/block/mmcblk0p28
There is no /dev/block/mmcblk0p29 mentioned.
mmcblk0p29 is /data on i9505, not i9505g 

log file
http://pastebin.com/jE9KrZeV

**Comment by Dees-Troy** [comment]
i9505 does not have official TWRP support. Only i9500. Sounds like it would be pretty easy to support i9505 and i9505g, but that's the reason your device isn't working.
