### ISSUE TITLE
[Bravo] Recovery cannot mount sd-ext

### ISSUE THREAD

**Issue by island3r** [TeamWin/Team-Win-Recovery-Project#21]
The sd-ext partition cannot be mounted by the recovery. In the backup menu it is reported as 0mb even though it is used by the rom. When you do a backup with the sd-ext checked it fails since it can't be mounted. Other than that the rest of the backup is completed succefully.

**Comment by Dees-Troy** [comment]
blkid detection code isn't picking up and saving the partition type (ext3 or ext4)

**Comment by Dees-Troy** [comment]
Improved blkid detection today in the master branch.  Please test and let me know.  Thanks.

**Comment by Dees-Troy** [comment]
Made several improvements to the sd-ext code which should fix this problem.

**Comment by island3r** [comment]
2012/8/31 Dees-Troy notifications@github.com
