### ISSUE TITLE
TWRP 2.6.1.0 self encryption/password request preventing system boot

### ISSUE THREAD

**Issue by ScryerSteve** [TeamWin/Team-Win-Recovery-Project#211]
Samsung sprint L710 on Paranoidroid 3.99. And PA kernel.
Steps that's caused issues.
Update from stock root 4.1.2 to pa_3.99 while updating twrp to 2.6.1.0. 
Formatted all data.
Flashed : pa, gapps, and BMS kernel. 
Format data again.
Reboot
Successful system boot
Reboot
Samsung bootlock ( Samsung splash by PA)
Repeated steps without flashing BMS kernel
Successful system boot
Reboot 
Samsung bootlock

Following steps:
Reboot to recovery
! It requests a password
Press cancel
No longer able to access several folders and unable to boot to system or flashing zips
Select Wipe then format data
Wipe is successful ( any other format option fails)
Boot to system succcessful
Reboot to recovery 
No request for password 
Reboot to system 
bootlock at Samsung
Reboot to recovery
! It requests a password this time

I'm stuck in this cycle. 

I've attempted formating all partitions, reverting TWRP,  and so on.

**Comment by Dees-Troy** [comment]
Data decryption isn't supported on all devices. Sorry.
