### ISSUE TITLE
TWRP 2.6.3.0 ; HTC One X : Data decryption process failes 

### ISSUE THREAD

**Issue by lenthele** [TeamWin/Team-Win-Recovery-Project#213]
I recently enabled the encryption of my Data partition. Now when booting into TWRP I am asked to enter my password. But when I do I just receive an error... The log says that the decryption process failed...
Like this:

I:Copying file /cache/recovery/log to /cache/recovery/last_log
I:Is encrypted, do decrypt page first
I:Switching packages (TWRP)
I:Set page: 'decrypt'
I:Set page: 'trydecrypt'
Bad magic for real block device /dev/block/mmcblk0p15
Error getting crypt footer and key
E:Failed to decrypt data.
I:Set page: 'decrypt'
I:Set page: 'trydecrypt'
Bad magic for real block device /dev/block/mmcblk0p15
Error getting crypt footer and key
E:Failed to decrypt data.
I:Set page: 'decrypt'
I:Set page: 'trydecrypt'
Bad magic for real block device /dev/block/mmcblk0p15
Error getting crypt footer and key
E:Failed to decrypt data.

I am on a HTC One X running Android 4.2.2. Same issue occurred on TWRP version 2.6.0.x

Edit: will upload the full log file as soon as I get to a Computer. 

Edit 2: Here is the full recovery.log http://pastebin.com/mC6YAyqZ

**Comment by blaa** [comment]
Happens as well on openrecovery-twrp-2.6.3.3-m7.img or openrecovery-twrp-2.6.3.4-m7ul.img on HTC One. ONCE, after breaking running install i managed to mount /data. No idea how and can't reproduce it. It is certainly capable. It's not password thing. I've even simplified my password to one letter and it didn't  helped either.

**Comment by blaa** [comment]
I can reproduce it: First I pass password and get information that the decryption failed. Then I cancel decryption and try to install stock rom which has mount(/data) instruction in script, but I kill the install (unplug otg), and voilla - /data mounted with my decrypted data. So probably the decryption stuff is in place and works, but it can't mount decrypted block device.

**Comment by Dees-Troy** [comment]
HTC Sense ROMs don't use AOSP encryption methods so TWRP is not able to decrypt Sense ROMs.
