### ISSUE TITLE
Can't install 2.6.3.0 on ASUS tf700t

### ISSUE THREAD

**Issue by weathertom** [TeamWin/Team-Win-Recovery-Project#215]
I've tried installing TWRP 2.6.3.0 via goomanager and terminal method, but when I reboot into recovery I'm still at 2.6.0.0. I don't get any errors when doing things via terminal (following instructions from TWRP site) or via goomanager, but it just doesn't seem to take. Anyone else having this issue? I'm going to try via adb when I get home and can connect to my PC, but it seems like it should be working.

I saw a message on xda indicating the blob may be too large for the recovery partition. Is this correct, and if so, is there a workaround? Thank you.

**Comment by landstander668** [comment]
Assuming that you're running Android 4.3, the answer is almost certainly that you need to modify the Download Path value in GooManager settings.  Just replace "/0/" with "/legacy/" (i.e. /storage/emulated/legacy/goomanager) and you should be good to go.

On the off-chance that you use it, Titanium Backup has the exact same issue under 4.3.

**Comment by weathertom** [comment]
Just tried that, same result. It downloaded 2.6.3.0 went through the reboot process, but when I reboot into recovery it's still 2.6.0.0.

**Comment by Dees-Troy** [comment]
I updated TF700T to a 2.6.3.1 using a kernel and ramdisk that's compressed with lzma which makes the recovery image almost 2MB smaller. Should be good to go for future updates for a while now.

**Comment by weathertom** [comment]
Thanks, I'll give a shot.
