### ISSUE TITLE
Auto Complete feature in TWRP Create Backup Name

### ISSUE THREAD

**Issue by shaggyskunk** [TeamWin/Team-Win-Recovery-Project#216]
Please remove the default "auto complete" feature in Create Backup Name
or , At least allow the user to make their selection under settings.
One of the unique aspects (and intially "sold as a benefit"  of the ui for twrp was being able to select a custom backup name
With the most recent release, the user has to highlight the backup name and erase it, in order to input the Custom backup name

**Comment by Dees-Troy** [comment]
Swiping left across the keyboard (with the swipe covering at least 50% of the width of the keyboard will delete everything in the box. It takes less than a second to do. Leaving the name there allows you to tweak the default name without having to type out everything.
