### ISSUE TITLE
I AM HK HTC ONE X USER！ALL ABOUT HBOOT 1.73！

### ISSUE THREAD

**Issue by hldh214** [TeamWin/Team-Win-Recovery-Project#217]
I am very sorry to found that yesterday my htc one x got the FOTA to sense5 android4.2
and hboot update to 1.73
and recovery can't touch!!!:-(
vol and power is ok
and aroma installer also can't work!!!
PLEASE!UPDATE YOUR RECOVERY AS SOON AS POSSIBLE!
@HONGKONG

**Comment by Dees-Troy** [comment]
We'll need a copy of the new kernel that came with the update, so we'll need a copy of the stock boot or recovery.

**Comment by hldh214** [comment]
Must i send it to your team?
You need hboot or recovery?
Or i give the link of the FOTA?
Thanks!:-)
 ÔÚ 2013-9-26 ÉÏÎç2:34£¬"Dees-Troy" notifications@github.comÐ´µÀ£º

**Comment by hamedvipergtx007** [comment]
On the my phone is not work tuch .
When solve isue mesage to me.

**Comment by Dees-Troy** [comment]
Which HTC One do you have? endeavoru? evita? enrc2b? There's a number of different chipsets involved.
