### ISSUE TITLE
2.6.3.0 .img file for i9500

### ISSUE THREAD

**Issue by ai94iq** [TeamWin/Team-Win-Recovery-Project#218]
Hi 
Guys 2.6.3.0 .img file for i9500 break the recovery 
many users have this problem in xda-devs

Users also have problems with .tar file 
They get blank page after go in recovery 
Please fix it

**Comment by Dees-Troy** [comment]
We don't have an i9500 ourselves. If it's really broken we'd pretty much just have to pull support for i9500 completely.
