### ISSUE TITLE
Can't update the new version on N7100

### ISSUE THREAD

**Issue by LightSunChen** [TeamWin/Team-Win-Recovery-Project#219]
Why did I download and install the version 2.6.3.0 but when I booted into recovery it still showed the old version 2.6.0.1 ?
My device is N7100

**Comment by bigbiff** [comment]
Is there still an issue?

**Comment by LightSunChen** [comment]
Even worse, this time I tapped "install OpenRecoveryScript" it showed "no recoveries were found for your device"

**Comment by LightSunChen** [comment]
Even worse, this time I tapped "install OpenRecoveryScript" it showed "no recoveries were found for your device"

**Comment by bigbiff** [comment]
We can't help goo downtime.
