### ISSUE TITLE
TWRP 2.6.3.0 don't flash file (scripts not working)

### ISSUE THREAD

**Issue by gpvecchi** [TeamWin/Team-Win-Recovery-Project#220]
As title says, on Mako I can't flash this file
http://androidtweak.in/downloads/blue_mms_jb.zip
It's working fine with CMW Recovery (this one creates temp folder in data/media, TWRP in storage/emulated)

**Comment by gpvecchi** [comment]
I can add that I'm on 4.3 and older TWRP versions worked fine

**Comment by ziddey** [comment]
Refer to http://forum.xda-developers.com/showpost.php?p=30950470&postcount=140 for solution from over a year ago.

**Comment by gpvecchi** [comment]
Thanks, this solved the issue!
