### ISSUE TITLE
d2vzw fix permissions not working..

### ISSUE THREAD

**Issue by mystiquefbsd** [TeamWin/Team-Win-Recovery-Project#221]
Should the Fix Permissions be finished in a second? 

When I run the fix permission by hand from adb shell, [/sbin/fix_permissions.sh] it takes a few minutes and shows output.. 

Is that a problem? 

/sbin/fix_permissions.sh 2.04 ended at 10-02-2013 18:05:49 (Runtime:1m34s)

**Comment by lenthele** [comment]
I was wondering about the same thing lately...

**Comment by bigbiff** [comment]
Run it from the gui. The shell script is different.

**Comment by mystiquefbsd** [comment]
So there is a log when it is run from the gui?

Gui is done in _seconds_ from the shell script it takes over a minute.

So how can I find evidence that the gui worked?

For example 'Beautiful Widgets' does not work right when I run the script from the shell, from the gui nothing is different.
