### ISSUE TITLE
On v2.6.3.0  unable to wipe Data Partition

### ISSUE THREAD

**Issue by Perseus71** [TeamWin/Team-Win-Recovery-Project#223]
Hi,

I seem to have this reproducible issue with version 2.6.3.0. My device is D2TMO.

Every time I try to wipe DATA partition, I get the following error.

E:error opening '/data/media/0/Android/data/com.android.providers.media'
E:error: Not a directory

I can run any commands you want in the adb shell. 

I checked and there was no bug reported for this version. The closest one was reported against v 2.5 and that was going to be fixed in version 2.6. From that bug, expecting further request, I have run 
df -h
mount -v
I do not wish to paste the output here as it is too long. The full log file is Uploaded to
http://www.androidfilehost.com/?fid=23159073880934660

Kindly let me know if you need additional information.

**Comment by Perseus71** [comment]
Bump!
Anyone ?

**Comment by Dees-Troy** [comment]
Odds are your data partition has some kind of file system corruption. Because this is a data/media device, you'll need to back up anything you want to keep that's on internal storage (pictures, downloads, TWRP backups, etc) to a separate device like a computer. Then go to wipe -> format data.

**Comment by Perseus71** [comment]
I had tried those steps at that time. It had not worked.

Now that I have next version 2.6.3.1, the issue is not occurring.
