### ISSUE TITLE
4.3 on i9300

### ISSUE THREAD

**Issue by CtrlPlusA** [TeamWin/Team-Win-Recovery-Project#229]
TWRP 2.6.3.0 is causing problematic flashes with Android 4.3 and 4.3.1 as reported on XDA by a number of users from this page on: http://forum.xda-developers.com/showthread.php?t=1943592&page=57

The flash happened ok (taking much longer than usual to get past boot animation) but then on reboot, it would hang on the Samsung S3 logo and go no further. A work around that worked (sometimes) was to boot up in recovery and do a factory reset.
Other users report this hanging with each reboot.

This is reported to happen on a number of ROMs, including SlimBean and LiquidSmooth ROMs.

**Comment by Dees-Troy** [comment]
ROM flashes are almost entirely up to the update binary and update script. Recovery pretty much does nothing but display text and progress bar updates during the install process. If there's an issue, it's probably related to SELinux contexts. Users should update to 2.6.3.1 on the i9300 to ensure that their recovery fully supports reading and writing SELinux contexts.
