### ISSUE TITLE
Installed GooManager then installed OpenRecovery, phone rebooted now its stuck saying "Downloading... do not turn off target"

### ISSUE THREAD

**Issue by gyounan84ec** [TeamWin/Team-Win-Recovery-Project#230]
if i remove battery and turn on normally...
if i hold vol up, home and power...
if i hold vol down, home and power...

it is still stuck on the "downloading... do not turn off target"

what now???

**Comment by bigbiff** [comment]
Please send this to the author of Goo Manager. We don't maintain that application.
