### ISSUE TITLE
when booting into recovery theirs a serious lag

### ISSUE THREAD

**Issue by zoltan1960** [TeamWin/Team-Win-Recovery-Project#231]
This has been like this since day one,3 months ive even went to rom manager but quickly switched back.it seems to sit on team win boot up screen sometimes have to reboot again.on average at least 1 to 2 minutes. On my s3 it was immediate bam into settings

**Comment by bigbiff** [comment]
Have you tried formatting the partitions on your phone. There might be a lot of file corruption.

**Comment by that1** [comment]
"updating partition details" can be slow if there are lots of files on /data.

**Comment by Dees-Troy** [comment]
No device listed, no logs posted.
