### ISSUE TITLE
Installing ZIPs Fails in TWRP

### ISSUE THREAD

**Issue by djbeck** [TeamWin/Team-Win-Recovery-Project#232]
I have been trying to install the new ROM "OmniRom" for my HTC One (m7ul) but I have had problems.  After a full wipe, I install the OmniRom with no problems.  The next step is to install the SU & Gapps zip files.  When I try to install the zips, I get the following in my log 

E:Unable to open zip file.
Error flashing zip '/sdcard/Download/UPDATE-SuperSU-v1.65.zip'
Updating partition details...

Thanks for any ideas

**Comment by bigbiff** [comment]
Please provide /tmp/recovery.log after the install.

**Comment by milindlokde** [comment]
I am having same problem. I have iBall Andi4.5h. Error flashing zip for all files I zip. 
1) I tried with working zip files, uncompressed it and compressed it again. It still got the same error.
2) I tried the above on Ubuntu 64-bit, Windows 7 64-bit (normal and with winrar), Debian 32-bit and 7-zipper on android. It still gave the same error.
3) Used kitchen tool to open a ROM and finished it (prepared zip) without making any changes using the kitchen. The ROM again gave same error.
4) Tried with TWRP2.5.0.0, TWRP2.5.5.5 and TWRP 2.3.3.0 Still same issue.
5) Tried installing 4.1.2 ROM and 4.2.1 ROM, still same issue. 
6) All flashable kernels and ROMs from the developers are working file.

Here is the link to my recovery.log file, showing non-flashing and flashable zips.
https://drive.google.com/file/d/0B3ORdhoiYRSWOXEyOER4Z09WMmc/edit?usp=sharing

**Comment by milindlokde** [comment]
I checked everything, the zip was not unzipped properly. Files need to be unzipped with complete paths.
I used 7z (7zip) command in Ubuntu to do it. 1st command to uncompress does not work. 2nd always works. 
$ 7z e FileToUnzip.zip //normal extract of zip file. Does not work
$ 7z x FileToUnzip.zip //To eXtract with full path. Always works
$ 7z a -tzip File1 File2 AllFiles\*  NewFile.zip

**Comment by Dees-Troy** [comment]
Zips that are failing are invalid / not correct. Not TWRP's fault.

**Comment by milindlokde** [comment]
Definitely not TWRP's fault and thanks for closing the thread. But it was very difficult to locate the source of error. The default unzip tool in Linux (both Debian and Ubuntu) and Windows were not compatible. I lost almost three weeks and even hope, until it failed with CWM recovery as well. So I tried all different ZIP tools and ofcourse 7zip the swiss knife of compression and decompression.
Recommended tool is WinRAR and 7zip with 'x' option. 
I think this should be added in FAQ or HOW-TO of TWRP

**Comment by srishtimathur6** [comment]
Trying to flash any ROM zip in TWRP and while doing so you are facing this error, "invalid zip file format". Then don't worry, as here I will show you a complete tutorial to fix this issue.

What you have to do is click on this error title, "**[TWRP Invalid Zip File Format](https://techgearz.com/fix-twrp-invalid-zip-file-format/)**" to browse the complete tutorial and fix the issue right now on your Android device.

**Comment by 1e-skip** [comment]
fuckt up that the link is Dead. So no howto for this solution. So thanks for nothing srishtimathur6

**Comment by abchacking1234** [comment]
I want to flash the custome rom b/c after installing the twrp when i want to boot to system it says no os installed. I had known that i wiped the system so i decided to install new rom for my infinix phone but i faced the problem of invalid zip format. I don't know what to do. I am stuck in twrp i can't boot into the system. plz help me🙏🙏

My phone is 
:- infinix smart 3 plus ( x627 )

**Comment by abchacking1234** [comment]
I want to flash the custome rom b/c after installing the twrp when i want to boot to system it says no os installed. I had known that i wiped the system so i decided to install new rom for my infinix phone but i faced the problem of invalid zip format. I don't know what to do. I am stuck in twrp i can't boot into the system. plz help me🙏🙏

My phone is 
:- infinix smart 3 plus ( x627 )

**Comment by linchan9001** [comment]
same problem:(((

**Comment by 2003emachinesDesktop** [comment]
no solution?
