### ISSUE TITLE
Note 3 no recovery available

### ISSUE THREAD

**Issue by sejmand** [TeamWin/Team-Win-Recovery-Project#234]
Rooted note 3 international qualcomm
Installed goo manager 
su enabled
Notification: no recovery available

**Comment by shaggyskunk** [comment]
You may find that it's because goo.im is in the process of upgrading it's servers - As is posted on goo and on their Twitter account.

**Comment by sejmand** [comment]
No are the serves up again:
"GooInsideme: Status Update! https://t.co/Wo3EFmhvaJ"

But I did not manage to get twrp; here are my data (is there the mistake?):

AP: N9005XXUBMJ3
CP: N9005XXUBMJ2
CSC: N9005DBTBMJ3
Added: 2013-10-17

Odin mode
SM-N9005
Current Binary: samsung Official
Sysrem Status:Custom
Reactivation lock: off
Knox Kernel Lock: 0x0
Knox Warranty void 0x1
Qualcomm scureboot enable (CSB)
RP SWREV: S1 T1 A1 A2 P1
Write Protection: enable

**Comment by sejmand** [comment]
still "no recoverys wer found for your device"

but there is "twrp" from "teamw.in":
boxopenrecovery-twrp-2.6.3.7-hlte.img.tar

Am I confused?

**Comment by bigbiff** [comment]
We can't help goo downtime.
