### ISSUE TITLE
Can't unencrypt 4.4

### ISSUE THREAD

**Issue by uxBrad** [TeamWin/Team-Win-Recovery-Project#235]
I'm able to flash a 4.4 ROM from 2.6.3.2 recovery, but I'm not able to decrypt when entering back into recovery.

**Comment by mjasin** [comment]
I have this same problem after flash Galaxy Nexus to 4.4 (TWRP v2.6.3.1)

**Comment by ich0** [comment]
I initially had this problem with the older build on grouper, crespo, and maguro, however i was unaware of the 2.6.3.2 build... Going to find a built image (none exists for crespo and maguro?) and try again with that.

**Comment by shaggyskunk** [comment]
Looks like some TWRP versions, need an update. 
TWRP 's latest version for Grouper works fine - But for the t0lte variants - It seems to be presenting some issues with 4.4.

**Comment by ilarrain** [comment]
I'm having the same problem on maguro. My data partition has been encrypted for several months, and I've been using TWRP without problems, until I first booted kitkat. Now I can't decrypt my internal storage in TWRP.

Has anyone been able to find an updated image for maguro?
Right now I don't have the pc nor the bandwidth to download cm11 sources.

**Comment by Dees-Troy** [comment]
Check for updates for your devices. For instance, maguro is on 2.6.3.2
