### ISSUE TITLE
Missing decrypt data (i9505)

### ISSUE THREAD

**Issue by houmles** [TeamWin/Team-Win-Recovery-Project#237]
I was using 2.6.1.0 on Galaxy S4 (i9505) where decrypting works perfectly. Unfortunately I have sometime problem with flashing some zips so I wanted to try newer version 2.6.3.1.
However in this version there in no button in mount option to decrypt data and when booting it didn't ask me for password either.
Is it removed in this version or is it some bug?
Thanks

**Comment by vtsingaras** [comment]
Same issue in 2.7.1.0
