### ISSUE TITLE
2.6.3.2 Backups have incorrect dates

### ISSUE THREAD

**Issue by JSON123** [TeamWin/Team-Win-Recovery-Project#238]
Using Nexus 5 Android 4.4 KitKat dates of backup folders are incorrect. Start at 1969-12-31 and go up from there 1970-01-01 etc.

**Comment by JSON123** [comment]
Also the time displayed in the recovery is incorrect.

**Comment by bigbiff** [comment]
Can't fix S800 SOC which doesn't set RTC in android.
