### ISSUE TITLE
Backup  E:unable to locate recovery partition

### ISSUE THREAD

**Issue by ghost** [TeamWin/Team-Win-Recovery-Project#241]
TWRP 2.3.1.0
Nook Color  
CM10.2

I have spent almost  a day  on  many forums trying to fix TWRP. It will not run a backup. Fails for above error.
I have re-installed many times
Trying to use external SD.
CWM 6. x  will run and back up to SD
Any help
Thanks
Roger R

**Comment by bigbiff** [comment]
Have you tried deselecting the recovery partition to backup?

**Comment by ghost** [comment]
Not really sure what you mean?? So where in the menu of TWRP  do I do that?
I was able to get a good  abckup running CWM recovery.  I saw the same error msg but the program ran fine and I obtained a good backup. 
So for now I wont be using TWRP

**Comment by bigbiff** [comment]
OK, closing bug since we won't be able to verify.
