### ISSUE TITLE
CM-11 official zips fail installation

### ISSUE THREAD

**Issue by seefood** [TeamWin/Team-Win-Recovery-Project#246]
Since CM11 changed something in November or maybe early december, installing a cm11 zip in TWRP fails on my i9300. reading around I found people say it's an issue with TWRP's lack of support in ext4 XATTRibutes or maybe an issue with SELINUX. TWRP just sits there unzipping for a minute or three before I get a red FAILED and go recover from the latest nandroid. I found a link to a patched, unofficial TWRP that is supposed to solve this, but I'm too scared of installing from unknown, unsupported sources.

To contrast, I have no problem installing Temasek's unofficial cm11 builds, Whatever they are doing differently.

**Comment by Dees-Troy** [comment]
Make sure you're on the latest version:
http://goo.im/devs/OpenRecovery/i9300//openrecovery-twrp-2.6.3.1-i9300.img
