### ISSUE TITLE
Can't mount FAT32 formatted external 16GB SD Card

### ISSUE THREAD

**Issue by wpbear** [TeamWin/Team-Win-Recovery-Project#248]
TWRP 2.6.3.2 on LG G Pad 8.3 (not GPE version) says "E: Unable to mount '/externel_sd'

The same card works with Asus TF700 with same TWRP version.  Card works and is seen on G Pad once full system boots to CM11. 

I pulled the log: http://tinyw.in/VmRt

Xda thread: http://forum.xda-developers.com/showthread.php?p=48912553

**Comment by Dees-Troy** [comment]
Updated the recovery.fstab and will be fixed in the next release for this device. fstab was missing a reference for the alternate block device of /dev/block/mmcblk1
