### ISSUE TITLE
Most TWRP actions causes stock Nexus 5 to reboot

### ISSUE THREAD

**Issue by Bugsbane** [TeamWin/Team-Win-Recovery-Project#257]
Hi there,

STEPS TO REPRODUCE:
Open TWRM. Click backup or install. Choose a file(name) and swipe to begin the action.

ACTUAL:
Phone reboots as soon as the actual action begins. For example, if I choose backup, it will ask me for the file name and that's fine, but as soon as I swipe to backup, the phone instantly reboots. The same with installing. I can choose a file to install, but the instant I tell it to perform the install, the phone reboots.

EXPECTED:
It is possible to choose Backup, Install etc and have those functions perform as they do in video tutorials on YouTube rather than having my phone just reboot.

NOTES:
I turned logging on, but I'm not seeing any logs in /tmp/ as I was told there would be.

SPECS:
This is a brand new Nexus 5 with all updates applied (Android 4.4.2), with nothing done to it other than unlocking the bootloader, rooting it and installing TWRP from the Play Store.

**Comment by Bugsbane** [comment]
OK. So I've realised that rebooting into recovery mode is actually the expected behaviour HOWEVER the issue seems to be that despite having TWRP installed that it still boots to stock recovery mode instead of TWRP recovery mode.

Any ideas how to get it to boot to TWRP recovery mode?

**Comment by ghost** [comment]
This is a chicken vs egg deal. Don't install from the Play Store.

Follow the directions from this site:

http://forum.xda-developers.com/showthread.php?t=2507905

I install "superuser" from koush (http://download.clockworkmod.com/superuser/superuser.zip) rather than SuperSU.

**Comment by Dees-Troy** [comment]
It works find on numerous other people's Nexus 5 phones. Try reinstalling the factory images from Google to revert back to stock.
