### ISSUE TITLE
v2.6.3.1 SPH-L710 d2spr Sprint Samsung Galaxy S3

### ISSUE THREAD

**Issue by roirraWedorehT** [TeamWin/Team-Win-Recovery-Project#259]
Reported by several members in this thread http://forum.xda-developers.com/showthread.php?t=1809307, v2.6.3.1 prompts for a password when booting into recovery. After entering just a blank password, the recovery doesn't see any partitions at all on the phone. Odin back to v2.6.3.0 restores all functionality.

**Comment by roirraWedorehT** [comment]
Reference http://forum.xda-developers.com/showthread.php?p=47879792:

I only found out there was difference when I tried to install a custom recovery in the process of rooting my new GS3 a few weeks ago and the recovery wouldn't mount any of the storage partitions, so I couldn't flash anything, restore nandroid backups, etc. Come to find out newer GS3s have an additional security flag in the kernel and the custom recovery needs to be modified to circumvent it. I'm running an older version of TWRP that was made to work with the newer GS3s, and just wanted to see if anyone knew if these newer versions would work with my device. 

I may just try it out when I get home from work and I can always re-flash my current recovery if the newest version doesn't work.

_edit_ 

Confirming that these files do not work with newer GS3 devices. If the workaround is fairly easy I would be willing to give it a try myself but I'm not sure where to start.

**Comment by andrewjkerr** [comment]
I'm having the same problem and entering the encryption pin doesn't work. :/

**Comment by roirraWedorehT** [comment]
Same problem with v2.7.0.0: it didn't see any partitions at all on my S3. As noted in v2.7.0.0's changelog, it no longer asks for the password that doesn't exist on my phone, but still won't see any partitions.

**Comment by generalmx** [comment]
Can you upload your recovery.log file? I'm currently not having this problem with my own d2spr SGS3, instead having a different problem relating to encryption. You can use either ADB, USB-OTG using a flash drive, or an external microSD card to copy the recovery.log file to.

**Comment by roirraWedorehT** [comment]
@generalmx, I'll try to remember to re-load the faulty version. and get a log file for you ASAP, thanks for asking.

Also, interestingly, as I detail in this post http://forum.xda-developers.com/showpost.php?p=51360091&postcount=1243, Phil_Suz has made (with permission) a modified version of TWRP v2.7.0.0 for multi-boot purposes, and it works 100% on my phone.  It doesn't solve everyone's problems with v2.7.0.0, though.

It's worth trying in case it helps you, although I'm not too hopeful since you have a different issue.
