### ISSUE TITLE
TWRP Restore

### ISSUE THREAD

**Issue by wataboss7** [TeamWin/Team-Win-Recovery-Project#261]
I backed up all my data with TWRP, but when I restore, it says that it failed. If I try to restore anything else like my Boot or System, it restores properly, but when I get to the Data, the restore fails. I was wondering how to fix this problem. Just restoring Data alone causes failure. I attached a log because it might be useful. Can you please help me with this problem? THANK YOU!!!

Log File: http://www.mediafire.com/view/1ga3tqtyz8ccc4c/recovery.log

**Comment by Dees-Troy** [comment]
The log that you posted doesn’t contain. Just restore data and copy the log before rebooting.

**Comment by wataboss7** [comment]
Okay thank you for the reply, but what doesn't the log contain?
