### ISSUE TITLE
Can't restore backup encrypted by TWRP 2.7.0.0

### ISSUE THREAD

**Issue by amiv1** [TeamWin/Team-Win-Recovery-Project#265]
Hello! Recently I updated TWRP on my **Nexus 7 3G (2012)** to **twrp-2.7.0.0-tilapia** and made an encrypted backup. Today I tried to restore this backup and failed, because it says that password is not correct, although it is 100% correct. Every encrypted backup that I made with 2.7.0.0 is not possible to restore. Also, I'm using compression.
Restore Log: http://pastebin.com/EXuRZMDv
Backup & Restore log: http://pastebin.com/8ezwXgvE

Encrypted backups made by previous versions are fine.

**Comment by ishemes** [comment]
I'm having the exact same problem. My last non 2.7 branch backup is from weeks ago, so I do not know what to do. Only backups from before 2.7 can be restored. Can somebody confirm if this is a problem with the restore process (backups can be salvaged) or the backup process (backups are lost)?

**Comment by amiv1** [comment]
ishemes, I had a conversation with developers on IRC channel about it, and it's most likely encryption issue, so your backups are probably lost. So this feature turns out to be extremely unreliable.

**Comment by ishemes** [comment]
Damn... that is bad news... I tried a new ROM and did a factory reset thinking I would have the backup in case anything went wrong. I'll go and manually restore the apps that Titanium backup backed up. Thank you for the update!

**Comment by amiv1** [comment]
I don't know if it's fixed but I'm going to close it because if inactivity
