### ISSUE TITLE
2.7.0.0 on d2vzw - Backup Failed when trying to create backup

### ISSUE THREAD

**Issue by bawaji** [TeamWin/Team-Win-Recovery-Project#267]
When I try to create a nandroid backup on my Verizon Samsung Galaxy S3 running rooted Android 4.3 using TWRP 2.7.0.0,  I get a "Backup Failed" error regardless of whether I try to save the backup on my external SD card or internal storage. I reverted back to TWRP 2.6.3.1 and backup works fine.

The last few lines of my error log are as follows (I have replaced my device ID with <device id>):
.
.
.
I:addFile '/system/xbin/makedevs' including root: 0
setting selinux context: u:object_r:system_file:s0
I:addFile '/system/xbin/makemime' including root: 0
setting selinux context: u:object_r:system_file:s0
I:addFile '/system/xbin/man' including root: 0
setting selinux context: u:object_r:system_file:s0
Splitting thread ID 0 into archive 2
E:tar_open error opening ''
E:Error creating tar '' for thread 0
I:ERROR tarList for thread ID 0
E:Error creating backup.
I:createTarFork() process ended with ERROR=255
I:Set page: 'action_complete'
I:Set page: 'clear_vars'
I:Set page: 'backup'
I:Set page: 'main'
I:Set page: 'clear_vars'
I:Set page: 'main2'
I:Set page: 'advanced'
I:Set page: 'filemanagerlist'
I:Set page: 'filemanageroptions'
I:Set page: 'filemanageroptions'
I:Set page: 'filemanagerconfirm'
I:Set page: 'filemanageracction'
I:Running command: 'rm -rf "/external_sd/TWRP/BACKUPS/<device id>/2014-03-16--16-28-39 JSS15J.I535VRUCML1"'
I:rm -rf "/external_sd/TWRP/BACKUPS/<device id>/2014-03-16--16-28-39 JSS15J.I535VRUCML1" process ended with RC=0
I:Set page: 'action_complete'
I:Set page: 'clear_vars'
I:Set page: 'filemanagerlist'
I:Unable to open '/external_sd/TWRP/BACKUPS/<device id>/2014-03-16--16-28-39 JSS15J.I535VRUCML1'
I:Set page: 'advanced'
I:Set page: 'main'
I:Set page: 'clear_vars'
I:Set page: 'main2'
I:Set page: 'mount'
I:Set page: 'main'
I:Set page: 'clear_vars'
I:Set page: 'main2'
I:Set page: 'wipe'
I:Set page: 'main'
I:Set page: 'clear_vars'
I:Set page: 'main2'
I:Set page: 'advanced'
I:Set page: 'confirm_action'
I:Set page: 'action_page'
I:Copying file /tmp/recovery.log to /external_sd/recovery.log

**Comment by lefth** [comment]
I have this problem on the HTC One. I noticed that if backups are compressed, the failure is silent, but if uncompressed, we see the expected "backup failure" message on the screen.

Facts:
- HTC One, reproducible on 2.7.0.0 and 2.7.0.5 beta build.
- The error is that a second archive wants to be created, but it has an empty filename. Line 1000 of twrpTar.tar
- The SYMLINKS in /system/xbin are backed up alphabetically, up to "i", after which it fails.
- The BINARIES in /system/xbin are all backed up, even those that are alphabetically after "i".
- The FOLDER /system/ybin (containing a script) is not backed up.

Log 1: http://pastebin.com/t2859Grb
Log 2: http://pastebin.com/AU9N3Y7A

I am happy to help reproduce this, even potentially debugging and patching it myself, if someone can help with some modern build instructions.

**Comment by joscha** [comment]
I can see this error on 2.8.6.1:

``` console
Backing Up Data...
E:createTarFork() process ended with ERROR=255
Backup Failed.
```

Seems to happen only when I also select the "Data" partition.

**Comment by axelsimon** [comment]
Seeing this right now on a Xperia Z3 Compact with TWRP 3.0.2-0, when choosing compression + encryption.
The backup completed once I unticked the box to enable compression (but not encryption).

**Comment by DonRadlauer** [comment]
I'm seeing it on my new Huawei P9 Plus. FWIW, I never had the problem on my old Galaxy S3 - and I'm using the same external SD card and pretty much the same apps and Android version (albeit now I'm stock Android, and my S3 was running CM13).

I've installed FlashFire and used it to create a backup - but I'm not sure if I trust it! Help!!!

**Comment by Joeyzo** [comment]
Having the exact same problem on Samsung SM G389F

**Comment by pizzarabe** [comment]
Have the same problem backing up with TWRP 3.0.1-0 on a One Plus One

Edit: might be related to all the restore error 255s (https://github.com/TeamWin/Team-Win-Recovery-Project/issues/1048, https://github.com/TeamWin/Team-Win-Recovery-Project/issues/964)

**Comment by maxammann** [comment]
Having the same problem on oneplus5
