### ISSUE TITLE
HTC One, encrypted userdata partition cant mount in TWRP 2.7.0.0

### ISSUE THREAD

**Issue by altexdim** [TeamWin/Team-Win-Recovery-Project#269]
I have htc one official stock, updated to 4.4.2 official ota, unlocked and rooted, s-on
Encrypted userdata partition with android out of the box encryption method (settings -> storage -> encription)
Set up latest TWRP (2.7.0.0)
After loading TWRP it asks for password, i give it, but it cant mount encrypted /data partition.

I searched for solutions in google, 
tried latest CWM (it does not support encryption, but has minivold), 
tried adb in recovery (both twrp, cwm) the following method

> setprop ro.crypto.state encrypted
> vdc cryptfs checkpw 'password'

Tried mount /system and use /system/bin/vdc instead of /sbin/vdc from recovery
... still without any luck 

I'm looking forward to help debug this issue, send any logs and other information, i'm familiar with console, linux, source code etc, can provide you access to my pc via teamviewer to manualy debug phone.

P.S. I noticed similar issue like in https://github.com/TeamWin/Team-Win-Recovery-Project/issues/247

**Comment by MikeDacre** [comment]
I have the same issue.  I upgraded to Cyanogen Mod cm-11-20140406-SNAPSHOT-M5-toroplus.zip and decryption failed in TWRP, despite working fine in the OS.

**Comment by Blaimi** [comment]
same here with cm-11-20140504-SNAPSHOT-M6 with 2.7.0.0 on Galaxy S3 International (i9300)

**Comment by ChrisG683** [comment]
I'm having a similar issue, although mine differs just slightly.  My phone is encrypted since it is required for work, however when I boot into recovery, I am not even asked for my encryption password, all I get in the console is multiple messages saying along the lines of

"Unable to mount /data"

I've seen a lot of people on various forums having this same problem, hopefully you guys can look into getting this fixed.

TWRP 2.7.0.1
AT&T Galaxy S 4 (SGH-I337)
Android 4.4.2, Google Play Edition based ROM

**Comment by Thracky** [comment]
Same issue here, HTC One Google Play Edition just installed the 4.4.3 update. Storage decrypts fine when booting into system, no dice with TWRP.

**Comment by akang6** [comment]
I too have this problem HTC One Google Play Edition. Boots fine but I can't decrypt on TWRP.

**Comment by Thracky** [comment]
It was mentioned to me in IRC that GPE uses Sense framework underneath and
as such does not use AOSP encryption.

**Comment by ChrisG683** [comment]
Would that also mean that the Samsung GPE would use a TouchWiz based encryption, and not the AOSP one?

**Comment by MikeDacre** [comment]
Would this affect Cyanogenmod 11 M7 (4.4.3)? I am still unable to decrypt with TWRP 2.7.1.0. Is anyone else having this issue? Is Google Play Edition somehow different from Android 4.4.3?

**Comment by HerbCSO** [comment]
Same issue here on a Samsung Galaxy S3 (d2vzw) with CM 11.0 (M6) and TWRP 2.7.1.0. The phone was encrypted under CM 11 so I don't believe it's a custom encryption...?

I'm happy to help debug this as long as somebody can tell me what to do.

**Comment by maaraneasi** [comment]
Same here on M7 and twrp....

**Comment by altexdim** [comment]
I've found a way to mount encrypted partition on HTC ONE with the latest android version 4.4.3 
It's a python script, that can extract decrypted key from encrypted header and footer, so you can unterstand the algorythm.
I've got original python script from https://github.com/santoku/Santoku-Linux.git and hardcoded support for the HTC ONE (basicaly changed key size to 32, iv size to 32, aes_128_cbc to aes_256_cbc).
Here it is http://pastebin.com/TAeA6rSw
So, can i ask you @Dees-Troy to implement HTC ONE encryption into your TWRP project based on the algorythm in my script?

**Comment by werty1st** [comment]
with the information @altexdim provided it should be possible to compile a custom version with changed values for key size, iv size and encryption mode.

i think with android 5.0 encryption more and more comes to focus and it should be possible to use the recovery with encryption enabled.

**Comment by ghost** [comment]
I have the same issue on HTC One M7 using stock encryption. TWRP 2.8.6.0.
Is it possible to get this fixed or do I have to reset factory settings?

**Comment by bgcngm** [comment]
For the moment, a reset to factory settings will be your only option as it will remove encryption. If you don't need encryption enabled then don't do it. On my case, I can't do nothing about it because I really need encryption enabled due to mandatory Exchange policies.
