### ISSUE TITLE
HTC One /system backups fail--silent failure if compressed, "BACKUP FAILED" otherwise.

### ISSUE THREAD

**Issue by lefth** [TeamWin/Team-Win-Recovery-Project#270]
The failure happens when the tar archive is split, but archive #2 has no filename. The failure starts when the files in /system/xbin are being backed up. The symlinks with alphabetically "high" filenames are not backed up, but strangely, the binaries are. A directory called /system/ybin is skipped entirely, probably because it's alphabetically after /system/xbin.

Note: the error is line 1000 of twrpTar.cpp.

Logs:
Silent failure (using TWRP compression): http://pastebin.com/91zbWQJs
Explicit failure (uncompressed): http://pastebin.com/96AxbhMd

**Comment by lefth** [comment]
The files necessary to reproduce this error can be found in: http://zwell.net/m7-system-backup/

First, an incomplete but errorless TWRP /system backup can be restored, then a tar archive can be extracted in the device root to fill /system/xbin and /system/ybin with some missing files.

Note: the larger file's md5sum is 01ad7c7b852b95b698d622aba3eabb90, and it should be 1030 MB.

**Comment by Dees-Troy** [comment]
Using the files posted I was able to reproduce the problem. I'll let you know when I find the fix.

**Comment by lefth** [comment]
Glad to hear that. Thanks!
