### ISSUE TITLE
No support for KEXEC

### ISSUE THREAD

**Issue by hevel86** [TeamWin/Team-Win-Recovery-Project#28]
The Verizon Galaxy S3 has the locked bootloader, and the workaround is KEXEC to install custom kernels.  Currently this is not supported on anything but CWM 6.0.1.0 and it would be awesome to have this in TWRP as it's by far my favorite recovery! Thanks!

**Comment by Dees-Troy** [comment]
I don't have a VZW SGS3 (or any SGS3 actually) so I'm not even sure what would be needed in order to add this support.  If you or someone else can provide more details, we can look into it or someone could even submit a patch to add it.

**Comment by hevel86** [comment]
I'm not a developer and wouldn't even know where to begin to help, but I am eager to learn and/or figure out as much as possible.  I posted a link to this spot on Rootzwiki. I hope you don't mind, if that causes too many problems then I will edit the post.  What else can I do to help?

**Comment by justlovejoy** [comment]
if it's ok i chime in, I am no professional developer yet but i have only seen kexec used in the formalities of kernel development, not recoveries per-say, so i wonder if the cwm6 version that u speak of came as a flashable kernel and not just a recovery. that does what you'd like to see be doable with twrp . that said, I'd look into the kernel devs for the phone mentioned and ask for a twrp version with kexec capabilities. forgive me if i am incorrect. 8)

**Comment by hevel86** [comment]
Yes, justlovejoy, the point of KEXEC is to allow custom kernels, however there is a version of CWM that allows for an auto KEXEC kernel installation without user input.  KEXEC in and of itself requires user input and just isn't quite as clean.  But on a more important note.. the bootloader is now unlocked!  Now we can worry about bug fixes and updates rather than KEXEC! :)

**Comment by Dees-Troy** [comment]
KEXEC support no longer needed with the unlocked bootloader.
