### ISSUE TITLE
can't install apps after restoring a CM11 backup in TWRP 2.7

### ISSUE THREAD

**Issue by ktulu84** [TeamWin/Team-Win-Recovery-Project#280]
if you perform a restore of a CM11 backup, you can't install any app, no matter the source, the only fix is to restore SELinux contexts, here is a diff file that shows the situation before the restore and after the restore. this bug is on all TWRP 2.7 build i tried, official and unofficial

--- before.txt
+++ after.txt
@@ -1,6 +1,6 @@
 drwxr-xr-x root     root              u:object_r:system_file:s0 addon.d
 drwxr-xr-x root     root              u:object_r:system_file:s0 app
-drwxr-xr-x root     shell             u:object_r:system_file:s0 bin
+drwxr-xr-x root     shell             u:object_r:zygote_exec:s0 bin
 -rw-r--r-- root     root              u:object_r:system_file:s0 build.prop
 drwxr-xr-x root     root              u:object_r:system_file:s0 cameradata
 drwxr-xr-x root     root              u:object_r:system_file:s0 etc
@@ -9,7 +9,7 @@
 drwxr-xr-x root     root              u:object_r:system_file:s0 fonts
 drwxr-xr-x root     root              u:object_r:system_file:s0 framework
 drwxr-xr-x root     root              u:object_r:system_file:s0 lib
-drwxr-xr-x root     root              u:object_r:system_file:s0 lost+found
+drwxrwx--- root     root              u:object_r:system_file:s0 lost+found
 drwxr-xr-x root     root              u:object_r:system_file:s0 media
 drwxr-xr-x root     root              u:object_r:system_file:s0 priv-app
 drwxr-xr-x root     root              u:object_r:system_file:s0 tts

**Comment by smeroni68** [comment]
Another problem has been found with SlimKAT ROMs... after restoring a backup with v2.7.0.0 the wifi hotspot is not working... same backup restored with v2.6.3.0, the hotspot works... probably some permission missing after restore action...

I tested personally also on S4 with Official TWRP, and the same problem described from ktulu84 on CM11 Official builds: after restore, no way to install any apk... reflashing the ROM solve the problem...

**Comment by Dees-Troy** [comment]
The before and after command needs to be changed a little. Mount system and cd /system then run this command:
ls -alZR > /before.txt
and again for /after.txt to compare the 2.

**Comment by Dees-Troy** [comment]
Also run just:
ls -alR > /beforeperms.txt
ls -alR > /afterperms.txt
So we can capture the regular file permissions as well as the selinux contexts.

**Comment by ktulu84** [comment]
you mean to do ls -alZR in / ?

EDIT: ok, i understood now :D

**Comment by Dees-Troy** [comment]
I said to "cd /system" then run the command. Running it in / will include way more stuff than we want.

**Comment by smeroni68** [comment]
Hi,
here the differences on S4 restore with CM11:

http://pastebin.com/WPGg55Cd

Hope it help to understand

PS: Tested after restore, no apk can be installed... flash of setmetadata.zip and the rom is back working... both perm and selinux are in the same doc...

**Comment by Dees-Troy** [comment]
I am going to try to reproduce on Nexus 7 2012 with CM 11. In the meantime, please find the recovery.log in the backup folder and do another restore. Send me both the log from the backup and grab the log after the restore.

**Comment by Dees-Troy** [comment]
I did a clean install of the latest CM11 nightly on grouper plus gapps then ran a backup and restore and had no problem installing apps after the restore. Are you running fix permissions or doing anything else after the restore before trying to install apps?

**Comment by smeroni68** [comment]
Will provide in the evening. No fix permissions and nothing else.
Backup -> Restore -> reboot to system and check
Checked also after a new reboot, the problem is still there.
For backup folder log no problem... what about grabbing the log after restore? Just some hint on what you mean.

**Comment by Dees-Troy** [comment]
adb pull /tmp/recovery.log or use the copy log button under advanced while still in the same recovery session.

**Comment by mdmower** [comment]
smeroni68, after you've completed Dees-Troy's request, could you also run the following test? I'd like to try an isolate whether this is an issue with TWRP backups or something funny during flashing packages. Some of the files in your before.txt have incorrect permissions. Also, can you mention whether you're using compressed or uncompressed backups?

1) Starting from a working state of your ROM (i.e. apps install fine), reboot to recovery and mount system, then

```
adb shell "ls -alZR /system/ > /tmp/pre-cm-install.txt"
adb pull /tmp/pre-cm-install.txt
```

2) While still in recovery, flash the cm-xxxxx.zip that is the _same_ as the version you currently have installed (just flash the cm package, no wiping or any other packages), then remount system and

```
adb shell "ls -alZR /system/ > /tmp/post-cm-install.txt"
adb pull /tmp/post-cm-install.txt
```

3) Verify you can reboot to Android and packages still install fine
4) Reboot to recovery, mount system, and once again:

```
adb shell "ls -alZR /system/ > /tmp/post-cm-install-rebooted.txt"
adb pull /tmp/post-cm-install-rebooted.txt
```

5) Make a backup of system, restore the backup, and once again:

```
adb shell "ls -alZR /system/ > /tmp/post-cm-install-restored.txt"
adb pull /tmp/post-cm-install-restored.txt
```

**Comment by smeroni68** [comment]
I'm preparing all stuff for you guys... will put here a dropbox link with all files...

Here we are...
https://www.dropbox.com/sh/jd7m16zyfgxy3vv/AABRWtKGaOBTf_7oXOKTE5dwa

Followed exactly your indications... the only thing I used TWRP tools to do the job, so mount system from Mount and Terminal Command to execute all lines pushed directly on my sdcard root.

I hope this will help to find the reason of the issue... please update here if any result.

Thanks for your time and interest!!

EDIT: I used CM11 Nightly 20140602 for S4 jflte, backup are normal, no compression

**Comment by mdmower** [comment]
By the looks of it, the last restore (after step 5) should have worked fine. It looks like /system/bin picked up a zygote_exec label instead of system_file, which is strange, but I don't think related to your package install issue. Dees_Troy: is twrp for jflte built with a stock samsung kernel?

**Comment by smeroni68** [comment]
Just to answer you, after every restore operation, the apk installation broke. That problem appear with official recovery and also with one version compiled on CM11 base.
When we saw the problem i was using that version unofficial, so I switched back to official one and I saw the same result with both versions. Unfortunately the only way we found to fix was to flash back the rom over the restore... or more fastly we prepared an updater-script derived from original CM11 one without all file extraction/copy, with only all lines with mount and set metadata stuff, and we solved the problem with it (it is faster than flash a complete rom).

EDIT: I added this flashable file to the previous dropbox link.

**Comment by Dees-Troy** [comment]
From the recovery_backup.log the last file restored from /system/bin is app_process.orig which has the zygote_exec context set (lines 1807 to 1808 in the log file). There is some code in libtar currently that sets the same context on the parent directory of a file. We have a patch set to remove this code:
https://gerrit.omnirom.org/#/c/7876/

Here's a test build for jfltexx:
http://techerrata.com/dees_troy/jfltexx.img
http://techerrata.com/dees_troy/jfltexx.tar

Restore the same backup and let me know please. Since this issue appears to be on the restore side, the backup itself should still be valid. Thanks.

**Comment by ktulu84** [comment]
Hi, smeroni68 is not at home, but he told me that the test twrp is working good, the restore goes well

**Comment by smeroni68** [comment]
Hi Dees_Troy,
I confirm... installed test twrp and restore now works... thanks for your time and prompt solution...
