### ISSUE TITLE
Screen timeout on G2 variants

### ISSUE THREAD

**Issue by JRJ442** [TeamWin/Team-Win-Recovery-Project#281]
I've seen an issue where once the screen timeouts, it won't come back on at all. You have to long press the power button to boot the phone back up to get out of it. I've seen this on 2 variants so far but its probably on all of them.

**Comment by janpetras** [comment]
I'm currently having this issue too.

I installed TWRP 2.7.1 by flashing it through TWRP 2.7.0

Basically, to reproduce this issue:

Get a D802 International updated to the latest stock kernel and ROM and with ioroot.

Install TWRP 2.7.0.0 through AutoRec.

Boot into TWRP and flash TWRP 2.7.1.0

Reboot into TWRP 2.7.1.0 and wait until the screen turns off. Try touching it, nothing happens. The phone is either off or the screen unresponsive. Only fix is holding power button for a longer time.

**Comment by JRJ442** [comment]
I'm pretty sure Dees Troy knows about the issue and its been fixed in newer versions of TWRP. We just haven't gotten anything newer than 2.7.1 yet. For a temp fix you can go to screen settings and disable the screen timeout. Then the issue won't pop up.
