### ISSUE TITLE
TWRP 2.7.1.1 will not decrypt Android 'L' storage

### ISSUE THREAD

**Issue by frenzeldk** [TeamWin/Team-Win-Recovery-Project#286]
After installing Android L and encrypting storage with a PIN TWRP is no longer able to decrypt storage.
This was tested on a Nexus 5 (hammerhead)

**Comment by Dees-Troy** [comment]
The source code for L isn't available yet, so we won't be working on adding support for L decryption until after it goes final.

**Comment by frenzeldk** [comment]
Totally understandable. I just wanted to inform you about it.
Just a simple question: now that the preview source code has been released, will you work on it? If no, I totally understand that.
