### ISSUE TITLE
ADB / ADB Sideload Broken on T989 / Hercules [2.7.1.0]

### ISSUE THREAD

**Issue by ChaoticHolon** [TeamWin/Team-Win-Recovery-Project#288]
ADB does not work at all in the last couple releases of TWRP for this phone. When in main menu, no devices show up in ADB at all.

If you try and start ADB Sideload it shows 'Starting ADB sideload feature...' with an empty progress bar. No devices show up in ADB still. Try and sideload anyways you get 'error: device not found' as expected given there are no devices showing up. Have to hit back and cancel to get out of that menu or it will just sit there. Phone shows up perfectly fine in ADB under devices as soon as you boot into the OS and is fully functional.

**Comment by Dees-Troy** [comment]
What OS are you using? Windows is super picky about drivers so we tend to not trust reports from Windows users. You may need to force install a driver to make it work in Windows.

**Comment by ChaoticHolon** [comment]
Windows 7 Ultimate SP1 x64. 

Figured it out! Thanks so much for the driver tip. This was indeed a driver issue. TWRP seems to be using a different Hardware ID than the stock Samsung recovery? There really should be documentation about this somewhere as it doesn't pop in the tray as an unknown device for some reason.

Here are fixed drivers with the proper Hardware ID's for the ADB Interface under TWRP (32 and 64-bit):
http://goo.gl/yCr6w7

I would appreciate it if you could add them to the page/article for the Hercules. These modified drivers might work for any of the Samsung phones that can use these same drivers (S2-S5, Note-Note III?).

**Comment by ChaoticHolon** [comment]
Another option would be setting a proper Hardware ID in init.recovery.hardware.rc instead of the generic one that's being used.

Any one of the following would work and windows would recognize the hardware automatically:
VID_04E8&PID_685D&ADB
VID_04E8&PID_685E&ADB
VID_04E8&PID_6860&ADB
VID_04E8&PID_6861&ADB
VID_04E8&PID_6862&ADB
VID_04E8&PID_6864&ADB
VID_04E8&PID_6866&ADB
VID_04E8&PID_6867&ADB
VID_04E8&PID_6868&ADB
VID_04E8&PID_686A&ADB
VID_04E8&PID_686B&ADB
Even the generic works:
SAMSUNG_MOBILE&ADB
