### ISSUE TITLE
[d2att] Can't mount /data

### ISSUE THREAD

**Issue by PacoBell** [TeamWin/Team-Win-Recovery-Project#29]
I installed twrp-2.2.1-d2att and tried to flash the Wallet fix, but it just claims it can't mount /data. Is there something I'm missing?

**Comment by Dees-Troy** [comment]
Did you encrypt your device at some point?

**Comment by PacoBell** [comment]
Sorry it's taken me so long to followup with this bug report. The problem was indeed the encryption. TWRP now supports decryption, so this should no longer be a problem going forward. Mod can close this now.

**Comment by Dees-Troy** [comment]
TWRP only supports decrypt on the Galaxy Nexus, Nexus 7, and just recently the Asus Transformer TF300T.  Afaik it doesn't work on the d2att. If you want to test, we can try adding it to the d2att, but it seems to only work on some devices.

Download this file:
http://db.tt/xEDZ6byZ
Push or copy it to /system/bin
chmod 755 it or use an app like root explorer or es file manager (with root and remount system as r/w settings) to give it execute permissions
Then run the binary via adb shell or terminal emulator in Android, not in TWRP.  It will output some text.  Copy and paste that text into here and I will use that information to make a new build of TWRP for your device with decrypt support for you to test.

**Comment by PacoBell** [comment]
This tool will gather the build flags needed for decryption support for TWRP.
This tool comes with no warranties whatsoever.
http://teamw.in

Your device is not encrypted, continuing anyway.

TW_INCLUDE_CRYPTO := true
TW_CRYPTO_FS_TYPE := "ERROR"
TW_CRYPTO_REAL_BLKDEV := "ERROR"
TW_CRYPTO_MNT_POINT := "ERROR"
TW_CRYPTO_FS_OPTIONS := "ERROR"
TW_CRYPTO_FS_FLAGS := "ERROR"
TW_CRYPTO_KEY_LOC := "footer"

As you can see, it's currently unencrypted. If you need me to run the diagnostic again while encrypted, I can do that too.

**Comment by Dees-Troy** [comment]
This version might work if you're encrypted:
http://techerrata.com/dees_troy/d2attcrypto.img

**Comment by PacoBell** [comment]
Okay, after a nightmare of having device encryption bootloop euroskank CM10, I went into TWRP and entered my decryption code. IT WORKED! Unfortunately, because it did work, when I went to wipe everything it didn't get rid of the encryption (obvious in hindsight). I had to reboot and cancel the decryption and re-wipe. Everything's hunky dory now. So, yeah, I'd say this was a success all around! =)
