### ISSUE TITLE
FIX PERMISSIONS MADE INTERNAL STORAGE READ ONLY

### ISSUE THREAD

**Issue by deepakjuly20** [TeamWin/Team-Win-Recovery-Project#294]
Hello,
Using TWRP 2.7 on my rooted S4. Recently tried fixed permissions in the advanced menu. After reboot found that file explorer could not move/delete files from or to the internal memory. Dolphin browser couldn't download in sdcard0 download directory.Camera couldn't store pictures on internal sd card, changes automatically to extsdcard. But when i grant root permissions to my file explorer, it can move/delete files on sdcard0/download. I think the fix permissions made my internal storage's ownership change  from 1000:system to 0:root. Please tell how to revert and suggest a solution.

**Comment by bigbiff** [comment]
Fix permissions is deprecated.
