### ISSUE TITLE
HTC One m7 TWRP 2.8.0.x E: Error executing updater binary in zip

### ISSUE THREAD

**Issue by srt10coupe** [TeamWin/Team-Win-Recovery-Project#299]
after updating from 2.7.1.1 to 2.8.0.x TWRP don't install cm11 nightly - E: Error executing updater binary in zip.
SuperSU.zip is easily installed with TWRP 2.8.0.x.

If I go back to TWRP 2.7.1.1, everything is installed without error.

**Comment by Arise** [comment]
Same issue happens with TWRP 2.8.0.0 or 2.8.0.1 on One Plus One trying to update nightlies.

![screenshot_2014-10-02-15-59-28](https://cloud.githubusercontent.com/assets/510392/4516361/8753017e-4bf1-11e4-8a7c-a26266825fc2.png)

Basically, to make it work, I have to wipe/clear data, then I can flash the nightly build, then I reboot to android it works, boot back in recovery trying to flash the same nightly flashed 2 minutes before and it gives me the error once again. 

Reverting to TWRP 2.7.1.1 fixes the problem.
