### ISSUE TITLE
No Scrollbars in terminal view

### ISSUE THREAD

**Issue by JoeSchubert** [TeamWin/Team-Win-Recovery-Project#3]
Using TWRP v2.1.0 on Nook Color. When updating Rom and GAPPS through goomanager (using openrecoveryscript) I was attempting to watch the progress from the terminal view in TWRP. It seem that the text starts with '\*  Verifying filesystem" at about the middle of the screen, then the rest of the text scrolls from that point off the screen. The text never moves up to where it's readable nor are scroll bars provided. The gray background for the terminal also appears to shoot off the bottom of the screen as well. 

I'm unsure if this is a local issue to my device or not.

**Comment by Dees-Troy** [comment]
The entire terminal window is scrollable.  If you can't scroll any further then there is no other text to view.
