### ISSUE TITLE
SuperSU needs to be updated

### ISSUE THREAD

**Issue by CaptainThrowback** [TeamWin/Team-Win-Recovery-Project#302]
Starting with Android 4.4.2 (I believe), some additional changes were necessary to SuperSU for it to root ROMs properly. These changes need to be reflected in TWRP source. See paste of SuperSU script here: http://tinyw.in/BuiT

The items related to "sugote" and "sugote-mksh" specifically are what needs to be added for full compatibility.

**Comment by obiwan-bartek** [comment]
+1

**Comment by bigbiff** [comment]
SuperSu is deprecated now.
