### ISSUE TITLE
Aroma Installer Fails on TWRP 2.2.0

### ISSUE THREAD

**Issue by lyrakat** [TeamWin/Team-Win-Recovery-Project#31]
I was able to install roms that used Aroma on previous versions, but not on 2.2.0.

Acer a500

**Comment by Dees-Troy** [comment]
Can you try to install an Aroma ROM then copy the log and paste it to a paste site and provide the link?

**Comment by Dees-Troy** [comment]
No logs and no reply. I can assure you that Aroma does work in TWRP, but it depends on the implementation.
