### ISSUE TITLE
Only Recovery can access TWRP folder - Nexus 4 stock Lollipop

### ISSUE THREAD

**Issue by ashjas** [TeamWin/Team-Win-Recovery-Project#311]
TWRP folder created by TWRP v openrecovery-twrp-2.8.1.0-mako.img
is unreadale from android.
Though TWRP can read the folder fine. adb shell while in TWRP also lists files fine.
When i browse for the folder on android, i see only TWRP folder as a file with 0 bytes in solid explorer. In root explorer i dont even see the 0 byte file.
From android, "adb shell > su > ls -l "   .. i see permission denied error for TWRP folder..
I tried changing permissions and also chown as similar to other folders on sdcard.. but all in vain.
I am experiencing this on Lollipop stock on Nexus 4.. on kitkat this was all fine.

Is this a known issue?

**Comment by jfeise** [comment]
Root works differently on Lollipop. From what I've seen from Chainfire and Koush, the boot image (kernel and/or initrd) has to be patched for su to work. Check XDA.
So, it doesn't surprise me that you can't see the folder contents. You probably don't have proper root.

**Comment by bam80** [comment]
@jfeise could you please be more specific? What exactly problem do we have here? Where in XDA should we check?
Thanks

**Comment by bam80** [comment]
Solution for me:
https://forum.xda-developers.com/google-nexus-5/general/sdcard-problems-upgrading-android-t2938749
```
$ su
# restorecon -FR /data/media/0

**Comment by jfeise** [comment]
This thread is 3 years old... I don't even have any phone with lollipop anymore.
But yeah, this was probably an issue with selinux.
