### ISSUE TITLE
2.8.1.0 not working on nozomi

### ISSUE THREAD

**Issue by LLP3t3r** [TeamWin/Team-Win-Recovery-Project#312]
The image for Sony Xperia S (LT26i aka nozomi) does now work. Installed over TWRP Manager. On reboot to recovery the Sony Logo appears and nothing more happens.
Version 2.8.0.1 does work.

**Comment by ghost** [comment]
Reported this to Dees_Troy long ago. Hopefully there's going to be a fix soon

**Comment by ghost** [comment]
2.8.3.0 hasn't fixed this issue. Kindly look into it

**Comment by mirh** [comment]
This bug also affect xperia [T/V](http://forum.xda-developers.com/showthread.php?t=2115726) and [Z](http://forum.xda-developers.com/showpost.php?p=58207337)

**Comment by ghost** [comment]
Surely some dev must have a Z at least. Hope this gets fixed in the next version :|

**Comment by mirh** [comment]
This has been solved by Dees_troy in 2.8.4.1

**Comment by LLP3t3r** [comment]
Its working, thanks
