### ISSUE TITLE
TWRP 2.8 can't decrypt Android L storage

### ISSUE THREAD

**Issue by jacopo-j** [TeamWin/Team-Win-Recovery-Project#314]
This issue has already been reported [here](https://github.com/TeamWin/Team-Win-Recovery-Project/issues/286), but it was closed because at that time Android L was a developer preview and the source was not available yet. Now that the final version is out and that the source is available, I think that it should be solved.

**Comment by Arno500** [comment]
I haven't tested it but I want to change of ROM when I want. And I don't want to sideload or anything like this.

**Comment by ninja-** [comment]
are you sure that it doesn't work as described in changelogs? they are stating support for decrypting /data

**Comment by jacopo-j** [comment]
After further testing, I can confirm that the feature works correctly. It was a my mistake, I'm very sorry.

**Comment by ninja-** [comment]
@jaggions thank you for clarifying, I was wondering about this before using lollipop's encryption
