### ISSUE TITLE
TWRP 2.8.2.0 on Nexus 5 Stock Kernel Android Build LRX21O no access  reboot phone

### ISSUE THREAD

**Issue by GoogleNexus5** [TeamWin/Team-Win-Recovery-Project#315]
after flashing  twrp 2.8.2.0 hammerhead on my N5 i didn´t have access to twrp menue.

you see short the twrp logo but no access into menue after few seconds  N5 boot back system.

PLEASE PATCH ASAP

(back on 2.8.1.0 work)

**Comment by MuhamedFathy** [comment]
i have the same issue!
i just installed it 2 day after installing "hammerhead-lrx21o-factory-01315e08" and when try to boot into it it's just show TWRP splash then reboots into system normally!

---EDIT---

Someone fixed it for me on xda

Just install the previous version "2.8.1.0" then download that root update http://download.chainfire.eu/636/SuperSU/UPDATE-SuperSU-v2.37.zip then install it on that recovery and then boot into system and install the latest version of that TWRP and it will work perfectly:)

**Comment by ghost** [comment]
The same issue here:

https://github.com/TeamWin/android_device_lge_hammerhead/issues/1
