### ISSUE TITLE
Phone stays not off when it is on the charger

### ISSUE THREAD

**Issue by sebastiaan15** [TeamWin/Team-Win-Recovery-Project#32]
oke flashed the new recovery
openrecovery-twrp-endeavoru-2.2.2.0
the problem is still not solved
my phone was on 60% - turned the phone completely off - put it on charger
after a hour i was taking a look if the phone was already fully charged - and then i see that the phone was booted up in recovery (not good at all if you leave it on charger all night)

this is really a big bug
the phone is not staying off if it is on the charger
after some time it goes by it self in to recovery
this is really not good at all

maybe it is a good idea what is different about the 2.2.2.0 and 2.1.7 for the charging

back to TWRP 2.1.7 (that has not that problem)

**Comment by Dees-Troy** [comment]
As mentioned in PM on XDA, I can find no differences between the 2.1.7 build and the 2.2.2.0 build when it comes to charging:
dees_troy@xlii:~/unpack$ md5sum openrecovery-twrp-endeavoru-2.1.7.img-kernel.gz
dddd6c30af5a670b77920120c441c3b5 openrecovery-twrp-endeavoru-2.1.7.img-kernel.gz
dees_troy@xlii:~/unpack$ md5sum openrecovery-twrp-2.2.2.0-endeavoru.img-kernel.gz
dddd6c30af5a670b77920120c441c3b5 openrecovery-twrp-2.2.2.0-endeavoru.img-kernel.gz
dees_troy@xlii:~/unpack$ md5sum openrecovery-twrp-endeavoru-2.1.7.img-ramdisk/init.rc
6c991a3c49083943834ecb31e0a8c259 openrecovery-twrp-endeavoru-2.1.7.img-ramdisk/init.rc
dees_troy@xlii:~/unpack$ md5sum openrecovery-twrp-2.2.2.0-endeavoru.img-ramdisk/init.rc
6c991a3c49083943834ecb31e0a8c259 openrecovery-twrp-2.2.2.0-endeavoru.img-ramdisk/init.rc
dees_troy@xlii:~/unpack$ md5sum openrecovery-twrp-endeavoru-2.1.7.img-ramdisk/sbin/htcbatt
836db52c864154cac87d53b84b2927ee openrecovery-twrp-endeavoru-2.1.7.img-ramdisk/sbin/htcbatt
dees_troy@xlii:~/unpack$ md5sum openrecovery-twrp-2.2.2.0-endeavoru.img-ramdisk/sbin/htcbatt
836db52c864154cac87d53b84b2927ee openrecovery-twrp-2.2.2.0-endeavoru.img-ramdisk/sbin/htcbatt
dees_troy@xlii:~/unpack$ md5sum openrecovery-twrp-endeavoru-2.1.7.img-ramdisk/sbin/offmode_charging
b2f7cfaea54c18c7fff602e75ea60e8f openrecovery-twrp-endeavoru-2.1.7.img-ramdisk/sbin/offmode_charging
dees_troy@xlii:~/unpack$ md5sum openrecovery-twrp-2.2.2.0-endeavoru.img-ramdisk/sbin/offmode_charging
b2f7cfaea54c18c7fff602e75ea60e8f openrecovery-twrp-2.2.2.0-endeavoru.img-ramdisk/sbin/offmode_charging
dees_troy@xlii:~/unpack$ md5sum openrecovery-twrp-endeavoru-2.1.7.img-ramdisk/sbin/choice_fn
23e215f5b4606ad507b04c2f260ecb68 openrecovery-twrp-endeavoru-2.1.7.img-ramdisk/sbin/choice_fn
dees_troy@xlii:~/unpack$ md5sum openrecovery-twrp-2.2.2.0-endeavoru.img-ramdisk/sbin/choice_fn
23e215f5b4606ad507b04c2f260ecb68 openrecovery-twrp-2.2.2.0-endeavoru.img-ramdisk/sbin/choice_fn
dees_troy@xlii:~/unpack$ md5sum openrecovery-twrp-endeavoru-2.1.7.img-ramdisk/sbin/detect_key
84f22a6bc6a5d4fb37929370af0ecac1 openrecovery-twrp-endeavoru-2.1.7.img-ramdisk/sbin/detect_key
dees_troy@xlii:~/unpack$ md5sum openrecovery-twrp-2.2.2.0-endeavoru.img-ramdisk/sbin/detect_key
84f22a6bc6a5d4fb37929370af0ecac1 openrecovery-twrp-2.2.2.0-endeavoru.img-ramdisk/sbin/detect_key

**Comment by ghost** [comment]
So check other points at the source...there must be something...even it is not related to charging that makes the phone wake up..

**Comment by Dees-Troy** [comment]
I believe that this is now fixed in the latest versions based on the reports that I see on XDA.
