### ISSUE TITLE
Backup- E: Unable to create folder: /...

### ISSUE THREAD

**Issue by chxpsuey** [TeamWin/Team-Win-Recovery-Project#324]
Device: Moto X 2014 victara 
ROM: Stock KitKat
Root: Latest Chainfire SuperSU
Bootloader status: Unlocked 
TWRP: 2.8.3.0 from TWRP server flashed with adb.

Problem: When trying to do a backup in TWRP 2.8.3.0 on victara, the following error is given:

E:/ Unable to create folder: /data/media/0/TWRP
(errono=13)
E:Failed to make backup folder.

**Comment by chxpsuey** [comment]
Heres a link to XDA victara TWRP post with screenshot of error http://forum.xda-developers.com/showthread.php?t=2911523

**Comment by chxpsuey** [comment]
I'm not encrypted BTW.

**Comment by hkorth** [comment]
I am having the same issue with this version. v2.8.0.1 works fine. Any help greatly appreciated. 

Update 1/3/15: I should have noted that my hardware and config is same as dobbs3x.

**Comment by thisjaymaloney** [comment]
Same issue here:
Phone: Moto e - XT1019
TWRP: v2.7.1.0
ROM: Stock 4.4.4

**Comment by hkorth** [comment]
As another data point, using an OTG adapter, backups with 2.8.3.0 are successfully completed to an external USB drive. So the issue seems to be with the Moto X (victara) internal memory.

**Comment by coolbeans2015** [comment]
HTC One sv (Boost) K2_CL
4.2.2 Android
Used SuperSU 2.45, TWRP 2.8.4.0
went through fine, now without any changes, at all, busybox says it is not installed, will not install and TWRP Manager says it cannot write to sd card and will not run backup??

Phone functions fine except for restarts (crashes) when trying to install BusyBox.  I need to get this issue fixed before continuing on to the main reason I rooted; one_sv_swapper-0.6 to enlarge app storage partition.

Can anyone help with this beginner error?

Thanks,

lee

**Comment by coolbeans2015** [comment]
On TWRP's 2.8.4.0 issue it says cannot write/read to sd cards because of using stock kernel on phone, and I guess flashing another ROM will fix this.  I am wondering if this is also the issue with BusyBox?

**Comment by Alfa55** [comment]
I had the same, the factory format FAT32 was the problem (Sandisk 16GB USB3.0 OTG Dual). After reformatting - FAT32  - it worked ok.
btw I put the phone on a wireless QI-charger and that stopped the backup, I presume it closed the USB connector of the phone (Note4)
