### ISSUE TITLE
asus tf201  twrp v2.6.3.0  password? help me

### ISSUE THREAD

**Issue by wzstudio555** [TeamWin/Team-Win-Recovery-Project#327]
tf201  twrp v2.6.3.0  password?  no bootloader usb   help me
mail:wzstudio555@gmail.com
![aa1](https://cloud.githubusercontent.com/assets/10398661/5611710/de0d0ada-9504-11e4-8e1c-932703a0fe14.jpg)
![aa2](https://cloud.githubusercontent.com/assets/10398661/5611705/dda2ac80-9504-11e4-8fe2-679253265227.jpg)
![aa3](https://cloud.githubusercontent.com/assets/10398661/5611706/dda97bf0-9504-11e4-8cab-0c98e0f06e0f.jpg)
![aa4](https://cloud.githubusercontent.com/assets/10398661/5611707/ddd1716e-9504-11e4-880c-d8bac3e99a21.jpg)
![aa5](https://cloud.githubusercontent.com/assets/10398661/5611708/ddd693e2-9504-11e4-90ab-7ce91f83db92.jpg)

**Comment by Chuckymon** [comment]
Hi wzstudio555,

I am presently having the same exact problem as you.
I can access into TWRP v2.6.3 and can Fastboot but was not able to mount System, Data, Cache and External SDCard inside without decrypting with a password....strange...I did not even assign a password to TWRP. Is there a way to overcome this stage in TWRP? Or Can I install ClockWorkMod Recovery over TWRP to gain access and restore my nandroid backup files in my External SDCard?

Trouble started when I installed Hairy Bean Custom ROM 2.63 on its own custom bootloader 4.2.1.
At first all was fine until I tried Katkiss 5.02 which failed and I backed with a Nandroid backup which I created using Online Nandroid Backup from Play Google Store. I had also did a prior backup using TWRP which I stored in Cloud.I do not have NVFlash as was highly recommended amongst bloggers online....So isthere anyone able to advise me to unbrick my Prime?
If successful..it will certainly be a very valuable lesson for me...
I will even go back to stock Jelly Bean 4.1.1 if thats what it takes...I had already downloaded the
Asus original firmware WW_epaduser_10_4_2_18UpdateLauncher.zip

Thanks guys..
