### ISSUE TITLE
Battary status in Recovery always shows 66%

### ISSUE THREAD

**Issue by azenra** [TeamWin/Team-Win-Recovery-Project#33]
I saw that the battery status always shows a fixed value at 66% no matter what the status of the battery is, is it a little bug here ?
Note: I'm using version 2.2.2.0 of the TWRP

**Comment by Dees-Troy** [comment]
Which device?

**Comment by azenra** [comment]
Im using HTC One S - S3 (villeC2, C2)

**Comment by Dees-Troy** [comment]
Try this build and let me know if this corrects the battery percent please:
http://techerrata.com/dees_troy/villec2.img

**Comment by azenra** [comment]
The new version has fixed the battery status issue but it didn't show the correct percent like in the ICS
example: in the ICS shows 47% but in the Recovery shows 49% (always plus 2% from the percent from the ICS)

**Comment by Dees-Troy** [comment]
That's as close as we're going to be able to get with it.  Thanks for testing.
