### ISSUE TITLE
Broken TWRP since 2.7.0.5 for the Samsung Galaxy Mega 6.3 (GT-I9200)

### ISSUE THREAD

**Issue by alexischino** [TeamWin/Team-Win-Recovery-Project#331]
As the title says this recovery is broken since the version 2.7.0.5. last night i flash the new version of twrp (2.8.4.0) and still have the same bugs, i can make a backup,restore a backup or flash anything it always reboot back to twrp in the middle of any task.

**Comment by alexischino** [comment]
Twrp 2.8.5.0 is still broken it has the same issues, it won't flash,backup or restore anything.

**Comment by demonstan** [comment]
I really love this recovery,but it doesn't work after 2.7.0.5

**Comment by Dees-Troy** [comment]
Bear in mind that no one on the team owns a Galaxy Mega 6.3 or 5.8 for that matter. A log of the bug would help. For best results, stop by the IRC channel.
