### ISSUE TITLE
Decryption on Nexus 7 2013 LTE (deb) not working

### ISSUE THREAD

**Issue by J0s3f** [TeamWin/Team-Win-Recovery-Project#343]
Today I wanted to try out Xposed on my Nexus. I only enabled encryption on Android 5, so I don't know how TWRP should ask about decryption. Should it ask on boot?
I use TWRP 2.8.5.0
It just boots into recovery. The log says cannot mount /data and enabling it at mounts does nothing.
The partition is shown as 0MB.
I can flash files from /cache to /system, but obviously not to /data
I tried to switch my code from pattern to pin, but no change.
![20150218_205451](https://cloud.githubusercontent.com/assets/604089/6255595/75f1cbaa-b7b1-11e4-8372-d6177dc949ea.jpg)

**Comment by wbedard** [comment]
Ditto on my encrypted Galaxy Nexus running Lollipop.

**Comment by silverl** [comment]
Ditto on Nexus 7 2013 Wifi running Lollipop.

**Comment by cha0sify** [comment]
Diito on Nexus 7 2013 LTE and OnePlus with CM12_lastest_nightly and twrp 2.8.5.1

**Comment by jenswet** [comment]
Ditto on Nexus 7 2013 Wifi Stock 5.0.2

**Comment by ilyvasile** [comment]
Ditto on nexus 7 2013 wifi 5.0.2 stock

**Comment by antart** [comment]
Ditto on LG G3 (d855) running Lollipop.

**Comment by KBanause** [comment]
Last working version for me (Nexus 7 LTE (deb)): 2.8.2.2

**Comment by J0s3f** [comment]
2.8.2.2 works for me too on Android 5.1
