### ISSUE TITLE
failed to put fb0 info: Invalid argument

### ISSUE THREAD

**Issue by shminer** [TeamWin/Team-Win-Recovery-Project#344]
I got this messages from recovery.log

I:TWFunc::Set_Brightness: Setting brightness control to 255
Starting the UI...Pixel format: 1440x2560 @ 32bpp
Pixel format: RGBX_8888
failed to put fb0 info: Invalid argument
Unable to get framebuffer.
: Invalid argument

should I update mdss ? I dont know how to fix it 

LG-F460

**Comment by hoangnova** [comment]
hello shminer
I have same problems. Please how to fix ? 
Now i'm using your JZ-shminer-CWM Recovery. (http://bbs.sonyue.com/thread-104136-1-1.html)
I'm trying to debug graphics.c, your cwm works like charm.

**Comment by hoangnova** [comment]
i'm tried many many time to compile TWRP for F460 :(

**Comment by Dees-Troy** [comment]
I presume that F460 is a variant of the LG G3. If so, then TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888" should be the correct pixel format and will most likely clear the problem. It will also need RECOVERY_GRAPHICS_USE_LINELENGTH := true

Correct device settings for G3 can be found in one of the many G3 repos: https://github.com/TeamWin/android_device_lge_d852/blob/android-4.4/BoardConfig.mk#L47

**Comment by hoangnova** [comment]
Dear Dees-Troy, 
Thanks you for your quick reply.
i'm sure config RGBX_8888.
i will try again with RECOVERY_GRAPHICS_USE_LINELENGTH  := true
G3 Cat6 not a variant of the LG G3. it is use APQ8084. (Snapdragon 805).

**Comment by shminer** [comment]
Thanks for you relay
I use device branch from note 4 .recovery run with RECOVERY_GRAPHICS_USE_LINELENGTH = true
It seems that MDSS needs some other characteristics.

**Comment by shminer** [comment]
it seem that we need use "RGBA_8888" for LG-F460

**Comment by Dees-Troy** [comment]
Sounds like you found the fix for your device. Closing.
