### ISSUE TITLE
2.8.5.0 "Recovery is not seandroid enforcing" JFLTESPR.

### ISSUE THREAD

**Issue by SunsparcSolaris** [TeamWin/Team-Win-Recovery-Project#348]
Tried to update to 2.8.5.0 through the TWRP app, which says it flashed successfully. When I attempt to reboot, it gives the "Recovery is not seandroid enforcing" error and also says "Warranty bit: recovery". When I ODIN to 2.8.4.0, the TWRP app says I'm still on 2.8.3.0.

**Comment by Dees-Troy** [comment]
The TWRP app is developed by a separate team. Please contact that developer for support for the app.

**Comment by SunsparcSolaris** [comment]
I'm still getting the same error messages even after flashing 2.8.4.0 through ODIN. I'll contact the app team about that issue, but I would like to see what I can do about the error messages.

Also, 2.8.5.0 is not listed under the JFLTESPR section on the website even though the app shows it available.
