### ISSUE TITLE
TWRP Does not boot for v2.8.5.0

### ISSUE THREAD

**Issue by GamerROMInc** [TeamWin/Team-Win-Recovery-Project#350]
When i saw the update for my Samsung GALAXY S4 SGH-M919 it doesnt boot all it says is booting recovery after 5 mins it goes black and nothing i had to reflash v2.8.4.0 for my s4 to boot can u fix

**Comment by kjsaale** [comment]
I'm having the same issue with my Sprint Galaxy S4.

Whenever I reboot to recovery it freezes at the Galaxy S4 splash screen, it never makes it to the TWRP splash screen.

**Comment by GamerROMInc** [comment]
I hope they fix this
