### ISSUE TITLE
logcat in TWRP recovery not working?

### ISSUE THREAD

**Issue by Diapolo** [TeamWin/Team-Win-Recovery-Project#352]
Using S4 i9506 (ks01lte) with TWRP 2.8.5.0 from here (http://forum.xda-developers.com/galaxy-s4/i9506-develop/recovery-twrp-2-8-1-0-touch-recovery-t2942159).

When I use `adb shell` I can connect to the device from my PC, but then executing `logcat` leads to `CANNOT LINK EXECUTABLE: cannot locate symbol "signal" referenced by "/system/bin/logcat"...`. Is this possibly related to a non working data dir decryption within TWRP? (see: https://github.com/TeamWin/Team-Win-Recovery-Project/issues/333#issuecomment-81656921)

**Comment by Dees-Troy** [comment]
logcat has never worked in any recovery. The recovery log is in /tmp/recovery.log while the recovery is running.

**Comment by MartinX3** [comment]
https://gerrit.omnirom.org/c/android_bootable_recovery/+/16489

Confirmed and tested with 9.0 omni/twrp
