### ISSUE TITLE
twrp sideload fail on samsung i9500

### ISSUE THREAD

**Issue by haobug** [TeamWin/Team-Win-Recovery-Project#353]
$ adb sideload cm-11-20141216-NIGHTLY-i9500.zip
error: cloesed

detail log uploaded here:
https://gist.github.com/haobug/6cc2eaadafb61b06dc93

TWRP using:
http://dl.twrp.me/i9500/twrp-2.8.5.0-i9500.img
cyanogenmod rom:
https://download.cyanogenmod.org/get/jenkins/95014/cm-11-20141216-NIGHTLY-i9500.zip

**Comment by bigbiff** [comment]
No debug logs so closing.
