### ISSUE TITLE
twrp 2.8.5.0 bug when flashing GApps 5

### ISSUE THREAD

**Issue by gatosardina** [TeamWin/Team-Win-Recovery-Project#354]
i flashed CM12 on my xperia T using the recovery mod that came in the boot.img inside the cm12 build, and then the GApps 5
everything was fine except for a small bug in which some apps couldn't detect the sd
i decided to do a clean install, but this time i installed TWRP and performed the data wipe/factory reset and flash using it
i got the TWRP manager, and installed the version 2.8.5.0
i booted into recovery, wiped data, flashed cm12, reboot into system, reboot into recovery, flashed gapps, wipe dalvik/cache, reboot into system and the GApps keep crashing all the time.
I tried all the GApps available, the 5 packages of PA GApps, and all the basket team GApps 5 i could find and all crash
i decided to flash cm11 and GApps 4 and it works perfectly, and if i flash CM12 itself the system works, it's the gapps that have problems
it must be a recovery mod problem then

**Comment by dagaua** [comment]
I also had problems with several cm12 nightlies: After flashing gapps (also tried different versions) notifications about google application "...has stopped" occur, making the phone unusable.

A workaround is flashing stock and using the CM recovery [1], but after reinstalling TWRP, again gapps make trouble.

No problems without gapps (after wiping /system and reinstalling cm12 without gapps).

Would be great to keep TWRP though.
Any ideas?
Is this somehow linked to the special boot procedure of the device (TWRP needing to be flashed on a special partiton)?

[1] http://forum.cyanogenmod.org/topic/106620-all-gapps-crashing/
