### ISSUE TITLE
2.8.6.0 image too big on i9300

### ISSUE THREAD

**Issue by RoelD** [TeamWin/Team-Win-Recovery-Project#363]
The new 2.8.6.0 image is too big to fit on the i9300's recovery partition. Users are experiencing loss of imei (overwritten EFS?) and broken recoveries on XDA.
http://forum.xda-developers.com/showpost.php?p=59759933&postcount=957
returning to 2.8.5.0 magically fixes all problems.

All users of official version are reporting:broken imei or broken recovery or bootloop. My phone kept booting into download mode for no reason. Using Odin to flash 2.8.5.0 fixed it.

1 user repacked 2.8.6.0, and now it flashes succesfully,
http://forum.xda-developers.com/showpost.php?p=59695988&postcount=891
But probably something went wrong with packing the official version, which is now distributed through twrp.me. It should be checked to make sure it does not propagate to future releases.

**Comment by RoelD** [comment]
resurfaced in 2.8.7.0
https://github.com/TeamWin/Team-Win-Recovery-Project/issues/436

**Comment by Dees-Troy** [comment]
We don't have a device maintainer for i9300, so we'll pull all of the builds after 2.8.5.0 and stop trying to issue future updates until a device maintainer steps up to fix these issues.
