### ISSUE TITLE
TWRP 2.8.6.0  sideload broken on multiple devices 

### ISSUE THREAD

**Issue by spider623** [TeamWin/Team-Win-Recovery-Project#366]
i can't sideload with the new twrp on mako, it always fail

**Comment by ghost** [comment]
same problem
Nexus 4

**Comment by spider623** [comment]
12 days later and continues to be broken making a device that is on bootloop a brick, thanks for checking the issues, also just confirmed that it's also broken on the transformer devices

**Comment by ViRb3** [comment]
@spider623 You can always flash the previous version of TWRP (MTP works) via bootloader, that's what I did.

**Comment by spider623** [comment]
that is also what i did but i should not have to transfer everything on the phone when i can just run a script

**Comment by chadjaros** [comment]
nexus 5 broken on 2.8.6.1 - always saying "device not found". Can still push files to sdcard using adb.

**Comment by bigbiff** [comment]
No debug logs so closing issue.
