### ISSUE TITLE
Your TWRP Manager app doesn't have 2.8.6.x for hammerhead

### ISSUE THREAD

**Issue by mikhaelkh** [TeamWin/Team-Win-Recovery-Project#369]

**Comment by CaptainThrowback** [comment]
TeamWin isn't responsible for this app - you should probably report it to the app dev via the Play Store.

**Comment by mikhaelkh** [comment]
@CaptainThrowback how about to pull new versions to the mirror used in an app?

**Comment by CaptainThrowback** [comment]
TWRP Manager is not a TeamWin app. Again, contact the app dev for anything related to the app.
