### ISSUE TITLE
Can't open ZIP?

### ISSUE THREAD

**Issue by atomspring** [TeamWin/Team-Win-Recovery-Project#376]
Hello, I've installed several ROMs off my external SD card, this latest ROM is also my first but I cannot test it because TWRP 2.8.0.0 complains with "E: Unable to open zip file."

Full log is at http://paste.ubuntu.com/10806510

Thanks for your help!

**Comment by Dees-Troy** [comment]
minzip: Filename contains invalid character '320'

Rename the zip file and remove any special characters.

**Comment by atomspring** [comment]
No special characters in zip name, renamed to "update.zip", still no dice.

Strangely, adb shell allows me to test unzip the file with no issues.

What's going on here?

~A
