### ISSUE TITLE
META: Open source teamw.in website code

### ISSUE THREAD

**Issue by patcon** [TeamWin/Team-Win-Recovery-Project#378]
Trying to write up instructions for a project, and wanted to deeplink to your device install directions. There's no anchor, so thought I'd just submit a PR to add anchors to each devices' page, but can't find the website source.

Assuming it's a static site, and chance we could discuss hosting the code on github?

Thanks!

**Comment by CaptainThrowback** [comment]
https://github.com/TeamWin/twrpme

**Comment by patcon** [comment]
:+1: thanks!
