### ISSUE TITLE
2.8.6.0 not working with CM12S and encrypted devices on Bacon/OPO

### ISSUE THREAD

**Issue by rarog** [TeamWin/Team-Win-Recovery-Project#379]
This was reproduced by multiple users. If Oneplus One with 12S is encrypted, TWRP can't mount the partition. It tells something about correct password but destroyed data.

This happens on devices updated to 12S form 11S via OTA, but also on a factory reset 12S which is encrypted afterwards.

**Comment by mydewji** [comment]
I'm having the same issue. Would be happy to provide logs/any other info that you think would help.

**Comment by jfeise** [comment]
Duplicate.
See https://github.com/TeamWin/Team-Win-Recovery-Project/issues/333
