### ISSUE TITLE
Neither ADB Nor USB Mounting Work on the VZW GS3

### ISSUE THREAD

**Issue by akbyrd** [TeamWin/Team-Win-Recovery-Project#38]
USB Drivers are installed, ADB works when booted.
"adb devices" is empty
Choosing "Mount USB Storage" doesn't allow USB access to the device from a PC.

**Comment by Dees-Troy** [comment]
ADB is confirmed to work in 2.3.1.0 for VZW SGS3, at least it works in Linux.  Not sure about USB storage but that depends on the kernel used more than anything. I don't have a VZW SGS3 and if USB storage still doesn't work, then I'd be more tempted to disable / remove it until someone else can find a fix for it.

**Comment by akbyrd** [comment]
That doesn't make it any less broken on Windows...
