### ISSUE TITLE
TWRP 2.8.6.0 Unable to mount encrypted data on Nexus 7 wifi running 5.1

### ISSUE THREAD

**Issue by knyghtryda** [TeamWin/Team-Win-Recovery-Project#381]
Mount fails with "twrp could not mount /data and unable to find crypto footer".  In 2.8.1.0 I get a password prompt but the password is not being recognized correctly.

**Comment by Ceremony64** [comment]
Same issue here on a Galaxy Nexus and the Euphoria OS v1.1 ROM (5.1 AOSP base).
P.S. dupe of #323 #333 #358 and a few more

**Comment by iliaross** [comment]
Same on HTC One M8

**Comment by bigbiff** [comment]
No debug logs so closing.
