### ISSUE TITLE
Backup function fails after upgrading to 2.8.6.0

### ISSUE THREAD

**Issue by jyundt** [TeamWin/Team-Win-Recovery-Project#382]
Unable to complete an encrypted + compressed or encrypted (uncompressed) backup running 2.8.6.0 on unlocked GSM M7.

Reverting back to 2.8.5.0 as a temporary work around.

**Comment by CaptainThrowback** [comment]
Known issue. Fix already merged for next release.

Fix is here: https://github.com/omnirom/android_bootable_recovery/commit/2252d24c964df89189143e8d09626e9455e0f580
