### ISSUE TITLE
TWRP installation fails on Note 3 Neo SM-N7505

### ISSUE THREAD

**Issue by John3620** [TeamWin/Team-Win-Recovery-Project#383]
Hi,
Device : Samsung Galaxy Note 3 Neo SM-N7505 (kitkat 4.4.2) rooted with the help of Odin 3.09 & CF-Auto-Root-hllte-hlltexx-smn7505.tar.md5
I'm trying to install TWRP with the Install Method of the TWRP Manager App.
Following instructions are done :
Install the app and open it.
Tap on Install TWRP.
Select device Note 3 Neo (hlltexx) from list.
Select "twrp-2.8.6.0-hlltexx-4.4.img" from the list (the file is NOT downloaded automatically ! !)
After the download, I get following message :
"Ensure the partition listed below is the correct one for your device.... :  dev/block/platform/msm_sdcc.1/by-name/recovery"   Yes / No
(I Don't known the meaning of this ??) 
Tap Yes
After that I get a second message :  Something....  wrong....  flashing recovery was unsuccessfull....Would you like to attempt rebooting to recovery now ?
Tap No
I've done all this twice (deleted TWRP Manager and downloaded it again... but with same effect !)
I really don't known what is wrong.
Please help.

**Comment by shaggyskunk** [comment]
I'd use Odin to flash TWRP Recovery

**Comment by John3620** [comment]
Ok... I chose the App Install Method because there is a step in Odin Install Method that I don't understand ! :
"Note many devices will replace your custom recovery automatically during first boot.
To prevent this, use Google to find the proper key combo to enter recovery. 
After typing fastboot reboot, hold the key combo and boot to TWRP."
I know the proper key combo to enter recovery on my device but what about "typing fastboot reboot" ??
What is it ? Can someone explain me clearly what to do just after the installation TWRP with Odin.
(Sorry for my bad english)

**Comment by shaggyskunk** [comment]
All I have ever done was - Download the TWRP 2.8.6.0 img.tar to the pc -
Using Odin 3.09 and running it as Administrator - Pull the battery and
replace - Copy the img.tar to the AP tab - Boot into Download Mode - Flash
TWRP - Wait for it to finish (maybe a minute max) and done

**Comment by John3620** [comment]
Ok... just one more thing :
After my useless trial to install TWRP, I saw in the recovery screen,  a red triangle with exclamation mark on the Android Icon ! ? ?
Nevertheless... I did the same installation as yours and I have now the TWRP menu !
I hope that there will be no bad effects in the future (due to the previous red triangle seen on the screen).
So now... is there any need to keep the TWRP Manager as the installation was done with Odin ?

**Comment by shaggyskunk** [comment]
I personally wouldn't bother with TWRP Manager - Odin is your friend 😉

**Comment by ghost** [comment]
Is this problem present with the latest version of TWRP?

**Comment by bigbiff** [comment]
No debug logs so closing issue.
