### ISSUE TITLE
TWRP is asking for password after encrypting storage - HTC One M7

### ISSUE THREAD

**Issue by ghost** [TeamWin/Team-Win-Recovery-Project#384]
After I encrypted my phone memory, TWRP is asking for password. "Empty" password or my PIN code doesn't work. I've used both 2.8.6.0 and 2.8.5.0 versions.
-HTC One M7, stock ROM

**Comment by RichardEb** [comment]
Same problem on M8 (Google Play edition Android 5.1) with twrp-2.8.6.0. twrp says wrong password, but my password works on normal boot without problems

**Comment by RichardEb** [comment]
Does clockworkmod decrypt the storage correctly? maybe twrp can adopt a solution from them.

**Comment by RichardEb** [comment]
*maybe  *adopt

**Comment by bgcngm** [comment]
CWM does not support encryption.

**Comment by RichardEb** [comment]
Ist this a duplicate of #333 or a seperate bug? So there`s no solution atm, but someone is working on it, right?

**Comment by ghost** [comment]
Can this issue be solved or is factory reset my only solution? I want to use custom ROMs.
If there's a fix coming everything's fine.

**Comment by ghost** [comment]
Also, I can't find TWRP folder/backup on my phone after encrypting. Please tell me it still exists.

**Comment by RichardEb** [comment]
Use astro app. If you can't see it with astro it isn`t there.

**Comment by RichardEb** [comment]
Why is the issue report closed? Problem still exists on my M8

**Comment by jfeise** [comment]
All the "decryption fails" issues seem to have the same root cause, a change in Android 5.x/CM12.x that results in TWRP not being able to get the key to decrypt on recent devices.
All these are essentially duplicates of https://github.com/TeamWin/Team-Win-Recovery-Project/issues/333

**Comment by ghost** [comment]
I closed this issue because it's a duplicate.

**Comment by RichardEb** [comment]
Please reopen this. They say in #333 that this thread is not a duplicate of #333 it's an own issue

**Comment by RichardEb** [comment]
A solution for HTC Phones (at least GPE edition) can be found @ #411

**Comment by bgcngm** [comment]
@SnowGabe, please re-open this thread. It is the only one already existing for the issue of HTC decryption. The above one (#411) is for GPE edition HTC devices.

**Comment by RichardEb** [comment]
SnowGabe can`t reopen it. Only an admin can do. I think it will be faster for you to open a new issue and link it here.
