### ISSUE TITLE
TWRP 2.8.6.0 cannot work, but 2.8.1.0 work properly on CMDC M812

### ISSUE THREAD

**Issue by jchjian** [TeamWin/Team-Win-Recovery-Project#386]
Hi, I compiled the TWRP code of branch Android 4.4 downloaded on omnirom, it work properly on my phone CMDC M812. After the replacement is Android 5.0 or 5.1 branches can't work. After running into recovery about three seconds it will autorestart to system, in the few seconds nothing happen neither touch the sreen or press volume and power button, also adb shell cound‘t find it. After restarting to system, the log in cache/recovery/last_log cound't find anything about this, it appears to be normal. So i am using the 2.8.1.0 version however i want to use 2.8.6.0. My phone is msm8926 platform.

**Comment by Dees-Troy** [comment]
Sounds like you have some kind of kernel panic. You can check /proc/last_kmsg and maybe get some idea. You also might try building TW_EXCLUDE_MTP := true as some devices seem to have issues with MTP timing during boot.
