### ISSUE TITLE
twrp 2.8.6.0 freezes when rebooting [Huawei Y300]

### ISSUE THREAD

**Issue by Alpha-UMi** [TeamWin/Team-Win-Recovery-Project#387]
I have a problem with twrp 2.8.6.0 flashed on a Huawei Ascend Y300-100 (stock rom, Jelly Bean v4.1.1): when i choose any of the reboot options, the program freezes, nothing responds anymore and I have to remove the battery in order to turn the divice off. Is this a known bug? Any suggestions?

**Comment by Alpha-UMi** [comment]
Any news?

**Comment by f4natix** [comment]
Same phone, same issue. None of the reboot options work. I also noticed SlimBean has boot problems on it, at least on its first boot. And SlimBean also recognizes the internal sd-card just until the very first reboot, if 2.8.6 is installed. 2.8.5 is just fine.

**Comment by faisal80** [comment]
I have same problem on Huawei Ascend Y300 with this version (2.8.6.0) of TWRP.

**Comment by viisauksena** [comment]
same issue , its minor but a little bit annoing ..

**Comment by tristan-k** [comment]
I can confirm the issue.

**Comment by bigbiff** [comment]
No debug logs so closing issue.
