### ISSUE TITLE
Unexplained Git Change

### ISSUE THREAD

**Issue by airend** [TeamWin/Team-Win-Recovery-Project#390]
Between commits 075ad800c539503d0515e5e0b4af160eccedead9 and c7eee6fef0263ed4eb5aa0d934a0a8c972d41b30, something happened to etc/init.rc that doesn't seem to be captured in the logs. Under "on property:ro.debuggable=1", what are lines 136 & 137 now become commented out, and "setprop service.adb.root 1" appears, without any indication in the diffs.

I was trying to understand why those lines are commented out, since my device shows as unauthorized without them, and now I'm even more confused about the commit logs.

**Comment by CaptainThrowback** [comment]
Those commits are from 8 months ago. Have you looked at current source to see what's in the file?

Is your device using a custom init.rc, perhaps?

**Comment by airend** [comment]
The current init.rc has those lines commented out, which is confusing since this change is not recorded in any diff. I simply tracked down the change to the commits mentioned. Somewhere in between those two trees, the change happened, and I wanted to understand why.

Either way, if I uncomment them, adbd works from the beginning, and I don't have to unplug and plug back the USB cable.

**Comment by Dees-Troy** [comment]
We modify the stock init.rc from AOSP to force triggering service.adb.root=1 which is just a little further down in the init.rc file. The goal is to get adb shell to run as root so the user can do anything they want.

**Comment by airend** [comment]
Thanks, I understand the purpose of triggering `on property:service.adb.root=1`. I am only reporting that if you start recovery with USB plugged in, `adbd` doesn't actually start properly, and the device shows as unauthorized, until the cable is re-plugged. Everything works properly when I uncomment those two lines under `on property:ro.debuggable=1`.
