### ISSUE TITLE
Since lollipop 5.x.x twrp don't perform the factory reset via Rom Settings/Backup & Reset on GS3-i9300

### ISSUE THREAD

**Issue by Naveed-Abbas** [TeamWin/Team-Win-Recovery-Project#391]
Since lollipop 5.x.x twrp have this problem ,
if you do the factory reset via Rom (Settings/Backup & Reset)
It's don't boot up to perform the factory reset.(just stuck on booting screen) 
We're facing this problem with CM based Roms on our device(GS3-i9300) 
But don't know about stock lollipop or others devices..?

Thank's

**Comment by bigbiff** [comment]
No debug logs so closing issue.
