### ISSUE TITLE
TWRP encryption backup error. (2.8.6.0 - KLTE).

### ISSUE THREAD

**Issue by Yanngs** [TeamWin/Team-Win-Recovery-Project#392]
I can't complete any backup with encryption. Presents error "failed" when start "data" backup.
Please add encrypt option on "Live Backup".
Thank you.

**Comment by Yanngs** [comment]
CM12.1 / G900F / KLTE.

**Comment by CaptainThrowback** [comment]
Live Backup isn't a TWRP option. And I commented on the encryption issue here: https://github.com/TeamWin/Team-Win-Recovery-Project/issues/382

**Comment by bigbiff** [comment]
No debug logs so closing issue.
