### ISSUE TITLE
TWRP 2.8.6 bootloop with OnePlus One

### ISSUE THREAD

**Issue by MarcusOptimus** [TeamWin/Team-Win-Recovery-Project#393]
TWRP 2.8.6 has a problem with OnePlus One. When I do a factory reset from the system settings, OnePlus One reboots and goes into bootloop the TWRP.﻿

**Comment by kwhat** [comment]
Same issue nexus 6

**Comment by Dees-Troy** [comment]
Should be fixed in 2.8.6.1

**Comment by MarcusOptimus** [comment]
Ok, thanks.
