### ISSUE TITLE
Cancel 'Live Backup' broken in TWRP 2.8.4

### ISSUE THREAD

**Issue by prataczak** [TeamWin/Team-Win-Recovery-Project#395]
I am running TWRP 2.8.4, Samsung Galaxy S4 Sprint, and Cyanogenmod 12.1 (the latest nightly). I cancelled a "Live Backup," after I realized that it was being saved to internal storage. This was despite the fact that in the settings, I have it set to 'Save Backup Settings.' It will be set to internal storage every time you open Live Backup, and this is not what I want.

I went into my file manager program to delete the backup on the internal storage, and I noticed after checking the folder size about 10 seconds apart, the folder was bigger. I checked again, and it was bigger. It is as though I had never cancelled the backup - TWRP was still writing to it apparently. A notification was present stating there was an error during the backup, but the folder kept getting bigger and bigger.

**Comment by CaptainThrowback** [comment]
"Live Backup" isn't a TWRP feature. Sounds like you're using an unofficial app not developed or supported by TeamWin.

**Comment by prataczak** [comment]
Oh my bad. I had assumed that "TWRP Manager" was a part of the project, the install directions recommended downloading it. Please disregard this thread, I will contact the developer of that app.
