### ISSUE TITLE
Cannot decrypt sdcard on Yuga (Sony Z3)

### ISSUE THREAD

**Issue by a-chaudhari** [TeamWin/Team-Win-Recovery-Project#396]
Running the latest stock lollipop build.  TWRP cannot access the encrypted partition.  It asks for a password but that password fails every time.    I tried downgrading to KK and TWRP is also unable to access a KK encrypted partition either.

**Comment by Dees-Troy** [comment]
Not sure which device you're referring to. Yuga is the original Z. Z3 doesn't have official TWRP support.
