### ISSUE TITLE
Multiple unlock screens piling on top of each other

### ISSUE THREAD

**Issue by Hobadee** [TeamWin/Team-Win-Recovery-Project#399]
Updated to 2.8.6.0 recently from an older TWRP (Can't remember exactly, but it was decently old).

I noticed, after a little while, that the unlock screen is spawning again while the screen is still locked, causing multiple unlock screens to be piled on top of each other.  This means that to unlock the screen you need to swipe several times, each unlocking one more layer, until you finally unlock the last one.

This became REALLY apparent when I left my phone in Recovery mode overnight (fell asleep while working on it!) and woke up to discover 10-deep unlock screens and a bunch of error messages in the log saying something along the lines of "Failed to create overlay: 10 overlays max".  (Or something to that effect.)

My device is a Samsung Galaxy S5. No clue how to get debugging info from TWRP but happy to provide it if someone tells me how.

**Comment by saveman71** [comment]
I can confirm having these multiples unlock screens after leaving my phone in recovery for about an hour as well.
I had to unstack them in order to access the main interface again.

**Comment by Dees-Troy** [comment]
This was fixed in 2.8.7.0

**Comment by saveman71** [comment]
Well, that's one less issue in the tracker! Glad it was fixed, will update.
