### ISSUE TITLE
Persistent "(Wipes Data and Cache)"

### ISSUE THREAD

**Issue by kelvinx** [TeamWin/Team-Win-Recovery-Project#4]
After going into Factory Reset (in the Wipe Menu), and you go back into Wipe Menu, and go into any of the other wipes (Cache, Battery Stats etc.); "(Wipes Data and Cache)" remains at the top when it shouldn't. I haven't tested whether this occurs if you actually factory reset though, but this bug occurs if you go into the Factory Reset page and go back without actually factory resetting.

This is for Galaxy Nexus GSM, though it may affect other devices as well.

**Comment by Dees-Troy** [comment]
This should be fixed in our latest code.  Thanks for reporting it.

**Comment by kelvinx** [comment]
No worries :), can't wait for the next release!
