### ISSUE TITLE
Charging while off

### ISSUE THREAD

**Issue by ghost** [TeamWin/Team-Win-Recovery-Project#40]
When we charge our phone in off, it automatically turns on when the charge reach arround 80%-90%...if it's off it must continue off..

**Comment by Dees-Troy** [comment]
What device?

**Comment by ghost** [comment]
*HTC One X but this issue was solved on version 2.3.1.0 released 2 days
ago..
*
On Wed, Oct 17, 2012 at 1:33 PM, Dees-Troy notifications@github.com wrote:

> What device?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/TeamWin/Team-Win-Recovery-Project/issues/40#issuecomment-9534022.

## 

# 

| Bruno Zouein Pereira - Eng. da Computação/Software
| Tel.: 55 (11) 98954-3964
| Hospedagem de sites: http://brunozp.com.br
| Site pessoal: http://brunozp.com

# | MSN: zopostyle@hotmail.com

**Comment by Dees-Troy** [comment]
Thanks for the update.
