### ISSUE TITLE
TWRP freeze and reboot when flash or backup something on i9082

### ISSUE THREAD

**Issue by baks97** [TeamWin/Team-Win-Recovery-Project#401]
every time when i flash something TWRP freeze. Zip isnt flash, and backups isnt complete.
i try flash AOSP 5.1.1., AOSP 5.1, CM12 and CM12.1. Somethimes when select multiple zip to flash TWRP complete installation.

**Comment by Dees-Troy** [comment]
No one in team win owns this device and there's no current maintainer. Best we can do is stop future builds until someone can find a fix for us.
