### ISSUE TITLE
[Request] Support Samsung Galaxy S4 i9506

### ISSUE THREAD

**Issue by Diapolo** [TeamWin/Team-Win-Recovery-Project#406]
This is the Qualcomm Snapdragon 800 version of the S4 and it seems there is only this unofficial port:
http://forum.xda-developers.com/galaxy-s4/i9506-develop/recovery-twrp-2-8-1-0-touch-recovery-t2942159

I'd love to see an official one :), thanks.

**Comment by Dees-Troy** [comment]
This isn't the proper place to request support for new devices. See here for more information:
https://plus.google.com/u/1/+DeesTroy/posts/iyyM1kYULEa
