### ISSUE TITLE
TWRP newer than 2.8.5.0 missing on 5 Sony devices

### ISSUE THREAD

**Issue by mirh** [TeamWin/Team-Win-Recovery-Project#408]
That is
~~[Xperia S (nozomi)](https://twrp.me/devices/sonyxperias.html)~~
[Xperia T (mint)](https://twrp.me/devices/sonyxperiat.html)
~~[Xperia Z (yuga)](https://twrp.me/devices/sonyxperiaz.html)~~
[Xperia Z tablet (pollux_windy)](https://twrp.me/devices/sonyxperiaztablet.html)
[Xperia Z Ultra (togari)](https://twrp.me/devices/sonyxperiazultra.html)

**Comment by ziggyke** [comment]
I noticed it to! Is there any progress for making them available or isn't there a maintainer anymore for those devices?

**Comment by mirh** [comment]
The [latter](http://forum.xda-developers.com/xperia-s/s-development/rom-ucyan-xperia-s-t3027172/post61660565) probably

**Comment by mirh** [comment]
Ok, since this seems definitively a problem with _devices_ (maintainers) and not with TWRP itself, I guess this can be closed
