### ISSUE TITLE
Visualization problems in TWRP 2.8.6.1 for Mako (Nexus 4)

### ISSUE THREAD

**Issue by fprietog** [TeamWin/Team-Win-Recovery-Project#409]
There are visualization problems in TWRP 2.8.6.1 for Mako (Nexus 4).

Here is a comparative between 2.8.6.0 and 2.8.6.1:
![x1](https://cloud.githubusercontent.com/assets/9756455/7668881/4b075ba2-fc54-11e4-9846-24ab666e367d.png) 
![x2](https://cloud.githubusercontent.com/assets/9756455/7668882/52198974-fc54-11e4-8006-fc6427a035e9.png)

The main problem, besides the obvious definition downgrading, is that in 2.8.6.1 the theme is shifted to the right so several functions are cut. Here is a example (look the keyboard):
![x0](https://cloud.githubusercontent.com/assets/9756455/7668887/b18c3d48-fc54-11e4-9808-aad10b64af3c.png)

It happened several versions ago and was caused by an unneeded offset that was used to center the theme prior to the auto-stretching feature.

Thanks and best regards.

**Comment by Dees-Troy** [comment]
Will be fixed in the next release:
https://github.com/TeamWin/android_device_lge_mako/commit/c375f37e9cea8d558c4b81c44d9558b433dc265b
