### ISSUE TITLE
password

### ISSUE THREAD

**Issue by wayn-r** [TeamWin/Team-Win-Recovery-Project#41]
When I try to flash a rom, after booting into twrp, I am immediately requested a password... why? Have I done something wrong? Running v2.2.2.0 on an unlocked and (obviously) rooted transformer prime tf201. Thanks for any help you guys can offer!!

**Comment by Dees-Troy** [comment]
Some TF201's tell TWRP that data is formatted as ext3 when it's really formatted as ext4. You have 2 choices, revert to 2.2.1.4 and stay on that forever, or back up everything that's on your internal storage along with your apps to another device (computer, microSD), then boot the latest TWRP and choose Format Data under wipe.

**Comment by simonbcn** [comment]
Same problem with 2.4.4.0 and tf300t.
I have installed the v2.2.1.3-tf300t and it doesn't start.
This is a bug.

**Comment by GTRsdk** [comment]
I've got the same problem with 2.5.0.0 and tf300t with the 4.2.1 jellybean bootloader
I can't mount anything either

**Comment by danjng** [comment]
I am in the same boat.  2.5.0.0 with TF300T and 4.2.1 JB bootloader.  This is after reflashing to the latest ASUS OTA JB update and doing a factory reset.

Can't mount anything, Can't do the Format Data per the first response.  Also can't run the following command to convert the partition:
adb shell
mke2fs -t ext4 -m 0 /dev/block/mmcblk0p8

Any suggestions, thoughts, or ideas?

**Comment by GTRsdk** [comment]
I've heard that the TF300T issue is result of a hard brick :-/

**Comment by kirelagin** [comment]
Just got this issue with HTC One S (ville) after upgrading to HBOOT 2.15. TWRP keeps asking for a password when started (even though zips are flashed just fine) and won't wipe dalvik cache.

Downgrading to 2.2.1 as suggested by @Dees-Troy helps: it is still asking for a password but wipes the cache.

**Comment by maxkueng** [comment]
Me too with v2.6.3.3 Nexus 4
