### ISSUE TITLE
deb: 2.8.6.1 Image is too big for recovery partition

### ISSUE THREAD

**Issue by gtjoseph** [TeamWin/Team-Win-Recovery-Project#415]
twrp-2.8.6.1-deb.img at 11284480 bytes is too big for the deb's recovery partition.

**Comment by cyanfr** [comment]
Confirmed for me as well.  Will not flash through bootloader/fastboot.  Current recovery TWRP deb 2.8.6.0.  CM12.1 nightly.

Error as follows:
sending 'recovery' (11020 KB)..
OKAY [  0.353s]
writing 'recovery'...
FAILED (remote: size too large)
finished. total time: 0.365s

**Comment by Xranix** [comment]
Hello,
confirmed on Nexus 7 2013 LTE (deb) with lollipop 5.1.1

Update method 
fastboot flash recovery twrp.img

writing 'recovery'...
FAILED (remote: size too large)
finished. total time: 0.365s

**Comment by Fmstrat** [comment]
Confirmed on another deb with lollipop 5.1.1 and fastboot.

**Comment by brianjking** [comment]
Confirmed as well.

**Comment by brianjking** [comment]
Anyone figure out a solution to getting TWRP installed when on 5.1.1?

**Comment by Fmstrat** [comment]
@brianjking I'm just using 2.8.6.0

_EDIT_ Though I just realized it's pretty useless because of the encryption bug. Doh.

**Comment by alkemist** [comment]
same problem :(
