### ISSUE TITLE
Not working on Android M - Hammerhead

### ISSUE THREAD

**Issue by herghost** [TeamWin/Team-Win-Recovery-Project#418]
I know its early....

Results in never booting back into android after flashing 2.8.6.1, I didn't expect it to work but thought I would give it a go to save others the bother!

**Comment by Dees-Troy** [comment]
Did you try to root or install SuperSU when TWRP prompted? SuperSU doesn't work with M and that may be the cause of your issue.

**Comment by herghost** [comment]
I did indeed, in which case my apologies

**Comment by Dees-Troy** [comment]
Works fine here on hammerhead. Flashed M, booted. Rebooted to bootloader and booted TWRP and then rebooted system from the TWRP GUI. I did not let TWRP install SuperSU and the device booted fine.
