### ISSUE TITLE
can't work on amazon kindle fire 1

### ISSUE THREAD

**Issue by git2015-tech** [TeamWin/Team-Win-Recovery-Project#421]
- amazon kindle fire 1
- twrp 2.8.5
- firefirefire 1.4a

when flash a rom like cyanogenmod 11、cyanogenmod 10,the twrp only show "updating partition details", can't flash the rom

**Comment by git2015-tech** [comment]
Starting TWRP 2.7.0.1 on Sun May 31 02:05:04 2015
I:=> hardware id from cpuinfo: 'OMAP4430'
I:=> serial from cpuinfo: '0000000000000000'
BOARD_HAS_NO_REAL_SDCARD := true
I:Single storage only.
I:No internal storage defined.
I:No storage defined, defaulting to /sdcard.
I:Lun file '/sys/devices/virtual/android_usb/android0/f_mass_storage/lun/file'
I:TW_BRIGHTNESS_PATH := /sys/devices/platform/omap_pwm_led/leds/lcd-backlight/brightness
Starting the UI...Pixel format: 1024x600 @ 32bpp
Pixel format: BGRA_8888
framebuffer: fd 3 (1024 x 600)
=> Linking mtab
=> Processing recovery.fstab
I:Processing '/sdcard'
I:Created '/sdcard' folder.
I:Processing '/data'
I:Processing '/cache'
I:Processing '/system'
I:Processing '/bootloader'
I:Processing '/recovery'
I:Processing '/boot'
I:Created '/and-sec' folder.
I:Creating Android Secure: /sdcard/.android_secure
I:mount '/sdcard/.android_secure' '/and-sec' process ended with RC=0
I:Backup folder set to '/sdcard/TWRP/BACKUPS/0000000000000000'
I:Settings storage is '/sdcard'
Updating partition details...
I:Unmounting main partitions...

Partition Logs:
/sdcard | /dev/block/mmcblk0p12 | Size: 5110MB Used: 3047MB Free: 2063MB Backup Size: 0MB
   Flags: Can_Be_Mounted Can_Be_Wiped Can_Be_Backed_Up Wipe_Available_in_GUI Removable IsPresent Has_Android_Secure Is_Storage Is_Settings_Storage 
   Symlink_Path: /sdcard/.android_secure
   Symlink_Mount_Point: /and-sec
   Primary_Block_Device: /dev/block/mmcblk0p12
   Display_Name: sdcard
   Storage_Name: sdcard
   Backup_Path: /and-sec
   Backup_Name: and-sec
   Backup_Display_Name: Android Secure
   Storage_Path: /sdcard
   Current_File_System: vfat
   Fstab_File_System: vfat
   Backup_Method: files

/data | /dev/block/mmcblk0p10 | Size: 1119MB Used: 19MB Free: 1099MB Backup Size: 19MB
   Flags: Can_Be_Mounted Can_Be_Wiped Can_Be_Backed_Up Wipe_During_Factory_Reset Wipe_Available_in_GUI IsPresent Can_Encrypt_Backup Use_Userdata_Encryption 
   Primary_Block_Device: /dev/block/mmcblk0p10
   Display_Name: Data
   Storage_Name: Data
   Backup_Path: /data
   Backup_Name: data
   Backup_Display_Name: Data
   Storage_Path: /data
   Current_File_System: ext4
   Fstab_File_System: ext4
   Backup_Method: files

/cache | /dev/block/mmcblk0p11 | Size: 251MB Used: 4MB Free: 247MB Backup Size: 4MB
   Flags: Can_Be_Mounted Can_Be_Wiped Can_Be_Backed_Up Wipe_During_Factory_Reset Wipe_Available_in_GUI IsPresent 
   Primary_Block_Device: /dev/block/mmcblk0p11
   Display_Name: Cache
   Storage_Name: Cache
   Backup_Path: /cache
   Backup_Name: cache
   Backup_Display_Name: Cache
   Storage_Path: /cache
   Current_File_System: ext4
   Fstab_File_System: ext4
   Backup_Method: files

/system | /dev/block/mmcblk0p9 | Size: 503MB Used: 8MB Free: 495MB Backup Size: 8MB
   Flags: Can_Be_Mounted Can_Be_Wiped Can_Be_Backed_Up Wipe_Available_in_GUI IsPresent 
   Primary_Block_Device: /dev/block/mmcblk0p9
   Display_Name: System
   Storage_Name: System
   Backup_Path: /system
   Backup_Name: system
   Backup_Display_Name: System
   Storage_Path: /system
   Current_File_System: ext4
   Fstab_File_System: ext4
   Backup_Method: files

/bootloader | /dev/block/mmcblk0p2 | Size: 0MB
   Flags: IsPresent 
   Primary_Block_Device: /dev/block/mmcblk0p2
   Display_Name: bootloader
   Storage_Name: bootloader
   Backup_Path: /bootloader
   Backup_Name: bootloader
   Backup_Display_Name: bootloader
   Storage_Path: /bootloader
   Current_File_System: emmc
   Fstab_File_System: emmc
   Backup_Method: dd

/recovery | /dev/block/mmcblk0p5 | Size: 16MB
   Flags: IsPresent 
   Primary_Block_Device: /dev/block/mmcblk0p5
   Display_Name: Recovery
   Storage_Name: recovery
   Backup_Path: /recovery
   Backup_Name: recovery
   Backup_Display_Name: Recovery
   Storage_Path: /recovery
   Current_File_System: emmc
   Fstab_File_System: emmc
   Backup_Method: dd

/boot | /dev/block/mmcblk0p7 | Size: 10MB
   Flags: Can_Be_Backed_Up IsPresent 
   Primary_Block_Device: /dev/block/mmcblk0p7
   Display_Name: Boot
   Storage_Name: boot
   Backup_Path: /boot
   Backup_Name: boot
   Backup_Display_Name: Boot
   Storage_Path: /boot
   Current_File_System: emmc
   Fstab_File_System: emmc
   Backup_Method: dd

I:Loading package: TWRP (/script/ui.xml)
I:Loading package: TWRP (/sdcard/TWRP/theme/ui.zip)
I:Loading resources...
E:Resource type (font) failed to load
I:Loading variables...
I:Loading mouse cursor...
I:Loading pages...
I:Loading page main
E:Unknown object type.
I:Loading page install
E:Unknown object type.
I:Loading page flash_zip
E:Unknown object type.
I:Loading page flash_done
E:Unknown object type.
I:Loading page wipe_cachedalvik
E:Unknown object type.
I:Loading page wipe_installdone
E:Unknown object type.
I:Loading page reboot
E:Unknown object type.
I:Loading page mount
E:Unknown object type.
I:Loading page usb_mount
E:Unknown object type.
I:Loading page usb_umount
I:Loading page wipe
E:Unknown object type.
I:Loading page wipe_cache_confirm
E:Unknown object type.
I:Loading page wipe_cache
E:Unknown object type.
I:Loading page wipe_dalvik_confirm
E:Unknown object type.
I:Loading page wipe_dalvik
E:Unknown object type.
I:Loading page wipe_data_confirm
E:Unknown object type.
I:Loading page wipe_data
E:Unknown object type.
I:Loading page wipe_battery_confirm
E:Unknown object type.
I:Loading page wipe_battery
E:Unknown object type.
I:Loading page wipe_rotate_confirm
E:Unknown object type.
I:Loading page wipe_rotate
E:Unknown object type.
I:Loading page wipe_system_confirm
E:Unknown object type.
I:Loading page wipe_system
E:Unknown object type.
I:Loading page wipe_sdcard_confirm
E:Unknown object type.
I:Loading page wipe_sdcard
E:Unknown object type.
I:Loading page wipe_sdext_confirm
E:Unknown object type.
I:Loading page wipe_sdext
E:Unknown object type.
I:Loading page wipe_done
E:Unknown object type.
I:Loading page backup
E:Unknown object type.
I:Loading page backup_run
E:Unknown object type.
I:Loading page backup_done
I:Loading page backup_success
E:Unknown object type.
I:Loading page backup_failed
E:Unknown object type.
I:Loading page restore
E:Unknown object type.
I:Loading page restore_setrestoredata
I:Loading page restore_select
E:Unknown object type.
I:Loading page restore_run
E:Unknown object type.
I:Loading page restore_done
I:Loading page restore_success
E:Unknown object type.
I:Loading page restore_failed
E:Unknown object type.
I:Loading page settings
E:Unknown object type.
I:Loading page timezonemain
E:Unknown object type.
I:Loading page timezoneminus
E:Unknown object type.
I:Loading page timezoneplus
E:Unknown object type.
I:Loading page advanced
E:Unknown object type.
I:Loading page copylog_done
E:Unknown object type.
I:Loading page partsdcard
E:Unknown object type.
I:Loading page partsdcardaction
E:Unknown object type.
I:Loading page partsdcard_done
E:Unknown object type.
I:Loading page fixperms
E:Unknown object type.
I:Loading page fixperms_done
E:Unknown object type.
I:Switching packages (TWRP)
No file contexts for SELinux
Full SELinux support is present.
E:Cannot load volume /misc!
E:Cannot load volume /misc!
Startup Commands: ro.serialno=
ro.bootmode=unknown
ro.baseband=unknown
ro.bootloader=unknown
ro.hardware=omap4430
ro.revision=16
ro.emmc=0
ro.boot.emmc=0
ro.factorytest=0
ro.secure=0
ro.allow.mock.location=1
ro.debuggable=1
persist.sys.usb.config=mtp,adb
ro.build.id=JZO54K
ro.build.display.id=cm_otter-eng 4.1.2 JZO54K eng.dees_troy.20140311.040344 test-keys
ro.build.version.incremental=eng.dees_troy.20140311.040344
ro.build.version.sdk=16
ro.build.version.codename=REL
ro.build.version.release=4.1.2
ro.build.date=Tue Mar 11 04:04:00 UTC 2014
ro.build.date.utc=0
ro.build.type=eng
ro.build.user=dees_troy
ro.build.host=ded1.ktechnology.net
ro.build.tags=test-keys
ro.product.model=Amazon Kindle Fire
ro.product.brand=Android
ro.product.name=cm_otter
ro.product.device=otter
ro.product.board=otter
ro.product.cpu.abi=armeabi-v7a
ro.product.cpu.abi2=armeabi
ro.product.manufacturer=Amazon
ro.product.locale.language=en
ro.product.locale.region=US
ro.wifi.channels=
ro.board.platform=omap4
ro.build.product=otter
ro.build.description=cm_otter-eng 4.1.2 JZO54K eng.dees_troy.20140311.040344 test-keys
ro.build.fingerprint=Android/cm_otter/otter:4.1.2/JZO54K/eng.dees_troy.20140311.040344:eng/test-keys
ro.build.characteristics=tablet,nosdcard
ro.cm.device=otter
ro.cwm.forbid_format=/bootloader,/dfs,/backup,/splash
omap.audio.mic.main=AMic0
omap.audio.mic.sub=AMic1
omap.audio.power=PingPong
af.resampler.quality=3
ro.rommanager.developerid=cyanogenmod
keyguard.no_require_sim=true
ro.url.legal=http://www.google.com/intl/%s/mobile/android/basic/phone-legal.html
ro.url.legal.android_privacy=http://www.google.com/intl/%s/mobile/android/basic/privacy.html
ro.com.google.clientidbase=android-google
ro.com.android.wifi-watchlist=GoogleGuest
ro.setupwizard.enterprise_mode=1
ro.com.android.dateformat=MM-dd-yyyy
ro.com.android.dataroaming=false
ro.cm.version=10-20140311-UNOFFICIAL-otter
ro.modversion=10-20140311-UNOFFICIAL-otter
ro.config.ringtone=CyanTone.ogg
ro.config.notification_sound=CyanMessage.ogg
ro.config.alarm_alert=CyanAlarm.ogg
ro.carrier=unknown
ro.sf.lcd_density=160
dalvik.vm.heapstartsize=5m
dalvik.vm.heapgrowthlimit=42m
dalvik.vm.heapsize=128m
wifi.interface=wlan0
wifi.supplicant_scan_interval=120
ro.opengles.version=131072
persist.lab126.chargeprotect=1
com.ti.omap_enhancement=true
omap.enhancement=true
ro.crypto.state=unencrypted
persist.sys.root_access=3
ro.sf.hwrotation=270
ro.com.google.locationfeatures=1
ro.com.google.networklocation=1
ro.kernel.android.checkjni=1
dalvik.vm.dexopt-flags=m=y
net.bt.name=Android
net.change=net.bt.name
dalvik.vm.stack-trace-file=/data/anr/traces.txt
init.svc.ueventd=running
init.svc.recovery=running
service.adb.root=1
init.svc.adbd=running

Running boot script...
I:/sbin/runatboot.sh process ended with RC=0

Finished running boot script.
I:Copying file /cache/recovery/log to /cache/recovery/last_log
I:Attempt to load settings from settings file...
I:Loading settings from '/sdcard/TWRP/.twrps'.
I:Backup folder set to '/sdcard/TWRP/BACKUPS/0000000000000000'
I:Copying file /etc/recovery.fstab to /cache/recovery/recovery.fstab
I:Version number saved to '/cache/recovery/.version'
I:Switching packages (TWRP)
I:Set page: 'mount'
I:Set page: 'usb_mount'
I:Set page: 'usb_umount'
I:mount '/sdcard/.android_secure' '/and-sec' process ended with RC=0
Updating partition details...
Updating partition details...
Updating partition details...
I:Unmounting main partitions...
I:Set page: 'mount'
I:Set page: 'main'
I:Set page: 'install'
Updating partition details...
I:Set page: 'main'
I:Set page: 'backup'
I:Set page: 'main'
I:Set page: 'advanced'
I:Copying file /tmp/recovery.log to /sdcard/recovery.log

**Comment by Dees-Troy** [comment]
According to the log:
Starting TWRP 2.7.0.1

You're using an old version of TWRP. Further, you're using a custom theme that isn't compatible with the version of TWRP that you're using. Remove the custom theme and update your TWRP.

**Comment by git2015-tech** [comment]
thanks , del folder : /sdcard/twrp/theme/ , then twrp is ok
