### ISSUE TITLE
Slow backup with TWRP 2.8.6.1 on OneplusOne

### ISSUE THREAD

**Issue by rarog** [TeamWin/Team-Win-Recovery-Project#432]
Uncompressed backup of all partitions with 2.8.6.1 takes 350 seconds:
(file system and imaged drives written with 16 MB/s)

Uncompressed backup of all partitions with 2.8.6.0 takes 154 seconds:
(file system is written with 34 MB/s and imaged drives with 16 MB/s)

**Comment by bigbiff** [comment]
No debug logs so closing.
