### ISSUE TITLE
Once again the size of  twrp_2.8.7.0_i9300 is bigger than recovery partition

### ISSUE THREAD

**Issue by Naveed-Abbas** [TeamWin/Team-Win-Recovery-Project#436]
Once again the size of newer version of twrp_2.8.7.0_i9300 is bigger than recovery partition on our device(i9300)
Therefore it is not flashable at all. (like twrp_2.8.6.0_i9300)

Regards 

Naveed Abbas.

**Comment by Dees-Troy** [comment]
We don't have a device maintainer for i9300, so we'll pull all of the builds after 2.8.5.0 and stop trying to issue future updates until a device maintainer steps up to fix these issues.

**Comment by DimitriMayakovsky** [comment]
This is a twrp issue compres zip no device partition size is same as i9500 maybe more compres zip :)

**Comment by DimitriMayakovsky** [comment]
Och sorru more compres img ;)
