### ISSUE TITLE
/system does not mount when restoring backup or when flashing zip files.

### ISSUE THREAD

**Issue by AdityaPatange1** [TeamWin/Team-Win-Recovery-Project#44]
I built TWRP for Galaxy SL GT i9003 (ICS) Device Configs: https://github.com/AdiPat/android_device_samsung_galaxysl

I added these configs: http://pastebin.com/PHYQ72JX

I can take backups, but can't restore (E: Unable to mount /system (tw_mount) )
Same error when flashing a zip file.

Any help would be appreciated! 

Thanks!

**Comment by Dees-Troy** [comment]
A full recovery.log would be good. You might also want to try the newer jb-wip code branch with our 2.3 code.

**Comment by Dees-Troy** [comment]
No recovery log so no choice but to close.
