### ISSUE TITLE
Document how encrypted backups work

### ISSUE THREAD

**Issue by naftulikay** [TeamWin/Team-Win-Recovery-Project#445]
I as a user of TWRP would like to rely on the security of the encrypted backups feature. I'm often backing up to unencrypted media, so I'd like my data to be secured from the time that it is backed up until the time it is restored.

How is encryption done? What KDF and cipher are used? Is there a way to decrypt the backups from, say, a Linux desktop? If so, how? All of this would be a welcome addition to the FAQ.

**Comment by ant9000** [comment]
See #582

**Comment by bigbiff** [comment]
Duplicate of #582 
However, this feature will be removed and you should rely on desktop encryption tools.

**Comment by beerisgood** [comment]
> 

> However, this feature will be removed and you should rely on desktop encryption tools.

With removing you mean the whole encryption of backups?

**Comment by bigbiff** [comment]
Yes, there are security issues in OpenAES.
