### ISSUE TITLE
Setting time zone - minor issue

### ISSUE THREAD

**Issue by cytherian** [TeamWin/Team-Win-Recovery-Project#45]
In "Settings" --> "Time Zone", changing the zone and then executing the selection results in a gray screen showing the output:
- Verifying filesystems...
- Verifying partition sizes...

And then nothing else happens.  The return button works though and after rebooting, the time zone appears to have been set as selected.  It's a minor issue, but I thought it worth reporting it.

**Comment by Dees-Troy** [comment]
You must have accidentally hit the small button in the bottom center that brings up the console text output.  Hitting that button again closes the console output.
