### ISSUE TITLE
samsung nexus s missing from list of devices after choosing "install TWRP"

### ISSUE THREAD

**Issue by furlongm** [TeamWin/Team-Win-Recovery-Project#462]
The samsung nexus s (crespo) is missing from the list of devices after choosing "install TWRP".

**Comment by SdtBarbarossa** [comment]
https://dl.twrp.me/crespo/

you can find the img files here

**Comment by furlongm** [comment]
Great, thanks, will use those.

However, I meant that the android app is missing this device from it's list of devices.

**Comment by CaptainThrowback** [comment]
Contact the app devs at support@jmzsoftware.com to fix it. There is no "official" TeamWin app.

**Comment by furlongm** [comment]
Done.
