### ISSUE TITLE
Flash Error!!!

### ISSUE THREAD

**Issue by msfjarvis** [TeamWin/Team-Win-Recovery-Project#463]
I tried to flash kirmaniarslan's 2.8.5.0 build for HTC Explorer aka Pico and it gives the following error.
![image](https://cloud.githubusercontent.com/assets/13348378/8696619/79b0ba80-2b0b-11e5-836e-31d91a72c3e9.png)
My device has always popped an error with recoveries with size >4MB

**Comment by CaptainThrowback** [comment]
According to the TWRP page for this device, it's no longer being updated. The last upload I see is 2.4.4.0. So I'm wondering why you're posting here about someone else's custom, unsupported build?

**Comment by msfjarvis** [comment]
Yes I agree but the guy, @kirmaniarslan has posted the official twrp git for his unofficial build so i believe that is where i should be posting

**Comment by CaptainThrowback** [comment]
You should post in the thread from which you got the build, until the person who builds the unofficial decides to help update the official.

**Comment by msfjarvis** [comment]
Thanks for helping me out.
