### ISSUE TITLE
2.8.7.0 does not work on sm-p600 / lt03wifiue

### ISSUE THREAD

**Issue by sur5r** [TeamWin/Team-Win-Recovery-Project#464]
Trying to update from 2.8.0.0, I had to find out that 2.8.7.0 does not start on said device. I tried installing first from TWRP itself, then via heimdall, suspecting sth. went wrong.

Of course I checked the md5sums before flashing.

Finally, I tried 2.8.6.0 which works just fine.

If I can help you tracking this down, just let me know.

**Comment by EvanCarroll** [comment]
Should close this 3.1 boots and works. Having a problem getting a flash to work though it, but TWRP certainly boots in recovery when flash with either heimdall or ordin.

**Comment by sur5r** [comment]
Thanks for the reminder. Will try and report back.
