### ISSUE TITLE
MD5 checksum is not trustful 

### ISSUE THREAD

**Issue by sorgelig** [TeamWin/Team-Win-Recovery-Project#465]
TWRP calculates checksum after finish backup of partition. But it's NOT correct.
For example, if target storage has file system problem and backup parts overlap each other, or has other problems, then MD5 checksumms will be calculated on broken backup. 

The correct place to calculate MD5 is before data written to disk. The procedure of writing current portion to disk should include MD5 function call.
At the same time, backup time will be greatly reduced because it won't require re-read whole backup in order to calculate checksumms.

And if possible, it's better to put MD5 checksumms of all parts of partition to ONE MD5 file. It will help to check backup outside TWRP more easy. I mean this:

```
data.ext4.win000
data.ext4.win001
data.ext4.win002
data.ext4.win003
data.ext4.md5
system.ext4.win000
system.ext4.win001
system.ext4.md5
```

**Comment by sorgelig** [comment]
Also can add new feature "Check MD5 after backup" to insure backup has been written without problems.

**Comment by Dees-Troy** [comment]
You can't md5 the files before the backup and use that to verify the backup because the tar format adds header and other file details such as path, permissions, selinux contexts, etc. The tar format includes its own internal basic crc checking to validate that the restored data is correct in case of a faulty backup file.

**Comment by sorgelig** [comment]
You always can pipe output if it's hard to trap file write functions. Anyway, MD5 should have some meaning. Currently MD5 is useless. It's like to calculate block checksumm on receiver side instead of transmitter side.
Not, sure if you got it right, but i didn't mean to calculate MD5 of archived files. I mean, calculate MD5 of tar in time when it's being written to disk.
