### ISSUE TITLE
corrupt twrp 2.7 and 2.8 files for Samsung S3 Mini

### ISSUE THREAD

**Issue by vdhamer** [TeamWin/Team-Win-Recovery-Project#466]
![screen shot 2015-07-18 at 20 23 28](https://cloud.githubusercontent.com/assets/13396568/8763016/2f4150ea-2d8b-11e5-9702-284a1c074946.jpg)

The tar files for twerp-2.7.0.0 and newer are 10 kBytes and there are no .img files.
The older tar files are 7 Mbytes in size and there are .img files.

Peter

**Comment by bigbiff** [comment]
This was fixed at some point.
