### ISSUE TITLE
Motorola Photon 4G cannot access THE internal SDCard on TWRP 2.3.0.0

### ISSUE THREAD

**Issue by jixiangqd** [TeamWin/Team-Win-Recovery-Project#47]
I've been test it for several times, and surely confirm that the issue exists on my device.
When I select internal,the list still shows me the external files. Maybe this is because the internal not mounted at that time, but I really don't konw how to do this manually.
Is anyone here can hlep me?I'll appreciate it if you give me any help!

**Comment by Dees-Troy** [comment]
Both internal and external storage mount for me on my Photon 4G. If you want further assistance, come to our IRC channel and have a recovery.log ready.
