### ISSUE TITLE
ASUS ZenFone 2 (Z00A) ro.build.asus.sku assert failed

### ISSUE THREAD

**Issue by mrmathematica** [TeamWin/Team-Win-Recovery-Project#475]
I have twrp-2.8.7.2-Z00A.img on my zenfone2, and when trying to flash stock rom V2.19.40.22 WW I get:

assert failed: getprop("ro.build.asus.sku") == "WW"

**Comment by SdtBarbarossa** [comment]
Workaround:

IN TWRP Go to terminal emulator and enter:

setprop ro.build.asus.sku WW

Only if you are 100% sure that this rom is correct... Then you must be able to flash

**Comment by pedroadami** [comment]
T.Hanks SdtBarbarossa
