### ISSUE TITLE
HTC One S/Ville: Screen turns on in off state while charging

### ISSUE THREAD

**Issue by Yzoni** [TeamWin/Team-Win-Recovery-Project#48]
When the phone is off and charging, the screen turns on. It is only noticeable if in a dark environment, because the screen displays black.

**Comment by Dees-Troy** [comment]
Try again with the latest 2.3.1.0 build please.

**Comment by Yzoni** [comment]
Sorry, I wasn't patient enough. The screen turns off after 30 seconds from the moment you put the power cable in. So it isn't really a problem.

**Comment by Dees-Troy** [comment]
Thanks for the update.  Most newer HTC devices use a software charging mode that's part of the recovery image. It actually silently boots recovery to start charging while the device is off, which is probably what you were seeing.
