### ISSUE TITLE
What does it take to get official TWRP for my device

### ISSUE THREAD

**Issue by msfjarvis** [TeamWin/Team-Win-Recovery-Project#498]
I have been collaborating with a guy in London in building twrp 2.8.7.0 for my device HTC Pico. I want to know which exact files are required by TeamWin to recontinue support for the device. I am ready to provide all necessary files from Android 4.3 to 5.1.1

**Comment by CaptainThrowback** [comment]
Go to #twrp on IRC and tell bigbiff and Dees_Troy you have an updated device tree for the device. They'll fork your repo and set it up to build. You'll just have to tell them what you're building those device files with. I believe the Omnirom/Android 5.1 is preferred, but CM trees work as well.

**Comment by msfjarvis** [comment]
I have CM 11 and CM 12 trees, hope there's no problem. The CM 12 trees haven't been updated in a while, but we've built TWRP 2.8.5.0 with it so we know it works well.

**Comment by msfjarvis** [comment]
https://github.com/TeamRedux/android_device_htc_pico

This is the link to the CM 11/OmniROM device tree. I don't get enough time to sit out staring at the irc screen for hours. Please someone notify @Dees_Troy or @bigbiff about this submission.

**Comment by CaptainThrowback** [comment]
Are you agreeing to maintain the tree going forward, as well?

**Comment by msfjarvis** [comment]
If you're talking about makefiles and libs, it's a yes from my side. Plus I've got a team to help me out.

**Comment by CaptainThrowback** [comment]
If you jump on IRC now, Dees_Troy and bigbiff are around if you want to let them know. And then you can work together on getting the build set up.
