### ISSUE TITLE
charging light indicator not working while in recovery (EVO LTE)

### ISSUE THREAD

**Issue by xlxcrossing** [TeamWin/Team-Win-Recovery-Project#50]

**Comment by xlxcrossing** [comment]
This was updated in 2.3.0 supposedly but doesn't seem to work

**Comment by xlxcrossing** [comment]
This was updated in 2.3.0 supposedly but doesn't seem to work

**Comment by xlxcrossing** [comment]
This was updated in 2.3.0 supposedly but doesn't seem to work

**Comment by Dees-Troy** [comment]
Charging light on all newer HTC devices does not work in recovery.  There is a + sign next to the battery percentage to indicate that the device is charging while in recovery.  That's the best that we're going to do.  Sorry.
