### ISSUE TITLE
Can't unblock encrypted htc one m9

### ISSUE THREAD

**Issue by rumanzo** [TeamWin/Team-Win-Recovery-Project#509]
Hi. I have a problem with flash zip. My phone (htc one m9) is encrypted, and TWRP ask me a password, I input this correct, but TWRP can't unblock partition.
I use twrp-2.8.7.1_CPTB-B1-hima.img .

**Comment by CaptainThrowback** [comment]
TWRP cannot decrypt HTC encryption. You'll have to format data to remove it.
