### ISSUE TITLE
Time is way off Sprint SGS3

### ISSUE THREAD

**Issue by tsudeily** [TeamWin/Team-Win-Recovery-Project#51]
I have the appropriate timezone set on the latest TWRP but it is 6 hours off.

**Comment by Dees-Troy** [comment]
None of the USA SGS3 devices save the time to a RTC (real-time clock) to maintain the proper date and time between reboots. The CM team tried to fix this problem in their kernel and they lost Internet connectivity within 24 hours. We won't be able to fix this issue. Sorry.
