### ISSUE TITLE
Please enable 4x4, 5x5, 6x6 grid sized for pattern unlock

### ISSUE THREAD

**Issue by xenithorb** [TeamWin/Team-Win-Recovery-Project#511]
I use CyanogenMod, which supports alternative grid sizes for pattern locking. The code generated from this pattern is obviously being used to encrypt the LUKS master key. Without proper support for this in TWRP it is very inconvenient to have to change the lockscreen password when I want to do something in recovery.

To be perfectly clear, all that's needed here are larger grid sizes in order to decrypt the data partition.

**Comment by donut44** [comment]
BUMP. This is really important. I don't think that it would be a big problem, cause the decryption is already available for 3x3 patterns.

**Comment by frozenpandaman** [comment]
Would love to see this functionality added as well!

**Comment by Dees-Troy** [comment]
TWRP is open source. Feel free to add the support yourselves and submit a patch to our Gerrit. These grids are not part of AOSP and I don't plan on adding support for them myself. Sorry.

**Comment by xenithorb** [comment]
Any reason we can't keep the ticket open in case someone wants to do exactly what you suggested? As a feature request? Why close it?

**Comment by CaptainThrowback** [comment]
Someone submitted a potential patch for this, but test versions of TWRP will need to be built and tested by the people requesting this. So if you really want this, you'll need to report what device you're using and work with a device maintainer to test and confirm the patches are working.
