### ISSUE TITLE
Twrp and wireless charging

### ISSUE THREAD

**Issue by joihn** [TeamWin/Team-Win-Recovery-Project#512]
I use Usb Otg to make my nandroid backup.

Since those can be pretty long, I would like to charge my phone in the same time.

The usb port being unavailable, I want to charge via wireless charging, however it doesn't work in twrp (it works on my stock rom)

Lg G4 h815 with twrp 2.8.7.0

**Comment by Dees-Troy** [comment]
Won't fix.
