### ISSUE TITLE
Samsung GN8000-Installing CM10 zips fails (backup and recovery works though)

### ISSUE THREAD

**Issue by dbonner** [TeamWin/Team-Win-Recovery-Project#52]
Hi,
I have a Samsung Galaxy Note 10.1 tablet GSM version (Model GN8000).  I installed TWRP  (openrecovery-twrp-2.3.1.0-p4notewifi) using GooManager.  Backup and recovery works great.  However, I can't install CyanogenMod Nightlies. I haven't changed any of TWRP's default settings.
EDIT: I forgot to mention that ClockWorkMod installs CM10 nightlies perfectly (unofficial version from xda-dev "HighOnAndroidCWMRecoveryGTN8000").
I tried to install both:
cm-10-20121027-NIGHTLY-n8000.zip and
cm-10-20121026-NIGHTLY-n8000.zip.
It fails right at the start, with the following output showing on my screen:

Installing '/sdcard/goomanager/cm-10-2012027-NIGHTLY-n8000.zip'...
Checking for MD5 file ...
Skipping MD5 check: no MD5 file found.
assert failed: getprop("ro.product.device") == "c0" || getprop("ro.build.project") ++ "c0" ||
              getprop("ro.product.device") == "p4noterf" || getprop("ro.build.project") ++ "p4noterf" ||
              getprop("ro.product.device") == "n8000" || getprop("ro.build.project") ++ "n8000" ||
              getprop("ro.product.device") == "GT-N8000" || getprop("ro.build.project") ++ "GT-N8000" ||
E:Error in /sdcard/goomanager/cm-10-2012027-NIGHTLY-n8000.zip
(Status 7)
Error flashing zip '/sdcard/goomanager/cm-10-20121027-NIGHTLY-n8000.zip'
Updating partition details ....

**Comment by bigbiff** [comment]
This means the recovery has the wrong product device.

**Comment by Dees-Troy** [comment]
Whoever made the assert check on that zip derped it up. There are ++ instead of == in the assert check which is causing it to fail.
