### ISSUE TITLE
OnePlus One TWRP fails to decrypt and work on encrypted device

### ISSUE THREAD

**Issue by xpseudonym** [TeamWin/Team-Win-Recovery-Project#522]
TWRP version: 2.8.7.0
Cyanogen OS version: 12.1-YOG4PAS2QL

Description of problem:
At the prompt 'Please Enter Your Password' I enter my numeric 7 digit password and press 'Go' the fleeting and momentry response is-
Updating partition details...
...done
E: Unable to mount storage.
Full SELinux support is present.
E: Failed to decrypt data.

Before I am returned to the 'Please Enter Your Password' screen where below the password entry field in read is 'Password Failed, Please Try Again'.  Trying again produces the same response.

How reproducible:
Always

Steps to Reproduce:
1. # fastboot boot twrp-2.8.7.0-bacon_recovery.img
2.
3.

Actual results:
Boot fails

Expected results:
Boot into TWRP recovery

Thanks - a fix for this is really really important as all devices are going to be encrypted by default with Android 6.

**Comment by Dees-Troy** [comment]
The OnePlus One bootloader has a bug that prevents TrustZone from working properly when you use fastboot boot. You have to flash TWRP to the recovery partition and boot it from the recovery partition instead of using fastboot boot. You will get the same failure to decrypt if you fastboot boot the boot.img from the CM ROM as well. It's not a TWRP bug and not something we can fix. Talk to CM or OnePlus for a bootloader fix.

**Comment by xpseudonym** [comment]
THanks

**Comment by xpseudonym** [comment]
Hi Again - I've installed twrp-3.0.0-1-bacon.img to recover - I get the same.
On first boot following flashing I get:
Mount
Decrypt Data
Enter Password

I enter my password and I get:
Mount
Trying Decryption
Updating partition details...
...done
Unable to mount storage [RED]
Full SELinux support is present.
Data successfully decrypted, new block device: 'dev
/block/dm-0'
Updating partition details...
...done

It looks like the the error is in the 'Unable to mount storage [RED]' flag rather than actually failing to do so?

**Comment by xpseudonym** [comment]
Linked to #581

**Comment by Pietia10** [comment]
Same problem here I think this bug is critical tried with cm13 and TWRP 2.8.7.0 and 3.0.0.1 same bug happens.

**Comment by pippo73** [comment]
I'm experiencing the same problem with oppo find 7 + omnirom 601
I cannot understand which password is asked. I've to set up the password to unlock the phone but it does not work, I've tried also to remove it.... no way to mount the data partition ;(

**Comment by cmonty14** [comment]
Same issue with CM12.1 and TWRP 3.0.0.1
