### ISSUE TITLE
(Important) Custom Recovery Download doesn't Work.

### ISSUE THREAD

**Issue by hvnnes** [TeamWin/Team-Win-Recovery-Project#523]
If I try to download a recovery version from the app it takes me to the jmzsoftware website and doesnt download anything. There is no possibility to click on "download" or something similar. I've already tried to download the .img file on my PC but didn't know in which folder I have to paste the file on my phone.

**Comment by CaptainThrowback** [comment]
You want support@jmzsoftware.com. As far as how to flash recovery without the app, see the page for your device on twrp.me.
