### ISSUE TITLE
TWRP cannot decrypt partition with a larger than 3x3 pattern

### ISSUE THREAD

**Issue by cyphar** [TeamWin/Team-Win-Recovery-Project#525]
The UI only allows for 3x3 patterns to be used, while my pattern is larger. There is a workaround described in #323, but it's annoying to have to calculate what the equivalent passphrase is for my pattern and then use `adb` to decrypt it.

Something similar to how stock Android deals with decryption using patterns (having a set of radio options that specify the sizes that can be used to decrypt the phone) would be ideal IMO.

**EDIT**: I'm currently working on a patch, but I need to know what the UI should look like for choosing the grid size (I can't find a radio group object).

**Comment by cyphar** [comment]
A patchset has been proposed: https://gerrit.omnirom.org/#/q/topic:issue/525
I was not able to compile a bootable version of TWRP for my device, however the code was tested separately from Android (by stubbing out the code).

**Comment by CaptainThrowback** [comment]
My comments are added here: 

https://gerrit.omnirom.org/#/c/15803/

The decryption code for the larger grids isn't working, and the grid itself needs to be bigger for the larger grid sizes.

**Comment by cyphar** [comment]
@CaptainThrowback I'm having issues building a bootable recoveryimage. Did you test this on your phone or in an emulator? Is there a Docker build script, a VM I can boot into or even a proper comprehensive guide (which is **NOT** [this one](http://forum.xda-developers.com/showthread.php?t=1943625))?

**Comment by CaptainThrowback** [comment]
I tested this on my device (M8). That's the guide I used to get started. You can always go to IRC at #twrp to try and get some help.

**Comment by ghost** [comment]
just wanted to say i have a 6x6 and experiencing the same issue.

**Comment by CaptainThrowback** [comment]
The fix for this has already been merged and will be included in the next version of TWRP (or any custom builds from the latest source).

**Comment by cyphar** [comment]
Yeah, I wrote a patch for this and it's been merged. This isn't an issue on `master` anymore.

**Comment by CaptainThrowback** [comment]
FYI - CM13 breaks this functionality, so a new patch will be needed.
