### ISSUE TITLE
Secure Boot Error 1003 - LG G3

### ISSUE THREAD

**Issue by cma371** [TeamWin/Team-Win-Recovery-Project#527]
Installed TWRP, when I re-start receive error, "Secure Boot Error, Error 1003". Phone completes boot and phone works fine. Want to correct error. Any ideas?

**Comment by Dees-Troy** [comment]
The G3 has a locked bootloader. If you update to the latest version of LG's official software, you will have installed a bootloader that is patched against BUMP which will prevent you from installing TWRP. You can search on xda or look for an app called AutoRec which may help you downgrade to a vulnerable version of LG's software.
