### ISSUE TITLE
setting backup name doesnt work properly

### ISSUE THREAD

**Issue by mamumami** [TeamWin/Team-Win-Recovery-Project#53]
device: galaxy s3 t999

when i set a backup name, after trying to type a long name, it just goes back to the backup screen, wont let me type specific name, took me more than 15 tries to fully type "original tmobile backup"

**Comment by mamumami** [comment]
actually, twrp goes back itself quite often from any screen, at random intervals, something is wrong, can someone confirm

**Comment by saltorio** [comment]
I've noticed the same issue on my Galaxy Note 10.1 (N8010) using TWRP 2.3.3.3. I can't set a backup name, as typing on the keyboard will randomly cause key repetition (so I get 3-4 of the same letter from a single key touch), or it simply goes back to the backup screen.

Works fine on my SGS3 (I747M).

**Comment by bigbiff** [comment]
Is this still an issue? If you can give us /tmp/recovery.log that would be great.
