### ISSUE TITLE
[2.8.7.0][OnePlus X] E: Unable to locate partition by backup name

### ISSUE THREAD

**Issue by sebastianst** [TeamWin/Team-Win-Recovery-Project#530]
I used the [beta TWRP from xda](http://forum.xda-developers.com/oneplus-x/orig-development/recovery-twrp-2-8-7-0-touch-recovery-t3252840) to backup my _system_ partition before rooting my OnePlus X. Now I wanted to flash that system image back to install the official OTA Update.

However, TWRP doesn't understand anymore for which partition the backup files were. The logs show:

```
E: Unable to locate partition by backup name: 'system_image'
E: Unable to locate partition by backup name: 'oppostanvbk'
```

The only backup recognized is that of the _boot_ partition.

I also [reported](http://forum.xda-developers.com/showpost.php?p=64092678&postcount=104) this bug to the xda thread mentioned earlier, but didn't receive a response yet.

**Comment by Dees-Troy** [comment]
The OnePlus X does not have official support. We don't have a OnePlus X (and have no plans on spending our money to buy one). If someone submits a fully working device tree to build a TWRP for it from source, then we can add official support. Until then, we cannot offer you much in the way of support.

TWRP is open source, so developers like the one you see on xda can download our source and port it to their devices, but we are unable to help fix issues with these unofficial builds. I hope you can understand. Sorry.
