### ISSUE TITLE
[TWRP 2.8.7.1] [Clark aka XT1575 aka 2015 Moto X Pure] Unable to mount encrypted data partition

### ISSUE THREAD

**Issue by lachesis** [TeamWin/Team-Win-Recovery-Project#537]
When I boot, TWRP does not ask me for the encryption password (actually a pattern in this case). I'm running Android 6.0. I also tried using `adb shell` to provide the pattern manually, but neither the pattern in the standard number format nor the same thing in ASCII hex (as some random forum suggested) worked.

**Comment by cdhawan** [comment]
+1.

**Comment by sydlexius** [comment]
Hoping this gets implemented, along with pattern support (the 6P has both working).

**Comment by Diapolo** [comment]
Is 2.8.7.1 an official release?

**Comment by ahrenstein** [comment]
+1

**Comment by HashBang173** [comment]
http://forum.xda-developers.com/showpost.php?p=65045112&postcount=474

**Comment by Dees-Troy** [comment]
Fixed in 3.0.0-0 builds.
