### ISSUE TITLE
Nandroid backup in Nexus 7 with twrp 2.3.1.1

### ISSUE THREAD

**Issue by chris-koz** [TeamWin/Team-Win-Recovery-Project#54]
Hello.I have a nexus 7 8gb with stock android 4.1.2 JZO54K.I installed twrp 2.3.1.1 but i cant take nandroid backup.When i am trying to backup i get error
E:\Unable to locate android secure partition. 
i installed twrp 2.2.2.0 and it worked.Can you tell me please what to do to make the new version to work?
Ι uploaded recovery.log here https://www.dropbox.com/s/yylk8ia37cdrnpk/recovery.log after i took the message error.Thank you very much

**Comment by Dees-Troy** [comment]
Settings, reset defaults will probably clear this issue.

**Comment by chris-koz** [comment]
yes this solved the issue
