### ISSUE TITLE
Supported sdcard formats?

### ISSUE THREAD

**Issue by valkayrie** [TeamWin/Team-Win-Recovery-Project#543]
Device: Nvidia Shield Tablet
TWRP Version: v2.8.7.0
Android Version: Stock 5.1.1 Rooted

The sdcard in my Shield Tablet is formatted as NTFS but TWRP can't create folders for backups. It's reading my sdcard properly since I can install zips from the sdcard so I'm not sure what the issue is, unless TWRP can't get r/w permission for some reason

**Comment by Dees-Troy** [comment]
NTFS support in the Linux kernel is pretty poor. Usually the kernel ends up mounting NTFS as read-only. There is ntfs-3g which can be added to a TWRP build via a build flag and maybe lj50036 can add it as he is the maintainer for the Shield Tablet. That said, you're probably the only person using TWRP on the Shield Tablet with an NTFS formatted sdcard. Most people use FAT32 or exFAT. Also, with Android 6.0, users will probably start moving towards using adopted storage.

**Comment by valkayrie** [comment]
Thought so, but I didn't see the issue anywhere else (and I searched both closed issues and Google). Thank you for your help
