### ISSUE TITLE
T-Mobile LG G4 (H811) recovery not booting

### ISSUE THREAD

**Issue by shepherdjerred** [TeamWin/Team-Win-Recovery-Project#544]
Having a very strange issue here.

To put it shortly, I'm able to use the international image of TWRP for the H815 just fine, however flashing the TWRP image for the H811 results in the recovery not booting, it will just hang at a black LG screen until the battery is pulled.

I'm able to boot into my system regardless of which is installed.

[More info is here](http://forum.xda-developers.com/g4/help/installed-twrp-boot-stuck-lg-screen-t3286684)

**Comment by Dees-Troy** [comment]
We don't own any model of G4. Sounds like you got it working, but I have no idea why one works and not the other. Maybe T-Mo started using a different hardware variant for some reason. Who knows...
