### ISSUE TITLE
The problem:display of battery percentage is incorrect on TWRP for htc M9(hima)

### ISSUE THREAD

**Issue by adsoucyyx** [TeamWin/Team-Win-Recovery-Project#549]
First, I can't be sure if it is a bug of TWRP or not. I have tried to flash the latest framework when the battery life is 100%. But the problem is still occur. For instance:I charge my device to 100% battery life, then I reboot my device to the TWRP and the percentage display of battery life become 90%. By all rights, the display of battery life should be 100%. Next, I reboot my device to system, the battery display of system is same as the display on TWRP.

**Comment by CaptainThrowback** [comment]
Android typically considers anything between 90-100% as 100% charged. So it sounds like TWRP is reporting the real value to you and then so is system when you reboot. I don't see how this is possibly a TWRP issue.

**Comment by adsoucyyx** [comment]
However, when I reboot it again and again, the battery life become 80% or less. The battery display will decrease as long as I reboot my device again.

**Comment by CaptainThrowback** [comment]
Ok, but I still don't see how that's a TWRP problem.

**Comment by adsoucyyx** [comment]
Yes, so I write" I can't be sure if it is a bug of TWRP or not" at first. I just ask for help on this website if someone knew how to solve the problem. Because I have searched lots of forum but not found the answer yet.

**Comment by Dees-Troy** [comment]
This isn't a TWRP issue. The battery percent is either reported by the kernel or via some proprietary closed source HTC binaries. Also, booting and rebooting the device will drain the battery somewhat. Even if you leave the device plugged in, during some parts of the booting process, the device won't actually be charging at all. Further, on many devices, even when charging, the display and processor will be using more power than the charger can put out, causing the battery percentage to drop even while charging.
