### ISSUE TITLE
Stuck at TWRP screen

### ISSUE THREAD

**Issue by demonr6** [TeamWin/Team-Win-Recovery-Project#55]
Had trouble installing via Goo manager, finally worked but on reboot it is stuck on the TWRP logo screen and I cannot get into recovery now.

**Comment by jjlwork** [comment]
I also had very similar issue. Using TWRP to clear cache froze my device it eventually timed out and re-booted. On reboot and trying to get back into TWRP I got stuck at the TWRP logo. I think it got stuck trying to parse logs as when I installed CWM to try and get back into some sort of recovery it said it couldn't open log or log_last and kept looping. I am using a Samsung T989 (Hercules)

**Comment by Dees-Troy** [comment]
I need a recovery.log to be able to fix this. The only way to get it when TWRP won't boot is to use adb:
adb pull /tmp/recovery.log
