### ISSUE TITLE
Removed

### ISSUE THREAD

**Issue by imanust** [TeamWin/Team-Win-Recovery-Project#553]

**Comment by ekinexus** [comment]
Editor: I don't know what is the PC detected. And the IMG.tar would be helpful for flashing with ODIN.

**Comment by ekinexus** [comment]
The image was removed from downloads.

**Comment by ekinexus** [comment]
Flashed img.tar with odin and the same problem happens.

**Comment by achozex** [comment]
same problem , but when entering twrp windows can identifiy the internal storage and im able to browse it.

**Comment by powyncify** [comment]
I can confirm: After installation of treltexx 3.0.0-0, the recovery screen is not showing. The screen is blank, but the device vibrates in response to touches and is detected and can be browsed from Windows. It boots normally.
The device was SM-N910C, a Note 4 version that uses **Exynos**, not Qualcomm Snapdragon 805. The file we used was _twrp-3.0.0-0-treltexx-treltexx.img.tar_ from [here](https://dl.twrp.me/treltexx/). This was a virgin installation, and we resolved it by downgrading to 2.8.7.0. 
Hope you can eliminate this screen bug

**Comment by achozex** [comment]
looks that theres a problem with the img.tar file.

i flashed IMG instead of img.tar through flashify and it works now

**Comment by powyncify** [comment]
The problem is now resolved. Just use [twrp-3.0.0-0-treltexx.img.tar](https://dl.twrp.me/treltexx/twrp-3.0.0-0-treltexx.img.tar.html). Thanks!
