### ISSUE TITLE
digitizer inconsistent on touchpad

### ISSUE THREAD

**Issue by ghost** [TeamWin/Team-Win-Recovery-Project#56]
TWRP touch screen response is inconsistent on the HP Touchpad...  at times, there is no response until after the screen is left alone for a period of time.  (not the same behavior as I experience on my SGS3).

**Comment by Dees-Troy** [comment]
The HP TouchPad uses a CyanogenMod team developed touchscreen driver instead of using touchscreen firmware like most other devices. Unfortunately the touchscreen on the TouchPad just isn't quite as good.
