### ISSUE TITLE
TWRP 3.0.0.0 on Nvidia Shield Tablet: split display 

### ISSUE THREAD

**Issue by HJvD123** [TeamWin/Team-Win-Recovery-Project#564]
Install from 2.8.7.0 to 3.0.0.0 went fine. After install everything seems fine, the only thing is that I have a screen that is splint vertically in two parts. Image says it all. 
![img_20160214_142943](https://cloud.githubusercontent.com/assets/11976483/13033974/7abb25da-d328-11e5-8b37-b8cd0927844a.jpg)

**Comment by PrototypeNM1** [comment]
Seconded, same issue on my device. Touch interacts as though the screen is not offset.

**Comment by 13scoobie** [comment]
same experience here.

**Comment by HJvD123** [comment]
Beautiful fix in 3.0.0.1. Thanks.
