### ISSUE TITLE
Error with Zips larger then 2GB on HIMA_WL TWRP 3.0.0-1

### ISSUE THREAD

**Issue by santod** [TeamWin/Team-Win-Recovery-Project#572]
http://hastebin.com/elirapijus.md

When zip size was reduced to 1.9GB's, installation worked fine.
Thank you for your time.

**Comment by Dees-Troy** [comment]
Zips larger than 2GB are flashable with TWRP 3.0.0-0 but you will also have to update your updater-binary as the binary inside the zip also has to be able to handle zips larger than 2GB. The max size now will vary somewhat depending on the device. The theoretical limit is now 4GB but in practice it will probably be more like 2.8GB.
