### ISSUE TITLE
TWRP 3.0.0-0 : Very slow flashing speed after upgrade AOSP-base to 6.0

### ISSUE THREAD

**Issue by jesec** [TeamWin/Team-Win-Recovery-Project#574]
It tooks me 2 min to flash a SuperSU zip with AOSP-6.0.1 base.
But after i downgrade AOSP-base to 5.1.1,this problem disappear.
And it tooks me only 10s to flash the same zip with 5.1.1-base.

**Comment by DienoX** [comment]
I have this same problem.
+1

**Comment by Dees-Troy** [comment]
What device are you using? This issue has popped up on a few devices but not all.

**Comment by jesec** [comment]
Mine is S5 LTE-A(G906).
@DienoX is S5 Plus. (G901)
Both of them are powered by Snapdragon 805 (APQ8084),the same as Note 4.

**Comment by eligao** [comment]
+1, super slow on Nexus7 2013 wifi (flo)

**Comment by Zipsnet** [comment]
Nexus7 2013 LTE (deb) took more than 1 hr to flash aicp's 6.0 rom and gapps !!

**Comment by Dees-Troy** [comment]
https://gerrit.omnirom.org/#/c/17076/

**Comment by ghost** [comment]
I too have the same problem, on a Nexus 7 2013 (flo) WiFi. Took ~3-4 minutes to flash SuperSU on a stock 5.1 image. As soon as I downgraded to an older version, the problem vanished.

**Comment by Dees-Troy** [comment]
This was fixed in newer releases already.
