### ISSUE TITLE
victara xt1092 twrp 3.0.0.0 backup error - Error during restore process. extractTarFork() process ended with ERROR: 255

### ISSUE THREAD

**Issue by ericcostes** [TeamWin/Team-Win-Recovery-Project#577]
motorolla xt1092 victara - CM13 - 18 feb 2016

**Comment by ericcostes** [comment]
[twrpfailed.docx](https://github.com/TeamWin/Team-Win-Recovery-Project/files/139244/twrpfailed.docx)

**Comment by Dees-Troy** [comment]
I:Error adding file '/data/data/org.cyanogenmod.audiofx/code_cache/com.android.opengl.shaders_cache'

Try deleting the offending file.
