### ISSUE TITLE
Regression in TWRP 3.0.0-1 for OnePlus 2

### ISSUE THREAD

**Issue by mechanicker** [TeamWin/Team-Win-Recovery-Project#578]
I tried the latest TWRP recovery (3.0.0-1 found at https://dl.twrp.me/oneplus2/twrp-3.0.0-1-oneplus2.img.html) on OnePlus2.

Installing OnePlus2 OxygenOS 2.2.0 firmware fails stating unsupported device. It is trying to compare "oneplus2" from recovery with "OnePlus2" from ROM update zip (case mismatch).

Ideally, OxygenOS firmware zip could have used a case-insensitive match. I cannot say it is a bug in TWRP, it is a regression from 3.0.0-0

A simple reproducer zip file (checking the property): https://www.dropbox.com/s/0uztyqk05s63zsu/getprop-test.zip

The above works on 3.0.0-0 and fails on 3.0.0-1﻿

**Comment by mechanicker** [comment]
I request you to please remove 3.0.0-1 from the download till the issue is fixed. This will prevent duplicate bug reports

**Comment by Dees-Troy** [comment]
Should be fixed in 3.0.0-2

**Comment by mechanicker** [comment]
@Dees-Troy Thank you, tested and it works fine
