### ISSUE TITLE
TWRP 3.0 Password "theme" 

### ISSUE THREAD

**Issue by FrancisXI** [TeamWin/Team-Win-Recovery-Project#579]
Hello geniuses! I just wanted to politely ask the TEAM if you could make a PASSWORD theme for 3.0? 
I've read your opinion that it is pointless (which it is in a sense) BUT let's keep in mind that most people don't have any clue about any of this. However, for me and many others like me such a locked theme does give us some time to track our devices in a worst case scenario. Most thieves do know how to get into recovery.

With such a theme it then atleast comes down to who gets to a computer first, the thief/finder or the owner.

I'm of the opinion that you should make it (such a theme) part of TWRP or make a locked theme to be downloaded separately, even if it seems pointless to you.

This is impossible for me to do, but i doubt that this is too much to ask from you guys.

I thank you in advance, for whatever the decision you make. Respect!

**Comment by 0x2b3bfa0** [comment]
:+1: for pattern lock :smile: 

Would be great to have a locked recovery, even if seems a nonsense. If anybody steals your device...

**Comment by Dees-Troy** [comment]
Any thief who has the presence of mind to wipe the device will also have the presence of mind to turn off the device to prevent remote tracking. I have already weighed in on this issue multiple times. We are open source so feel free to code it yourself if you think you know better than me.

**Comment by FrancisXI** [comment]
Ethan Yonkers, little moron if i was a developer i could guarantee you that
you would take your words back.

I'm better at my professions but my ideas go beyond my professions, i was
very respectful in my comment BUT you little asshole wasn't in your reply!

Aren't we humans? Supposed to behave intelligently? Knowing better?

So i believe that you are just a little kid, giving you the benefit of the
doubt. Or you are a damaged spoiled brat? 1 or 2?

I couldn't care less.

Now to the point, a password theme is to PREVENT A RECOVERY, unless a
person would install a "TWRP" Recovery that came later (which would render
the theme useless) just as 2.8 with 3.0

Get it?

A wipe isn't the issue, it is ALL ABOUT protecting the SD!

EVEN THOUGH ANDROID IS CLAIMED TO BE OPEN SOURCE, IT IS DEFINITELY POSSIBLE
TO MAKE IT SAFE FROM THE MAJORITY, THE FACT THAT YOU ARE INCAPABLE OF
MAKING THE  CHANGE, ISN'T ENOUGH REASON FOR YOU TO BLAME "OPEN SOURCE
ANDROID" AND CLAIM TO KNOW ANY BETTER, you are educated on the field but
you are obviously not intelligent!

When you show this reply to the rest of your crew, then show it completely
because you are the least capable!

Go make a widget or bootlogo incompetent little google fuck!

Op wo 24 feb. 2016 01:15 schreef Ethan Yonker notifications@github.com:

**Comment by that1** [comment]
Thanks. We all had a good laugh. Now go away.

**Comment by msfjarvis** [comment]
@FrancisXI, please, ignore @that1 and join us at #twrp on freenode. We are missing the presence of a full time court jester

**Comment by FrancisXI** [comment]
Thank you Harsh, i actually laughed about his reply. It was funny but yet i
feel sad for him at the same time. I don't care about the subject, and
definitely not about "teamwin" (which is a childish name for a
program/software to begin with) Power Ranger / Virtual Reality Troopers
style.

However, the project can be perfected, nothing starts off as perfect
(everything in life goes is stages)

Now the focus is on the UI as this is the age of the superficial and not
the core, in this case (recovery and safety)
I have personally preformed a encrypted backup on 3.0 and recovery didn't
recognize the password which was 100% right, i tried multiple times to
verify whether it was my error or yours.

This is all interesting to me but it really isn't my passion.

These are only worthless devices in reality, and as much as i hate to say
it Android Developers are incompetent, i could keep an Android and not root
it by which my info stays with 1 company and i could "enjoy" all the
horrible ads that come along with it by Google of course! Or switch to
Apple and give my info to one enterprise which is also not trustworthy AT
ALL!

Maybe the best option for me is to go back a few years and buy a old nokia
gsm, a separate simple camera and 1 home computer without Wifi or Bluetooth.

I really whole heartedly thank you for your reply and i love you for that
goodness.

May peace remain with you.

My best wishes.

Op ma 4 apr. 2016 18:01 schreef Harsh Shandilya notifications@github.com:

**Comment by vaibhav3027** [comment]
I know password in the recovery is not totally secure.
But i don't know anything which is completely and totally secure.
As you know passwords are only meant to slow down the progress of hacking in to the system.
Even the encryption algorithm used in SSL (RSA), can be broken but it need heck lot of time to come up with the factors of the public key.
The passwords in the android or any devices are mainly used for preventing their unauthorised use when you physically possess that devices.
Losing the device is totally another case.
Without having the possession of the physical unit you can never be sure of the usage of your data even with the partition encryption its just the matter of time to recover the original data from your encrypted device .
If you say no one would take that much effort, I agree and would say no one would take that much effort to bypass the locked recovery either.
It's not even the matter of effort,
Most of the thief don't have the knowledge about what to do with the locked device and locked recovery.
It's not even the case when you have lost your device, password protection is mostly required to evade the prying eyes of the people around you.
TWRP also provides MTP connection directly to the connected Computer which is a handy option to have in a recovery but it also let the people around you,to invade your privacy by just simply connecting the device to a computer while in TWRP.

And these are the reason for which i want TWRP to have a password protection.

**Comment by CaptainThrowback** [comment]
@vaibhav3027 Just encrypt your device in Android and set a password on boot. Then that password will also be required to log into TWRP. That seems much more secure than a theme with a password which can just be removed via adb.
