### ISSUE TITLE
Full format internal memory on Asus TF300T

### ISSUE THREAD

**Issue by BrateloSlava** [TeamWin/Team-Win-Recovery-Project#58]
Is there a way to completely format the internal memory?

I installed the CM10, and then decided to abandon it. When checking the internal memory, I found file system errors. 
I decided to completely clean the tablet's internal memory.
I have read the documentation ( http://teamw.in/DataMedia ) and found that the wipe command will not help me.

I removed the memory card, from TWRP consistently performed four commands wipe and two command format (system and internal data).

Install stock firmware and TWRP 2.3.1.0 and trying to check for errors. Errors were again.

It turns out that the partition is not formatted?

Screenshot - http://i48.fastpic.ru/big/2012/1130/12/73e5ac67dc0799f3d4df705822c96d12.jpg

**Comment by Dees-Troy** [comment]
On the wipe page, use "Format Data" to truly format the file system.
