### ISSUE TITLE
TWRP 3.0.0-0 Cannot decrypt phone with 6x6 pattern

### ISSUE THREAD

**Issue by Scorcher7986** [TeamWin/Team-Win-Recovery-Project#595]
Cannot decrypt phone with a 6x6 pattern on TWRP 3.0.0-0. Have not tested other sized patterns, but PIN codes work.
Using Samsung Galaxy S3 (I9300) with Cyanogenmod 13

**Comment by Dees-Troy** [comment]
Try the -2 build
