### ISSUE TITLE
PLEASE ADD MY PHONE'S NAME FLY QIK PLUS TO YOUR SUPPORTED DEVICE LIST.

### ISSUE THREAD

**Issue by directtosumit** [TeamWin/Team-Win-Recovery-Project#599]
PLEASE ADD MY PHONE'S NAME FLY QIK PLUS TO YOUR SUPPORTED DEVICE LIST.

**Comment by noahajac** [comment]
It doesn't work that way.

**Comment by skynet11** [comment]
MAYBE HE DOESN'T EXPECT YOU TO ACTUALLY SUPPORT IT, PERHAPS YOU COULD JUST ADD THE NAME TO THE SUPPORTED DEVICE LIST AND WHEN THEY TRY TO DOWNLOAD IT THEY GET RICKROLLED 😜

**Comment by shaggyskunk** [comment]
Nice.... No need to be disrespectful.

**Comment by robygt** [comment]
YOU CAN USE #TARP IN THE MEANTIME AND GO #BLACKSCREENROM IF YOU WANT TO BE #CYANOGENMODDED

**Comment by Dees-Troy** [comment]
The TWRP issues log is not a place for requesting TWRP for devices that do not have TWRP support.

**Comment by noahajac** [comment]
@shaggyskunk I changed it when I first posted it as I relised my mistake, not sure why you got the old one.
