### ISSUE TITLE
Recovery doesnt boot on new bootloader a500

### ISSUE THREAD

**Issue by dalb8** [TeamWin/Team-Win-Recovery-Project#6]
1. Flash tw recovery from within Thor recovery or via fastboot
2. Reboot recovery and the screen hangs on "booting kernel "

Only on Ics bootloader for a500 picasso: 0.3.11, 0.3.12

**Comment by Dees-Troy** [comment]
I released a new version that should boot on more versions of the bootloader.  No one in team win owns an A500 so we aren't able to easily verify operation on all versions of bootloaders.

**Comment by dalb8** [comment]
Dees-Troy reply@reply.github.com wrote:

> I released a new version that should boot on more versions of the
> bootloader.  No one in team win owns an A500 so we aren't able to
> easily verify operation on all versions of bootloaders.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/TeamWin/Team-Win-Recovery-Project/issues/6#issuecomment-5832479

Yes, I have it now, works great, although it didn't seem to be able to update the bootloader, a feature billed in Skrilax' v4 unlocked bootloader. That's no big deal though as we can do that with fastboot now.
