### ISSUE TITLE
PLEASE ADD MY PHONE'S NAME FLY QIK PLUS TO YOUR SUPPORTED DEVICE LIST.

### ISSUE THREAD

**Issue by directtosumit** [TeamWin/Team-Win-Recovery-Project#600]
PLEASE ADD MY PHONE'S NAME FLY QIK PLUS TO YOUR SUPPORTED DEVICE LIST FOR DOWNLOADING RIGHT TWRP (.IMG) VERSION.

**Comment by CaptainThrowback** [comment]
Are you saying there's already an official build available for the device, but no device page? I looked, but I don't see a build for your device on the official TWRP site. And if there's no official build, what are you expecting here?

Please read this: https://plus.google.com/+DeesTroy/posts/iyyM1kYULEa

**Comment by Dees-Troy** [comment]
The TWRP issues log is not a place for requesting TWRP for devices that do not have TWRP support.
