### ISSUE TITLE
TWRP 3.0.0-0 cannot decrypt MHC19i on Nexus 6P

### ISSUE THREAD

**Issue by Kameechewa** [TeamWin/Team-Win-Recovery-Project#602]
I just flashed the latest build for Nexus 6P and now I have to live without root because it can't decrypt data.

**Comment by nklmilojevic** [comment]
You don't have to live without root because you can enter the recovery, go to advanced, adb sideload and then connect the phone to the computer, enter adb sideload supersu.zip and watch the magic show.

But yes, this needs to be fixed.

**Comment by Kameechewa** [comment]
I just tried an it's not working. I keep getting stuck on waiting for device and TWRP can't start the adb sideload feature.

**Comment by CaptainThrowback** [comment]
There's a test build for angler in the comments here: https://plus.google.com/u/1/+shofiqulanwar/posts/gqAMQ3yZW1o

**Comment by Kameechewa** [comment]
It worked!!! Thank you so much!!!

**Comment by jasonlyle88** [comment]
I am having this issue as well.  As a temporary work around (and I have no idea WHY this works), you can downgrade TWRP.  I loaded the twrp-2.8.7.1-angler.img and it decrypts MHC19i on a Nexus 6P just fine.  Note: I also tried twrp-2.8.7.2-angler.img and it is failing to decrypt the phone.  So if you absolutely need a stable TWRP, you can do 2.8.7.1 for now.
