### ISSUE TITLE
Install zip too slow in twrp 3.0.0

### ISSUE THREAD

**Issue by 1a57danc3** [TeamWin/Team-Win-Recovery-Project#603]
install CM13 and gapps pico spent a hour....

**Comment by that1** [comment]
Already fixed in source code (https://gerrit.omnirom.org/#/c/17076/).
Workaround: run "adb shell rm /sbin/modprobe" (or the same without "adb shell" in TWRP's terminal) before installing.

**Comment by 1a57danc3** [comment]
thx~
