### ISSUE TITLE
Settings for navbar height

### ISSUE THREAD

**Issue by alex-pex** [TeamWin/Team-Win-Recovery-Project#608]
Hello!

I have a Nexus 4 with a (little) damaged screen, which disable a small part of the bottom of the screen.
I can still use the phone thanks to Gravity Box "navbar height" setting but the recovery is a problem.

Can you make a setting to increase the navbar height (like x2 in my case) or can you add a "go back" button on the top left corner ?

**Comment by that1** [comment]
The TWRP logo is already a back button.

**Comment by alex-pex** [comment]
Oh, never saw that. It works !

**Comment by msfjarvis** [comment]
But that still leaves the point @that1, that a nav bar height customisation, if not terribly tough to code, would be a welcome feature.
