### ISSUE TITLE
LG G4 H815 V20D recovery doesnt boot

### ISSUE THREAD

**Issue by the-erazer** [TeamWin/Team-Win-Recovery-Project#611]
the is a similar issue in the bug tracker... but here its vice versa
phone is h815 ships v20d newest marshmallow build... testet every version of twrp.
twrp for h815 doesnt boot up only a few seconds black screen then it boots to os.
twrp for h811 boots just fine but no serios way to flash something because it says it is 
h811 but the phone is h815. 
is there any way to change the model in twrp itself?
and what is the difference between this two variant of twrp?

**Comment by RALUNTITLED** [comment]
Nadie sabe por qué ocurre esto???

Nobody knows it?

**Comment by steadfasterX** [comment]
there is no difference anymore if you use the latest BETA in the official TWRP thread. Go over there and it should work. 

This work will be merged to official soon. h811 and h815 are identical devices when it comes to TWRP. They differ in parts which doesnt matter for TWRP - for ROM it is another thing. There you have to use the correct version though.

**Comment by steadfasterX** [comment]
@bigbiff please close. this is fixed since 3.1.x
