### ISSUE TITLE
linker problems with TWRP 3.0.0-0 and AOSP 6.0.1

### ISSUE THREAD

**Issue by OlafLostViking** [TeamWin/Team-Win-Recovery-Project#616]
I wanted to setup encryption manually (as setting it through the CustomMod always fails) but stumbled upon the following linkage problem:

```
~ # /system/bin/vdc
CANNOT LINK EXECUTABLE: cannot locate symbol "stderr" referenced by "/system/bin/vdc"...
page record for 0xb6eba04c was not found (block_size=32)
~ # /system/bin/yes
CANNOT LINK EXECUTABLE: cannot locate symbol "stderr" referenced by "/system/bin/yes"...
page record for 0xb6f3f04c was not found (block_size=32)
~ #
```

TWRP does not include a vdc on its own, so I am dependent on the one installed by the mod, right?

My naíve `chroot` try didn't work out, either ;-)

```
~ # chroot /system /bin/sh
chroot: can't execute '/bin/sh': No such file or directory
~ # ls -l /system/bin/sh
-rwxr-xr-x root     shell      170012 2008-12-31 23:00 sh
~ #
```

**Comment by that1** [comment]
You may need to set LD_LIBRARY_PATH to point to /system/lib before /sbin. But I guess that even if you can get vdc to run, it still won't work as vold isn't running.

**Comment by mjfwalsh** [comment]
Thanks @that1, was suffering the same problem as @OlafLostViking, but setting

`LD_LIBRARY_PATH=/system/lib:/system/vendor/lib:.:/sbin`

fixed it.

**Comment by qsantos** [comment]
Trying to reset the encryption password (Lineage OS fails to decrypt) from TWRP, but I get the following error after applying @that1 /@mjfwalsh's fix:

```
# vdc cryptfs
Error connecting to cryptd: No such file or directory
```

**Comment by ghost** [comment]
@qsantos Did you ever succeed? I have the same problem, changed the encryption password but forgot to put the newpass in quotes and it contained a "$" - now booting TWRP it accepts the pass (up until before the $) but the regular boot does not accept it. Now I'm trying to change the pass in a recovery terminal but failing at the same point you describe in your last post.
Even after mounting all volumes, and doing a "find / -name cryptfs" it finds nothing :-(

**Comment by qsantos** [comment]
No, I just formatted eventually.

**Comment by stefanobalzan** [comment]
Hi, I'm facing the same issue trying to mount an encrypted /data partition and recover some files on a Galaxy A5 2017 (running Oreo). I'm getting the "integrity verification failed" error at boot and the phone requires a data wipe.

I've installed TWRP and tried to decrypt the data partition with `vdc cryptfs` via adb. I was able to set the library path required to run vdc, as @mjfwalsh suggested, however the volume daemon is not running therefore I get @qsantos error: 
```
# vdc cryptfs
Error connecting to cryptd: No such file or directory
```

Maybe if I manage to manually start vold, I can decrypt the /data partition. Any idea how to start it?

Also, `twrp decrypt <password>` was no help, it fails to decrypt with an error.

Has any of you come to a solution? Is there any "low-level" tool I could use? I just need to extract the decrypted image of the data partition, I would then be able to mount it as a loopback device on any Linux system.

**Comment by CaptainThrowback** [comment]
This isn't a TWRP issue. TWRP doesn't use vdc to decrypt. You can build TWRP with system vold decrypt support, which might help your situation, and will handle vdc automatically. However it will only decrypt; it won't allow you to ever change your password while in TWRP. This "issue" should be closed @bigbiff.
