### ISSUE TITLE
homtom ht7

### ISSUE THREAD

**Issue by garyfailsafe** [TeamWin/Team-Win-Recovery-Project#617]
Hi I installed the twrp as per this site below and using google translate 
http://www.elchiringuitochino.es/2016/01/rootear-homtom-ht7-e-instalacion-de.html
on reboot, the recovery environment was in russian and the interface frozen, I then replaced twrp folder as per a recomendation from the same site and now I have an english team win interface when I enter recovery but the phone remains completely frozen...it wont boot to normal mode either...
diags run on the phone itself seems to pass sucessfully and I can still access it via usb, 
i then also tried to put a new rom on it using a sp flast tool but that wont work either so I am left with a brick it seems, any help on this would be great 
its my first time doing this too so go easy

many thanks

**Comment by Dees-Troy** [comment]
The HomTom HT7 does not have official support so we are unable to provide any assistance. Sorry.

**Comment by garyfailsafe** [comment]
thats marvellous, could you even give a generic Idea of how to remove twrp? or a how to for a similar phone tks
