### ISSUE TITLE
Decryption not working on GT-N7100 with 2.3.x.y recoveries

### ISSUE THREAD

**Issue by brocktice** [TeamWin/Team-Win-Recovery-Project#62]
Please accept my apologies if this is not supported. All of the posts I have seen indicate that it is. I am using TWRP 2.3.2.3 on my Note 2 (GT-N7100), and I have encrypted the device. It does not prompt me to decrypt on booting recovery like my Galaxy Nexus does in TWRP2, and I am not able to mount /data.

I'm handy with the command line, so please let me know if there's anything I can do to help get this up and running.

**Comment by Dees-Troy** [comment]
Decrypt support doesn't work on all devices and we don't compile it into all builds. Samsung doesn't use AOSP encryption and if you encrypt with a TouchWiz ROM, TWRP won't be able to decrypt it. We haven't tried adding decrypt support for AOSP-based ROMs like CM but we may be able to decrypt your device if you used CM to do the initial encryption.
