### ISSUE TITLE
Cannot navigate up in file manager in an empty dir

### ISSUE THREAD

**Issue by rugk** [TeamWin/Team-Win-Recovery-Project#620]
I managed to get the file manager into a state where the "Go up" (or similar) "directory" is not shown.

~~(sorry for the bad picture quality)~~

**Comment by CaptainThrowback** [comment]
How to reproduce, and where's your recovery log?

**Comment by rugk** [comment]
Reproduce: Well... I just navigated to `/external_sd/Android`, which is en empty dir on a FAT32 partition of the sd card.

Regarding the log: I did not know a log is created at all. Where is it stored?

I may try to reproduce the problem soon and I'll look for a log...

**Comment by CaptainThrowback** [comment]
Advanced -> Copy Log to SD. Log is stored in /tmp/recovery.log while in TWRP.

**Comment by rugk** [comment]
I have no idea how I did this. I cannot reproduce it right now...
