### ISSUE TITLE
Access encrypted adoptable storage of Android 6

### ISSUE THREAD

**Issue by rugk** [TeamWin/Team-Win-Recovery-Project#623]
Can TWRP access the [adoptable storage](https://android.stackexchange.com/questions/137855/how-does-the-format-as-internal-storage-feature-work-in-android-6-0), e.g. an adopted sd card?
If so: In which path is it stored?

I think an FAQ entry about this feature would be helpful.

**Comment by msfjarvis** [comment]
@rugk, adopted storage as such shouldn't be accessible separately since it has been attached to your data partition. Please check and ensure that your user data partition is now as large as internal storage+adopted storage in size

**Comment by rugk** [comment]
> is now as large as internal storage+adopted storage in size

Actually it should only be the size of the external sd card AFAIK. See:

> But if you had a phone with 8GB of storage and a 32GB microSD card, you’ll only have 32GB of space for music, movies, games, or other files, not 40GB.

http://liliputing.com/2015/10/android-6-0-can-treat-sd-cards-as-internal-storage-at-a-cost.html

I'll check how it is in my case.

**Comment by rugk** [comment]
The size of `data` it shows is completely incorrect (it shows the partition would only be around 6 GB large), but I still see that it mounted the adopted storage. So to answer my own questions:

> Can TWRP access the adoptable storage, e.g. an adopted sd card?

Yes.

> If so: In which path is it stored?

At least in my case it is `/sdcard`. (the other external storage seems to be mounted in `/external_sd`)
