### ISSUE TITLE
md5sum-manipulated packets?

### ISSUE THREAD

**Issue by xXn0n4m3Xx** [TeamWin/Team-Win-Recovery-Project#625]
Hello everybody!

I wanted to get the TWRP for the Nexus 4. So i type (in my Linux Terminal) 

`wget https://dl.twrp.me/mako/twrp-3.0.0-0-mako.img`

`--2016-03-31 20:43:11--  https://dl.twrp.me/mako/twrp-3.0.0-0-mako.img
Auflösen des Hostnamen »dl.twrp.me (dl.twrp.me)«... 198.27.116.169
Verbindungsaufbau zu dl.twrp.me (dl.twrp.me)|198.27.116.169|:443... verbunden.
HTTP-Anforderung gesendet, warte auf Antwort... 200 OK
Länge: 5207 (5,1K) [text/html]
In »»twrp-3.0.0-0-mako.img«« speichern.

100%[======================================>] 5.207       --.-K/s   in 0s      

2016-03-31 20:43:12 (809 MB/s) - »»twrp-3.0.0-0-mako.img«« gespeichert [5207/5207]`

Sorry, that the output above is in German.

The false md5 sum was: b9c88252a08e28f94be8550a4c5aba04
The right is: 433a3b32c46c92915e3f112aa58ff9bc

As I downloaded the image over the Website with my Browser I got the correct image. 
How can that be?

**Comment by nailyk-fr** [comment]
the downloaded size via wget is 5,1K: 
@xXn0n4m3Xx 

> Länge: 5207 (5,1K) [text/html]

and: 

> nailyk@nailyk :) % head -1 twrp-3.0.0-0-mako.img                                                                                                        /tmp
> <!DOCTYPE html>

Maybe it is due to some url rewrite/~~javascript~~ on the webpage? 
Same thing with maguro image: 

> nailyk@nailyk 1 :( % wget https://dl.twrp.me/maguro/twrp-maguro-2.1.2.img                                                                               /tmp
> --2016-04-01 13:41:49--  https://dl.twrp.me/maguro/twrp-maguro-2.1.2.img
> Résolution de dl.twrp.me (dl.twrp.me)… 198.27.116.169
> Connexion à dl.twrp.me (dl.twrp.me)|198.27.116.169|:443… connecté.
> requête HTTP transmise, en attente de la réponse… 200 OK
> Taille : 5213 (5,1K) [text/html]
> Sauvegarde en : « twrp-maguro-2.1.2.img »
> 
> twrp-maguro-2.1.2.img                   100%[==============================================================================>]   5,09K  --.-KB/s   ds 0s     
> 
> 2016-04-01 13:41:50 (222 MB/s) — « twrp-maguro-2.1.2.img » sauvegardé [5213/5213]
> 
> nailyk@nailyk :) % head -1 twrp-maguro-2.1.2.img                                                                                                        /tmp
> <!DOCTYPE html>

P.S.: javascript disabled on my browser
P.S.2: if I use [user agent switcher](https://addons.mozilla.org/fr/firefox/addon/user-agent-switcher/) to use my firefox as 'wget', the downloaded file is ok.

**Comment by Dees-Troy** [comment]
We try not to allow directly downloading images from our website. The Web server requires a referer to make sure that people don't directly link to our files. The setup is designed to make sure that you have to see at least one of our website pages with the ads to help our ad revenue.

As much as I hate forcing people to view ads, it's a necessary evil to ensure that we receive the financial support that we need to sustain the project.

**Comment by xXn0n4m3Xx** [comment]
Thank you!

**Comment by rathann** [comment]
I was surprised by this as well.
@Dees-Troy people with adblockers in their browsers won't see the ads anyway and you will keep getting bug reports like this. You could at least mention this on the download pages (that one needs to send a Referrer: header if using CLI tools).

**Comment by nailyk-fr** [comment]
Into my browser download gets wrong too. Take me a while to understand it was my 'noreferer' addon ;)

**Comment by rancidfrog** [comment]
@Dees-Troy

This is silly.
Finally was able to download with curl:
```
curl -e https://dl.twrp.me/polaris/twrp-3.2.3-0-polaris.img.html  -L  -O https://dl.twrp.me/polaris/twrp-3.2.3-0-polaris.img
```
