### ISSUE TITLE
TWRP 3.0.1-0 does not decrypt on Nexus 6 (shamu)

### ISSUE THREAD

**Issue by skidaway** [TeamWin/Team-Win-Recovery-Project#628]
ROM:  PureNexus 6.0.1 (20160315)
TWRP:  3.0.1-0

Entering the correct password does not decrypt the internal storage or the encrypted backups on my USB-OTG drive.  The previous version of TWRP has no problems decrypting.

**Comment by KlondikeBar** [comment]
Same thing happened to me... 3.0.0-1 works just fine, flashed 3.0.1-0 to apply the new factory image and tested this first, failed with the right password several times. Reflashed 3.0.0-1 and it works again.

**Comment by nailyk-fr** [comment]
The [3.0.2](https://dl.twrp.me/shamu/) correct something that could be related. Can you give a try?

**Comment by skidaway** [comment]
3.0.2 confirmed working.  Thanks for the fix.
