### ISSUE TITLE
Can't mount FAT32 formatted external 64GB SD Card

### ISSUE THREAD

**Issue by Koetermann** [TeamWin/Team-Win-Recovery-Project#63]
TWRP 2.3.1.0 says "E: Unable to mount '/externel_sd'"

The card works without any problems under CWM. The device in a S3 Int.with CM10. TWRP was installed by GooManager.

I would appriciate it, if the card will run without to be new formartted. :-)

**Comment by Dees-Troy** [comment]
Boot up TWRP, go to Advanced -> Terminal Command. Browse to /dev/block then hit select, use the keyboard and type ls and hit the enter button. Erase the "ls" and then type blkid and hit enter. Press the home button and then Advanced -> Copy Log. Find the recovery.log in the root of your internal storage and upload that or paste it onto a paste site and link it here please. I know it sounds like a lot of work, but it should only take a couple of minutes.

**Comment by Koetermann** [comment]
Hi Dees-Troy,

here's the recovery.log: http://tinyw.in/9X1k

Regards

Koetermann

**Comment by Dees-Troy** [comment]
The log that you posted is cut off and does not contain the crucial details from the steps that I requested that you perform.

**Comment by Koetermann** [comment]
Sorry for that.

Here a new try: http://tinyw.in/FbIR

**Comment by Koetermann** [comment]
Installed 2.3.3.0 this morning. The external SD-Card was found immediately.

Tested Backup and Restore without any problems.

Issue solved, thanks.

**Comment by elshantaram** [comment]
Hello Dees I am having a similar prob to this. I tried making it fat32 but still not recognized. Any ideas? Thanks!
