### ISSUE TITLE
TWRP 3.0.1-0 can no longer decrypt Nexus 6p

### ISSUE THREAD

**Issue by delro92** [TeamWin/Team-Win-Recovery-Project#630]
ROM: CyanogenMOD 13 (cm-13.0-20160331-NIGHTLY)
TWRP: 3.0.1-0
DEVICE: Nexus 6P 64 GB Frost White

Entering the correct password does not decrypt the internal storage. The previous version of TWRP has no problems decrypting.

---

Edit: Fixed in 3.0.2-0, update as needed. Issue closed.

**Comment by storm1ng** [comment]
This seems to be the case on all devices. At least for my Oneplus One, Nexus 6P and HTC One M7.
And from the other issues the Nexus 5 and 6.

**Comment by markreg** [comment]
Same on Nexus 5X. Stock MHC19J.

**Comment by Fullmetal5** [comment]
Having this issue as well on the Nexus 6P with a near stock rom (just Xposed and 2-3 tweaks as well as an ad blocker).
ROM: Android 6.0.1 Marshmallow (MHC19I)
TWRP: 3.0.1-0
DEVICE: Nexus 6P 128 GB Graphite

**Comment by sultanqasim** [comment]
Do all of you use pin codes or passwords that are entered through the keyboard? If so, you probably hit a regression in the text entry code that I fixed here: https://gerrit.omnirom.org/#/c/17571/

**Comment by Fullmetal5** [comment]
Mine was indeed a pin.

**Comment by jfchevrette** [comment]
I use fingerprint - no pin or password other than the usual encryption password required on boot.

**Comment by storm1ng** [comment]
I use pin as well.

**Comment by LawnGnome** [comment]
> Do all of you use pin codes or passwords that are entered through the keyboard? If so, you probably hit a regression in the text entry code that I fixed here: https://gerrit.omnirom.org/#/c/17571/

Password, on a Nexus 5X. That would explain it.

**Comment by Sea-Worker9552** [comment]
I assume the buildbots will push out a new update automatically? 3.0.2.0?

https://gerrit.omnirom.org/#/q/project:android_bootable_recovery

**Comment by delro92** [comment]
Yep, 4 digit pin. 3.0.2 works perfectly. Thank you for your work @sultanqasim ! Closing the issue now.
