### ISSUE TITLE
TWRP not working on kltechn

### ISSUE THREAD

**Issue by amir-arad** [TeamWin/Team-Win-Recovery-Project#631]
Hi

I couldn't get TWRP to work on my galaxy S5 chineese version (SM-G9006V). It just crashes on load and restarts the device. CM recovery 13 (cm-13.0-20160316-SNAPSHOT-ZNH0EAO1QD-kltechn-recovery) seems to work well enough to instal CM, but I does not do well with other images (opengapps for instance).

I've noticed [this project](https://github.com/TeamWin/android_device_samsung_kltechnduo). is it considered GA ready?

**Comment by that1** [comment]
Your link leads to a 404 error, so not GA ready. ;)

**Comment by amir-arad** [comment]
It was a public project when I linked to it (a 'works on my machine' github variant)!
