### ISSUE TITLE
swipe slider is not functional on Letv x800+

### ISSUE THREAD

**Issue by vaidosas** [TeamWin/Team-Win-Recovery-Project#632]
the swipe "to do something" is too big and goes out of screen range, so impossible  to make any action. 

![letv x800](https://cloud.githubusercontent.com/assets/18236612/14229208/3d2f3538-f936-11e5-975b-293d2e12d95c.gif)

**Comment by that1** [comment]
If this is an official version of TWRP: which version?
If this is an unofficial build, please contact the person who made it.

**Comment by vaidosas** [comment]
it's version 2.8.7.0. 
How do I know if it's official or not?

**Comment by nailyk-fr** [comment]
If you download twrp [here](https://twrp.me/Devices/) it is an official build. Unofficial otherwise.

**Comment by Dees-Troy** [comment]
I have only made one Letv device official and it didn't start until after 3.0.0 was released. The fact that you are using a Letv device with 2.8.7.0 means that it's unofficial.
