### ISSUE TITLE
TWRP 3.0.1-0 I Can not change userdata partition for my nexus 5 64 gb

### ISSUE THREAD

**Issue by Kapetz2** [TeamWin/Team-Win-Recovery-Project#633]
Please help change partition size too 64gb.
I change flash memory and I can not change the partition USERDATA
How to do it through ADB or terminal?
****imageshack.com/user/Kapetz2

**Comment by nailyk-fr** [comment]
I think after the flash replacement you flash a copy of your old 16Gb flash in the new one. 
So your old [GPT header](https://en.wikipedia.org/wiki/GUID_Partition_Table) (which show 16Gb available) is written on the 64. 
You should change the disk size in your GPT before growing your partition and everything goes fine. 
I think it is not related with twrp development.

**Comment by Kapetz2** [comment]
I need a TWRP integrated with GDISK ( Alcatel One Touch Idol 3, it has  twrp-2.8.7.0-idol3-6039y-with-gdisk.img)
http://x-touch.ru/3526-uvelichivaem-pamyat-v-alcatel-one-touch-idol-3.html
Please make TWRP with the function GDISK to NEXUS5

**Comment by that1** [comment]
There's a "resize" button somewhat hidden in the "Advanced Wipe" menu that will resize the filesystem to the containing partition.

**Comment by Dees-Troy** [comment]
The Nexus 5 is only available in 16 and 32GB variants. There were rumors of a 64GB model, but AFAIK it was never released. If the resize button in TWRP doesn't work for what you need, then I'm sorry, you're on your own. Good luck.

**Comment by Kapetz2** [comment]
#
![img_20160324_214025](https://cloud.githubusercontent.com/assets/18243781/14396719/e73c3e5e-fde1-11e5-92b4-697f3da78e16.jpg)
![img_20160324_180509](https://cloud.githubusercontent.com/assets/18243781/14396743/06f77b46-fde2-11e5-98dd-fdfe01db4bc4.jpg)
![img_20160324_205427](https://cloud.githubusercontent.com/assets/18243781/14396769/2536501e-fde2-11e5-8d71-9f5147b601dc.jpg)
![img_20160325_081607](https://cloud.githubusercontent.com/assets/18243781/14396800/5b2f4b8a-fde2-11e5-97ad-2f1ddf6f04ee.jpg)
I myself made a 64 GB!
Through reсowery - resize fails (Since the partition size is not changed!)

Why do not you want to add a function to fdisk the Nexus 5, so that I could  one according to the instructions:
http://x-touch.ru/3526-uvelichivaem-pamyat-v-alcatel-one-touch-idol-3.html

**Comment by Kapetz2** [comment]
Sorry , I need GDISK

**Comment by that1** [comment]
You could probably extract the gdisk binary from that unofficial TWRP image, then adb push it to your device running TWRP, chmod 777, and run it from the terminal or adb shell.

**Comment by Kapetz2** [comment]
please help me, I do not know how to do it

**Comment by 459below** [comment]
I got this issue as a Google result, thusly I want to add my two cents. [fdisk does understand GPT nowadays](http://man7.org/linux/man-pages/man8/fdisk.8.html), thusly one is able to modify GPTs in TWRP using **f**disk.

```
~ # fdisk -l /dev/block/mmcblk0
Found valid GPT with protective MBR; using GPT

Disk /dev/block/mmcblk0: 30777344 sectors, 2740M
Logical sector size: 512
Disk identifier (GUID): REDACTED
Partition table holds up to 128 entries
First usable sector is 34, last usable sector is 30777310

Number  Start (sector)    End (sector)  Size       Code  Name
   1            8192           38911       15.0M   0700  apnhlos
   2           38912          156543       57.4M   0700  modem
   3          156544          157567        512K   0700  sbl1
   4          157568          157695       65536   0700  dbi
   5          157696          157759       32768   0700  ddr
   6          157760          161855       2048K   0700  aboot
   7          161856          162879        512K   0700  rpm
   8          162880          163903        512K   0700  tz
   9          163904          170047       3072K   0700  fsg
  10          170048          184319       7136K   0700  pad
  11          184320          204799       10.0M   0700  param
  12          204800          233471       14.0M   0700  efs
  13          233472          239615       3072K   0700  modemst1
  14          239616          245759       3072K   0700  modemst2
  15          245760          272383       13.0M   0700  boot
  16          272384          303103       15.0M   0700  recovery
  17          303104          329727       13.0M   0700  fota
  18          329728          344045       7159K   0700  backup
  19          344046          344047        1024   0700  fsc
  20          344048          344063        8192   0700  ssd
  21          344064          360447       8192K   0700  persist
  22          360448          378879       9216K   0700  persdata
  23          378880         5498879       2500M   0700  system
  24         5498880         5908479        200M   0700  cache
  25         5908480         5928959       10.0M   0700  hidden
  26         5928960        30777303       11.8G   0700  userdata
```
