### ISSUE TITLE
File Manager gets stuck after deleting or moving a folder

### ISSUE THREAD

**Issue by seanparmelee** [TeamWin/Team-Win-Recovery-Project#64]
After moving or deleting a folder, the File Manager is unable to navigate anywhere. The only way I was able to use the File Manager again was to reboot the recovery.

I'm using TWRP v2.3.2.1 on a Verizon Galaxy Nexus (toro).

**Comment by Dees-Troy** [comment]
This will be fixed in our next release. Thanks for reporting it:
http://review.teamw.in/#/c/442/
