### ISSUE TITLE
TWRP 3.0.2 (and 3.0.1) for D855 aren't released

### ISSUE THREAD

**Issue by DavisNT** [TeamWin/Team-Win-Recovery-Project#649]
If I look inside download section for LG G3 D855 on TWRP website (the same happens on TWRP installer app): https://dl.twrp.me/d855/ 
I don't see version 3.0.2 (nor 3.0.1, nor some 2.8.7 versions).

According to https://jenkins.twrp.me/job/d855-prod/6/console the D855 was built on April 4 but was not uploaded to the TWRP website (there are errors like `ssh: connect to host twrp.me port 22: Connection timed out` near the end of the output). 
As this has happened several times I assume other devices might be affected as well.

Was this something intentional?
If not, would it be possible to fix the issue and re-run 3.0.2 build(s)?

**Comment by raoulbhatia** [comment]
I'd like to see this build too.

**Comment by gitflo** [comment]
Same here...

**Comment by raoulbhatia** [comment]
Any chance to get this accomplished?

**Comment by lazyfatmeow** [comment]
still no 3.0.2 version

**Comment by 71** [comment]
There's always the [unofficial modified TWRP 3.0.2-0](http://forum.xda-developers.com/lg-g3/development/recovery-twrp-3-0-0-0-t3309475) if you want. You're free to trust the dev or not. Personally, I had no issue whatsoever with the modified version.

**Comment by lazyfatmeow** [comment]
Yes, But I see some feedback about bugs in that thread so I want official build to more stable :)

**Comment by lambdaupb** [comment]
I see 3.0.2.0 now on the download page. Maybe this can be closed ?

**Comment by lazyfatmeow** [comment]
Ok. **twrp-3.0.2-0-d855.img** available now on the download page.
https://dl.twrp.me/d855/

**Comment by raoulbhatia** [comment]
Thanks! Will try the new version soon. Cheers

**Comment by synace** [comment]
@lazyfatmeow same issue on d850 could you give that one some love as well? thanks!

**Comment by lazyfatmeow** [comment]
@synace oh. sorry. I'm not dev. I'm just user who is waiting a official build like you.
You can create another issue report to d850

**Comment by synace** [comment]
@invisiblek not sure if you have a hand in packaging, looks like you were the latest on the changelogs for these particular devices prior to github.

**Comment by synace** [comment]
thanks goes to @bigbiff for re-running d850 and d851, d852, d852g

https://jenkins.twrp.me/user/bigbiff/builds

https://dl.twrp.me/d850/

sadly, decryption not prompting.

ticket can be closed though

**Comment by synace** [comment]
@Dees-Troy this ticket can be closed.
