### ISSUE TITLE
No option to forget decrypt password

### ISSUE THREAD

**Issue by endlesslight0** [TeamWin/Team-Win-Recovery-Project#652]
I've just read  faq/securetwrp.html and I have a question.
My device is encrypted. When I first time setup twrp (3.0) it asked me for password (or passphrase) used to decrypt the device. 
Now each time I get into recovery it doesn't ask me for the password. It decrypts the partitions automatically and if I connect the phone via usb to a PC(while in recovery), all the data is readable.
Can you add an option(no need to make it default) to not remember the password and ask for it at each recovery boot?
Otherwise, I see no meaning in my device(nexus 5x) being encrypted.

I don't care if somebody steals my device, wipes the data, flashes other ROM and resells it.
But I do mind that my data is too easily accessible via recovery.

**Comment by that1** [comment]
TWRP does not store the password. Are you sure you have a lock screen password or pattern enabled in Android?

**Comment by endlesslight0** [comment]
I enter the lock screen password each time I boot into system.

**Comment by Dees-Troy** [comment]
In Android 5.0 and higher, whenever you set or change your lockscreen password, Android asks you if you want to require your password during boot. If you say no, then Android changes your password to "default_password" which means that both TWRP and Android can decrypt your device without prompting you for a password. This is not a TWRP issue.

**Comment by endlesslight0** [comment]
Many thanks.
For anyone who has the same noob question as I did, looks like I found a solution today.
To change the password manually: 
`# vdc cryptfs changepw password current_password new_password`

The lock screen password remained the same. But now it asks me for a password (new_password) during boot.
TWRP now also asks for decrypt password every time.
