### ISSUE TITLE
[3.0.2-0] Unable to decrypt in NPC91K on nexus 5x

### ISSUE THREAD

**Issue by punkeroso** [TeamWin/Team-Win-Recovery-Project#666]
Flashed latest developer preview 2 NPC91K and TWRP is unable to decrypt anymore.
Doesn't matter if the password is wrong, after hitting return no message is given and the only way to do something is restart the phone.

Let me know if you need more information.

**Comment by Dees-Troy** [comment]
We don't support developer previews. Sorry.
