### ISSUE TITLE
Build failed (linker)

### ISSUE THREAD

**Issue by paulobrien** [TeamWin/Team-Win-Recovery-Project#668]
I am trying to compile TWRP for a new device and I am getting the following error, compiling on Ubuntu 16.04:

`make: *** No rule to make target '/media/psf/SSHD/omni/out/target/product/hwplk/system/bin/linker', needed by '/media/psf/SSHD/omni/out/target/product/hwplk/obj/SHARED_LIBRARIES/libbmlutils_intermediates/teamwin'. Stop.`

I'm completely stumped so any advice would be much appreciated. Thanks.

**Comment by paulobrien** [comment]
Rebuilt from scratch and problem has disappeared. Hmmm. Closing issue.

**Comment by scyllarusllc** [comment]
Please, same problem with me, how to "Rebuilt from scratch"?

**Comment by ElXreno** [comment]
> Rebuilt from scratch and problem has disappeared. Hmmm. Closing issue.

How to "Rebuilt from scratch"?
