### ISSUE TITLE
TWRP too big to fit into boot partition

### ISSUE THREAD

**Issue by Technohacker** [TeamWin/Team-Win-Recovery-Project#670]
Hey team,
I was building TWRP 3.0 for the Samsung Galaxy SL GT-I9003.
Unfortunately, it won't fit in the boot partition with the normal ramdisk and kernel (It's 8MB in the boot partition). TWRP 2.8.7.0 would fit (7.8MB boot.img)

Is there any way i could make TWRP 3 fit into my phone's boot partition? I know I'm asking for a lot but please do help.

Thanks in advance! :)

**Comment by that1** [comment]
TWRP 3 should be similar or even smaller than 2.8.7. The usual methods to make it fit:
- use LZMA or XZ compression on kernel and ramdisk
- remove features (e.g. partitioning or encryption)
- build a smaller kernel (remove networking, sound, drivers, etc. from the kernel config)

**Comment by Technohacker** [comment]
Thanks for the reply :)

1) Kernel's compressed using XZ and is 2.6MB
2) The previous device maintainer removed all possible features
3) I guess this is as small as I think I can get it. I have to balance between kernel size and system partition usage as well

P.S. The current bootstrap's compressed using gz (where the boot.img would reach maybe 8.5MB approx.). When i tried xz, it shrank drastically to 5.6MB but did not work properly. Any suggestions?

P.S. If you need to check my device's source, it's on [https://github.com/Technohacker/android_device_samsung_galaxysl](url) branch n-3.0

**Comment by that1** [comment]
I remember some discussion of non-gzip ramdisks failing on certain Samsung devices. Apparently your init is a shell script anyway, so you might succeed if you pack /sbin with xz first, add an un-xz step into your init script, then pack the whole thing with gzip.

**Comment by Technohacker** [comment]
Hmm... I'll check that out... Thanks :)

**Comment by Technohacker** [comment]
ok so your method works pretty much..... boot.img is 7.4MB so it fits in the boot partition. All i need to do now is fix the init script (which keeps bootlooping in my face). Thanks again :)

**Comment by ghost** [comment]
@Technohacker 
**YOUR TITLE = TWRP too big to fit into boot partition**

thing is that TWRP belongs to the recovery partition not the boot partition, cannot work like this

**Comment by Technohacker** [comment]
@magnamentis My device is made by Samsung. Most Samsung devices (including mine) put the recovery as a ramdisk in the boot partition rather than as a separate partition

**Comment by ghost** [comment]
hi @Technohacker 

true that, i myself have to GS an 2 G-Notes, mostly the recovery comes with the kernel pre-installed and somehow it evaded me that you are on a samsung device. thanks for the clarification :-)

would have been too easy and to be honest, i was reading further down and was wondering why no-one wrote something of the kind i did LOL, now i know why.

**Comment by Technohacker** [comment]
@magnamentis you're welcome :D

**Comment by Technohacker** [comment]
Some fixes to my init script and TWRP boots perfectly. Closing this now :)

**Comment by bgman111111** [comment]
please help i too se ethe sme issue

**Comment by 1Jesper1** [comment]
> please help i too se ethe sme issue

Maybe try https://github.com/TeamWin/android_device_samsung_hlltexx/blob/86bfcde2bbd8da847bbc18200b0b0333b57b8a71/custombootimg.mk#L12 or https://github.com/Technohacker/android_device_samsung_galaxysl/commit/b0e801bbcd6bdf31ea701d3a9ee6960027904c55
