### ISSUE TITLE
Zenfone Selfie reboot loop after flashing recovery

### ISSUE THREAD

**Issue by dantependragon** [TeamWin/Team-Win-Recovery-Project#673]
Hello, i´ve tryed to flash the recovery mode to the TWRP recovery mode in my zenfone selfie (Z00UD). 
i´ve installed the drivers, and ADB was seeing the device. After entering the ADB command to flash the recovery, my zenfone rebooted and got into a loop: it starts, vibrates and when it shows the ASUS logo it reboots again and so on.
i cannot enter in recovery, but i am able to enter in fastboot mode, however, the ADB do not recognize the device anymore.

Is there any solution for this?

**Comment by Dees-Troy** [comment]
The Zenfone Selfie does not have official TWRP support. We do not support unofficial devices. Sorry.
