### ISSUE TITLE
TWRP changes the type of "data" partition from ext4 to ext3

### ISSUE THREAD

**Issue by ifurnadjiev** [TeamWin/Team-Win-Recovery-Project#68]
I have HTC One X International (Endeavoru) updated to JB 4.1.1 (stock ROM). My "data" partition is in ext4, but when I make a backup with TWRP 2.3.1.0 it creates a file "data.ext3.win". Here is the recovery.log - http://pastebin.com/J2Kea5fM
Suspicions lines:
...
I:Processing '/data'
I:'/data' was 'ext4' now set to 'ext3' 
...

**Comment by Dees-Troy** [comment]
TWRP is not changing your data partition to ext3. We use a busybox utility called blkid to determine what file system is in use and blkid is saying that your /data partition is formatted to ext3 and not ext4.
