### ISSUE TITLE
Restore of system partiton failing on LG LS670 on 2.3.2.3

### ISSUE THREAD

**Issue by thekraven** [TeamWin/Team-Win-Recovery-Project#69]
The restore of of system partiition has not been working on any of the 2.3.x.x versions.  2.3.2.3 made backups do restore fine on 2.2.2.1.  

Log of failed restore on 2.3.2.3
http://pastebin.com/HxQCK3wJ

Log of successful restore on 2.2.2.1
http://pastebin.com/BENCCnTg

**Comment by Dees-Troy** [comment]
This commit should fix it. Let me know if it doesn't.
https://github.com/TeamWin/Team-Win-Recovery-Project/commit/2204203a949234ceb652b1236c89837405d8fe5f

**Comment by thekraven** [comment]
Thank you, that commit fixed my issue.
