### ISSUE TITLE
How does TWRP detect that you have no OS installed?

### ISSUE THREAD

**Issue by TheComputerGuy96** [TeamWin/Team-Win-Recovery-Project#690]
Point at the code lines that do that sort of thing

**Comment by ttimz1313** [comment]
I got it fixed it was a glitch that you tell me it was there then it wasn't
there how was it still working you tell much.... Lol

**Comment by TheComputerGuy96** [comment]
TWRP still detected that, but my ROM is fully booted 😱

**Comment by TheComputerGuy96** [comment]
Nevermind, I got it fixed 👍
