### ISSUE TITLE
Problema al instalar el TWRP del LG G4 H815 (Problem to install TWRP LG G4 H815)

### ISSUE THREAD

**Issue by RALUNTITLED** [TeamWin/Team-Win-Recovery-Project#691]
No arranca el TWRP para la versión LG G4 H815 https://twrp.me/devices/lgg4h815.html

He conseguido instalar el TWRP del H811 https://twrp.me/devices/lgg4h811.html, pero la que necesito es la del H815.

Gracias

Not boot TWRP for LG G4 version H815 https://twrp.me/devices/lgg4h815.html

I succeed to install the TWRP H811 version https://twrp.me/devices/lgg4h811.html, but I need H815.

Thank you

**Comment by steadfasterX** [comment]
Try the latest version. If this doesnt work go to the official TWRP thread and use the latest BETA.

**Comment by steadfasterX** [comment]
@bigbiff pls close (missing feedback)

**Comment by bigbiff** [comment]
Thanks, closing.
