### ISSUE TITLE
should a list of selected ZIP files

### ISSUE THREAD

**Issue by 0rt** [TeamWin/Team-Win-Recovery-Project#7]
I like the big button of TWRP2 , but unfortunately, it's not the case when selecting zip file... the fonts of files name is too small in my Galaxy Nexus.

When you select a incorrect zip file by mistake, there are no easy way to cancel it, in fact, there are no easy way to check out which zip files you've selected, it should be improved.

**Comment by Dees-Troy** [comment]
I increased the spacing on the 720x1280 layout in the file selectors.  Also, the back button cancels adding a zip and there's a message on the confirmation page that says that the back button cancels the zip.
