### ISSUE TITLE
Extreme battery drain when backing up

### ISSUE THREAD

**Issue by cwappy** [TeamWin/Team-Win-Recovery-Project#70]
I have a Nexus 4 running TWRP 2.3.2.3.  If my battery is under, say, 70% when starting a backup, it will crash to a blank screen after about 30 seconds.  I have to plug it into a wall charger and wait for the battery to go up a bit before it will boot into Android.  At that point it shows 0-1% battery.

If I have 80-90% battery when starting, it will complete the backup.

One time I just rebooted into TWRP without doing anything and the battery indicator showed around a 50% drop from what it had shown in Android.  When I rebooted back into Android, it showed the same thing.

It's like TWRP is doing something to drain my battery VERY quickly.  I can't imagine what that would be however.  I should note that using TWRP is the only time I've noticed my battery drain like this.

I have more details, including screenshots of the battery screen, here:
http://forum.xda-developers.com/showthread.php?t=2047453

**Comment by Dees-Troy** [comment]
The 2.3.3.2 build for the Nexus 4 downclocks the CPU cores to 1GHz and uses Bricked kernel with built-in thermal management which should help the heat and battery drain issues on the N4.
