### ISSUE TITLE
Stuck on TeamWin screen

### ISSUE THREAD

**Issue by DuoDex** [TeamWin/Team-Win-Recovery-Project#718]
Just found myself completely stuck on the Teamwin screen...power button does nothing, holding power button+volume down does nothing....

Phone: HTC One A9
TWRP version - 3.0.2-0

EDIT: Screen just timed out and now my phone will not start. Have I bricked it? If I plug in my charging cord the light will still come on, though.

**Comment by CaptainThrowback** [comment]
Hold Power+Volume Up, not Volume Down.
