### ISSUE TITLE
[klte - 3.0.2-2] Can't mount 128 GB extSD

### ISSUE THREAD

**Issue by ScratMan** [TeamWin/Team-Win-Recovery-Project#721]
Hi,
Using TWRP 3.0.2-2 on my SM-G900F (Samsung Galaxy S5, klte), my Lexar 128 GB sd card is not recognized in recovery. I can't mount it, so I can't use it ; but it works with a Lexar 32GB card.
The 128GB card works perfectly well in Android and on PC.

After downgrading recovery to TWRP 3.0.2-0, now both 32GB and 128GB cards are working in TWRP.

**Comment by SoWhy** [comment]
I have the same issue with my Samsung 128 GB sd card on my LG G5 (H850) runnijng TWRP 3.0.2.0. 64 GB card works as expected.

 Had the issue as well on my old LG G3 (D855) running  TWRP 2.8.7.0

**Comment by younggunna777** [comment]
Same problem here on kltvzw. Just had to downgrade to 3.0.2.0 before it would read my SD card

**Comment by emk2203** [comment]
Issue remains on lte03lte with TWRP 3.1.1. 128 GB is not usable. Would it be better to open a bug report elsewhere since this is klte?
