### ISSUE TITLE
twrp-3.0.2-1-kltechn: Failed to restore Modem partition

### ISSUE THREAD

**Issue by laggardkernel** [TeamWin/Team-Win-Recovery-Project#724]
Mldem backup succeeded, but restore failed. I was told this partition(Modem) was read only during restore. Maybe there is some problem about mounting process.

**Comment by samalaxys5** [comment]
Did you solved it?  Because i have the same problem! Pls help

**Comment by myself-69** [comment]
No sorry I've not been able to
