### ISSUE TITLE
No encryption key prompt on i9300

### ISSUE THREAD

**Issue by bcdonadio** [TeamWin/Team-Win-Recovery-Project#73]
I'm not sure if it's restricted to i9300. It simply yields an "E: Unable to mount '/data'" on terminal when starting. Manually mounting produces the same results.

Distro is CyanogenMod 10.1 20121223 nightly.

Thanks.

**Comment by Dees-Troy** [comment]
I posted a build with AOSP decryption support here:
http://forum.xda-developers.com/showpost.php?p=35693138&postcount=188
No one ever got back with me about whether it works though.

**Comment by bcdonadio** [comment]
Flashed this build. Although it asks for the password, it isn't able to decrypt, saying that the password is incorrect.
Thanks.

**Comment by Dees-Troy** [comment]
This will be fixed in our next release.
