### ISSUE TITLE
orscmd seems to be missing

### ISSUE THREAD

**Issue by Evengard** [TeamWin/Team-Win-Recovery-Project#738]
Hello!

Using orscmd to control TWRP from scripts (namely addon.d ones) would be very handy. It is present in the github repository, but I don't see it on the actual device (namely HTC M9 aka himaul, but I guess it's absent on all of them). Can you please add it to the recovery?

**Comment by that1** [comment]
The orscmd binary is called "twrp".

**Comment by Evengard** [comment]
Oh right, didn't knew it. Thank you.
