### ISSUE TITLE
TWRP 3.0.2 for Kenzo lacks the f2fs driver in kernel.

### ISSUE THREAD

**Issue by fff7d1bc** [TeamWin/Team-Win-Recovery-Project#739]
Hi,

It seems that the TWRP 3.0.2 for the Redmi Note 3 Pro (Kenzo) does not have f2fs driver in kernel. The 'f2fs' string is missng from `/proc/filesystems`. Formating partition to f2fs via the GUI of TWRP also results in errors, due to inability to mount the newly created file system.

**Comment by msfjarvis** [comment]
Ask the kenzo maintainer to add it then, TWRP is not responsible for this.

**Comment by msfjarvis** [comment]
I'd also like to mention you need to have both a F2FS supporting kernel and
F2FS flag in the device tree for this to work.
