### ISSUE TITLE
TWRP 2.3.3.0 unable to mount external sd card on TF300T with keyboard

### ISSUE THREAD

**Issue by robertciontos** [TeamWin/Team-Win-Recovery-Project#74]
I have tried in FAT,NTSC but can't mount it,E:Unable to mount  '/external_sdcard'.Any suggestions?

**Comment by Dees-Troy** [comment]
Which sdcard slot are you trying to use? The only slot that's currently supported is the microSD slot.

**Comment by robertciontos** [comment]
I use the asus tf300t dock keyboard sd reader with 8gb A Data SD HC class 6 for ee pc.tried with other sd cards but can't mount it.

**Comment by robertciontos** [comment]
Tried with microSD card in microSD slot and this one is recognised and mounted by TWRP but the SD card from dock keyboard card reader slot is still "invisible".Thanks.

**Comment by Dees-Troy** [comment]
Exactly. At this time the full size SD slot in the keyboard dock is not supported. Right now we're only able to support 2 storage locations. In the future we hope to expand the number of storage locations supported. You could mount the full size SD slot via the command line but I don't know the block device for the full size slot off the top of my head.
