### ISSUE TITLE
Sony Xperia V (tsubasa) is not included in TWRP Manager

### ISSUE THREAD

**Issue by nebrassy** [TeamWin/Team-Win-Recovery-Project#740]
As the title suggests, it's not available in the device menu

**Comment by CaptainThrowback** [comment]
This issue doesn't belong here, as it's not related to TWRP. Please contact the developers of that app at support@jmzsoftware.com so they can resolve your issue.

**Comment by nebrassy** [comment]
Thanks, I was not sure who I should contact as it's not mentioned on TWRP website, but also there is no support thread on XDA, the link on twrp.me doesn't exist
