### ISSUE TITLE
TWRP for Xiaomi Mi Max (helium)

### ISSUE THREAD

**Issue by Feliksas** [TeamWin/Team-Win-Recovery-Project#741]
Greetings,

When will(?) there be a version of TWRP for the Mi Max Snapdragon 652-based device? The variant from hydrigen is unable to decrypt the data partition :(

**Comment by Dees-Troy** [comment]
It will become available when a developer ports it and makes their device tree available to us.

For the record, this isn't the place for requesting TWRP for devices.

**Comment by AnClark** [comment]
Now I have solved the problem of encryption!

**Comment by AnClark** [comment]
@Dees-Troy @Feliksas I have posted my device configuration files on my own Github page.
See here: https://github.com/AnClark/twrp_device_xiaomi_helium
