### ISSUE TITLE
Check_FS_Type() returns the UUID if SD-Card's partition has been created with LABEL

### ISSUE THREAD

**Issue by n0d3** [TeamWin/Team-Win-Recovery-Project#75]
...instead of returning the TYPE. 

For example,
if my sd-ext partition is created with the LABEL "sd-ext" the blkid cmd would have this output :

/dev/block/mmcblk0p2: LABEL="sd-ext" UUID="59aaea38-d680-49a2-ae07-f12089951eb8" TYPE="ext3"

Then the Check_FS_Type() is returning "59aaea38-d680-49a2-ae07-f12089951eb8" as file-system:

I:Processing '/sd-ext'
E:Unknown File System: '59aaea38-d680-49a2-ae07-f12089951eb8'

I tried an other approach by changing the command of blkid:

```
string blkCommand;
blkCommand = "blkid " + Actual_Block_Device + " | rev | cut -d '\"' -f 2 | rev > /tmp/blkidoutput.txt";
system(blkCommand.c_str());
```

This just writes the TYPE of file-system to /tmp/blkidoutput.txt and is a lot easier to return the desired result. I did it like below, but if it could be done in a simpler way that would be even better.

```
char blkOutput[255];
string fstype = "auto";
while (fgets(blkOutput, sizeof(blkOutput), fp) != NULL) {
    blkOutput[strlen(blkOutput) - 1] = '\0';
    fstype = blkOutput;

    if (fstype.size() == 0 || fstype.size() > 8)
        fstype = "auto";

    if (Current_File_System != fstype) {
        LOGI("'%s' was '%s' now set to '%s'\n", Mount_Point.c_str(), Current_File_System.c_str(), fstype.c_str());
        Current_File_System = fstype;
    }
}
fclose(fp);
```

**Comment by Dees-Troy** [comment]
Thanks for submitting this error. I believe that this patch should fix the problem. We have also improved the overall method in our 2.4 code.
http://review.teamw.in/#/c/424/
