### ISSUE TITLE
Error restoring backup "extractTarFork() process ended with ERROR: 255"

### ISSUE THREAD

**Issue by Osiride80** [TeamWin/Team-Win-Recovery-Project#758]
Hi all!

I made a backup of my smartphone Xperia S with custom Android M (nAOSProm-6.0-b09_r43) from TWRP version 3.0.2.0, then I moved it from phone to pc (with Windows 7 pro 64 bit), cause I have to format the phone for a bootloop problem (no viruses found). The backup contains boot, system and data, but only data interest me.
When I try to restore the backup, both full (after Android reinstalled or after  formatted phone) and only data (only after Android reinstalled), I obtain an error: "extractTarFork() process ended with ERROR: 255" and another message is "failed to extract /data//data/com.google.android.gms/lib !!!" in particular, this file is 0 kb (I saw it renaiming .win file in .zip and browsing in relative folder) . Is possible this depends of mooving file from phone to pc and then from pc to phone? I'have read about immutable attributes and I tried also to set "chattr -i data.f2fs.win", but I receive same error (255) in this case too.
I need help cause I would get my data back, please.
I attach two logs, first of backup and second of restore, to undertand the problem better.
Is there a procedure to extrat, for example, data of backuped whatsapp to have it in the same state before backup?
All experiments I made in a copy of the original backup and original has no changes.
I hope in a help of some specialist not to lose my data. Thanks in advance!
[logs.zip](https://github.com/TeamWin/Team-Win-Recovery-Project/files/474155/logs.zip)

**Comment by kushalchauhan98** [comment]
I came across the same problem in my MotoE2(4G-LTE). Turns out that I was not having enough space in the Internal Storage to restore the /data partition. I deleted some music, photos, etc. and voila, it worked.
Hope it helps!

**Comment by shaggyskunk** [comment]
Doesn't really make sense to me that you get error 255 (not enough space) When you are trying to restore what was already on the device - in this case a Nexus 7 2012

**Comment by jeffsf** [comment]
See also #964

**Comment by illumii** [comment]
restore everything except data after finished ,go to mount and unmount data and go to restore and select storage from micro sdcard to internal storage or vice versa and restore only data after that

**Comment by aiamuzz** [comment]
This "extractTarFork() process ended with ERROR: 255" ... has become an thorn ... I just can't seem to be able to restore the last backup ... 

was this issue resolved and has returned for me ? ... I see discussion on this thread dates back to 2018 ... 

2 years down and i am still encountering this issue !

**Comment by bigbiff** [comment]
I am closing this bug, because the error is general and no one posts their debug logs. It could be anything from bad flash, a corrupted tar file, not checking digests on restore, who knows what it is. We are discussing this because people don't give us basic troubleshooting logs and the error system in libtar is too general to help. We welcome help with fixing the more general error messages. However it's hard when only 2 of us handle updating the project compared to the number of users.

Right now our focus is mainly to incorporate Android 10 changes to able to boot and mount the new partition structure and deprecation of libraries in Android 10.

**Comment by aiamuzz** [comment]
> I am closing this bug, because the error is general and no one posts their debug logs. It could be anything from bad flash, a corrupted tar file, not checking digests on restore, who knows what it is. We are discussing this because people don't give us basic troubleshooting logs and the error system in libtar is too general to help. We welcome help with fixing the more general error messages. However it's hard when only 2 of us handle updating the project compared to the number of users.
> 
> Right now our focus is mainly to incorporate Android 10 changes to able to boot and mount the new partition structure and deprecation of libraries in Android 10.

@bigbiff ... i understand ... i didn't know you were only 2 guys active ...

could you let me know what exactly you require ... log files and all ... i still have the backup that failed to restore ... If you are serious about helping me fix it ... i'll post here the relevant information(logs) you require to identify the issue ... but you'll have to provide me a step by step procedure on how to obtain those logs or other information(like the commands) and i'll provide the same to you.

PS : My device is a OnePlus 3T and i am yet to disable the forced encryption on my Oxygen OS 9.0.5 ... so whenever i try to disable i usually end up hanging myself ... and i have to start afresh with a stock ROM flash ... I will grab the specific `logs` or` command outputs` you require to identify this `extractTarFork()` issue

**Comment by aiamuzz** [comment]
> It could be anything from bad flash, a corrupted tar file, not checking digests on restore, who knows what it is.

FYI ... i faced this issue while restoring the system partition backed up and attempted to restore in the same recovery boot ... and it failed with this error !!! ... described the issue in detail here ... https://github.com/TeamWin/Team-Win-Recovery-Project/issues/964#issuecomment-554757001

**Comment by bigbiff** [comment]
> 
> 
> > I am closing this bug, because the error is general and no one posts their debug logs. It could be anything from bad flash, a corrupted tar file, not checking digests on restore, who knows what it is. We are discussing this because people don't give us basic troubleshooting logs and the error system in libtar is too general to help. We welcome help with fixing the more general error messages. However it's hard when only 2 of us handle updating the project compared to the number of users.
> > Right now our focus is mainly to incorporate Android 10 changes to able to boot and mount the new partition structure and deprecation of libraries in Android 10.
> 
> @bigbiff ... i understand ... i didn't know you were only 2 guys active ...
> 
> could you let me know what exactly you require ... log files and all ... i still have the backup that failed to restore ... If you are serious about helping me fix it ... i'll post here the relevant information(logs) you require to identify the issue ... but you'll have to provide me a step by step procedure on how to obtain those logs or other information(like the commands) and i'll provide the same to you.
> 
> PS : My device is a OnePlus 3T and i am yet to disable the forced encryption on my Oxygen OS 9.0.5 ... so whenever i try to disable i usually end up hanging myself ... and i have to start afresh with a stock ROM flash ... I will grab the specific `logs` or` command outputs` you require to identify this `extractTarFork()` issue

If you have the original recovery.log in your backup folder, please post that as well as the recovery.log under /tmp after the restore. You can use adb pull /tmp/recovery.log to get the log.

**Comment by aiamuzz** [comment]
> If you have the original recovery.log in your backup folder, please post that as well as the recovery.log under /tmp after the restore. You can use adb pull /tmp/recovery.log to get the log.

@bigbiff  ... i did run the operation turns out a backup taken on the latest recovery version for my device OnePlus 3T ... Ver. - 3.3.1-0 ... also is exhibiting this error when the /system partition is restored ...

to rule out foul play of the memory card ... i made a backup on my internal storage(as there is no sd card) and a backup over a sdcard using USB-OTG ...

trying to restore both backups failed when /system partition was being restored ... the error shows up after almost 96% - 97% is completed ...

I did save the log files from the TWRP advanced option at the time i didn't pay attention ... but when i opened those log files to post here ... i was surprised to find the recovery log after the failed /system restore was blank 0 KB ... However i have the dmesg log ... would that help ? ...

recovery log is empty ... 
 
please find the demsg.log from the failed /system restore is enclosed ... [failed-dmesg.log](https://github.com/TeamWin/Team-Win-Recovery-Project/files/3870835/failed-dmesg.log)

I also have a log files (dmesg and recovery logs) when the all other partitions(except /system) restored successfully ...

[success-dmesg.log](https://github.com/TeamWin/Team-Win-Recovery-Project/files/3870845/success-dmesg.log)

will comparing the 2 dmesg.log help identify the issue ?

[success-recovery.log](https://github.com/TeamWin/Team-Win-Recovery-Project/files/3870847/success-recovery.log)

**Comment by bigbiff** [comment]
Unfortunately dmesg only shows kernel errors, nothing related to the recovery unless it segfaults. If you can recreate the failed restore, please use adb pull /tmp/recovery.log before rebooting and post the log here.

Actually it may have been your OTG device.
Selinux reports opening a file at 596 seconds into boot.  Twice after that it is kworker is having trouble reading your OTG it seems for over 120 seconds.

[  596.439392] audit: type=1400 audit(1574237084.878:2363): avc:  denied  { open } for  pid=421 comm="recovery" path="/usb_otg/TWRP/BACKUPS/b0830467" dev="sdg1" ino=5 scontext=u:r:recovery:s0 tcontext=u:object_r:vfat:s0 tclass=dir permissive=1
[  597.495578] synaptics,s3320: all finger up
[  600.386846] INFO: task kworker/u8:1:53 blocked for more than 120 seconds.
[  600.386885]       Not tainted 3.18.120-lineageos-g4a67382 #1
[  600.386905] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  600.386926] kworker/u8:1    D ffffffc000087888     0    53      2 0x00000000
[  600.387000] Workqueue: mpm msm_mpm_work_fn
[  600.387028] Call trace:
[  600.387062] [<ffffffc000087888>] __switch_to+0xb8/0xc4
[  600.387095] [<ffffffc001037adc>] __schedule+0x324/0x7fc
[  600.387120] [<ffffffc001037fd8>] schedule+0x24/0x70
[  600.387149] [<ffffffc00103aef8>] schedule_timeout+0x1b8/0x294
[  600.387176] [<ffffffc001038f1c>] wait_for_common+0xbc/0x174
[  600.387200] [<ffffffc001039118>] wait_for_completion+0x14/0x1c
[  600.387225] [<ffffffc0004e6104>] msm_mpm_work_fn+0x34/0xa8
[  600.387248] [<ffffffc0000c10a8>] process_one_work+0x160/0x480
[  600.387270] [<ffffffc0000c1508>] worker_thread+0x140/0x478
[  600.387295] [<ffffffc0000c6ee0>] kthread+0xd8/0xec
[  600.387334] INFO: task mdss_dsi_event:146 blocked for more than 120 seconds.
[  600.387354]       Not tainted 3.18.120-lineageos-g4a67382 #1
[  600.387371] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  600.387390] mdss_dsi_event  D ffffffc000087888     0   146      2 0x00000000
[  600.387435] Call trace:
[  600.387462] [<ffffffc000087888>] __switch_to+0xb8/0xc4
[  600.387487] [<ffffffc001037adc>] __schedule+0x324/0x7fc
[  600.387511] [<ffffffc001037fd8>] schedule+0x24/0x70
[  600.387540] [<ffffffc000497280>] dsi_event_thread+0x158/0x2fc
[  600.387564] [<ffffffc0000c6ee0>] kthread+0xd8/0xec
