### ISSUE TITLE
Fix Permissions causes bootloop

### ISSUE THREAD

**Issue by supergaijin-xx** [TeamWin/Team-Win-Recovery-Project#76]
using script version 2.3.3.1 causes bootloop after running "fix permissions" on 2 different i747 sgs3's and one T999 sgs3.  confirmed by two different users.

**Comment by bigbiff** [comment]
Can you post /tmp/recovery.log please?

**Comment by supergaijin-xx** [comment]
I don't see that directory on my phone.  is it only created after recovering from a bootloop and deleted shortly after that?

**Comment by bigbiff** [comment]
Please use adb to pull the log while in recovery.

**Comment by supergaijin-xx** [comment]
ok, I got the logs. I've attached them in a zip, along with a brief description of the actions just before/after each log was recorded.  I also attached an extra log for the other issue I reported, which dees-troy said wasn't an issue, but they seem to have misunderstood my intent about the issue I reported.  I sent an email to give them more information but got no response.  I have attached my response below so you may see what I mean.  I have added a bit more (in parentheses) to elaborate a bit more:

"As you saw in my description, a factory reset "as the phone intended" 
would wipe app data from the internal memory.  A factory reset from 
recovery did not.  (I understand you can also choose to wipe the internal memory separately, but that's not exactly the issue here.)

I did not put all the information regarding the issue in there as I assumed someone would say 
"oh, a noob that doesn't know how to flash, so let's ignore it".  

The
 detail I chose not to put in the message because it may not have been 
100% relevant is that with a certain build of miui, (there was a gps issue, where flashing the newer version over the older version was causing gps to fail completely.)  a factory reset from
 recovery, along with a system format and wiping caches from recovery 
did not fix my issue even after all that and flashing the rom clean.  (even reflashing back to stock did not fix the issue.)
however, after doing all that and finding that it wasn't working, as a 
last resort I tried a factory reset while the phone was running (stock rom), and 
then the rom was working properly.  (I did this same test with the two miui versions, flashing the new after the old without a reset while the phone was running, and gps failed.  a reset with the phone on while using miui worked, just like stock.)  after doing the factory reset with the phone on, I noticed my app 
data from internal memory had been deleted.  Thus the complaint I made, 
so someone could look into why doing a 4-part cleanup (caches, factory 
reset, and system delete) seems to be missing something somewhere on the sgh-747
 s3 that a factory reset while the phone was running WOULD catch.  (this isn't even happening on all sgh-747's, as a developer with the same script version was able to successfully reset his phone without the extra "reset while running" that I had to do.)

Now that I have given all details, which is basically the same as I said in my other
 report, what might be the issue?"

**Comment by bigbiff** [comment]
Hi, we didn't receive your attachment on the github issues tracker. Can you resend it to bigbiff@teamw.in?

**Comment by bigbiff** [comment]
Can you provide a logcat during the bootloop please?

**Comment by supergaijin-xx** [comment]
alright but that'll take a bit, gotta learn a bit more adb for that :p

and I gotta reinstall android sdk, etc., because my hdd had crashed and I had to format it.  I'll have it for you in a couple days or so.

**Comment by supergaijin-xx** [comment]
Hi,

Sorry for the delay.  I've attached the logcat.  It's a bit long because I let it bootloop three times before stopping just in case there might be more than one potential cause for the bootloop.  

Is there any update on the other issue I reported, where wiping the system, etc., doesn't appear to fully format my system properly based on what I reported in detail and got no further response?

Thanks in advance!

**Comment by bigbiff** [comment]
I looked at the logcat you sent and it was missing some class definitions in the rom. TWRP shouldn't cause issues like this unless you were missing important jars in the rom.

**Comment by supergaijin-xx** [comment]
I'll be sending another one from a "stock" rom then, which is only deodexed.  the same thing happens there too.  and what about the other issue I asked about?

**Comment by supergaijin-xx** [comment]
looks like I was mistaken about it being on all roms I've tried.  it must be just a miui thing, caused by any version of miui from either the us or android version.  thanks for helping me find what the issue was!
