### ISSUE TITLE
TWRP does NOT encrypt the actual data!!!

### ISSUE THREAD

**Issue by xdevs23** [TeamWin/Team-Win-Recovery-Project#762]
I made a backup with the encryption turned on.
I thought my data would be safe as it would be encrypted.

But I can extract the backup on my computer simply using tar.

And the data is NOT corrupted. It just works.

Of course you might be thinking that I somehow did not turn on encryption.

But I did as TWRP asks me for the password whenever I want to restore it on my device over TWRP.

So why don't you guys let TWRP completely (or at least at file-basis) encrypt the data instead of just preventing the user to enter the restore section of twrp by a password? Is that how encryption works?

Please fix this, thx.

**Edit:**

And if the data is encrypted, but apps are not, please add that.
I want everything to be encrypted.

**Comment by Dees-Troy** [comment]
Encryption takes a long time on most devices, so we don't encrypt all of the backup. Instead, we encrypt the portion of the backup that contains app data and other private data. The parts of the data partition that do not contain private data are not encrypted. Also, other partitions such as system and cache are not encrypted.

The encryption that we use is not especially strong, either. If you need strong encryption, then we recommend using an external method to encrypt the backup.

**Comment by xdevs23** [comment]
Can you add a setting to specify whether a full encryption or only a partial encryption (only sensitive data) should be done?
