### ISSUE TITLE
"factory reset" not wiping internal data (internal sd)

### ISSUE THREAD

**Issue by supergaijin-xx** [TeamWin/Team-Win-Recovery-Project#77]
Only encountered on one i747 sgs3 so far.  Wiping all caches, system reset, and factory reset all at once still does not delete data from internal memory.  must do a factory reset while phone is running to get intended effect.  Script version is 2.3.3.1.

**Comment by Dees-Troy** [comment]
If you want to wipe the internal sdcard then use the Format Data option.

**Comment by supergaijin-xx** [comment]
As you saw in my description, a factory reset "as the phone intended" would wipe app data from the internal memory.  A factory reset from recovery did not.  

I did not put all the information regarding the issue in there as I assumed someone would say 
"oh, a noob that doesn't know how to flash, so let's ignore it".  

The detail I chose not to put in the message because it may not have been 100% relevant is that with a certain build of miui, a factory reset from recovery, along with a system format and wiping caches from recovery did not fix my issue even after all that and flashing the rom clean.  however, after doing all that and finding that it wasn't working, as a last resort I tried a factory reset while the phone was running, and then the rom was working properly.  at the same time, I noticed my app data from internal memory had been deleted.  Thus the complaint I made, so someone could look into why doing a 4-part cleanup (caches, factory reset, and system delete) was missing something somewhere on the sgh-747 s3 that a factory reset while the phone was running WOULD catch.

Now that I have given all details, which is basically the same as I said in my other report, what might be the issue?
