### ISSUE TITLE
Adb not authorized after deleting device keys

### ISSUE THREAD

**Issue by vladimiroltean** [TeamWin/Team-Win-Recovery-Project#771]
First of all, I'm using an unofficial build of TWRP 2.8.7 for the Lenovo Yoga Tab 2 830f (x86_64).
The behavior I'm describing might thus not be intended, but I think it's worth a discussion.
Here is my use case: booted into the recovery to do some repartitioning of the internal flash. In the process, "/data/misc/adb/adb_keys" got deleted, along with the whole data partition, in fact.
After a reboot back into recovery, "adb shell" would of course say:

> error: device unauthorized.
> This adb server's $ADB_VENDOR_KEYS is not set
> Try 'adb kill-server' if that seems wrong.
> Otherwise check for a confirmation dialog on your device.

Well, you would think, of course adb is no longer authorized if I deleted the keys, but I think this defeats the whole purpose of a **recovery**: to always be there and run, no matter what's on the target device. So depending on a file to be present on the internal flash seems like a stupid idea, because it cuts access to something critical like adb.
What am I missing?

**Comment by CaptainThrowback** [comment]
Seems like whoever built your recovery didn't build it as -eng. Official builds don't have this problem ;).

**Comment by vladimiroltean** [comment]
And how do the official builds treat this situation, exactly?

**Comment by CaptainThrowback** [comment]
ro.secure=0 & ro.debuggable=1 by default in -eng builds so adb authorization isn't needed.

**Comment by vladimiroltean** [comment]
I've got the same property values in the /default.prop file in the ramdisk.
However, ro.adb.secure=1 for me.
I guess that also has to be a 0?

**Comment by vladimiroltean** [comment]
Compiling as eng solves the problem, thanks.

**Comment by Borromini** [comment]
@vladimiroltean I'm looking for TWRP builds for the Lenovo Yoga Tab 2 Pro (1380L/F), do you happen to have a link, either to a source tarball or to binaries? They seem to have vanished from XDA. Would be very much appreciated!
