### ISSUE TITLE
2 question on android 7

### ISSUE THREAD

**Issue by adamchen233** [TeamWin/Team-Win-Recovery-Project#776]
hello gays, I have two questions:
1. I flash TWRP to my phone(nexus 6, android 7, NBD90Z) when the phone in bootloader mode, and i can enter TWRP mode but it returned to custom recovery when i reboot. The way you noticed in the tutorial didn`t work, Is it normal in the phone with android 7?

2.i want to move\chmod some files in the system partition, but my phone is no root(for some reasons```).So i want to use the file manage in the TWRP. But it is strange that my change only works in the TWRP mode.

I means ,for an example, i move a file from system partition to Sdcard\Download, it did move. I can find the file everytime i enter TWRP. BUT, it disappeared when i enter the phone OS and want to find the file in es explorer.
Do you have any ideas about that? Are there some connections between the two questions?

Thanksssssssssss!!!!!!!!!

**Comment by czarsuperstar** [comment]
If it isn't seen in  es file explorer you have to give es root permission and click showing hidden files. You have to be root for that. How was you able to use TWRP manager without root? But es won't show certain files unless granted root permission to view hidden files.

**Comment by czarsuperstar** [comment]
Also sometimes files will not show up right away unless you exit the app. I exit es file explorer by tapping back button until it exits

**Comment by adamchen233** [comment]
The file manage function only works with root? But I just did move the file
successfully and when I enter twrp again, I can find the file I moved last
time. The only trouble is that the change like not happen when I enter
Android OS and want the check the file.
btw, I move the file to the folder - download under sdcard(it's not hidden)
so it don't need the root permission to view in es explorer...

So, do you means, without root the twrp file manage can't work? When I just
move the file without root, it seems everything is going well😂

On Oct 30, 2016 7:08 AM, "Rodney Etienne" notifications@github.com wrote:

If it isn't seen in es file explorer you have to give es root permission
and click showing hidden files. You have to be root for that. How was you
able to use TWRP manager without root? But es won't show certain files
unless granted root permission to view hidden files.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/TeamWin/Team-Win-Recovery-Project/issues/776#issuecomment-257144860,
or mute the thread

**Comment by czarsuperstar** [comment]
No I am saying make sure you exit out of es file explorer. You have to be root if you are entering TWRP recovery.  But like I said you have to exit out of es or try a different file manager or make sure you adb pull the said file on computer and then transfer it like that.
