### ISSUE TITLE
Cannot install TWRP thru gooManager on my HP TP

### ISSUE THREAD

**Issue by avisekhg** [TeamWin/Team-Win-Recovery-Project#78]
## Hi, yesterday I had a horrifying day when I thought of moving over from CWM to TWRP. I never did it before and I saw my friend who was flashing the nightly builds very professionally using TWRP. Hence, I decided to move over to TWRP. I went to gooManager and from the 'Menu' clicked  'Install OpenRecoveryScript'. It did not reboot automatically as it says in the website. Instead, I rebooted myself and saw that 'Boot ClockworkMod' has changed to 'boot TWRP'. I was excited to see that but while selecting it, it gave the following error:

[in blue color]
Selected: 'boot TWRP'

Loading '/boot/uImage.TWRP'... OK
Checking uImage... Invalid Size

[in Red color]
BOOT FAILED!
## Press SELECT to continue

I tried many things reading through different forums but to no avail. I even tried CWM back again but nothing happened. Finally, I decided to uninstall everything thru ACMEUninstaller and uninstalled everything and reinstalled from the scratch. Then restored my backup from 12.26.

What might have been the problem? Is there any bug on 2.3.3? Should I try 'Install OpenRecoveryScript' again?

**Comment by Dees-Troy** [comment]
This may have been a bad download though that shouldn't happen with GooManager as it's supposed to check the MD5 before finishing the installation. It's possible that your boot partition didn't have enough room for TWRP as well.  There's instructions on our website that you can use to perform a manual installation:

http://teamw.in/project/twrp2/75
