### ISSUE TITLE
TWRP Open G Apps Aroma

### ISSUE THREAD

**Issue by Josar** [TeamWin/Team-Win-Recovery-Project#785]
When installing gapps with the aroma graphical installer the cmd line output of TRWP is not cleared and choosing the packages is hard to manage, because there is the old output and the package selector overlapping.

Used : TWRP 3.0.2-0, Motorola G falcon umts, CM13, open gapps 6.0 aroma

**Comment by Dees-Troy** [comment]
This is an aroma issue, not a TWRP issue.
