### ISSUE TITLE
TWRP recovery loop h815

### ISSUE THREAD

**Issue by 4maself** [TeamWin/Team-Win-Recovery-Project#795]
When i tried to update my phone (LG G4 latest CM14 update (12-01-2016)), using the OTA, it got stuck in the TWRP Recovery. I've seen some people being able to fix this using the terminal using these commands:
dd if=/dev/zero of=/dev/block/platform/msm_sdcc.1/by-name/fota and
dd if=/dev/zero of=/dev/block/platform/msm_sdcc.1/by-name/misc

But since these aren't located on my device, it doesn't work for me. Is there any way to fix this?

**Comment by steadfasterX** [comment]
yes. use the latest version. if this doesn't work for you go into the official TWRP thread and download the latest BETA from there.

@bigbiff pls close
