### ISSUE TITLE
No decryption with Cyanogenmod 10.1 and TWRT 2.3.3.0. Can I mount with Terminal Emulator?

### ISSUE THREAD

**Issue by pauljamesharper** [TeamWin/Team-Win-Recovery-Project#80]
I don't get a decrypt prompt while using Cyanogenmod 10.1 and TWRT 2.3.3.0 on a Samsung Galaxy SIII.

I encrypted using Cyanogenmod. 

Is there a way I can mount with the Terminal Emulator?

**Comment by Dees-Troy** [comment]
Our next release of TWRP for SGS3 devices will include decryption for both AOSP (CM) and Samsung's own customized encryption from a TouchWiz ROM.
