### ISSUE TITLE
TWRP   Wiko SUNNY 

### ISSUE THREAD

**Issue by DesCoene** [TeamWin/Team-Win-Recovery-Project#810]
https://www.dropbox.com/s/63zpsndn1k0k5lu/MT6580_Android_scatter.txt?dl=0[](url)
this is the scatter file of the TWRP recovery , but the phone doesn´t boots in recovery, something must be wrong with it,
Android 6.0 marshmallow
mt6580 
chipset nr:  0x0000ca00
EXT_26M
DRAM
RAM Size 0x20000000

[[Hovatek] TWRP for Wiko Sunny.zip](https://github.com/TeamWin/Team-Win-Recovery-Project/files/665098/Hovatek.TWRP.for.Wiko.Sunny.zip)

if possible can you guys check these out so they could work on my phone please?

Many, many thanks

Sincerely

**Comment by Dees-Troy** [comment]
This is not a place to request a recovery for a device. We also cannot support unofficial devices.

**Comment by htmlo** [comment]
Does it work in wiko sunny max ??
