### ISSUE TITLE
BAD signature from "TeamWin <admin@teamw.in>"

### ISSUE THREAD

**Issue by edouard-lopez** [TeamWin/Team-Win-Recovery-Project#816]
Hi guys, 
I'm trying to verify the [TWRP image for the OnePlus 3T](https://dl.twrp.me/oneplus3t/twrp-3.0.3-0-oneplus3t.img.html) and to my surprise I got a bad signature result. I followd steps from [your FAQ](https://twrp.me/faq/pgpkeys.html):

First I fetch the TWRP file and its signature:
```
wget https://dl.twrp.me/oneplus3t/twrp-3.0.3-0-oneplus3t.img.asc
wget https://dl.twrp.me/oneplus3t/twrp-3.0.3-0-oneplus3t.img
```

Then verify with follow script (see [gist](https://gist.github.com/edouard-lopez/af9698ea355e6bd6ad68ab48b5fa8dba/93f55a80d4653996feb2d26595e915a678f4e991
)):

```
#!/usr/bin/env bash

if (($# == 0)); then
  printf "Usage:\n\t./verify.sh twrp-*.img\n"
else
  file="$1"
  curl --location --output twrp-publickey.asc https://dl.twrp.me/public.asc
  gpg --import twrp-publickey.asc
  gpg --verify "$file"{.asc,}
fi
```

And got this output:
```
./verify.sh twrp-3.0.3-0-oneplus3t.img
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3075  100  3075    0     0   4255      0 --:--:-- --:--:-- --:--:--  4253
gpg: key 891A43DF: "TeamWin <admin@teamw.in>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: Signature made Sat 17 Dec 2016 03:18:08 AM CET using RSA key ID 891A43DF
gpg: BAD signature from "TeamWin <admin@teamw.in>"
```

Could you replicate?

**Comment by edouard-lopez** [comment]
Seems the `curl` or `wget` command I use go to the webpage instead of downloading the `.img`. Manually downloading the file solve the issue

**Comment by nailyk-fr** [comment]
Was answering you but you find before. 
The server doesn't accept curl/wget and only work with cookies afaik. 
If you cat your downloaded file you will get the error page. 
https://github.com/TeamWin/Team-Win-Recovery-Project/issues/625

**Comment by rancidfrog** [comment]
This is silly.
Finally was able to download with curl:
```
curl -e https://dl.twrp.me/polaris/twrp-3.2.3-0-polaris.img.html  -L  -O https://dl.twrp.me/polaris/twrp-3.2.3-0-polaris.img
```
