### ISSUE TITLE
Can't enter TWRP recovery after flashing. Phone just boots normal.

### ISSUE THREAD

**Issue by Maxer95** [TeamWin/Team-Win-Recovery-Project#823]
I have an HTC 10 on Android 7.0. It's rooted with SU installed. I've downloaded and flashed TWRP recovery at least 10 different times using several different methods, each time successfully. But whenever I try to enter recovery mode my phone locks up and eventually just boots into the normal OS.

**Comment by CaptainThrowback** [comment]
Please read the FAQ on the TWRP support thread on XDA.

**Comment by Maxer95** [comment]
Thank you, I found the 3.0.3 unofficial TWRP recovery and it works.
