### ISSUE TITLE
Critical: bootloop after *#*#WIPECACHE#*#*

### ISSUE THREAD

**Issue by siealex** [TeamWin/Team-Win-Recovery-Project#83]
Samsung Galaxy Nexus, TWRP 2.3.3.
After typing _#_#WIPECACHE#_#_ (_#_#947322243#_#_) my phone is stuck with blinking TW logo and can't be booted via bootloader or via ADB in any mode. The only way to boot was... to flash CWM.

**Comment by Dees-Troy** [comment]
This was done on a Galaxy Nexus...

**Comment by ghost** [comment]
Just noticed the same thing on my Nexus 4 (rooted, AOKP, faux kernel, TWRP 2.3.3.2). The solution mentioned here also worked. I flashed CWM Recovery to fix the bootloop, and then reflashed TWRP.

**Comment by Dees-Troy** [comment]
This is the fix:
http://review.teamw.in/#/c/419/

**Comment by siealex** [comment]
When will the fixed version be available for Maguro?
