### ISSUE TITLE
Unable to restore modem from backup on klte

### ISSUE THREAD

**Issue by likeadragonmaid** [TeamWin/Team-Win-Recovery-Project#830]
While restoring a backup, TWRP says that it cannot mount modem, so I tried to mount modem manually but still it gives an error while restoring so I always have to uncheck modem while restoring a backup. Using official TWRP - 3.0.2-2
https://dl.twrp.me/klte/

Device Model: SM-G900W8
Device Name: klte (but build.prop says, kltecan)

**Comment by likeadragonmaid** [comment]
Issue still present on official TWRP - 3.1.0-0
https://dl.twrp.me/klte/

Device Model: SM-G900W8
Device Name: klte (but build.prop says, kltecan)

**Comment by senposage** [comment]
when you use a non stock kernel/recovery the modem and bootloader are set to read only
there is no fixing that thats a samsung feature to prevent idiots from overwriting there bootloaders on dev edition devices 

requesting close!

**Comment by likeadragonmaid** [comment]
Alright

**Comment by likeadragonmaid** [comment]
I researched a bit and look what I found:

https://forum.xda-developers.com/showthread.php?t=2727406&p=71460251#post71460251
https://forum.xda-developers.com/showthread.php?t=2727406&page=99

So, I classify it as a bug...
