### ISSUE TITLE
Can't mount SD on Galaxy Nexus

### ISSUE THREAD

**Issue by siealex** [TeamWin/Team-Win-Recovery-Project#84]
Try to push Mount SD. Nothing happens, and logs say that TWRP tries to mount /usb-otg. Galaxy Nexus, PA 2.99 (4.2.1), TWRP 2.3.3.

**Comment by Dees-Troy** [comment]
The Galaxy Nexus is a Data Media device as per here:
http://teamw.in/DataMedia

The "SD" option that you are referring to is only for USB OTG, a special USB cable plugged into the charging port of your Galaxy Nexus along with a USB thumb drive. It won't work unless you have a USB OTG setup plugged in at the time.

**Comment by siealex** [comment]
And how to mount /data/media? I do not see /sdcard via adb.
