### ISSUE TITLE
TWRP touch screen no response on Xiaomi MIX

### ISSUE THREAD

**Issue by Maziak2520** [TeamWin/Team-Win-Recovery-Project#843]
I did lithium version (all three ) as described here.. 
I'm sort of suspecting newer devices might not be supported.. Phone bought in December in China. 
https://twrp.me/devices/xiaomimimix.html
https://dl.twrp.me/lithium/
https://github.com/TeamWin/android_device_xiaomi_lithium
https://forum.xda-developers.com/mi-mix/development/recovery-official-twrp-xiaomi-mi-mix-t3498960

**Comment by ganlub** [comment]
Same here, after some restarts it starts working.

**Comment by Maziak2520** [comment]
Correct. several start over and it worked.

**Comment by ganlub** [comment]
@Maziak2520 I'm glad it worked! But keep the issue open so it can be fixed, because it's still randomly happening and it doesn't work unless you reboot several times.

**Comment by amtlib-dot-dll** [comment]
Please re-open this issue thanks, because it does not work at all on my MIX no matter how I reboot it.

**Comment by Maziak2520** [comment]
There's modified version that works fine now.. I found it while searching for nougat for Xiaomi mix.. IT has a name twrp.img, it's from 28.1.2017 and file size 28831744..

**Comment by amtlib-dot-dll** [comment]
@Maziak2520 Thanks but how can we download it?

**Comment by Maziak2520** [comment]
UTFG ?

**Comment by amtlib-dot-dll** [comment]
@Maziak2520 Sorry but I do not understand what UTFG is :joy:

**Comment by Maziak2520** [comment]
use the fine google :-)

**Comment by amtlib-dot-dll** [comment]
Well I did these:
1. Flash MIUI V8.0.8.0.MAHCNDI
2. Flash twrp-3.0.2-0-lithium.img
3. Since the TWRP is touchable now, flash latest MIUI, as well as latest Lineage OS
According to http://www.miui.com/forum.php?mod=viewthread&tid=6603676. 毕竟这是中国系统，用户应当有一定阅读中文的能力。
