### ISSUE TITLE
Can't reboot to system after OTA (ether)

### ISSUE THREAD

**Issue by lister-wrt** [TeamWin/Team-Win-Recovery-Project#844]
Every time I attempt an OTA update (LineageOS/CM) I cannot boot back to system. When I attempt it the device just boots back to TWRP. Tried booting to system from the bootloader as well, same result.

Googling the issue has lead me to these pages;

http://androidforums.com/threads/twrp-bootloop-fix-after-update-ota.922585/
https://forum.xda-developers.com/showthread.php?t=2451696

This fix doesn't work on my device as the directory doesn't exist. 

I have also experienced this issue on mako, though I didn't attempt these fixes.

This report is at the suggestion of others who say it is a TWRP issue, not LineageOS/CM.

**Comment by treuss** [comment]
Same here - I can confirm this with my **Mako** device.
The first time I ran into this bug was in CM14 and it still effects me now in Lineage 14.1

**Comment by lister-wrt** [comment]
3.0.3-0-ether appeared not long after this commit;

https://github.com/TeamWin/android_device_nextbit_ether/commit/57f8938696e2a54d519493428cf30c747351b0da

It appears to address this issue on ether, though I haven't had a chance to test it yet. Thank you @javelinanddart and @Dees-Troy

**Comment by treuss** [comment]
Excellent! \O/

**Comment by javelinanddart** [comment]
Yea, that commit is supposed to fix the OTA issue with ether. I haven't been able to test it because I roll my own builds and I don't use OTAs.

**Comment by spacemanskip** [comment]
@lister-wrt would you mind explaining (for a noob) what I should do with that link to 3.0.3-0-ether?

I looked at the page it leads to and am not sure what to do with the information. (sorry, I"m pretty new to this).

**Comment by lister-wrt** [comment]
@spacemanskip use the latest twrp image. This issue is ancient.

https://dl.twrp.me/ether
