### ISSUE TITLE
Daylight savings setting

### ISSUE THREAD

**Issue by patrickli** [TeamWin/Team-Win-Recovery-Project#85]
Hi there,

I just started to use TWRP on my international SGS3 and it is great.

I went into settings and tried to set the correct timezone. I live in New Zealand which is GMT+12, with daylight savings in effect it should be GMT+13. However I ticked daylight savings checkbox but the time is still 1 hour off. The adjustments options only have 15, 30 and 45 minutes, but I need 1 hour.

Is this a bug or something I did wrong?

Thanks.

**Comment by Dees-Troy** [comment]
Some devices like SGS3 don't properly save the date/time to the Real-Time Clock. Since the RTC isn't working properly the time and date in recovery is always wrong. The CM team attempted to fix this but shortly after they started testing the fix they found that they lost Internet connection on their devices, so they decided that this issue was unfixable. Sorry.

**Comment by toxicbubble** [comment]
Not sure if I need to create a new issue or if this one could be reopened, but I disagree with the diagnosis of this issue. Tested on latest 3.0.0.1 on a Nexus 6p and it was definitely the same under earlier versions of TWRP on my Nexus 5. Are these two phones both subject to the same issue as the SGS3 already mentioned?

Changing the "Use daylight savings time (DST)" checkbox in TWRP correctly changes the timezone displayed at the bottom, but the same offset of +12 is applied regardless of the timezone selected. If the phones Real-Time Clock time is off, I would still expect to see the daylight savings time checkbox change the displayed time by an hour, but it makes no difference. The time displayed in TWRP is correct for the half of the year where DST is not observed (GMT +12).

Two screenshots showing that despite the current timezone being altered to DST/ non-DST, the same time is displayed. The time displayed by the clock is in TWRP is GMT+12, 1 hour behind the actual local time of 12:11 at the time of the screenshots.
![screenshot_2016-03-16-11-11-57](https://cloud.githubusercontent.com/assets/13129267/13797313/7a709ad6-eb71-11e5-97ec-4189e455b388.png)
![screenshot_2016-03-16-11-11-53](https://cloud.githubusercontent.com/assets/13129267/13797314/7a72bd66-eb71-11e5-96cb-ffde51f8fd91.png)
