### ISSUE TITLE
Incorrect file owner & permissions in backup (TWRP 3.0.3-0 mako)

### ISSUE THREAD

**Issue by fprietog** [TeamWin/Team-Win-Recovery-Project#857]
After a backup done the first file (i.e. boot.emmc.win) have owner & group _root_ instead of _media_rw_. Also file permissions are incorrect. The rest of the backup files are correct. 

This causes that this backup file can't be used from within android.

Here is an screenshot:
![screenshot_2017-02-17-19-15-25](https://cloud.githubusercontent.com/assets/9756455/23092968/95b98544-f5d6-11e6-8d2c-79b7cf915dc9.png)

Workaround: change file ownership and permissions using TWRP built-in terminal.

**Comment by nailyk-fr** [comment]
This had been [fixed](https://gerrit.omnirom.org/#/c/21225/) on jan-19. Maybe your build is older and doesn't include this patch. Try to reinstall twrp and/or ask for a new build.

**Comment by fprietog** [comment]
I'm using the latest available official build "twrp-3.0.3-0-mako.img" dated 2017-02-01 17:35:37 EST

Since that built is dated before the patch commitment, maybe that patch was not included or it's still not working...

Thanks.

**Comment by fprietog** [comment]
I'm using the latest available official build "twrp-3.0.3-0-mako.img" dated 2017-02-01 17:35:37 EST

Since that built is dated after the patch commitment, maybe that patch was not included or it's still not working... Don't have the tools to compile a new build myself to check.

Thanks.

**Comment by nailyk-fr** [comment]
Right now I'am working on LineageOS so triggering a new build won't be easy.
Will try asap.

**Comment by fprietog** [comment]
Don't worry, it's not a big problem since the workaround I said before works well and is easy to be done.

Thank you.
