### ISSUE TITLE
reboot gets stuck with no OS flashed

### ISSUE THREAD

**Issue by levengli** [TeamWin/Team-Win-Recovery-Project#86]
TWRP warns when trying to reboot without an OS flashed on the device. If the warning is ignored, the device will go into an apparent infinite loop of not rebooting while not allowing any of the buttons to be pressed.
The only way out of this was to remove the battery and then power up in to recovery mode.

Seen on a Samsung SGH-I727

**Comment by Dees-Troy** [comment]
The device won't boot without a working OS installed (hence the warnings that you saw and ignored). This is user error, not a TWRP issue.

**Comment by levengli** [comment]
The issue is not that TWRP won't allow reboot, rather that it gets stuck
doing so
