### ISSUE TITLE
Nexus5 - Restore

### ISSUE THREAD

**Issue by fivel-321** [TeamWin/Team-Win-Recovery-Project#863]
Hi! 

I managed to get these files out of my unusable old Nexus5 (the phone was encrypted): 

data.emmc.win
system.ext4.win
system.ext4.win.md5
system.info

I moved  those files to a new Nexus5, accessed the folder via TWRP and told it to use it as recovery/restore from backup. Unfortunately this didn't work. (Device reamins in booting procedure). 

Do you have any advice on how to solve this issue and get my phone going?

**Comment by nailyk-fr** [comment]
What are you trying to do?

**Comment by fivel-321** [comment]
I have an old Nexus5 with no (recent) backup that had been encrypted and is not working any more.
all I have are those files mentioned above.  they were gathered of my old phone via a data recovery  service provider. 

I would either like to access the information on the old phone (i.e. browsing through the file-system behind "system.ext4.win" or "data.emmc.win"), or I'd like to restore the phone information onto a new nexus5 (favored option as I already bought a new nexus5) and continue using the phone as it had been. 

And I am desperately looking for help - as I already paid a whole lot of money to even get some files back... (which i am not albe to acceess at the moment, quite frustrating)

thank you in advance!

**Comment by nailyk-fr** [comment]
OK but it is not a twrp issue. 
You could get better help on the twrp chan I think. 
What exactly are your backups? The files you mentioned before looks like twrp backups but unencrypted: 'data.emmc.win' emmc mean it is a raw backup. 
If device was encrypted, you will get the same encryption when restoring your backup (same password). 
Your way to restored should work: 
1. Take your old backup (TWRP/**\<serial\>/\<backup name\>**)
2. Take a dummy backup of your new device to create the backup folder, 
3. Place the old <backup name> into the new TWRP/**\<serial\>** folder, 
4. Restore. 

If it still doesn't work there is two scenario: 1. Your backup is corrupted, 2. You have not the same rom. 
Your file list doesn't mention boot.img which is critical to get a rom started. 

Another way could be through fastboot but it is a different story. 
Does your old device still boot and is adb accessible?

**Comment by fivel-321** [comment]
hi, 
so I am a little confused right now. 

My phone is not usable any longer, it has a hardware failure and does not boot.

I have an old backup from february 2016 (titled: 15-01-44_cm_hammerhead-userdebug_5.1.1_LMY48B_1636aa) with those files: 

boot.emmc.win
boot.emmc.win.md5
data.ext4.win
data.ext4.win.md5
data.info
recovery.log
system.ext4.win
system.ext4.win.md5
system.info

the information the data recovery service was able to collect was:

data.emmc.win
system.ext4.win
system.ext4.win.md5
system.info

should i just replace the files of the old backup accordingly and try to restore the phone on my new nexus5?

**Comment by nailyk-fr** [comment]
Yes, replace all the files (not only the four) and it should work (with the listed one, not more).

**Comment by fivel-321** [comment]
still confused, I'd like to restore my phone to the state it was when it failed, not to my last backup from february 2016. are you telling me what to do in order to restore my phone to my backup from february 2016? 
sorry for bothering you again and thanks a lot for helping me!

**Comment by nailyk-fr** [comment]
If you can't dump the memory anymore you won't be able to restore it except from your backup. 
I just figure you used 'recovery service' word. If it is a dump of the actual storage try to mix files between them. 
system & boot need to be from the same backup/rom, 
data need to be from the currently installed rom. 

P.S.: I reread my 'process' post and some words are missing. I readd them in bold.

**Comment by fivel-321** [comment]
hi, ok, I did what you told me, created a new backup-folder mixing system & boot from the old backup with data from the new data-dump.

this is how the file looks like: 
boot.emmc.win
system.ext4.win
data.emmc.win

I tried to restore - but TWRP says it failed.
when I try to start the device I am asked for my device-encryption-password. 
once I type the correct pwd the phone tells me: 
"Decryption unsuccessful - The password you entered is correct, but unfortunately your data is corrupt."

Is there any way to access the information stored in "data.emmc.win" directly? with a file browser?

**Comment by nailyk-fr** [comment]
I probably miss express myself. 
You need the working device with system+boot+the data you want to restore. 
The best way should be: 
from old device: cp /storage/TWRP/BACKUPS/1234567890/backup_of_broken_device/*
into new device: /storage/TWRP/BACKUPS/ABCDEF/backup_of_broken_device
then restore system,boot,data, but not sure if the footer is backuped too. 
There is probably a way to use dm-crypt to mount the dump. If you are comfortable with luks command you could try. But the hammerhead is 'hardware' encrypted which mean the software implemented dm-crypt will probably not be able to work with this dump. 
If you have other restore errors read the /tmp/recovery.log, maybe it will contain something useful.

**Comment by fivel-321** [comment]
hi, 
thanks a lot, I was able to restore my old but working backup to the new phone, great! :)

unfortunately the dump of the image of the broken device does not work... 

specificially: system.ext4.win does work, I am able to unzip the tar. 
but data.emmc.win which is a 13,73 GB file does not open. Is it possible that data.emmc.win is still encryptet? with "file data.emmc.win" in a terminal it is not recognized.

**Comment by nailyk-fr** [comment]
Glad the backup works. 
Yes, raw dump of the emmc will be encrypted. You can try to flash it through fastboot/dd. (it should be a real dd dump of the device). 
But as you said the older device isn't working anymore (and don't know why) it will probably not work.

**Comment by fivel-321** [comment]
ok, I would like to try - can you tell me how to flash the data.emmc on my phone? or provide me with a link?

well - the device was not working anymore because of a hardware failure, but I payd a data recovery service provider to extract the phone storage to a storage device... but am now left wondering what to do with the data.emmc...

**Comment by nailyk-fr** [comment]
Yes got the hardware failure. But which one ;) I mean if it is a cracked screen don't care, we can still use the device. If a truck run on it, it is over :p 
This is really risky task (for the new device) if you flash it to the wrong partition. Look at fastboot options but something like fastboot -s 512M flash userdata data.emmc should do the trick. 
You can also use dd to flash it (look at the man page) then use the right partition (you probably have a symlink in /deb/block/platform/something/by-name/userdata). 

I didn't own a N5 so commands/path need to bu adjusted. 
Please be careful, dd and flashboot flash can be destructive if not used the right way.

**Comment by fivel-321** [comment]
oh well - it is a bit complicated. 
at first there was a cracked screen and I took the phone to a small phone repairing shop in order to get a new screen. shortly after that (a few days) the phone stopped working and started to run boot-cycles only when plugged in. I took the phone back to the shop. 
there they told me it was a water related failure (but my phone was never dumped into water), and they will try to get it going - with the result that it did not do anythingn when I got it back. 
so I went to a data recovery provider, in order to get the data extracted. 

well, she now told me, that on the phone, right where the display connector ist located, a few chips got kicked out of the board and were missing. 
but the provider was able to get some data back from my phone - those are: 

data.emmc.win
system.ext4.win
system.ext4.win.md5
system.info

but my old phone  is now completely useless... 

and that brings me to this forum :)

**Comment by nailyk-fr** [comment]
ok. Just, worth to try, please try to power the _old _ device into twrp mode/fastboot mode. 
Good luck with the data.emmc.win.

**Comment by fivel-321** [comment]
well, something is happening, but the phone screen is definitely not working, so i have to guess. will try to go to recovery mode "blind"

edit: not working, but it was a nice try.

**Comment by nailyk-fr** [comment]
yes and connect with adb. But was just an idea. You can try to restore, at the meantime, your paid recovered datas. 

Anyway this is not a TWRP issue, it would be nice if you can open something else, like on xda, and close the issue. Also maybe other person can have ideas on your problem. Please highlight [me](https://forum.xda-developers.com/member.php?u=6979267) if you open a xda thread.

**Comment by fivel-321** [comment]
There already was a thread at [xda](https://forum.xda-developers.com/google-nexus-5/help/twrp-restore-data-damaged-encrypted-t3560985#post71373531) but I did not get the help I was looking for.

Thank you very much @nailyk-fr, you were a big help! 👍
