### ISSUE TITLE
TWRP won't start when device is encrypted but pattern/password isn't required on boot on Android

### ISSUE THREAD

**Issue by depau** [TeamWin/Team-Win-Recovery-Project#865]
I'm running TWRP 3.0.3-1 on a OnePlus 3T.
I was going to do some maintenance with the recovery, but I noticed it wouldn't start. It would stay stuck at the TWRP logo screen, no adb, nothing.
I tried running TWRP 3.0.2-0, and it started, but instead of asking for the unlock pattern, it asked for a text password.
Recently I installed an application that required enabling an accessibility service for its purpose. While enabling it, android required me to draw my pattern as that service "could interfere with device encryption."
I removed that service, re-enabled on-boot pattern request, and twrp worked just fine.
I think this is a bug.

**Comment by nailyk-fr** [comment]
https://github.com/TeamWin/Team-Win-Recovery-Project/issues/856

**Comment by depau** [comment]
Whoops, sorry!

**Comment by nailyk-fr** [comment]
No worry. Try to contact your device maintainer. (name is on the device page into twrp)
