### ISSUE TITLE
TWRP Factory Resets LineageOS 14.1 on OnePlus 3

### ISSUE THREAD

**Issue by stonerl** [TeamWin/Team-Win-Recovery-Project#873]
Here is my setup:
* OnePlus 3
* TWRP 3.1.0
* LinageOS 14.1 (20170309)

I flash LineageOS from TWRP and start the system. When I have my system configured, rebooting into TWRP results in a 20 seconds lasting TWRP Boot-Screen. After around 20 Seconds TWRP just reboots and when the system is started it has benn completely reset. 

The same happens with 3.0.3; it boots into the TWRP menu, but no buttons are "clickable" and after hard rebooting the system it has Factory Reset LinageOS.

3.0.2 doesn't even boot when LOS 14.1 is installed.

**Comment by kranich** [comment]
The issue may not be limited to OnePlus 3. I experienced a similar issue with LG G4 (h815).

I flashed TWRP 3.1.0 to recovery, then rebooted to recovery because I wanted to make a backup. Recovery briefly booted and wiped `/data`.

**Comment by xkid1** [comment]
I  think did not support your phone with the version...

**Comment by blastagator** [comment]
On LG G2, if you boot to recovery using key combination, the bootloader writes a wipe command to /misc.  Related to G4, it probably does same thing.  Starting with android-N /misc is mounted for ROM to communicate with recovery.  If TWRP was built with a /misc mount, starting TWRP with the key combo would probably cause the wipe.  This can be remedied with this:  https://review.lineageos.org/#/c/165294/
(All ROMs would need it also, for working OTA, but to fix the wipe issue, only TWRP build would need it, OR disable /misc mount)

As for OP3, I doubt this is your issue, but perhaps.

**Comment by nailyk-fr** [comment]
You can also try this: https://gerrit.omnirom.org/#/c/20849/

**Comment by nmaggioni** [comment]
Same here, even just booting in TWRP and immediately rebooting to System has the same effect of a factory reset. How can one collect logs in such a situation? Issue happening on 3.0.3, 3.0.4-1, 3.1.0.

Reflashing stock recovery and then any TWRP again had no effect on the issue.

**EDIT:** I saw no random wipes using [blu_spark's TWRP](https://forum.xda-developers.com/devdb/project/dl/?id=23572), at least for now.

**Comment by yoncy** [comment]
Can confirm had the same problem on an Oneplus 3T. On blu_spark it's ok.

**Comment by linrunner** [comment]
I'm affected too:
-  OnePlus 3
-  TWRP 3.1.0
-  LineageOS 14.1 (20170504)

Workaround [twrp-3.1.0-x_blu_spark_v27.1-op3_op3t.img](https://forum.xda-developers.com/devdb/project/?id=15934#downloads) confirmed.

**Comment by stonerl** [comment]
Just saw that 3.1.1 is out. Has this issue been resolved? I don't dare to install it because I don't want my device to be wiped.

**Comment by stonerl** [comment]
With 3.1.1 this issue seems to be resolved.

**Comment by orgua** [comment]
i can confirm it is not resolved. had this wipe-problem 2x with 3.1.1 in the last two days with a OP3. switching to blu spark now :-(

**Comment by stonerl** [comment]
@orgua which device?

**Comment by orgua** [comment]
its an op3. and i can confirm, that blu spark 3.1.1 is a solution for this problem. had several reboots between recovery and system in the last 2h and still got all data

**Comment by stonerl** [comment]
That's interesting I'm running the official 3.1.1 and LineageOS 14.1-20170518-nightly-oneplus3 without any problems...

**Comment by orgua** [comment]
yes, same setup. flashing same recovery, installing same nightly and the matching boeffla-kernel. after configuration of the rom i booted to recovery and it was showing the twrp-start-screen followed by a automatic restart. same everytime. next lineage start was longer than usual with all data gone. just flashing the recovery didn't repair it, i had to format the partition to fix it. then same procedure as described with the same result.

**Comment by blastagator** [comment]
This seems to be indicative of a device tree misconfiguration.  On LG G2/G3, bootloader writes a wipe command to /misc, and if the device tree mounts /misc, TWRP will wipe the device due to the command.

**Comment by stonerl** [comment]
@orgua maybe the problem is caused by your kernel

**Comment by nailyk-fr** [comment]
Am not sure what the problem is but maybe some of you still have old '--wipe-data' into the 'communication' between twrp and ROM. 
Check content of /misc partitions and /cache/recovery/commands (iirc, check similar path)
The 'strings' command could be helpful. 
I experienced this issue because it seems twrp read both locations but only clear one. 
Hope this help. 

Le 22 mai 2017 22:47:51 GMT+02:00, "Toni Förster" <notifications@github.com> a écrit :
>@orgua maybe the problem is caused by your kernel
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/TeamWin/Team-Win-Recovery-Project/issues/873#issuecomment-303215688

-- 
Envoyé de mon appareil LineageOS avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by kranich** [comment]
Problem persists with TWRP 3.1.1 on LG G4 (h815).

**Comment by linrunner** [comment]
Solved for my Oneplus 3 with TWRP 3.1.1-2.

**Comment by Robbilie** [comment]
I feel like I have this issue on my Nexus 5, every time I setup my phone, reboot into recovery with the key combo I end up with a broken factory reset phone.

EDIT: I run Paranoid Android latest version and latest TWRP, even when adb reboot recovery the factory reset gets triggered.
