### ISSUE TITLE
(All?) download links broken

### ISSUE THREAD

**Issue by matthijskooijman** [TeamWin/Team-Win-Recovery-Project#904]
I just tried to download an image for the Fairphone2, but the download link is broken (on both the EU and US mirrors). I tried a few other devices, and all have the same problem, so it seems that it is a general problem with the website infrastructure, rather than a problem with specific files themselves.

What happens is that on the download page for a specific version (e.g. https://eu.dl.twrp.me/fp2/twrp-3.1.0-0-fp2.img.html) there is a link to the image (https://eu.dl.twrp.me/fp2/twrp-3.1.0-0-fp2.img). However, the latter just returns the same HTML page as the former, instead of returning the actual file. The link to the .img.asc works as expected, offering a download.

**Comment by z3ntu** [comment]
Works for me (Austria) with Chrome on Linux.

**Comment by matthijskooijman** [comment]
Interesting, there seems to be a browser-aspect to this. I noticed the problem using Firefox 45.4 on Debian Linux. Using chrome, I do get the download. With wget, I get the HTML:
```
matthijs@grubby:~$ wget https://eu.dl.twrp.me/fp2/twrp-3.1.0-0-fp2.img --server-response ; head -n 2 twrp-3.1.0-0-fp2.img
--2017-04-03 15:19:07--  https://eu.dl.twrp.me/fp2/twrp-3.1.0-0-fp2.img
Resolving eu.dl.twrp.me (eu.dl.twrp.me)... 163.172.217.28
Connecting to eu.dl.twrp.me (eu.dl.twrp.me)|163.172.217.28|:443... connected.
HTTP request sent, awaiting response...
  HTTP/1.1 200 OK
  Server: nginx/1.10.0 (Ubuntu)
  Date: Mon, 03 Apr 2017 13:19:07 GMT
  Content-Type: text/html
  Content-Length: 7145
  Last-Modified: Mon, 03 Apr 2017 01:28:47 GMT
  Connection: keep-alive
  ETag: "58e1a54f-1be9"
  Expires: Mon, 03 Apr 2017 13:19:06 GMT
  Cache-Control: no-cache
  Accept-Ranges: bytes
Length: 7145 (7.0K) [text/html]
Saving to: ‘twrp-3.1.0-0-fp2.img’

twrp-3.1.0-0-fp2.img                    100%[==============================================================================>]   6.98K  --.-KB/s    in 0s

2017-04-03 15:19:07 (150 MB/s) - ‘twrp-3.1.0-0-fp2.img’ saved [7145/7145]

<!DOCTYPE html>
<html>

```

**Comment by z3ntu** [comment]
They apparently check the refer(r)er. It works for me with `curl -O --referer https://eu.dl.twrp.me/fp2/twrp-3.1.0-0-fp2.img https://eu.dl.twrp.me/fp2/twrp-3.1.0-0-fp2.img` (don't know the wget-equivalent).

**Comment by z3ntu** [comment]
See https://github.com/TeamWin/Team-Win-Recovery-Project/issues/816#issuecomment-269639761 and https://github.com/TeamWin/Team-Win-Recovery-Project/issues/625#issuecomment-204391681

**Comment by matthijskooijman** [comment]
Ah, good point. Turns out I had disabled the referrer header in my Firefox configuration, probably for debugging something else long ago and forgot about it. I think this is working as intended then, thanks for diving in!
