### ISSUE TITLE
HTC One S s3 villec status 7

### ISSUE THREAD

**Issue by p1nox** [TeamWin/Team-Win-Recovery-Project#91]
Im trying to install Cyanogenmod 10 http://download.cyanogenmod.org/?type=stable&device=ville

My device is already unlocked, and TWRP 2.3.3.0 works ok, but after making factory reset and wiping cache/dalvik I proceed to install CM10 and I see an error that make fail installation 

Installing 'sdcard/Donwload/cm-10.0.0-vile.zip'...
Checking for MD5 chack: no MD5 file found.
assert field: getprop("ro.product.device") == "ville"
E:Error in /sdcard/Download/cm-10-0-0-ville.zip
(Status 7)
Error flashing zip '/sdcard/Download/cm-10.0.0-ville.zip'
Updating partition details

**Comment by Dees-Troy** [comment]
We need the full recovery.log to identify the issue but I suspect that you actually have a ville_c2 or ville_u instead of a ville that's preventing you from installing this.

**Comment by p1nox** [comment]
Thanks, and yes that's the reason... 

https://github.com/CyanogenMod/android_device_htc_ville/issues/2#issuecomment-12889873
