### ISSUE TITLE
Fails to build on other ROMs than omni due to Hackish workaround for 7.1.2

### ISSUE THREAD

**Issue by rancidfrog** [TeamWin/Team-Win-Recovery-Project#915]
TWRP will not build as System/Core requires other structs in 7.1.2 which is dealt with improperly in https://github.com/omnirom/android_system_core/commit/bf3d96c9c0e0774af8118f4a6d7dc29116bae1c9

Merge tag 'android-7.1.2_r5' 
`gr_init_font` and `gr_sys_font()` have been added into system/core aosp but not taken into consideration:
https://android.googlesource.com/platform/system/core/+/android-7.1.2_r5/healthd/healthd_mode_charger.cpp#443

DU have handled it: https://github.com/DirtyUnicorns/android_bootable_recovery/commit/094b32f7deb2f7320c2ac58e44483d39a5868b3c 

```
target thumb C++: libhealthd_internal <= system/core/healthd/healthd_mode_charger.cpp
system/core/healthd/healthd_mode_charger.cpp:274:33: error: use of undeclared identifier 'gr_sys_font'
    int str_len_px = gr_measure(gr_sys_font(), str);
                                ^
system/core/healthd/healthd_mode_charger.cpp:280:13: error: use of undeclared identifier 'gr_sys_font'
    gr_text(gr_sys_font(), x, y, str, 0);
            ^
system/core/healthd/healthd_mode_charger.cpp:296:41: error: member access into incomplete type 'GRFont'
    int str_len_px = length * field.font->char_width;
                                        ^
system/core/healthd/animation.h:24:8: note: forward declaration of 'GRFont'
struct GRFont;
       ^
system/core/healthd/healthd_mode_charger.cpp:306:42: error: member access into incomplete type 'GRFont'
        *y = (gr_fb_height() - field.font->char_height) / 2;
                                         ^
system/core/healthd/animation.h:24:8: note: forward declaration of 'GRFont'
struct GRFont;
       ^
system/core/healthd/healthd_mode_charger.cpp:310:55: error: member access into incomplete type 'GRFont'
        *y = gr_fb_height() + field.pos_y - field.font->char_height;
                                                      ^
system/core/healthd/animation.h:24:8: note: forward declaration of 'GRFont'
struct GRFont;
       ^
system/core/healthd/healthd_mode_charger.cpp:321:44: error: member access into incomplete type 'GRFont'
    if (field.font == nullptr || field.font->char_width == 0 || field.font->char_height == 0) return;
                                           ^
system/core/healthd/animation.h:24:8: note: forward declaration of 'GRFont'
struct GRFont;
       ^
system/core/healthd/healthd_mode_charger.cpp:339:5: error: no matching function for call to 'gr_text'
    gr_text(field.font, x, y, clock_str, false);
    ^~~~~~~
bootable/recovery/minui/minui.h:50:6: note: candidate function not viable: requires 4 arguments, but 5 were provided
void gr_text(int x, int y, const char *s, bool bold);
     ^
system/core/healthd/healthd_mode_charger.cpp:352:44: error: member access into incomplete type 'GRFont'
    if (field.font == nullptr || field.font->char_width == 0 || field.font->char_height == 0) {
                                           ^
system/core/healthd/animation.h:24:8: note: forward declaration of 'GRFont'
struct GRFont;
       ^
system/core/healthd/healthd_mode_charger.cpp:363:5: error: no matching function for call to 'gr_text'
    gr_text(field.font, x, y, str.c_str(), false);
    ^~~~~~~
bootable/recovery/minui/minui.h:50:6: note: candidate function not viable: requires 4 arguments, but 5 were provided
void gr_text(int x, int y, const char *s, bool bold);
     ^
system/core/healthd/healthd_mode_charger.cpp:444:17: error: use of undeclared identifier 'gr_init_font'
                gr_init_font(anim->text_clock.font_file.c_str(), &anim->text_clock.font)) < 0) {
                ^
system/core/healthd/healthd_mode_charger.cpp:451:17: error: use of undeclared identifier 'gr_init_font'
                gr_init_font(anim->text_percent.font_file.c_str(), &anim->text_percent.font)) < 0) {
                ^
system/core/healthd/healthd_mode_charger.cpp:477:22: error: use of undeclared identifier 'gr_sys_font'
        gr_font_size(gr_sys_font(), &char_width, &char_height);
                     ^
12 errors generated.
```

**Comment by mikalackis** [comment]
+1

**Comment by nailyk-fr** [comment]
Yes it was an q&d way to get compatibility with 7.1.0

Look at [mr2-custom-fonts](https://gerrit.omnirom.org/#/q/status:open+project:android_bootable_recovery+branch:android-7.1+topic:mr2-custom-fonts) topic into gerrit.

**Comment by rancidfrog** [comment]
Saw the gerrit commit, will test if not merged on next compile. Currently 3.0.3.0 working well, even though wiping cache&data takes a long time.

**Comment by mikalackis** [comment]
I cherry-picked the commits from that gerrit but still get the following error:
`system/core/healthd/healthd_mode_charger.cpp:443:17: error: no matching function for call to 'gr_init_font'
                gr_init_font(anim->text_clock.font_file.c_str(), &anim->text_clock.font)) < 0) {
                ^~~~~~~~~~~~

bootable/recovery/minui/minui.h:60:5: note: candidate function not viable: no known conversion from 'GRFont **' to 'GRFont *' for 2nd argument; remove &
int gr_init_font(const char* name, GRFont* dest);
    ^

system/core/healthd/healthd_mode_charger.cpp:450:17: error: no matching function for call to 'gr_init_font'
                gr_init_font(anim->text_percent.font_file.c_str(), &anim->text_percent.font)) < 0) {
                ^~~~~~~~~~~~

bootable/recovery/minui/minui.h:60:5: note: candidate function not viable: no known conversion from 'GRFont **' to 'GRFont *' for 2nd argument; remove &
int gr_init_font(const char* name, GRFont* dest);
`

**Comment by nailyk-fr** [comment]
your pick shouldn't be good, I have the function: 
> minui/graphics.cpp:383:int gr_init_font(const char* name, GRFont** dest) {
> minui/minui.h:60:int gr_init_font(const char* name, GRFont** dest);

And your log show the old one. 
Use this command on top of your tree to pick: 
> repopick -g https://gerrit.omnirom.org -t mr2-custom-fonts -P bootable/recovery

**Comment by mikalackis** [comment]
Yup, my bad, that completely did the trick, thanks for the help. Compile succeeded, im gonna test it a bit now

**Comment by rancidfrog** [comment]
Applying following commits fixes build:
- https://gerrit.omnirom.org/#/c/22768/1
- https://gerrit.omnirom.org/#/c/22769/1
- https://gerrit.omnirom.org/#/c/22770/1

As @nailyk-fr mentioned above

**Comment by NeoBeum** [comment]
Is this one of the reasons why I can't build it for AOSP 7.0? Or probably just because I'm retarded and can't find where to link the bootloader messenger library...

I've been trying to find out more information on my error, but there isn't many examples to find on Google

**Comment by rancidfrog** [comment]
This only applies to android-7.1 and aosp sources 7.1.2

**Comment by NeoBeum** [comment]
my build is still failing with the libbootloader library on 7.0. i think init.real wants it before the static library is built.

it's somewhere in bootloader_message / uncrypt 

i tried both branches 7.0 and 7.1, and even just the default boards and emu, as well as for aosp_e5823-eng and -userdebug, and can't work out what's wrong.

I know I'm looking in the right area because I can build the stock recovery and it outputs correct static and shared libraries

**Comment by rancidfrog** [comment]
Fixed with following commit: https://gerrit.omnirom.org/#/c/23520/
