### ISSUE TITLE
F2FS Backups restores as Ext4

### ISSUE THREAD

**Issue by iefdev** [TeamWin/Team-Win-Recovery-Project#925]
When I (re)installed my system, I changed the filesystem to F2FS before. When done, I made a backup and put on a USB drive. Tested a few things and wanted to restore my backup. Wiped all clean and changed everything to F2FS again, and then restored chosing my backup.

The restore script started by running `mkfs.ext4`. So, no more F2FS.

Is there a reason behind that?

_If that's the intended behaviour? it feels a bit overkill to offer F2SF in the 1'st place, if you can't use it later to backup/restore . /2¢_

**Comment by nailyk-fr** [comment]
yes. you need to tick 'use rm -rf instead of format' into settings.

**Comment by iefdev** [comment]
@nailyk-fr, Thanks… 👍  I'll look in to that at next backup.
