### ISSUE TITLE
Adb backup issue: bu not found

### ISSUE THREAD

**Issue by PerfectSlayer** [TeamWin/Team-Win-Recovery-Project#927]
Hi,
I'm trying to make an adb backup over USB using ```adb backup --twrp```.
When I run this command from PC with recovery loaded, I got a 1kb backup.ab containing:
```
/sbin/sh: /system/bin/bu: not found
```
I also tried to mount /system partition from settings and the backup.ab file now cotains:
```
CANNOT LINK EXECUTABLE: cannot locate symbol "__register_atfork" referenced by "app_process"...
page record for 0xb6ee004c was not found (block_size=32)
```
In both case, backup doesn't start and doesn't display any information on the device screen.

Here is my configuration:
- Motorola Nexus 6
- TWRP 3.1.0.0
- Stock ROM shamu-mob31k-factory-49a4de6b
- SuperSU 2.78-SR

Any help is appreciated 😉

**Comment by rrama** [comment]
Same issue :cry: But apparently they are working on it.
https://github.com/TeamWin/Team-Win-Recovery-Project/issues/877#issuecomment-289128732

**Comment by PerfectSlayer** [comment]
Thanks for the highlight! I didn't find it before posting 😥 
I'll close this issue when the patch will be release.

**Comment by PerfectSlayer** [comment]
The latest version (3.1.1.0) fixes the issue for me. Thanks!
