### ISSUE TITLE
TWRP 2.4.0.0 - External SD card not mounting EVO 4G LTE

### ISSUE THREAD

**Issue by rpenrod23** [TeamWin/Team-Win-Recovery-Project#93]
I recently updated to TWRP 2.4.0.0 through GooManager and although it flashed correctly, it is not mounting my external SD card when I try to use it as a point to create or restore a backup, or mount so that I can read inside of Windows.

I attempted to attached the recovery.log but for some reason it's not working.  I can provide the log upon request.

**Comment by Dees-Troy** [comment]
This is fixed in 2.4.1.0
