### ISSUE TITLE
Bug in TWRP 3.1.0-1 with Galaxy S5 SM-G900F (and others too) and previous releases when using GApps-Aroma zip-package

### ISSUE THREAD

**Issue by ghost** [TeamWin/Team-Win-Recovery-Project#943]
Hi Devs,

it's necessary for me to use the latest TWRP Recovery (currently 3.1.0-1) to flash the current LineageOS to my Samsung Galaxy S5 SM-G900F cell phone. Releases prior 3.x all run into a status 7 installation error. After successfully flashing the current LineageOS to my cell phone, I want to apply the GApps-Aroma zip-package. I chose the Aroma package, because I want a graphical interface and the possibility to choose what to Install and what not. The problem/bug is the following:

- When launching the GApps-Aroma zip-package, TWRP totally hangs and just reboots. There is absolutely no chance of getting the GApps-Aroma zip-package to run. However, when I roll back to TWRP 2.8.4.0 after I installed LineageOS with TWRP 3.1.0-1, the GApps-Aroma zip-package runs and installs flawlessly without any problems. This results in:
1.) I need to flash TWRP 3.1.0-1 Recovery to install the main LineageOS package (the OS it-self)
2.) Then I need to rollback to TWRP 2.8.4.0 Recovery to install the GApps-Aroma zip-package
3.) After that I need to re-install(upgrade) to TWRP 3.1.0-1 Recovery, so that there are no further problems with the current LineageOS

That's very inconvenient to me and maybe to others as well. Took me quite a time to figure out, what the actual problem is. There seems to be a bug/problem in TWRP 3.1.0-1.

I would love to permanently have the TWRP 3.1.0.1 Recovery installed without having to go through the upper mentioned steps after every installation of a new LineageOS file.

Looking forward for a reply :-)

**Comment by ghost** [comment]
Any clue on this?

**Comment by ghost** [comment]
Only TWRP version which does on the job (at least on my Galaxy S5 SM-G900F) is 2.8.4.0; Whatever happened to the other releases - the GApps Aroma package, which is the best in my opinion (fully customisable) does not work after 2.8.4.0

**Comment by CaptainThrowback** [comment]
After the hang/reboot, try flashing it again.

**Comment by ghost** [comment]
Hi CaptainThrowback,
thanks for the feedback :-). I've tried to flash the GApps-Aroma package several times with TWRP 3.1.0-1. Everytime GApps launches, TWRP hangs/freezes. The only way to get out of TWRP is remove the device's battery and re-enter TWRP. The only current workaround for me is:
- Flash TWRP 3.1.0-1
- Flash LineageOS with TWRP 3.1.0-1 (TWRP 2.8.4.0 does not work for LineageOS 7.1.2)
- Flash TWRP back to old release 2.8.4.0
- Flash Aroma GApps (most of the times it works with 2.8.4.0, not always - but at least TWRP doesn't hard freezes, it just reboots)
- Flash TWRP back to latest 3.1.0-1 after GApps has been flashed with 2.8.4.0

I wonder what the problem is with the TWRP releases after 2.8.4.0, specially 3.x

**Comment by CaptainThrowback** [comment]
What I'm asking is, once you re-enter TWRP after it locks up, have you tried just flashing the GApps package again immediately? That seems to work on most other devices.

**Comment by ghost** [comment]
With 2.8.4.0 re-entering TWRP (after it auto reboots) and flashing it again, works lets say most of the time (80-90%). Unfortunately with 3.1.0-1 there's no chance - the phone always hard freezes and there's no response to anything. :-(

**Comment by CaptainThrowback** [comment]
Unfortunately AROMA is deprecated, as the source hasn't been updated to be compatible with newer versions of Android, while the TWRP source is constantly being updated. It seems that unless AROMA source is updated soon, it will eventually be completely incompatible with newer versions of TWRP. Unfortunately there's not much we can do about that.

**Comment by ghost** [comment]
Thanks for letting me know. I will try to open a ticket at the Github page for Aroma :-). Thanks for the feedback.

**Comment by CelesteBlue-dev** [comment]
I confirm that it also happens on S4 LTE-A GT-I9506 (ks01ltexx) under about same TWRP versions:
latest working well with AROMA installer is 3.1.1-0.
Later versions of TWRP either powers off device or freeze on AROMA language selection menu (1st page).
So it is more than GAPPS not working: any AROMA package doesn't work on TWRP > 3.1 on Samsung devices.
It is certainly due to the fact that Aroma development has stopped in 2015 and TWRP 3.1 was released in 2017.
Conclusion: either get rid of AROMA installer when creating a ROM and port existing ROMs META-INF...
or install older TWRP when installing an AROMA-embedded ROM.

**Comment by bigbiff** [comment]
Aroma issues are outside TWRP.
