### ISSUE TITLE
Galaxy S3, internal storage mounted incorrectly if using CM10.1

### ISSUE THREAD

**Issue by mcbyte-it** [TeamWin/Team-Win-Recovery-Project#95]
I have Galaxy S3 i9300, and I use Siyah dual boot kernel, and use 2 ROMs, a Samsung ROM (XXEMA2) as primary and CM10.1 nightly as secondary.

on this device, when using CM10.1, it creates a directory called "0" (zero) on the internal storage to be the base of the main user, so when running CM10.1 I see "0" as ROOT of the internal storage, while the original internal storage is visible only when using the Samsung ROM, and that's were I see a folder called "0" with all the rest inside it.

The issue is that when using TWRP recovery for my device (latest, 2.4.1.0), and want to install a zip from the internal storage, it also see only the contents of the "0" directory as root, and not the real internal storage, I tried renaming 0 to something else and only then TWRP showed the real content of the Internal storage.

Is this a feature or a bug? can something be done?

Thanks

**Comment by Dees-Troy** [comment]
The "0" folder is a result of the multi-user changes that Google introduced in Android 4.2. Flip flopping between 4.1 and 4.2 ROMs is not recommended and will require you to manually migrate your data from the /data/media/0 folder back to /data/media each time you want to hop back to 4.1. This is an issue with the ROMs that you are using and switching between and not an issue with TWRP.
