### ISSUE TITLE
Sorry no issue... much love and humble request.. please read me :)

### ISSUE THREAD

**Issue by lifeluvr** [TeamWin/Team-Win-Recovery-Project#951]
I guess it's a bit of a long story but, to cut to the chase...
I have put together a QR code reader that inputs an initial (init) command into the jackpal terminal. (if installed) instead of the default web browser! Also, I have put together a QR code generator for making custom QR codes (I like to see what I no longer have to type)...
Anyhow... as a bit of a noob exploring the unknown (i know, i know... i'm slow)... I was just wondering what it would take to add this as a function to TWRP? I have a feeling that it's not that hard ;)

**Comment by lifeluvr** [comment]
jaba?
jaba da booski?
(i just made that up)

**Comment by Dees-Troy** [comment]
Making the camera work at all within recovery would be a monumental task, let alone things like live viewing of the camera image or scanning and decoding a QR code. I can understand that scanning a QR code might be easier than keying in a shell command, but this is out of scope for what we are doing. You can use adb shell or even a USB keyboard with OTG adapter to help alleviate input. Sorry.

**Comment by lifeluvr** [comment]
Yeah... I kind of figured as much... I had a bunch of ROMS where that was the only thing not working... But ya never know till ya ask?

**Comment by lifeluvr** [comment]
Yeah... I kind of figured as much... I had a bunch of ROMS where that was the only thing not working... But ya never know till ya ask?

**Comment by lifeluvr** [comment]
Howdy,
It's okay... I mean... I totally get it if you don't want to tell me the
secret terminal command!
I'm just kidding! (ugh... I know... sorry)
Thank you all for the input and for indulging me and my crazy idea and for
not shredding me to pieces for asking silly questions...
That little "what if" has been nagging me lately... Glad it's solved ;)
Maybe now I can focus on stuff that is actually doable?
Thanks again!
Eric
