### ISSUE TITLE
Bad MD5 and PGP Signature for TWRP Clark 3.1.1-0

### ISSUE THREAD

**Issue by gadgetguy08** [TeamWin/Team-Win-Recovery-Project#957]
After downloading a few times, I get a consistent MD5 checksum on the TWRP Clark 3.1.1-0 img file.  That checksum does not match the checksum supplied on the download page.  Also the PGP signature for the file shows as BAD, too.  No such issue on Clark 3.1.0-0.

md5sum twrp-3.1.1-0-clark.img 
5a5ba3da62929e9ee71946ea14ddb6ad  twrp-3.1.1-0-clark.img

tail twrp-3.1.1-0-clark.img.md5 
6de4eb0e21744916357137acd421d78a  twrp-3.1.1-0-clark.img

gpg --verify twrp-3.1.1-0-clark.img.asc twrp-3.1.1-0-clark.img
gpg: Signature made Tue 16 May 2017 06:12:27 AM EDT using RSA key ID 891A43DF
gpg: BAD signature from "TeamWin <admin@teamw.in>"

**Comment by raedah** [comment]
https://github.com/TeamWin/Team-Win-Recovery-Project/issues/816
