### ISSUE TITLE
color with aroma

### ISSUE THREAD

**Issue by carl1961** [TeamWin/Team-Win-Recovery-Project#96]
Latest version TWRP 2.4.1.0 
http://forum.xda-developers.com/showthread.php?t=1677447
mount sdcard fine

just the color is wrong

red is clear, blue is yellow, making aroma installer ugly

Great Recovery (the best!!)
first with correct color TWRP 2.3.3.0
![100_0564](https://f.cloud.github.com/assets/3056821/125758/5de7a4c4-6f21-11e2-906e-4098fa0d55f2.JPG)

TWRP 2.4.1.0
![100_0570](https://f.cloud.github.com/assets/3056821/125759/60e4f776-6f21-11e2-9fbc-83821543cf82.JPG)

**Comment by Dees-Troy** [comment]
We had to change the kernel that TWRP uses to get touch working with the latest updates from HTC. The new kernel uses a different pixel format (32 bpp RGBX format) that will require aroma installers to be recompiled with the correct color output. This is not a TWRP issue. It is an issue with aroma.
