### ISSUE TITLE
Official TWRP App and LineageOS root addon

### ISSUE THREAD

**Issue by GrubC** [TeamWin/Team-Win-Recovery-Project#970]
I use LineageOS 14.1 on Sony huashan and have installed the official root addon. The Official TWRP App always reports: device not rooted. Other apps are working correctly with root access.

**Comment by Sekra** [comment]
I have same issue, but LineageOS 14.1 on Samsung Galaxy Note 3 (hlte) device. Official root addon enabled, other apps have root working fine, TWRP always says "device not rooted".

**Comment by Sekra** [comment]
Fixed the issue by enabling developer options on my phone OS and giving "Root Access" to apps.

**Comment by GrubC** [comment]
It's working now since an update of LineageOS and/or Official TWRP App.

**Comment by kpinc** [comment]
I have the same problem on the Oneplus 3T.  Reopened the issue as #1025.

**Comment by widewing** [comment]
Also have this issue on latest LineageOS on OnePlus X
