### ISSUE TITLE
Decrypt fails on 3.1.1-0 (piccolo)

### ISSUE THREAD

**Issue by bretello** [TeamWin/Team-Win-Recovery-Project#980]
Decryption of data partition fails on a BQ Aquaris M5 (latest LineageOS Nightly) with TWRP-3.1.1-0 (https://dl.twrp.me/piccolo/twrp-3.1.1-0-piccolo.img.html)

Here's recovery.log
http://termbin.com/bcb0
and here's dmesg.log
http://termbin.com/ix3v

**Comment by Pintaius** [comment]
Had the same problem, and after trying everything I could find I managed to get it working by installing the 4.5.0 firmware update with TWRP and re-flashing TWRP (3.1.1.0) afterwards. See the end of this thread for details and a link to the update file: https://github.com/TeamWin/android_device_bq_piccolo/issues/1 (many thanks to @Kra1o5!)

**Comment by bretello** [comment]
Thanks. Is this the firmware file?
FirmwareMM_v4.5.0_signed.zip (md5=0d80dbad7234e7a17341441c9de412fd)
Just flash it by choosing "Install zip" from TWRP?

**Comment by Pintaius** [comment]
Yes, that's the one and that's how I installed it. Hope it works for you as well!

**Comment by bretello** [comment]
Works like a charm, thanks!
