### ISSUE TITLE
struck in twrp recovery.

### ISSUE THREAD

**Issue by Yuvrajaryans** [TeamWin/Team-Win-Recovery-Project#986]
hi plz help me. 
I rooted my xperia z device and unlocked boot loader and flash custom recovery using twrp app and now after rebooting it struck to  twrp recovery and if I m rebooting it by selecting system then also it boots to recovery page .

**Comment by JonnyTech** [comment]
On some phones, unlocking the bootloader also wipes the device. Have you installed a new ROM? Grab LineageOS for that device [from here](https://www.androidfilehost.com/?w=files&flid=143403). Also make sure that you are using the [latest TWRP image](https://dl.twrp.me/yuga/).

**Comment by nailyk-fr** [comment]
And wipe /cache partition, it could still contain some recovery commands.

**Comment by Yuvrajaryans** [comment]
I have wipe it but it doesn't work.

**Comment by Yuvrajaryans** [comment]
I have just flash latest twrp recovery image for Sony experia . and then after rebooting it struck in twrp recovery page.

**Comment by JonnyTech** [comment]
It sounds like you have flashed the recovery image to the boot partition.

Did you install the ROM that I listed earlier? Copy it to your SD card and flash from TWRP.

Alternatively download and unzip the [boot image](https://github.com/TeamWin/Team-Win-Recovery-Project/files/1094520/boot.zip), boot to your bootloader and `fastboot flash boot boot.img`.

**Comment by Yuvrajaryans** [comment]
1. which one linosos.
i have downloaded lineage 14.1-20170618-unofficial-yuga.zip file

**Comment by Yuvrajaryans** [comment]
i have to swipe factory reset before flashing rom.

**Comment by Yuvrajaryans** [comment]
Thanks flash Sony firmware using flash tool now it boots in system. But now I m unable to enter in recovery mode.  Rooted phone again flash recovery but it doest enter in recovery mode it boots in system only.
Plz help.
