### ISSUE TITLE
Not Flashing ROMs from GooManager

### ISSUE THREAD

**Issue by girron** [TeamWin/Team-Win-Recovery-Project#99]
I had to restore my touchpad and I just installed GooManager and it installed the newest TWRP and when I click on Flash ROMs it just restarts into MoBoot. I go to the TWRP option and try and flash the roms manually with no luck.

**Comment by Dees-Troy** [comment]
Can you pull a recovery log after the failed install. There's a copy log button under advanced that should put the log onto /sdcard/recovery.log. Paste it to a paste site and then paste the link here please.

**Comment by Dees-Troy** [comment]
Closing due to no logs provided.
